### ISSUE TITLE
question about losses.py

### ISSUE THREAD

**Issue by kalubin-awym** [fizyr/keras-retinanet#1010]
I want to add one more loss func to replace the smooth l1 loss, and i want to ask about "y_pred: Tensor from the network of shape (B, N, 4). "
so the y_pred is (x1, y1, x2, y2) or (x, y, w, h) or (tx, ty, tw, th) as in faster RCNN ?

**Comment by martinzlocha** [comment]
If you look at `compute_input_output` in generator.py (https://github.com/fizyr/keras-retinanet/blob/master/keras_retinanet/preprocessing/generator.py#L318) and trace your way back to `anchor_targets_bbox` (https://github.com/fizyr/keras-retinanet/blob/master/keras_retinanet/utils/anchors.py#L53) then here in the comment it says that the format is (x1, y1, x2, y2).

**Comment by kalubin-awym** [comment]
> If you look at `compute_input_output` in generator.py (https://github.com/fizyr/keras-retinanet/blob/master/keras_retinanet/preprocessing/generator.py#L318) and trace your way back to `anchor_targets_bbox` (https://github.com/fizyr/keras-retinanet/blob/master/keras_retinanet/utils/anchors.py#L53) then here in the comment it says that the format is (x1, y1, x2, y2).

thank you！

**Comment by hgaiser** [comment]
Seems resolved :) thanks @martinzlocha
