### ISSUE TITLE
Class limit?

### ISSUE THREAD

**Issue by jaymefosa** [fizyr/keras-retinanet#1016]
Nvidia 1080 8gb, 8gb Ram, Ubuntu 16.04

Training can proceed with 700 classes, but with more than that it runs out of memory for resnet or mobilenet backbones. The final layer is a large 100,000 x classes tensor. Is this right? Have others been able to train with similar hardware for a higher number of classes? Does the image input size have a large effect on the network size?

**Comment by yustinaivanova** [comment]
any answer?
