### ISSUE TITLE
Datat augmentation with random_transform

### ISSUE THREAD

**Issue by GoilerElch** [fizyr/keras-retinanet#1017]

**Comment by GoilerElch** [comment]
Hi! I am using retinanet and doing some experiments with image transformation for augmenting my dataset. I know this question has been asked before, but doesnt seem 100% answered for me. Does the tranform generator always generate the double amount of images and annotations respectively of the local datatset? If i use --random-transform and check the results with debug.py I just see the transformed images and not the original ones. So it seems for me that training.py just uses the transformed images and not the originals. Am I wrong?

**Comment by de-vri-es** [comment]
You are not wrong, all data will be subjected to random transformations. Each time an image is used to train, it will be transformed with a new random transformation.

**Comment by de-vri-es** [comment]
Does this answer your question?

**Comment by GoilerElch** [comment]
ok perfect. 
Thanks!

**Comment by de-vri-es** [comment]
Good to hear :)

**Comment by 2696120622** [comment]
> Hi! I am using retinanet and doing some experiments with image transformation for augmenting my dataset. I know this question has been asked before, but doesnt seem 100% answered for me. Does the tranform generator always generate the double amount of images and annotations respectively of the local datatset? If i use --random-transform and check the results with debug.py I just see the transformed images and not the original ones. So it seems for me that training.py just uses the transformed images and not the originals. Am I wrong?

you are not wrong. Before images in a batch are input to the network,they are transformed randomly.
