### ISSUE TITLE
Need example for Retinanet with ROS service on python

### ISSUE THREAD

**Issue by Carlbouakl** [fizyr/keras-retinanet#1022]
Hello,
I'm working on Retinanet with TensorFlow and want to create a ROS service that loads the neural network when launched, and then keeps it running in the background. It should work when called without reloading the network every time.

The current state is that I'm launching the neural network when I take the first picture and then it keeps running. However, I want to do that even before taking the first picture.

Can anyone provide an example? It seems like I can't do that without loosing the session.

I'm using python 2.7

**Comment by hgaiser** [comment]
Not really a keras-retinanet problem, but more a tensorflow / keras issue. See [here](https://github.com/keras-team/keras/issues/2397#issuecomment-254919212).
