### ISSUE TITLE
Training model with custom dataset in Google Colab

### ISSUE THREAD

**Issue by RomRoc** [fizyr/keras-retinanet#1024]
I know this is not an issue, but I don't know where I can post this information, in case it is useful to someone.

Here is my repo where I train Fizyr Retinanet model in Google Colab with custom dataset:
[Github repo](https://github.com/RomRoc/objdet_fizyr_colab)

Thanks a lot for your amazing Retinanet implementation.

**Comment by hgaiser** [comment]
Thank you for the kind words and for the contribution. As you said, it's not an issue so I don't think it makes sense to leave this open though.
