### ISSUE TITLE
Retinaface

### ISSUE THREAD

**Issue by zhly0** [fizyr/keras-retinanet#1025]
Hi，Fizyr：
        Thanks for your work，this is not a issue.recently，there is a face detector based on RetinaNet，but they implement by mxnet，which is not a common use framework compared with keras，is there a schema to implement RetinaFace using keras？
        Thanks！

**Comment by hgaiser** [comment]
You're really better off asking on the RetinaFace repository, although I doubt they will have implemented it in Keras as well.
