### ISSUE TITLE
model.predict_on_batch only return the boxes and scores when test using evaluate.py.

### ISSUE THREAD

**Issue by lemon126** [fizyr/keras-retinanet#1026]
File "/home/keras-retinanet/keras_retinanet/bin/../../keras_retinanet/utils/eval.py", line 84, in _get_detections
boxes, scores, labels = model.predict_on_batch(np.expand_dims(image, axis=0))[:3]
ValueError: not enough values to unpack (expected 3, got 2)

I met this issue when I run evaluate.py using csv as the input. It seems model.predict_on_batch only return the boxes and scores, no labels. why?

**Comment by martinzlocha** [comment]
Please have a look at the FAQ section in the README. The solution to this error is described there.

**Comment by lemon126** [comment]
> Please have a look at the FAQ section in the README. The solution to this error is described there.

I have solved the problem，thank you.

**Comment by gmt710** [comment]
@lemon126 ,Hello,do you remember how you solve this proplem?

**Comment by gmt710** [comment]
Okay,I find [this](https://github.com/fizyr/keras-retinanet#converting-a-training-model-to-inference-model) which may be helpful.

**Comment by samomidi** [comment]
As above has been mentioned refer to the readme file. However, I thought to share my case if you are running into out of memory issues when evaluating your training model.

Convert model to inference model, this reduces size of the model as it is only reference not training model (google to figure out the differences):

`python keras_retinanet\bin\convert_model.py ./snapshots/resnet50_csv_100.h5  ./snapshots/inference/resnet50_csv_100.h5`

And then run the Evaluate script from the repository:
`python keras_retinanet\bin\evaluate.py --gpu 1  csv annotations.csv classes.csv  ./snapshots/inference/resnet50_csv_100.h5`
