### ISSUE TITLE
Saving data augmentation (images + annotations)

### ISSUE THREAD

**Issue by xAvyax** [fizyr/keras-retinanet#1029]
I'm using --random-transform for augmentation and I would like to save the augmented images and annotations as files.
I already encountered this issue (https://github.com/fizyr/keras-retinanet/issues/876) and tried to implement something similar in preprocessing/generator.py myself. However, due to my lack of deep knowledge for your code, I could not link the given image (which is only an np.darray) to the original one.
I also wondered how to add the name of the random transformation applied to the image to the filename.

**Comment by hgaiser** [comment]
You could have a look at `debug.py`, which creates a generator and optionally uses random transformation. You will have to make some modifications to save the files. There is no support for this in our generators.

>  I also wondered how to add the name of the random transformation applied to the image to the filename.

The name of the random transformation? I'm not sure what you mean by this.

**Comment by xAvyax** [comment]
Thanks, I will give that a try.
> The name of the random transformation? I'm not sure what you mean by this.

For example, the saved image file should be named img_001_flip_x.png if it was x flipped or img_001_rotation_15.png if this rotation was applied.

**Comment by hgaiser** [comment]
> For example, the saved image file should be named img_001_flip_x.png if it was x flipped or img_001_rotation_15.png if this rotation was applied.

Ah okay, that is quite difficult to get out of the current way we do data augmentation. All augmentations together form a transformation matrix that is applied over the image. The information on which individual augmentation methods have been applied are lost in creating the matrix.
