### ISSUE TITLE
anchor ratio question

### ISSUE THREAD

**Issue by daassh** [fizyr/keras-retinanet#1032]
Dear @hgaiser,
Thank you for your nice work.

I have change the _ratios_  to fit my dataset like below, and in _debug.py_ all the anchor box was green(that mean nice). But when I evaluate the trained model, although some result was right, but I found in all the label box,  the height of box large than the width of box(as you can see the red box in attach image, the green box is what I tagged, the red box is what _evaluate.py_ drawed). 

In my understanding, _ratio = height/width_ ,  setting all ratios less then 1, then the evaluate result should generate box like this (height/width < 1).

I have try add --config anchor_config.ini in  evaluate.py, but it did not work.
Please let me know where I am wrong.
Thanks.

```
[anchor_parameters]
# Sizes should correlate to how the network processes an image, it is not advised to change these!
sizes   = 32 64 128 256 512
# Strides should correlate to how the network strides over an image, it is not advised to change these!
strides = 8 16 32 64 128
# The different ratios to use per anchor location.
ratios  = 0.3 0.6 1
# The different scaling factors to use per anchor location.
scales  = 0.7 1 1.2
```
![14](https://user-images.githubusercontent.com/13551272/59500969-1992c600-8ecd-11e9-99fe-f25f71b73b22.png)

**Comment by hgaiser** [comment]
Closing as this does not appear to be an issue with the code base.

For reference, the height is calculated here: https://github.com/fizyr/keras-retinanet/blob/master/keras_retinanet/utils/anchors.py#L300

Which means:
```
height = width * ratio
```

So in other words:
```
ratio = height / width
```

**Comment by daassh** [comment]
> Closing as this does not appear to be an issue with the code base.
> 
> For reference, the height is calculated here: https://github.com/fizyr/keras-retinanet/blob/master/keras_retinanet/utils/anchors.py#L300
> 
> Which means:
> 
> ```
> height = width * ratio
> ```
> 
> So in other words:
> 
> ```
> ratio = height / width
> ```

So my understanding was not wrong, what happen in evaluate? (all the height of box large than the width of box)

**Comment by daassh** [comment]
I  realize the question now.  To convert model before evaluate, i need add _--config anchor_config.ini_ param to convert_model.py.
```
keras_retinanet/bin/convert_model.py  --config anchor_config.ini /path/to/training/model.h5 /path/to/save/inference/model.h5
```
