### ISSUE TITLE
Full memory consumption when running [predict_on_batch]

### ISSUE THREAD

**Issue by mohammed-Emad** [fizyr/keras-retinanet#1033]
welcome everybody

I am having a terrible memory consumption problem by the function
predict_on_batch

I used the training as a backbone. resnet50
I use cpu with 8 GB RAM. Not gpu
I can load the model into memory with security and actually consume a bit of space.

But when you access that function predict_on_batch, consumption increases dramatically until the last memory
Do you? Can run RetinaNet in cpu mode?
tensorflow-1.5
I hope to find a solution
Thanks.

**Comment by hgaiser** [comment]
Try updating tensorflow to a newer version (currently 1.13) to see if it makes a difference.

As this is not an issue with retinanet, I'm going to close this.
