### ISSUE TITLE
Multiple input images with different dimensions

### ISSUE THREAD

**Issue by mgersalan** [fizyr/keras-retinanet#1034]
Would it be possible to feed the Retina-Net with 2 input images which have different dimensions without cropping the larger image?

**Comment by hgaiser** [comment]
Yes, by padding the smaller image :p 

ps. this is what our generators do by default, padding smaller images.

**Comment by mgersalan** [comment]
Padding the smaller image and simply concatenating them would do it then?

**Comment by hgaiser** [comment]
Yes, concatenating them in the first axis, so your input would be shaped like:

```
(2, height_of_tallest_image, width_of_widest_image, 3)
```

Assuming two images.

**Comment by mgersalan** [comment]
Thank you

**Comment by shahsahilj** [comment]
How would you advise padding the smaller image? should I be using zeros to pad? will that affect the accuracy of predictions? Thanks

**Comment by hgaiser** [comment]
> should I be using zeros to pad?

That's what we do in our generators.

> will that affect the accuracy of predictions?

Probably :) test it and find out.
