### ISSUE TITLE
Fail to run example notebook

### ISSUE THREAD

**Issue by rex-yue-wu** [fizyr/keras-retinanet#1040]
Tried to run the notebook `keras-retinanet/examples/ResNet50RetinaNet.ipynb`, but failed. 

All strange errors, some got solved by reading historical issues and FAQs, but still many. I strongly suggest to make a `colab` notebook, such that one can easily reproduce all results.

**Comment by rex-yue-wu** [comment]
Can anyone check whether the example notebook is also up-to-date? 

BTW, I failed to see where is the pretrained weight. The whole `snapshots` folder is empty.

**Comment by hgaiser** [comment]
It would help if you shared the error you got.

**Comment by kolyadin** [comment]
@rex-yue-wu  you have to manually download model from this place:
https://github.com/fizyr/keras-retinanet/releases

and put model file resnet50_coco_best_v2.1.0.h5 in snapshots directory

**Comment by tseth92** [comment]
@rex-yue-wu snapshots folder will add weights once you have started the training . for each epoch run, one h5 file will be generated and will be placed in snapshots folder
