### ISSUE TITLE
Not able to change maximum number of detection box

### ISSUE THREAD

**Issue by zerovirus123** [fizyr/keras-retinanet#1047]
The default detection box cap is 300. #624 shows that max_detections parameter can be changed in keras_retinanet/layers/filter_detections.py. I set all instances of max_detections to a higher number, yet when I run the example notebook I still got 300 bounding boxes max. How can I change the max_detections paramater.

**Comment by hgaiser** [comment]
You will need to create a new model since these values are saved in the model. When you've changed your values, create a model as is done in `train.py` and load the weights you already have with `model.load_weights(weights_path, by_name=True)`.

Closing as this is not an issue with the code.

**Comment by muhanur** [comment]
Sorry.. another question.

how to make a new weight? does that mean to detect objects more than 300 i can't use pre-training model?
