### ISSUE TITLE
inference GPU memory so big

### ISSUE THREAD

**Issue by guker** [fizyr/keras-retinanet#1048]
resized image size （800, 1200, 3） and put it to retinanet， but GPU memory about 7GB used，anybody know reason？
retinanet inference setting as follow：
```python
def get_session():
      config = tf.ConfigProto()
      config.gpu_options.allow_growth = True
      return tf.Session(config=config)
```

**Comment by guker** [comment]
I solve  it,  only set TF_CUDNN_USE_AUTOTUNE=0.
setting in command line:
```
export TF_CUDNN_USE_AUTOTUNE=0
```
setting in python code:
```
os.environ['TF_CUDNN_USE_AUTOTUNE'] = 0
```

resized image size （800,1200,3），GPU  use  870MB

**Comment by xcaizewu** [comment]
Hello, where did you add this line of code, is it in train.py?

**Comment by xcaizewu** [comment]
@guker  Hello, where did you add this line of code, is it in train.py?
