### ISSUE TITLE
Output predicted anchors during inference time

### ISSUE THREAD

**Issue by naveenrajusg** [fizyr/keras-retinanet#1052]
As i have observed anchors r generated according to respective feature map sizes ,but after regression and classification is applied in which part of code do they convert the anchor sizes to the image dimensions.

So can anyone plz explain me this

**Comment by hgaiser** [comment]
Have a look in [this](https://github.com/fizyr/keras-retinanet/blob/master/keras_retinanet/utils/anchors.py) file. It contains almost all anchor related computations.
