### ISSUE TITLE
smaller object detection

### ISSUE THREAD

**Issue by xuxiyang1993** [fizyr/keras-retinanet#1054]
Hi,

Does anyone know how to detect smaller object in the image? I tried to set the `sizes` and `strides` in `AnchorParameters.default` to a smaller value but the resulting output bounding box appears in a wrong position. Is there other parts of the code I need to change, or I need to retrain the whole model for smaller anchor params? Thanks!

**Comment by hgaiser** [comment]
As the [example file](https://github.com/fizyr/keras-retinanet-test-data/blob/master/config/config.ini) mentions, `sizes` and `strides` correspond to how the backbone is set up and shouldn't be changed unless you change the backbone. You can try playing around with `scales` and `ratios` and check in `debug.py` that your annotations are properly covered by anchors.

That said, I'm closing this as it is not an issue with the code base.
