### ISSUE TITLE
[Help]Get recall values for each thresh [0 - 1]

### ISSUE THREAD

**Issue by scstu** [fizyr/keras-retinanet#1058]
I am trying to plot PR curve and I managed to get the average precision for different thresholds [0 -1] using `--score-threshold 0.0` .. but couldn't find a way to get the recall for each threshold. any help please

**Comment by hgaiser** [comment]
Precision and recall are actually already computed internally to compute the mAP. Check [here](https://github.com/fizyr/keras-retinanet/blob/master/keras_retinanet/utils/eval.py#L228-L229). Good luck!
