### ISSUE TITLE
Cannot save trained model after loading it AttributeError: 'list' object has no attribute 'tolist'

### ISSUE THREAD

**Issue by DPP93** [fizyr/keras-retinanet#106]
Hello,

I wanted to train model a bit more after some epochs. I had it saved and I loaded it and then I performed training. Loss function started to becoming smaller from the point where the previous model was saved, but after training it was not possible to save this newly trained model again.

Here's a listing with error:
Traceback (most recent call last):
  File ".../Programming/keras-retinanet-master/examples/train_csv.py", line 125, in <module>
    model.save(os.path.join('snapshots', 'resnet50_csv_final.h5'))
  File ".../MasterEnv/lib/python3.6/site-packages/keras/engine/topology.py", line 2556, in save
    save_model(self, filepath, overwrite, include_optimizer)
  File ".../MasterEnv/lib/python3.6/site-packages/keras/models.py", line 107, in save_model
    'config': model.get_config()
  File ".../MasterEnv/lib/python3.6/site-packages/keras/engine/topology.py", line 2329, in get_config
    layer_config = layer.get_config()
  File ".../Programming/keras-retinanet-master/keras_retinanet/layers/_misc.py", line 66, in get_config
    'ratios' : self.ratios.tolist(),
AttributeError: 'list' object has no attribute 'tolist'

I was following the script train_csv.py I checked alread if saving to other file will fix it and setting override attribute to True is not resolving it.

**Comment by DPP93** [comment]
Update: also tried json serialization and I received the same error

**Comment by de-vri-es** [comment]
Looks like a problem in the serialization/reconstruction of the layer. Can you try the [anchors-layer-numpy-array](https://github.com/fizyr/keras-retinanet/tree/anchors-layer-numpy-array) branch to see if that fixes your issue?

**Comment by de-vri-es** [comment]
The branch just got merged. If the problem persists after updating to the latest master, please re-open this issue :)

**Comment by DPP93** [comment]
Everything is working now - sorry for late comment - I didn't have an opportunity to verify this issue :) And thanks for fix

**Comment by de-vri-es** [comment]
Good to hear, thanks for reporting back :)
