### ISSUE TITLE
Dataset preparation cropping vs labelling

### ISSUE THREAD

**Issue by kolyadin** [fizyr/keras-retinanet#1062]
I am building custom dataset with only one class ("cashier_check") of images like this:
https://take.ms/M9lYD

And instead of labelling images i cropped images like this:
https://take.ms/kn1b4

And then filling csv file with dimensions on whole image:

train_images/0001c1d922aee3a5919d2dd5e22a08268140348c.jpg,0,0,872,4128,cashier_check
train_images/001c6a44ed88407715f7722b123056308ebc32f7.jpg,0,0,781,3445,cashier_check
train_images/002b7e9d059d50470c37a87b449026e9e5e0f5e9.jpg,0,0,351,989,cashier_check
train_images/005af9881cd07fae5000f7ac06d82712e01f5687.jpg,0,0,712,3859,cashier_check

I am wondering is it proper way to build dataset?
Maybe background is required for something?

**Comment by hgaiser** [comment]
If you're goal is to detect the receipt in images, then you shouldn't be cropping. You should be taking the entire image and annotate where the receipt is inside the image, or it won't work.

Closing this as it is not an issue with the code base.
