### ISSUE TITLE
Training voc data formats，mAP = 0

### ISSUE THREAD

**Issue by xcaizewu** [fizyr/keras-retinanet#1064]
I trained my own data set in voc format, and the mAP after each epoch was 0. What caused the problem?
![1](https://user-images.githubusercontent.com/48117810/61015215-21a33000-a3bd-11e9-83f4-15740ef51ace.png)

**Comment by hgaiser** [comment]
I see you're training resnet101, then I'm assuming you're training from imagenet weights. You'll need a lot more than 6 epochs to get to a stable network. My advice: use the pretrained COCO weights and start from resnet50.

That said, this is not an issue with the code base, so I'll close this.

**Comment by xcaizewu** [comment]
@hgaiser 
Thank you very much. I made a stupid mistake. I forgot to use the pre-training model to train my model. Thank you again for answering my questions.
