### ISSUE TITLE
run a long time

### ISSUE THREAD

**Issue by TianMingChen** [fizyr/keras-retinanet#1066]
![image](https://user-images.githubusercontent.com/20785298/61020675-1ce87700-a3d1-11e9-8437-a2312defcddd.png)
It cost about 267s to test a picture when I run the examples ,what is the problem?

**Comment by hgaiser** [comment]
Hmm why do you use sudo to run this command?

How did you install tensorflow? It seems it is not optimized properly. Also, what does your timing measure; how does your `test.py` look like?

**Comment by TianMingChen** [comment]
> Hmm why do you use sudo to run this command?
> 
> How did you install tensorflow? It seems it is not optimized properly. Also, what does your timing measure; how does your `test.py` look like?

Hmm in my server I have to use sudo when use python3,and the 'test.py' is just the 'ResNet50RetinaNet.ipynb'.

**Comment by hgaiser** [comment]
If you have to use `sudo`, then you likely misconfigured something (used `sudo` in the past where you shouldn't have).

How did you install tensorflow?

**Comment by hgaiser** [comment]
Any update here?

**Comment by sooyeonshin** [comment]
I had a similar problem with tensorflow-gpu 1.5.0. 
Version 1.8.0 fixed it.

**Comment by hgaiser** [comment]
Alright I'm assuming the issue is resolved then.
