### ISSUE TITLE
prediction time

### ISSUE THREAD

**Issue by kbrajwani** [fizyr/keras-retinanet#1069]
my model taking 1 second to predct image on colab but in cpu its take 40 second. so how can i reduce this time. i am only interested to predict the label of image.

**Comment by hgaiser** [comment]
Then you should be looking into image classifications, not object detections.

**Comment by kbrajwani** [comment]
I have 500 invoice all have same structure only logo is different. So i think classification wouldn't be work. Please tell me how to reduce time of prediction.

**Comment by Raghav-B** [comment]
What exactly are you trying to use the object detector for? Knowing what your requirements are and how you've implemented your solution should help us help you a lot better. As @hgaiser mentioned, perhaps object detectors aren't the best solution for your use case.

What's the resolution of the images you're running the model on?  In my experience I can easily get from around 0.05 seconds to 0.2 seconds per image ranging from 400x400 to 1080x1080 on my GPU. These are approximate numbers but in most cases retinanet's performance for me has been real-time, definitely not 1 second per image. I don't have much experience using colab so I really can't say how local GPU performance compares to performance on colab - could it be possible that colab is your bottleneck?

Did you modify any of the default anchor box sizes? Reducing the dimensions of the minimum anchor boxes should greatly increase inference time for an image.

Which backbone are you using?

**Comment by kbrajwani** [comment]
I am using resnet50 as backbone. i am getting best accuracy. I have invoice
with same structure so classification is not good for me so that reason i
am using logos of invoice. Now my interest is to take only logo label.

**Comment by tseth92** [comment]
@kbrajwani From what you have told so far, I am assuming you have invoices where only logo changes. So, if the logo is always at a specific area, eg. on the top right-hand corner, then I would suggest little engineering and go for classification instead of detection.
Eg. in that case, you can just crop that particular area from the image as a preprocessing step in your pipeline and then send it to retinanet for classification of that particular area. This should do your work in that case.

**Comment by kbrajwani** [comment]
I have 1000 images 10 classes and all classes logo are different position
in invoice.How can i crop.?

**Comment by Raghav-B** [comment]
@kbrajwani If the rest of the invoice is just black and white, maybe you could use OpenCV to filter out anything that's not coloured? This is assuming that all 10 logos have different colours. In fact, you could probably create 10 different filters for each logo and see which filter gives you the largest region of interest - this will be how you classify the different logos.

I know its not machine learning, but if your logos are simple enough it should be fairly straightforward to set up some HSV filters. This would also run way faster on your CPU than a CNN.

Could we maybe see an example of what the logos/invoices look like? You can blur out anything important.

**Comment by kbrajwani** [comment]
Like in this image big name of company is logo for us scs agency. My whole
invoice is black and white and all logo are at different position i am
getting best accuracy via keras retinanet . My final work is to reduce
time. Please help as soon as possible.

**Comment by Raghav-B** [comment]
I can't see any attached image.

From what I've researched, it seems that running a network on a local GPU is definitely faster than using colab's free cloud GPU/TPU, at least for training. It's possible that the same is true for inference as well. This is me assuming that you do not have a GPU installed on your local PC. Is that correct?

The only leads I can advise you to follow would be:
1. Trying to run your model on a machine with a GPU.
2. Checking the resolution of your input image.

Other than this, with the information you've provided so far, I can't really think of any other causes for the slow inference time.

**Comment by kbrajwani** [comment]
Ok thanks

**Comment by paruliansaragi** [comment]
I know this is late but, If you just change the `min_side` and `max_side` parameters of the `resize_image()` function, this has improved my inference time on the cpu from 8s to 0.7s. If this helps anyone going forward.

**Comment by tonmoyborah** [comment]
@Raghav-B I see you mention this line "Did you modify any of the default anchor box sizes? Reducing the dimensions of the minimum anchor boxes should greatly increase inference time for an image." I would like to know more about this. Does decreasing or increasing my anchors effect the inference time a lot (I think it would)?
Why would reducing the minimum anchor size do differently that it increases inference time?
Thanks a lot

**Comment by Raghav-B** [comment]
Hi @tonmoyborah, my apologies for the late reply.

To my understanding, you can treat the anchor boxes as a sliding window that slides over the image to propose regions of interest based on the specified anchor box aspect ratios. 

Having smaller anchor boxes means that the window takes a longer time to slide over the window completely, hence increasing the inference time. On the other hand, increasing the anchor box sizes means a faster inference time, at the cost of being unable to detect smaller objects.

I'm a bit rusty with how the backend of retinanet works so I would appreciate if anyone else would like to pitch in!

**Comment by tonmoyborah** [comment]
Hi @Raghav-B, thank you for your time. I am not totally sure but as far as I understood, retinanet assigns 9 anchor boxes for each cell of the output feature map, the size of which I think depends on the input image size. I mean if the feature map has size 3x3 then for each of these 9 cells there would be 9 anchors i.e. 9x9 = 81 anchors. Hence it might be that the positions and number of the anchors are fixed and irrespective of the size of the anchors. I would love it if anyone could point me if and where I am wrong.
