### ISSUE TITLE
Error "ValueError: generator already executing" during training 

### ISSUE THREAD

**Issue by mohammad-saber** [fizyr/keras-retinanet#1070]
Hi,

I face an error when I train the network. I use following command in Terminal: 

    python train.py --batch-size 20 --multi-gpu 1 --epochs 20 --steps 200 --snapshot-path /snapshots --workers 4  pascal /Dataset

I am using my own dataset for training. 
Environment:
    Ubuntu 16
    tensorflow 1.14.0
    keras 2.2.4

Expected behaviour:
training RetinaNet model without error

Actual behaviour:
In the first epoch, training stops with following error:
    ValueError: generator already executing

![1](https://user-images.githubusercontent.com/38423900/61102773-445f4280-a4aa-11e9-95bf-daa29a7ed97f.png)

Note:
When I use --epochs 2 --steps 2, I don't face any error. When I increase the number of epochs or steps, the above-mentioned error occurs.

**Comment by mak4alex** [comment]
possible bug was added to csv generator with thread unsafe structure OrderedDict [here](https://github.com/fizyr/keras-retinanet/commit/9252db4ded741b3c65dc1cbad583c35cb9fd8872#diff-d912303d9b696f0b227beec3b8bd4ae1)  FYI @hgaiser 

@mohammad-saber  for now use  --workers 1  to use only 1 generator

**Comment by mohammad-saber** [comment]
I tried --workers 1. Now, it works without error. Thanks.
