### ISSUE TITLE
Conversion of a custom Keras RetinaNet model (.h5) to native TF proto buffer (.pb)

### ISSUE THREAD

**Issue by sayakpaul** [fizyr/keras-retinanet#1072]
Hi.

I have fine-tuned a RetineNet model on a custom dataset for object detection. I was able to export the final model to a .5 file. I now want to convert it to a .pb file so that I can use that on NVIDIA  Jetson Nano (using the TensorRT) framework. 

With the current configurations that keras-retinanet have, is it possible to get the TF session?

**Comment by CHONGCHUANSHENG** [comment]
hello   have you resolved it ?  how do u use tensorrr to convert the pb
 to uff?
