### ISSUE TITLE
ModuleNotFoundError: No module named 'keras_retinanet'

### ISSUE THREAD

**Issue by chenyanyin** [fizyr/keras-retinanet#1077]
```
(keras) ubuntu@ubuntu:~/code/keras-retinanet-master/examples$ python ResNet50RetinaNet.py
Using TensorFlow backend.
Traceback (most recent call last):
  File "ResNet50RetinaNet.py", line 19, in <module>
    from keras_retinanet import models
ModuleNotFoundError: No module named 'keras_retinanet'
```

i converted .ipnb to .py, and run it, the erro happend, could you tell me how to solve it?thx

**Comment by Raghav-B** [comment]
Did you follow all the instructions under the Readme's Installation section? Is the error only happening in your .py file or is it also happening when you run the jupyter notebook?

**Comment by chenyanyin** [comment]
> Did you follow all the instructions under the Readme's Installation section? Is the error only happening in your .py file or is it also happening when you run the jupyter notebook?

both, i installation follow README.md, and i finished training by keras_retinanet/bin/train.py coco /path/to/MS/COCO.

**Comment by Raghav-B** [comment]
Hmm seems like the keras_retinanet module wasn't installed. Are you sure you ran `pip install . --user` in the root directory of your cloned repo? This should invoke the setup.py file included in the root.

You can double check by `pip list` and see if `keras-retinanet` is an installed module

**Comment by Raghav-B** [comment]
No problem! Glad it worked out :)

**Comment by samrawitergrtr** [comment]
Hi.
I face the same problem when i run it using Jupyter notebook. I followed all the steps which are found in the README.ME also i check it using pip list and it exist. But the python runs well so how am i run it in Jupyter notebook.
Thank You.
With Regards!

**Comment by minaahmed** [comment]
Hello could please mention the exact steps to setup environment ?
