### ISSUE TITLE
Out of memory when batch size is above 1

### ISSUE THREAD

**Issue by skier233** [fizyr/keras-retinanet#1078]
When I try to increase the batch size from 1 to anything above 1, I get out of memory errors and training stops. I’m using a GTX 1080 ti with 11gb of gpu memory so that should be enough for more than a batch size of 1. Is it possible that somehow my gpu memory has been marked as being used and it is not being freed and if so how should I fix this?

**Comment by tseth92** [comment]
Which dataset are you using? Coco/openImages etc. have very high resolution images . 11gb in 1080 is not enough for those . One thing you can do is resize images to a lower resolution and then feed it for training. Then you should be able to get batch size at least 2

**Comment by skier233** [comment]
Im using a custom dataset. How would 11gb not be enough for 2 1080p images?

**Comment by skier233** [comment]
Also, is it worth lower the resolution of my images to increase batch size?
Mainly, will increasing batch size increase my end mAP or just decrease
training time?

**Comment by hgaiser** [comment]
I'm training with batch-size=2 on a 1080ti as well, could you try prefixing your command with `TF_CUDNN_USE_AUTOTUNE=0` ?
