### ISSUE TITLE
failed to allocate from device cuda_error_out_of_memory

### ISSUE THREAD

**Issue by skier233** [fizyr/keras-retinanet#1083]
I'm trying to run the included convert-model python script to convert my trained model into an inference model. When I try to run the script, my chat is spammed with this error message:
failed to allocate from device cuda_error_out_of_memory
I do have memory as I can train or evaluate and use the convert-model argument in the evaluate function. Only this function is not working for me.

**Comment by skier233** [comment]
It's also telling me out of memory if I use the min-side 480 parameter for training. The strange thing is that my images are way higher resolution than 480 by default and they run fine normally so I'm not sure why scaling images DOWN would make me run of gpu memory?

**Comment by skier233** [comment]
sometimes I see these errors when training as well but they aren't reproducible. Sometimes it says out of memory and fails, sometimes it says out of memory but it's just a warning and it continues. Other times there are no errors or warnings at all. This is all on the same dataset as well.

**Comment by hgaiser** [comment]
It's strange to me that you get a CUDA OOM error, since we're disabling all GPUs in the convert-model script. How much CPU memory do you have?

**Comment by skier233** [comment]
32gb

**Comment by skier233** [comment]
I don't think the gpus were getting disabled correctly probably. I'll try it again tomorrow and see.

**Comment by hgaiser** [comment]
Any update on this ?
