### ISSUE TITLE
build anchor

### ISSUE THREAD

**Issue by zhou-frank** [fizyr/keras-retinanet#110]
I think every pyramid levels feature should have only one compatible size of anchor not all of anchor size in parameter.And the size have 3 ratio and 3 scales,so every spatial location have 9 anchor.

```
AnchorParameters.default = AnchorParameters(
    sizes   = [32, 64, 128, 256, 512],
    strides = [8, 16, 32, 64, 128],
    ratios  = np.array([0.5, 1, 2], keras.backend.floatx()),
    scales  = np.array([2 ** 0, 2 ** (1.0 / 3.0), 2 ** (2.0 / 3.0)], keras.backend.floatx()),
)
```
```
def __build_anchors(anchor_parameters, features):
    anchors = []
    for i, f in enumerate(features):
        anchors.append(keras_retinanet.layers.Anchors(
            size=anchor_parameters.sizes[i],
            stride=anchor_parameters.strides[i],
            ratios=anchor_parameters.ratios,
            scales=anchor_parameters.scales,
            name='anchors_{}'.format(i)
        )(f))
    return keras.layers.Concatenate(axis=1)(anchors)
```
in retinanet.py

I want to discuss with you about this question.

**Comment by de-vri-es** [comment]
Could you elaborate more on what you propose to change? What would `AnchorParameters` and `__build_anchors` look like ideally for you?

**Comment by zhou-frank** [comment]
Sorry，Sorry.
I just got it , a few seconds ago.Your implement is right.You use variable i to assign one size to one level.
Beginning ， I made a mistake that I think you use all size to each level feature.

**Comment by de-vri-es** [comment]
Alright, no problem. Thanks for thinking about it :)
