### ISSUE TITLE
i have different type of x1,x2,y1,y2 values, how to convert that?

### ISSUE THREAD

**Issue by yuliusd** [fizyr/keras-retinanet#1102]
I have bounding box coordinates from my labeling tools like below:
x1    x2                y1        y2                class
0.48 0.49666667 0.5025 0.53833336 abcd

how can i convert this value just like in README was mentioned?
Thank you for your help

**Comment by hgaiser** [comment]
Seems you're almost there. You'll just need to prepend your lines with the path to the image where the object is annotated and transpose some the coordinates to be x1, y1, x2, y2. Good luck!

**Comment by yuliusd** [comment]
ok thank you, noted @hgaiser
