### ISSUE TITLE
Re-Training Script :Please Guide Me About How We Can Retrain Further Model from existing Snapshots

### ISSUE THREAD

**Issue by NaeemKhan333** [fizyr/keras-retinanet#1105]
I am Trying to use retraining Command But It start training from Beginning.....Not continued the training from existing snapshot....... 

python bin/train.py --epochs 100 --snapshot-path ./snapshots --weights snapshots/resnet50_csv_145.h5 csv ./dataset/train.csv ./dataset/classes.csv

**Comment by hgaiser** [comment]
You can continue from a snapshot using `--snapshot`, which will also restore the optimizer state from when the snapshot was saved. Using `--weights` only copies the weights from that file, so it doesn't count as training from the beginning.

Both methods start from epoch 1 though, it's not that you continue from the epoch number you left off, you continue with the same state (or weights).

**Comment by NaeemKhan333** [comment]
So This command Will Work Perfectly For Retraining? Its Start Retraining from last saved State of the Weights?

**Comment by hgaiser** [comment]
I would advise to use `--weights`.

**Comment by NaeemKhan333** [comment]
In this way,I can start Retraining From existing Snapshot
python bin/train.py --epochs 100 --weights snapshots/resnet50_csv_145.h5 csv ./dataset/train.csv ./dataset/classes.csv
