### ISSUE TITLE
Training on ubuntu server suddenly stops

### ISSUE THREAD

**Issue by Exarillion** [fizyr/keras-retinanet#1108]
Hello everyone.

Our team is trying to train retinanet with resnet152 on an Ubuntu server. The server is a single computer we are connecting it via putty. We have been training models without any problem for like 20 days or more. But here is the thing: during training it suddenly stops somewhere in epoch. 
the command is:
nohup retinanet-train \
--backbone resnet152 \
--batch-size 2 \
--epochs 10 \
--random-transform \
--snapshot /home/hayes/burkut/retinanet-train-eval-152/[last snap folder]/[last snap file] \
--snapshot-path /home/hayes/burkut/retinanet-train-eval-152/[new snap folder] \
--tensorboard-dir /home/hayes/burkut/retinanet-train-eval-152/tbdir \
coco /home/hayes/burkut/coco4/ > output-152.log &
It worked totally fine but yester day we stareted to get these erors and the condition I mentioned above:
1) Segmentation fault (core dumped)
2)CUDA runtime implicit initialization on GPU:0 failed. Status: out of memory
3) Broken Pipe.

But we don't alway get these but we encountered with them few times.
After we start training it works perfectly for like 300-600 steps. Then it stops. When we checked nvidia-smi, tempr. and fan fell down but gpu memmory still in use!
We reinstalled nvidia driver but it didn't solved problem.

Oh we think there may be 2 reasons behind it:
1) owners of computer shut down the pc without killing the training process.
2) I tried to download a snap file that is used for training, during training process.
Any ideas to solve them?

**Comment by vcarpani** [comment]
Can you try with `--batch size 1`? It seems like you are using all the available memory. Which GPU are you using?

**Comment by hgaiser** [comment]
Any update on this? A segfault seems strange to me, but the out of memory does seem to indicate your GPU doesn't have enough memory. Maybe the training process reaches an image that requires more memory, causing the process to crash? What GPU are you using?

**Comment by hgaiser** [comment]
Alright, thanks for the feedback.
