### ISSUE TITLE
debug.py script not working correctly with COCO-type datasets

### ISSUE THREAD

**Issue by AndreaPi** [fizyr/keras-retinanet#1113]
I have a custom dataset, which uses COCO annotations, and I want to check it using the `debug.py` script.  On a Mac, I'm launching the script as

```
/somepath/.local/bin/retinanet-debug --display-name --annotations --anchors coco /someotherpath/COCO
```

The script is nearly identical to the master version: I only changed

```
        if key == 83:
            i = (i + 1) % generator.size()
        if key == 81:
```

to

```
        if key == ord('m'):
            i = (i + 1) % generator.size()
        if key == ord('n'):
```

because I couldn't, for the love of it, find what the heck keys 83 & 81 correspond to on my keyboard.

Anyway, as soon as I press key `m` to go to the next image, I get this error:

```
Traceback (most recent call last):
  File "/somepath/.local/bin/retinanet-debug", line 10, in <module>
    sys.exit(main())
  File "/somepath/.local/lib/python3.7/site-packages/keras_retinanet/bin/debug.py", line 269, in main
    run(generator, args, anchor_params=anchor_params)
  File "/somepath/.local/lib/python3.7/site-packages/keras_retinanet/bin/debug.py", line 221, in run
    draw_caption(image, [0, image.shape[0]], os.path.basename(generator.image_path(i)))
AttributeError: 'CocoGenerator' object has no attribute 'image_path'
```

Looks like the `debug.py` is expecting the `CocoGenerator`object to have some attribute that it doesn't have. Can you help me?

**Comment by hgaiser** [comment]
Seems that the argument `--display-name` is using an attribute that is not part of the base generator class. Could you make a PR to resolve this? The best way would be to add a base function in generator.py, `image_path`, and add this function to the different generators.

**Comment by AndreaPi** [comment]
@hgaiser thanks for the tip! I'm at a conference this week, but once I'm back I'll have a look at the code and let you know if I can do it. The main issue I can see with my first PR is that I'm not familiar with testing/CI conventions for the `keras-retinanet` source, thus I don't know what I would need to include (apart from bare,  functional code), in order for it to be an acceptable PR.

**Comment by de-vri-es** [comment]
It's okay to just submit a PR and let the CI server do it's thing. It will report problems automatically. Those problems can be fixed as they're reported. It's slower than running the tests locally, but there's no rush :)

And in the mean time you should be able to use your patched version locally to use the debug script with COCO.

**Comment by AndreaPi** [comment]
@hgaiser @de-vri-es (is it necessary to tag you guys? Or do you get a notification anyway since you wrote in the issue thread?) I started working on this, but I need your help to reduce the time needed to complete this task, or I'll have to give up (not enough free time). 

How I'm going about this: when I call `debug.py` work with the `--display-name` parameter, it executes

```
            if args.display_name:
                draw_caption(image, [0, image.shape[0]], os.path.basename(generator.image_path(i)))
```
Now, looking at the rest of the `debug.py` code, I believe  `i` is the image index. Thus, I added this function to `generator.py`, as suggested by @hgaiser,  where the formal argument `image_index` matches the actual argument `i`:

```
    def image_path(self, image_index):
    """ Returns the image path for image_index.
    """
    return os.path.join(self.base_dir, self.image_names[image_index])
```
Assuming this is correct, I now need to make this function available to each generator. Let's start with `coco.py`, since it's the one I need 😜 Here I find the class definition

```
class CocoGenerator(Generator):
.
.
.
```

I'm not familiar with the rules of inheritance in Python. Since `CocoGenerator` is inheriting from `Generator`, does this mean that any object of class `CocoGenerator` automatically inherits the method `image_path`, as it is in other OO languages? If this is so, then I'm done! I just need to commit the PR. If not, what should I modify in `CocoGenerator` so that objects of this class inherit the method? If you show me how to do it for `coco.py`, I'll do the same for 
, `kitty.py`, `csv_generator.py`, `open_images.py`, and `pascal_voc.py`. Thanks!

**Comment by AndreaPi** [comment]
hi, any news on this? Can you tell me if I'm going in the right direction or not...? I'd be glad to make my first real contribution to this repository...

**Comment by de-vri-es** [comment]
I'm not entirely sure what you're asking. The easiest thing to do is to submit a PR with your patch, then we can give feedback on the changes you made. Then we'll know for sure what changes you intended, because we can actually see them. And then we can give feedback and guidance much more easily.

It's perfectly fine to submit a PR if it's not done, or if you're not sure if the changes are correct. We won't be mean if the changes don't fit with the current design :)

If you have specific questions about parts of your changes, you can also post them as in-line comments on the PR yourself.


> is it necessary to tag you guys? Or do you get a notification anyway since you wrote in the issue thread?

You don't have to tag us. We'll be notified by github because we're maintainers and because we've joined in the conversation before.

**Comment by AndreaPi** [comment]
Ok thanks! Then I'll just submit it tomorrow.

**Comment by AndreaPi** [comment]
In the end I wasn't able to make the fix work by modifying `generator.py`: I had to work in `preprocessing/coco.py`. However, it works now! PR https://github.com/fizyr/keras-retinanet/pull/1143

**Comment by de-vri-es** [comment]
@AndreaPi: Thanks again :)

@hgaiser: Should we close this or do you want to keep it open until https://github.com/fizyr/keras-retinanet/pull/1143#issuecomment-545864695 is resolved?

**Comment by hgaiser** [comment]
Let's keep it open until that is resolved.

**Comment by AndreaPi** [comment]
We may share the workload. If you have the possibility to share a folder with one of the three remaining formats (PASCAL VOC, OID and KITTY), I can study its annotation system and fix the issue. You would have to fix the other two. I cannot fix all three of them myself, because finding a fix requires studying the annotation format and tools carefully (at leart, this was the case for COCO), and that takes time.

**Comment by hgaiser** [comment]
We have a small extract from the Pascal VOC dataset [here](https://github.com/fizyr/keras-retinanet-test-data). For OID and KITTI it will be guess work, but it should be simple since it basically means splitting up `load_image` into two functions, `image_path` and a modified version of `load_image` that uses `image_path`.

**Comment by hgaiser** [comment]
Fixed with https://github.com/fizyr/keras-retinanet/pull/1160
