### ISSUE TITLE
Tensorflow.Keras instead of Keras?

### ISSUE THREAD

**Issue by TimbusCalin** [fizyr/keras-retinanet#1117]
Hi, 

Since it is **recommended** that everyone uses **keras inside tensorflow**, I thought it would be a great idea to update the repository to tensorflow.keras instead of plain keras. 

The problem is that simply switching everything to tensorflow.keras instead of keras does not work. I do not have the necessary background knowledge in order to properly make the switch, is anybody(including the author) intending to switch to Tensorflow.Keras?

What I can confirm (if it helps anyone) up to this point, is that this repository (the training started working, I don't think there would be problems when converting from trainining_model to inference_model) with the following dependencies:

CUDA 10
CuDNN 7.6.3
Keras 2.2.5 (upgrading to 2.3.0 breaks the project)
TensorFlow 1.14.0 GPU

Thank you in advance.

**Comment by hgaiser** [comment]
We are internally working on this, but it is not yet finished (we have partly rewritten some code to be more modular). Additionally, we need to decide internally if it will be open source or not.

**Comment by Cospel** [comment]
Hi @hgaiser, do you have any news on this?

**Comment by hgaiser** [comment]
The decision is made, it will be open sourced, but the code is not yet complete. I suspect it will be open sourced before the end of the year.

**Comment by vcarpani** [comment]
Closing this issue

**Comment by sonfiree** [comment]
Is there any progress?

**Comment by hgaiser** [comment]
We are trying to dot the i's and train a network using the new code, which could take a while.

**Comment by alexattia** [comment]
Hello @hgaiser,
Do you have any news on this or any ETA? Congrats for your great work

**Comment by hgaiser** [comment]
It is released [here](https://github.com/fizyr/tf-retinanet), but some bugs on `tf`-side make it hard to use. Use at your own risk :)
