### ISSUE TITLE
Available inference models

### ISSUE THREAD

**Issue by spaul13** [fizyr/keras-retinanet#1121]
can anyone plz provide the link to already available inference models (keras) for resnet-50,101,152 trained on imagenet dataset?

**Comment by hgaiser** [comment]
https://github.com/fizyr/keras-models/releases

**Comment by spaul13** [comment]
@hgaiser  First of all thanks for the reply. I guess those are classification models those only provide the scores for 1000 classes as outputs and I am getting the following error
**_boxes, scores, labels = model.predict_on_batch(np.expand_dims(image, axis=0))
ValueError: not enough values to unpack (expected 3, got 1)_**

Is there any detection model from where I can get the bounding boxes also.

**Comment by hgaiser** [comment]
Imagenet is a classification dataset though, so I don't really understand what you're asking for then. We only provide one pretrained model trained on the coco dataset for object detection, which can be found in the reader.

**Comment by spaul13** [comment]
@hgaiser thanks for the reply. 
In the example script to detect objects inside an image 
https://github.com/fizyr/keras-retinanet/blob/master/examples/ResNet50RetinaNet.ipynb

**_boxes, scores, labels = model.predict_on_batch(np.expand_dims(image, axis=0))_** 

Its trying to get the boxes of the detected object from the image. What I am asking for how to get the boxes (or bounding boxes coordinates) using the model as the output?

For that do I need to train the model from scratch?

**Comment by hgaiser** [comment]
Check the readme, it explains that you can download a resnet50 model trained on Coco. That is the only model we provide.
________________________________

**Comment by spaul13** [comment]
Thanks a lot @hgaiser  its now working whatever I intended as there is only pretrained model resnet-50. Can u please do me another help telling is there any other open source for resnet-101 and 152 on coco dataset?

or I have to train my own network following the steps specified in README and then convert it to detection model?
https://github.com/fizyr/keras-retinanet#usage
