### ISSUE TITLE
ValueError: not enough values to unpack (expected 3, got 1) although using inference models

### ISSUE THREAD

**Issue by spaul13** [fizyr/keras-retinanet#1126]
I am using the already trained resnet-50 inference model from 
https://github.com/fizyr/keras-models/releases

But while using those models here for detecting the class of the object and bouding box, I am getting the following error

**_boxes, scores, labels = model.predict_on_batch(np.expand_dims(image, axis=0))
ValueError: not enough values to unpack (expected 3, got 1)_**

Can anyone please tell me how to get rid of the problem and get the bounding boxes of detected objects?

**Comment by phambao** [comment]
Hi @spaul13,
Have you converted model before predicting?

**Comment by hgaiser** [comment]
Please read the [README](https://github.com/fizyr/keras-retinanet/blob/master/README.md), you're using a classification model to do object detection.
