### ISSUE TITLE
Expected mAP results

### ISSUE THREAD

**Issue by VervenneThomas** [fizyr/keras-retinanet#1129]
I'm getting mAP values of below 1, which makes me think that my model is not performing very well. What is an expected mAP value for a well performing object detection model using ResNet50?

Thanks in advance!

**Comment by hgaiser** [comment]
1 is the maximum value, a value below 1 is perfectly normal.

**Comment by VervenneThomas** [comment]
So the mAP value is divided by 100?

**Comment by hgaiser** [comment]
mAP is generally scaled from 0-1: http://cocodataset.org/#detection-leaderboard

So it depends on your perspective to say if it is divided by 100. If you were expecting a score between 0-100, then yes.
