### ISSUE TITLE
mAp

### ISSUE THREAD

**Issue by zjp99** [fizyr/keras-retinanet#1135]
Running network: 100% (4974 of 4974) |##########################################################################| Elapsed Time: 1:04:38 Time:  1:04:38
Parsing annotations: 100% (4974 of 4974) |######################################################################| Elapsed Time: 0:00:00 Time:  0:00:00
331 instances of class aeroplane with average precision: 0.0780
417 instances of class bicycle with average precision: 0.0618
599 instances of class bird with average precision: 0.0564
398 instances of class boat with average precision: 0.0472
629 instances of class bottle with average precision: 0.0475
272 instances of class bus with average precision: 0.0697
1636 instances of class car with average precision: 0.2081
389 instances of class cat with average precision: 0.0177
1425 instances of class chair with average precision: 0.0484
356 instances of class cow with average precision: 0.1247
309 instances of class diningtable with average precision: 0.0008
536 instances of class dog with average precision: 0.0145
403 instances of class horse with average precision: 0.0259
390 instances of class motorbike with average precision: 0.0645
5392 instances of class person with average precision: 0.1191
620 instances of class pottedplant with average precision: 0.0835
353 instances of class sheep with average precision: 0.0459
419 instances of class sofa with average precision: 0.0038
328 instances of class train with average precision: 0.0210
366 instances of class tvmonitor with average precision: 0.2215
mAP using the weighted average of precisions among classes: 0.0936
mAP: 0.0680
-----------------------------------------------------
AP so low???????

**Comment by de-vri-es** [comment]
Sorry, we can't really do anything with this issue.
