### ISSUE TITLE
Out of memory with batch size greater than 1

### ISSUE THREAD

**Issue by yingzhec** [fizyr/keras-retinanet#1147]
I'm training the RetinaNet model on GTX 1070 which has 8GB memory. The batch size has to be set to 1 for avoiding resource exhausted. I'm wondering is there any way to reduce the memory occupied for training? Also, What's the exact size of model?

**Comment by hgaiser** [comment]
You could try prefixing your command with `TF_CUDNN_USE_AUTOTUNE`, this disables some mechanic of CUDNN which finds the most optimal conv layer for a given input, but it also requires an absurd amount of memory if you ask me. Regardless, I don't think you'll be able to use a batch size much larger than 2 given the default settings.
