### ISSUE TITLE
AttributeError: module 'tensorflow.compat' has no attribute 'v1'

### ISSUE THREAD

**Issue by 513221019** [fizyr/keras-retinanet#1149]
when I trained on only one image， something was wrong。
 
 return tensorflow.compat.v1.image.resize_images(images, size, methods[method], align_corners)

AttributeError: module 'tensorflow.compat' has no attribute 'v1'

who can help me ？ thanks

**Comment by de-vri-es** [comment]
Looks like adding compatibility with tensorflow 2 may have broken compatibility with tensorflow 1. Not sure if the intention is to stay compatible with tf1 for now. If so, we should probably check for the e old `tf1` function before trying `compat.v1` (or vice-versa).

@hgaiser, @vcarpani: is it the intention to still be compatible with tensorflow 1 for now?

**Comment by hgaiser** [comment]
I'm in favor of supporting tensorflow 1, but only 1.14 and 1.15 as they already have the same API as 2. Maybe it would be better to add a version check for tensorflow in `tensorflow_backend.py`, to ensure 1.14 or higher.
