### ISSUE TITLE
Did anyone do model compress about .h5 file?

### ISSUE THREAD

**Issue by xliu79** [fizyr/keras-retinanet#1150]
I already got an .h5 format file and the result is great. Right now I would like to compress the model because I need to run multiple model at the same time. But I have no clue about how to do it.
Could anyone give me some advice? I will be appreciate it.

**Comment by hgaiser** [comment]
I have no experience with compressing models so I can't help you there. However, as there is no issue here, I would like to close this. You could try asking your question on the Slack channel.
