### ISSUE TITLE
How can i train the model with P2 to P7?

### ISSUE THREAD

**Issue by McGaosai** [fizyr/keras-retinanet#1151]
I get P2 by upsampling from P3，and also change the anchors's size [32,64,128,256,512] to  [16,32,64,128,256,512] ,i change the code  in './models/retinanet.py'.but when i try to train the model,it did not work.so how can i train the model with P2 to P7?

**Comment by hgaiser** [comment]
It's likely that adding P2 will require an large amount of memory, the authors decided to ignore P2 for a reason. If you want to try to see if P2 fits in your memory then feel free to try, but I can't help.

I'm closing this as there is no direct issue with our code base. You could try discussing your case on the keras-retinanet Slack channel if you like.

**Comment by McGaosai** [comment]
> It's likely that adding P2 will require an large amount of memory, the authors decided to ignore P2 for a reason. If you want to try to see if P2 fits in your memory then feel free to try, but I can't help.
> 
> I'm closing this as there is no direct issue with our code base. You could try discussing your case on the keras-retinanet Slack channel if you like.

thank you very much,I have solved it.
