### ISSUE TITLE
Get the  Model history for analytical purposes

### ISSUE THREAD

**Issue by SalahAdDin** [fizyr/keras-retinanet#1154]
Hello,

I'm trying to get the training history log in order to plot him; i found a [tutorial](https://enmilocalfunciona.io/deep-learning-basico-con-keras-parte-4-resnet/) that show how we can do that using the model and its history attribute, but it does not work.

I load the model, and after i try to get the history from the model:
```model_path = os.path.join('/content/keras-retinanet/snapshots', sorted(os.listdir('/content/keras-retinanet/snapshots'), reverse=True)[0])
print(model_path)

# load retinanet model
model = models.load_model(model_path, backbone_name='resnet50')

model.history.keys()
```

But i got this bug:
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-44-f59c3018e123> in <module>()
----> 1 model.history.keys()

AttributeError: 'Model' object has no attribute 'history'
```

Why?

How can we plot the training results using this implementation?

Thanks.

**Comment by hgaiser** [comment]
My advice: use tensorboard if you want to plot training statistics. I don't know about the history attribute that you're looking for so I can't help you there.

Considering there is no issue here, I'm closing this.

**Comment by SalahAdDin** [comment]
@hgaiser, i think i cannot use tensorboard in Collab, also i tried but it requires install the latest Tensorflow version, isn't it?
