### ISSUE TITLE
Add more pre-trained models to releases

### ISSUE THREAD

**Issue by ZFTurbo** [fizyr/keras-retinanet#1161]
I recently trained several new model using Open Images Dataset. I propose to add them directly to releases section.

You can copy them from here:
https://github.com/ZFTurbo/Keras-RetinaNet-for-Open-Images-Challenge-2018/releases

## Pretrained models 2019

There are 3 RetinaNet models based on ResNet50, ResNet101 and ResNet152 for all [500 classes](https://github.com/ZFTurbo/Keras-RetinaNet-for-Open-Images-Challenge-2018/blob/master/a00_utils_and_constants.py#L130). 

| Backbone | Image Size (px) | Model (training) | Model (inference) | Small validation mAP | LB (Public) |
| --- | --- | --- | --- | --- |  --- |
| ResNet50 | 768 - 1024 | [534 MB](https://github.com/ZFTurbo/Keras-RetinaNet-for-Open-Images-Challenge-2018/releases/download/v1.3/retinanet_resnet50_500_classes_0.4594.h5) | [178 MB](https://github.com/ZFTurbo/Keras-RetinaNet-for-Open-Images-Challenge-2018/releases/download/v1.3/retinanet_resnet50_500_classes_0.4594_converted.h5) | 0.4594 | 0.4223 |
| ResNet101 | 768 - 1024 | [752 MB](https://github.com/ZFTurbo/Keras-RetinaNet-for-Open-Images-Challenge-2018/releases/download/v1.3/retinanet_resnet101_500_classes_0.4986.h5) | [251 MB](https://github.com/ZFTurbo/Keras-RetinaNet-for-Open-Images-Challenge-2018/releases/download/v1.3/retinanet_resnet101_500_classes_0.4986_converted.h5) | 0.4986 | 0.4520 |
| ResNet152 | 600 - 800 | [932 MB](https://github.com/ZFTurbo/Keras-RetinaNet-for-Open-Images-Challenge-2018/releases/download/v1.3/retinanet_resnet152_500_classes_0.4991.h5) | [312 MB](https://github.com/ZFTurbo/Keras-RetinaNet-for-Open-Images-Challenge-2018/releases/download/v1.3/retinanet_resnet152_500_classes_0.4991_converted.h5) | 0.4991 | 0.4651 |

**Comment by hgaiser** [comment]
I made a PR to incorporate the models in the README (https://github.com/fizyr/keras-retinanet/pull/1166). Thanks for the contribution!
