### ISSUE TITLE
TypeError: ('Keyword argument not understood:', 'freeze')

### ISSUE THREAD

**Issue by AldusLorde** [fizyr/keras-retinanet#1170]
Hi) I tried to estimate GPU requirements for a model, so I decided to lunch several predictions at the same time using ProcessPoolExecutor and Manager classes. Unfortunately, I got this error.
![Screenshot from 2019-11-05 19-20-55](https://user-images.githubusercontent.com/34024120/68230289-6bb1c080-0001-11ea-9427-c0452f49e418.png)

**Comment by jubick1337** [comment]
can you show command that you run?

**Comment by hgaiser** [comment]
You need to load your model with the correct set of custom objects (see [here](https://github.com/fizyr/keras-retinanet/blob/master/keras_retinanet/models/__init__.py#L87) for how we do it).

**Comment by zhangwei147258** [comment]
I also get the same problem when i use the function 
'from keras_retinanet import models
model = models.load_model(model_path, backbone_name='resnet18')'.

In fact,  in keras_resnet\layers\_batch_normalization.py :
class BatchNormalization(keras.layers.BatchNormalization):
    """
    Identical to keras.layers.BatchNormalization, but adds the option to freeze parameters.
    """
    def __init__(self, freeze, *args, **kwargs):
        self.freeze = freeze
        super(BatchNormalization, self).__init__(*args, **kwargs)

        # set to non-trainable if freeze is true
        self.trainable = not self.freeze

    def call(self, *args, **kwargs):
        # Force test mode if frozen, otherwise use default behaviour (i.e., training=None).
        if self.freeze:
            kwargs['training'] = False
        return super(BatchNormalization, self).call(*args, **kwargs)

    def get_config(self):
        config = super(BatchNormalization, self).get_config()
        config.update({'freeze': self.freeze})
        return config

Here is my library version：
tensorboard 1.14.0
Keras 2.3.1
keras-resnet 0.1.0
numpy 1.16.0
opencv-python 4.1.1.26

**Comment by hgaiser** [comment]
Could you try logging what the value of `custom_objects` is [here](https://github.com/fizyr/keras-retinanet/blob/master/keras_retinanet/models/__init__.py#L87)?

**Comment by sumannelli** [comment]
HI, I am also getting same error in with tesnorflow2 . I tried all the solutions mentioned above but unable to fix it

**Comment by jackie-angelswing** [comment]
Has someone figured out a solution?

**Comment by Mazenode** [comment]
Still an issue to this date, did anyone figured it out ?
