### ISSUE TITLE
AttributeError: module 'tensorflow' has no attribute 'ConfigProto'

### ISSUE THREAD

**Issue by ouening** [fizyr/keras-retinanet#1171]
OS: Ubuntu18.04
tensorflow: 2.0
keras: 2.3.1
cuda: 10.1
cudnn: 7.6

When I run trian.py using tensorflow2.0, I got error below:
<pre>Traceback (most recent call last):
  File &quot;train.py&quot;, line 514, in &lt;module&gt;
    main()
  File &quot;train.py&quot;, line 437, in main
    keras.backend.tensorflow_backend.set_session(get_session())
  File &quot;train.py&quot;, line 66, in get_session
    config = tf.ConfigProto()
AttributeError: module &apos;tensorflow&apos; has no attribute &apos;ConfigProto&apos;
</pre>

Hope for support for tensorflow 2.0!

**Comment by vcarpani** [comment]
In this moment the only solution is to install keras from our fork:
https://github.com/fizyr-forks/keras/tree/2.3.1.fizyr2
And run retinanet in this branch:
https://github.com/fizyr/keras-retinanet/tree/disable-tf2-behavior

We submitted a PR to keras for fixing this problem and we are working to port this repo to tf.keras

**Comment by CatLoves** [comment]
Reason for this bug:
Edit the keras-Retinanet\keras_retinanet\utils\gpu.py ,  find the the following line :
`if tf_version_ok((2, 0, 0)):`

this line doesn't work !!!

change to something else, for example:
`if True:`

**Comment by sudoandros** [comment]
Hi
@vcarpani was there any progress since? I am trying to use keras-retinanet 0.5.1 release and facing the same issue.
OS: Windows 10
tensorflow: 2.3.0
keras: 2.4.3
CUDA: 10.1
cuDNN: 7.6.5

Seems like current state of the master branch doesn't have it, but I'm not sure if it's stable enough to use in production environment
