### ISSUE TITLE
UserWarning:Skipping loading of weights for layer classification_submodel

### ISSUE THREAD

**Issue by wendaomu** [fizyr/keras-retinanet#1173]
I want to train a binay classification model, and I use the resnet101_oid_v1.0.0.h5 weights. However I encounter the following  warning.

**UserWarning:Skipping loading of weights for layer classification_submodel due to mismatch in shape ((3,3,256,9)) vs (4500,256,3,3)**

**Comment by hgaiser** [comment]
That's okay, the warning means that part of the loaded weights did not match with the created model. It most likely means that the number of classes for your weights and the number of classes you are trying to train are different. All the weights will be loaded, except for the ones determining the class.

**Comment by wendaomu** [comment]
> That's okay, the warning means that part of the loaded weights did not match with the created model. It most likely means that the number of classes for your weights and the number of classes you are trying to train are different. All the weights will be loaded, except for the ones determining the class.

Thanks!
