### ISSUE TITLE
Resnet101 working on one specific dataset only

### ISSUE THREAD

**Issue by MoizTaimuri** [fizyr/keras-retinanet#1176]
It works with only one specific dataset with all the images of equal size. 
If I use different size images it gives this error: tensorflow.python.framework.errors_impl.InvalidArgumentError: Inputs to operation loss/classification_loss/Select_1 of type Select must have the same size and shape.  Input 0: [13869,1] != input 1: [13869,3]
	 [[{{node loss/classification_loss/Select_1}}]]

Can you help me with this?

**Comment by hgaiser** [comment]
What dataset type are you using? How many classes? Does ResNet50 work?

**Comment by MoizTaimuri** [comment]
There are 4 classes but they can be more or less. I didn't check for resnet50 . 
What do you mean by dataset type?

**Comment by hgaiser** [comment]
I mean are you using a CSV dataset, COCO, Pascal, OID?

**Comment by MoizTaimuri** [comment]
Dataset is in Pascal format but Pascal generator was not working so I transformed data to use csv dataset format

**Comment by hgaiser** [comment]
It is working now ?

**Comment by MoizTaimuri** [comment]
Yes it is working but with only one dataset , bloodcell dataset; if you have seen that data set. 
But if I use my custom dataset it gives me above mentioned error

**Comment by hgaiser** [comment]
It sounds like you are creating a model with 2 classes, but your dataset is configured to only have 1 class?

**Comment by MoizTaimuri** [comment]
But I do give it number of classes for the dataset. I store it in a dictionary for later use. 
What would you suggest what should I do for it ?

**Comment by hgaiser** [comment]
> But I do give it number of classes for the dataset. I store it in a dictionary for later use.

I don't understand what you mean? You have converted your dataset to CSV, so you should have a `classes.csv` file? What is the content of that file, and how did you create a model? Are you using the standard training script? Can you share a single image of your dataset, its annotations and the `classes.csv`?

**Comment by MoizTaimuri** [comment]
No I did not create CSV files. I created xml files for annotations and as in the script it was creating dictionary and list for the dataset from CSV files so I changed that script and used xml files directly for the creation of those list and dictionaries.

I did used the CSV generator script for the creation of data for training. But I'm not creating it through CSV files. 

Am I clear now?

**Comment by MoizTaimuri** [comment]
![image](https://user-images.githubusercontent.com/56476724/68754992-1cbee900-0608-11ea-90fe-29b130e75631.png)

**Comment by MoizTaimuri** [comment]
@hgaiser  The above picture is a file for annotations. 
https://github.com/Shenggan/BCCD_Dataset
If I use this dataset and all the annotations from this it works fine, but when I use a custom dataset with the same structure it does not work.

**Comment by hgaiser** [comment]
Can you provide a minimum example dataset and command where it breaks for you?

**Comment by MoizTaimuri** [comment]
**model_retinanet.fit_generator(
            generator=train_generator,
            steps_per_epoch=800,
            validation_data=validation_generator,
            validation_steps=800,
            epochs=50,
            verbose=1,
            callbacks=[ModelCheckpoint(filepath=model_output + 'saved_model.h5', save_best_only=True)]
        )**

It breaks at the end of this line with this error.

**tensorflow.python.framework.errors_impl.InvalidArgumentError: Inputs to operation loss/classification_loss/Select_1 of type Select must have the same size and shape. Input 0: [13869,1] != input 1: [13869,3]
[[{{node loss/classification_loss/Select_1}}]]**

What do you mean by the minimum dataset?

**Comment by hgaiser** [comment]
I mean a dataset of hopefully just one image and its annotations that gives you this error.

**Comment by MoizTaimuri** [comment]
[Dataset.zip](https://github.com/fizyr/keras-retinanet/files/3842210/Dataset.zip)

It contains an image, annotated file and a txt file (for dividing dataset into 80.20)

**Comment by MoizTaimuri** [comment]
Then I changed the CSV generator script to read these files and to store everything into a dictionary

**Comment by hgaiser** [comment]
And the command you used to run your training?

**Comment by MoizTaimuri** [comment]
I'm not using any command I'm directly using the code and to start training I use this model_retinanet.fit_generator(
generator=train_generator,
steps_per_epoch=800,
validation_data=validation_generator,
validation_steps=800,
epochs=50,
verbose=1,
callbacks=[ModelCheckpoint(filepath=model_output + 'saved_model.h5', save_best_only=True)]
)

**Comment by hgaiser** [comment]
Ah, I see. Did you try with the provided train script? Also, how did you create your `model_retinanet` object?

**Comment by MoizTaimuri** [comment]
I used the provided script in the description for the creation of model.
Yes also tried the train script

**Comment by MoizTaimuri** [comment]
model_retinanet = models.backbone('resnet101').retinanet(num_classes=1) that's the script for creation

**Comment by hgaiser** [comment]
And how did you create your generator? I just tried training on your data using the provided `train.py` and it was working correctly.

**Comment by MoizTaimuri** [comment]
I created like this.
 Csvgenerator { 
Datafile,
Classfile,
Imagedatagenerator,
Batchsize}

**Comment by MoizTaimuri** [comment]
I think there is an issue with generator . Because if I use Pascal generator it gives error in aanchors or image.py

**Comment by hgaiser** [comment]
Oh I thought you were making using the Pascal format because you send it in Pascal format. Two questions:

1. For the Pascal generator, how do you create it?
2. For the CSV generator, what is the content of Classfile?

**Comment by MoizTaimuri** [comment]
The thing is , I used Pascal format data and created a dictionary out of the whole data and passed it into the csvgenerator, where I changed the script. Rather then reading the csvfile o made changes so that it can take directly dictionary and read the content from dictionary. 

The content of classfile is basically it's a dictionary which I'm passing it into the csvgenerator.

When I tried to yes Pascal generator, I used 
Pascal generator{
Foldername,
Filename,
Batchsize}
And it gives me error at a particular point and says data generator is not iterable.

Can you tell me which generator script you used for Pascal data set and which anchors script also?

**Comment by hgaiser** [comment]
I have the feeling you made a lot of changes or custom scripts that I am not aware of so I find it difficult to help you. 

I run the following command:
```shell
python keras_retinanet/bin/train.py pascal ~/2019-11-13-18-06-49/Dataset
```

And restructured the data you provided a bit to be of this form:
![Screenshot from 2019-11-14 11-24-52](https://user-images.githubusercontent.com/716138/68849103-c4ecb480-06d1-11ea-8728-fef141099243.png)

And made the following changes to `train.py`:
![Screenshot from 2019-11-14 11-27-01](https://user-images.githubusercontent.com/716138/68849130-ccac5900-06d1-11ea-9d1d-335bf0dd6562.png)

Also, I noticed that your bounding box from the annotation is incorrect. It is defined as:
```
    <bndbox>
        <xmin>395</xmin>
        <ymin>349</ymin>
        <xmax>454</xmax>
        <ymax>293</ymax>
    </bndbox>
```
As you see, `ymin` is equal to `349` and `ymax` is equal to `293`, that is not correct. The `PascalGenerator` prints a warning about this (`UserWarning: Image with id 0 (shape (480, 640, 3)) contains the following invalid boxes: [[394. 348. 453. 292.]].`) and continues without this annotation, so the image is treated as an image without any annotations.

**Comment by MoizTaimuri** [comment]
Okay so if have to use the Pascal generator with the same data format but without using the command line thing. Directly from the code, how should I do that and should I take the updated code ?
And for the annotations x,y min must be less then max right always? That would be a problem in my augmentation then.

**Comment by hgaiser** [comment]
Personally I would convert to CSV data format since it is more flexible and better implemented. And yes the min x,y values must always be lower than the max x,y values. You can use [imgaug](https://github.com/aleju/imgaug) for your data augmentation.

**Comment by MoizTaimuri** [comment]
But I already have the data in Pascal format , and I don't have enough time now to implement the whole conversion of data . So I will try to use Pascal data format with the implementation in train.py and let you know if there is any problem init now or not.

Thankyou so much for your help.

**Comment by MoizTaimuri** [comment]
I can also use it as a code right, rather then using through the command line?

**Comment by MoizTaimuri** [comment]
Training works thanks for the help.
But I have a question on how to convert this training model into an inference model?

**Comment by hgaiser** [comment]
Use the convert script for it :) check with the flag `--help` to see which arguments can be set.
