### ISSUE TITLE
GPU is not used when validating 

### ISSUE THREAD

**Issue by wendaomu** [fizyr/keras-retinanet#1177]
I set the args.gpu='0,1', and args.multi_gpu = 2.
when the model was trained, I found my two gpus work.  However,when the model validated the dataset, my two gpus didn't work. 
![image](https://user-images.githubusercontent.com/26783490/68539386-e2620b80-03bd-11ea-9d2c-39c93aa0e210.png)

**Comment by hgaiser** [comment]
Duplicate issue https://github.com/fizyr/keras-retinanet/issues/521
