### ISSUE TITLE
Any idea abot small object detection?

### ISSUE THREAD

**Issue by xliu79** [fizyr/keras-retinanet#1179]
Recently I am doing a project about small object detection but the result is not good enough. I already used imgaug tools to increase my image sets. Did anyone have idea about how to improve the accuracy???

**Comment by hgaiser** [comment]
You can try to use the debug tool to visualize the coverage of your objects by the anchors and you can try [this](https://github.com/fizyr/keras-retinanet#anchor-optimization) to change them to be better suited for your data.

**Comment by xliu79** [comment]
Thanks for the reply. I will give it a shot.
