### ISSUE TITLE
ipynb for pascal voc data is removed

### ISSUE THREAD

**Issue by SepidehAlassi** [fizyr/keras-retinanet#118]
Hi, 

in one of last commits you have removed ipynb of training with pascal voc data, can you please add it again?

**Comment by de-vri-es** [comment]
This was commit e1dcb18b649ca1ce8c8db9939459e178d71d868d. I'm not sure why it was removed. @hgaiser can probably shed some light on this.

**Comment by de-vri-es** [comment]
You can find the old version here: https://raw.githubusercontent.com/fizyr/keras-retinanet/c6eb5a1cb7048f3f279a001d58220555c03692dd/examples/ResNet50RetinaNet%20-%20Pascal%20VOC.ipynb
