### ISSUE TITLE
Hang when train with OID (open images dataset) 

### ISSUE THREAD

**Issue by ducmanhnguyen** [fizyr/keras-retinanet#1181]
I pull latest keras-retinanet version and start to train with OID by the basic instruction in README. the train start and hang at the printout "Epoch 1/50" and hang there for a day already. I try repeat many time but it still the same. anyone have any idea? I use single GPU for train.
![oid](https://user-images.githubusercontent.com/11374225/68676250-e62a9500-0559-11ea-941c-cf3ef6528c56.PNG)

**Comment by hgaiser** [comment]
OID data generator is a community contribution, so I don't know about it hanging. I would ask you to try `debug.py` to visualize the data to see if accessing it works fine, but `debug.py` doesn't seem to have support for OID generators at the moment. Could you look into adding that to `debug.py`, which would help you in testing the OID data generator? A PR for this would be welcome as well :)

**Comment by ducmanhnguyen** [comment]
I tried to convert OID to COCO format, but it still not work. I guess for COCO data, we have some hardcode/pre-define stuff for specific COCO data, that why COCO likes data is not work

**Comment by hgaiser** [comment]
Could you try my previous suggestion?
