### ISSUE TITLE
Cant import compute_overlap

### ISSUE THREAD

**Issue by bfialkoff** [fizyr/keras-retinanet#1182]
I cloned the repository again, the last version I worked with was 0.5.0 and although I have run `python setup.py build_ext --inplace` I am still getting `ModuleNotFoundError: No module named 'keras_retinanet.utils.compute_overlap'`. Not sure what else to try...

**Comment by hgaiser** [comment]
Can you show the output of `python setup.py build_ext --inplace`?

**Comment by bfialkoff** [comment]
(Desktop) cougar@cougar:~/Desktop/keras-retinanet-master$ python setup.py build_ext --inplace
running build_ext
cythoning keras_retinanet/utils/compute_overlap.pyx to keras_retinanet/utils/compute_overlap.c
/home/cougar/Desktop/keras-retinanet-master/.eggs/Cython-0.29.14-py3.6-linux-x86_64.egg/Cython/Compiler/Main.py:369: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: /home/cougar/Desktop/keras-retinanet-master/keras_retinanet/utils/compute_overlap.pyx
  tree = Parsing.p_module(s, pxd, full_module_name)
building 'keras_retinanet.utils.compute_overlap' extension
creating build
creating build/temp.linux-x86_64-3.6
creating build/temp.linux-x86_64-3.6/keras_retinanet
creating build/temp.linux-x86_64-3.6/keras_retinanet/utils
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.6m -I/home/cougar/.local/share/virtualenvs/Desktop-QXx28ukp/include/python3.6m -I/home/cougar/.local/share/virtualenvs/Desktop-QXx28ukp/lib/python3.6/site-packages/numpy/core/include -c keras_retinanet/utils/compute_overlap.c -o build/temp.linux-x86_64-3.6/keras_retinanet/utils/compute_overlap.o
In file included from /home/cougar/.local/share/virtualenvs/Desktop-QXx28ukp/lib/python3.6/site-packages/numpy/core/include/numpy/ndarraytypes.h:1830:0,
                 from /home/cougar/.local/share/virtualenvs/Desktop-QXx28ukp/lib/python3.6/site-packages/numpy/core/include/numpy/ndarrayobject.h:12,
                 from /home/cougar/.local/share/virtualenvs/Desktop-QXx28ukp/lib/python3.6/site-packages/numpy/core/include/numpy/arrayobject.h:4,
                 from keras_retinanet/utils/compute_overlap.c:598:
/home/cougar/.local/share/virtualenvs/Desktop-QXx28ukp/lib/python3.6/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:17:2: warning: #warning "Using deprecated NumPy API, disable it with " "#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
 #warning "Using deprecated NumPy API, disable it with " \
  ^~~~~~~
creating build/lib.linux-x86_64-3.6
creating build/lib.linux-x86_64-3.6/keras_retinanet
creating build/lib.linux-x86_64-3.6/keras_retinanet/utils
x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-Bsymbolic-functions -Wl,-z,relro -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 build/temp.linux-x86_64-3.6/keras_retinanet/utils/compute_overlap.o -o build/lib.linux-x86_64-3.6/keras_retinanet/utils/compute_overlap.cpython-36m-x86_64-linux-gnu.so
copying build/lib.linux-x86_64-3.6/keras_retinanet/utils/compute_overlap.cpython-36m-x86_64-linux-gnu.so -> keras_retinanet/utils

**Comment by hgaiser** [comment]
Hmm that seems fine. Can you also show what you try to run and the output?

**Comment by bfialkoff** [comment]
the issue magically disappeared :roll_eyes:
