### ISSUE TITLE
Long Training Time

### ISSUE THREAD

**Issue by hasan-mh-aziz** [fizyr/keras-retinanet#1188]
When I am trying to train the model on the COCO dataset using default parameters except for the batch size, which is two in my case, the estimated time its showing is more than two days. Is it normal? Even with batch size 1 (default value), it does not improve. Moreover, I have minimal experience in Deep Learning. I am providing two screenshots regarding GPU information and training.
![Annotation 2019-11-21 223138](https://user-images.githubusercontent.com/15884322/69398208-d8d67e80-0cae-11ea-8ea3-d18fc5f38b75.png)
![Annotation 2019-11-21 223438](https://user-images.githubusercontent.com/15884322/69398247-10452b00-0caf-11ea-84f2-564631910447.png)

I am using only one GPU. Can anyone please clear things for me?

**Comment by hgaiser** [comment]
Hmm where do you see an estimated time of more than two days? At the bottom of your first screenshot I see an ETA of 1 hour and 10 minutes?

**Comment by hasan-mh-aziz** [comment]
Ah, That's for the first epoch. To complete all the epoch, it took two days.

**Comment by Wemmy** [comment]
Yes, i have the same issue. I'm using GeForce RTX 2080 ti.

**Comment by gash1654** [comment]
do you using python 3?

**Comment by hasan-mh-aziz** [comment]
Yes, I am using 3.7.4.  The version of TensorFlow is 2.0.0, and Keras is 2.3.1. It's also using CUDA10.0.

**Comment by hgaiser** [comment]
A processing time of more than an hour per 10k steps seems normal, so two days for 50 epochs seems normal too.

**Comment by hasan-mh-aziz** [comment]
If that is the case, then I am closing this issue. Thank you for the confirmation.

**Comment by Dongjiuqing** [comment]
I have a question, the version of tensorflow-gpu must be 2.0.0?  And the version of CUDA must be 10.* ? Now, I can not use my GPU and I don't know why, I think maybe the CUDA version is wrong.  I use this command pip install  cudatoolkit=10.1but it didn't work.

**Comment by hgaiser** [comment]
I don't think you can install cuda using pip.

**Comment by Dongjiuqing** [comment]
so how should I install tensorflow-gpu？what about the version？



发自我的iPhone


------------------ Original ------------------
