### ISSUE TITLE
KeyError when i try to evaluate on CSV Dataset

### ISSUE THREAD

**Issue by iskorini** [fizyr/keras-retinanet#1189]
Hi! I'm having some problem when I try to evaluate on custom CSV dataset with pretrained COCO weights.

I get the following exception:
```
[-143.67514, -287.35028,  143.67514,  287.35028]], dtype=float32)> anchors
tracking <tf.Variable 'Variable:0' shape=(9, 4) dtype=float32, numpy=
array([[-362.03867, -181.01933,  362.03867,  181.01933],
       [-456.14017, -228.07008,  456.14017,  228.07008],
       [-574.70056, -287.35028,  574.70056,  287.35028],
       [-256.     , -256.     ,  256.     ,  256.     ],
       [-322.5398 , -322.5398 ,  322.5398 ,  322.5398 ],
       [-406.37466, -406.37466,  406.37466,  406.37466],
       [-181.01933, -362.03867,  181.01933,  362.03867],
       [-228.07008, -456.14017,  228.07008,  456.14017],
       [-287.35028, -574.70056,  287.35028,  574.70056]], dtype=float32)> anchors
/data/students_home/USER/.local/lib/python3.7/site-packages/keras/engine/saving.py:341: UserWarning: No training configuration found in save file: the model was *not* compiled. Compile it manually.
  warnings.warn('No training configuration found in save file: '
Running network: N/A% (0 of 27981) |                                                                                                       | Elapsed Time: 0:00:00 ETA:  --:--:--2019-11-25 11:16:38.264856: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
Traceback (most recent call last):
  File "/data/students_home/USER/.local/bin/retinanet-evaluate", line 10, in <module>
    sys.exit(main())
  File "/data/students_home/USER/.local/lib/python3.7/site-packages/keras_retinanet/bin/evaluate.py", line 161, in main
    save_path=args.save_path
  File "/data/students_home/USER/.local/lib/python3.7/site-packages/keras_retinanet/utils/eval.py", line 174, in evaluate
    all_detections     = _get_detections(generator, model, score_threshold=score_threshold, max_detections=max_detections, save_path=save_path)
  File "/data/students_home/USER/.local/lib/python3.7/site-packages/keras_retinanet/utils/eval.py", line 108, in _get_detections
    draw_detections(raw_image, image_boxes, image_scores, image_labels, label_to_name=generator.label_to_name, score_threshold=score_threshold)
  File "/data/students_home/USER/.local/lib/python3.7/site-packages/keras_retinanet/utils/visualization.py", line 81, in draw_detections
    caption = (label_to_name(labels[i]) if label_to_name else labels[i]) + ': {0:.2f}'.format(scores[i])
  File "/data/students_home/USER/.local/lib/python3.7/site-packages/keras_retinanet/preprocessing/csv_generator.py", line 191, in label_to_name
    return self.labels[label]
KeyError: 2
```

This is the command that I used:
`retinanet-evaluate --gpu 1  --score-threshold 0.30 --save-path ./evaluate csv KAIST_MPD/imageSets/csv_files_NO_PEOPLE/visible/test-day-01.csv KAIST_MPD/class_name_to_id_NO_PEOPLE_test.csv /data/students_home/USER/thesis/keras-retinanet/snapshots/resnet50_coco_best_v2.1.0.h5`

And this is the csv file contains classes:
`
person,0
cyclist,1
`

**Comment by hgaiser** [comment]
What version of keras-retinanet are you using? I don't see the code reported on the lines from the exception traceback.

**Comment by iskorini** [comment]
> What version of keras-retinanet are you using? I don't see the code reported on the lines from the exception traceback.

I use this version of _eval.py_. I've modified to make it work like _debug.py_ for saving images. 
https://github.com/iskorini/keras-retinanet/blob/master/keras_retinanet/utils/eval.py

**Comment by hgaiser** [comment]
Hmm that's strange then, it seems fine what you're doing. Could you debug the issue by printing the value of `self.labels` and `label` in `"/data/students_home/USER/.local/lib/python3.7/site-packages/keras_retinanet/preprocessing/csv_generator.py", line 191`?

**Comment by iskorini** [comment]
> Hmm that's strange then, it seems fine what you're doing. Could you debug the issue by printing the value of `self.labels` and `label` in `"/data/students_home/USER/.local/lib/python3.7/site-packages/keras_retinanet/preprocessing/csv_generator.py", line 191`?
```
Running network: N/A% (0 of 27981) |                                                                                                       | Elapsed Time: 0:00:00 ETA:  --:--:--2019-11-25 23:42:58.918215: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
label: 0.0
self.labels: {0: 'person', 1: 'cyclist'}
label: 2
self.labels: {0: 'person', 1: 'cyclist'}
Traceback (most recent call last):
  File "/data/students_home/USER/.local/bin/retinanet-evaluate", line 10, in <module>
    sys.exit(main())
  File "/data/students_home/USER/.local/lib/python3.7/site-packages/keras_retinanet/bin/evaluate.py", line 161, in main
    save_path=args.save_path
  File "/data/students_home/USER/.local/lib/python3.7/site-packages/keras_retinanet/utils/eval.py", line 174, in evaluate
    all_detections     = _get_detections(generator, model, score_threshold=score_threshold, max_detections=max_detections, save_path=save_path)
  File "/data/students_home/USER/.local/lib/python3.7/site-packages/keras_retinanet/utils/eval.py", line 108, in _get_detections
    draw_detections(raw_image, image_boxes, image_scores, image_labels, label_to_name=generator.label_to_name, score_threshold=score_threshold)
  File "/data/students_home/USER/.local/lib/python3.7/site-packages/keras_retinanet/utils/visualization.py", line 81, in draw_detections
    caption = (label_to_name(labels[i]) if label_to_name else labels[i]) + ': {0:.2f}'.format(scores[i])
  File "/data/students_home/USER/.local/lib/python3.7/site-packages/keras_retinanet/preprocessing/csv_generator.py", line 193, in label_to_name
    return self.labels[label]
KeyError: 2
```
Uhm, it's weird...

**Comment by iskorini** [comment]
I tried to use an _original_ version of RetinaNet, but the exception remains :'(

**Comment by hgaiser** [comment]
Are you sure you're not mixing up models trained on a different dataset? The model you're testing seems to be trained with 3 classes, but the generator you're using to test with only has 2 classes.

**Comment by iskorini** [comment]
So I'm not sure I understood how it works when a trained model has more class than thoose present in test phase.
I've used a pretrained model that I found here https://github.com/fizyr/keras-retinanet/releases. 
_Classes.csv_ file contains only two classes: people (0) and cyclist (1). 
Is it my mistake?

**Comment by hgaiser** [comment]
That model is trained with 80 classes and it will try to evaluate all the 80 classes, so that would explain the error you're seeing. You would need to write a custom evaluation function if you wish to only evaluate people and cyclist, or train a network only on people and cyclist.

**Comment by MaddyThakker** [comment]
Hi, I am facing the same issue as @iskorini. Is there a mapping available for the 80 classes that the pre-trained model is trained on so I can eliminate the classes?

**Comment by hgaiser** [comment]
> Hi, I am facing the same issue as @iskorini. Is there a mapping available for the 80 classes that the pre-trained model is trained on so I can eliminate the classes?

What kind of mapping do you mean? The 80 values to ... ?
