### ISSUE TITLE
TensorFlow tensor dimension error during training

### ISSUE THREAD

**Issue by snamjoshi** [fizyr/keras-retinanet#1190]
I am running `keras-retinanet` on Docker. I have wrapped the train/evaluate files of `keras-retinanet` into a single file called `wrapper.py` in a single class and removed the CLI interface which you will notice in the stack trace (almost nothing else has been altered). I realize that I have modified `keras-retinanet` core code... but if you've seen something like this before and wouldn't mind nudging me in the right direction I'd appreciate it!

I am using `tensorflow-gpu 2.0.0` and `Keras 2.3.1`. I can give versions of other installs if needed.

I am successfully able to run this wrap in a Docker image but it seems perhaps something has changed with this new Docker image I've pulled. I have no control over this particular Docker setup unfortunately and it has to run successfully on this image for me to proceed. It makes me think that package version or drivers might be causing this problem. 

When training begins I get this error:

```
ERROR:redirect:/usr/local/lib/python3.6/dist-packages/keras/utils/data_utils.py:616: UserWarning: The input 93 could not be retrieved. It could be because a worker has died.
ERROR:redirect:  UserWarning)
2019-11-25 15:24:35.894001: W tensorflow/core/framework/op_kernel.cc:1622] OP_REQUIRES failed at strided_slice_op.cc:108 : Invalid argument: Index out of range using input dim 0; input has only 0 dims
2019-11-25 15:24:35.894001: W tensorflow/core/framework/op_kernel.cc:1622] OP_REQUIRES failed at strided_slice_op.cc:108 : Invalid argument: Index out of range using input dim 0; input has only 0 dims
2019-11-25 15:24:35.894001: W tensorflow/core/framework/op_kernel.cc:1622] OP_REQUIRES failed at strided_slice_op.cc:108 : Invalid argument: Index out of range using input dim 0; input has only 0 dims
2019-11-25 15:24:35.894001: W tensorflow/core/framework/op_kernel.cc:1622] OP_REQUIRES failed at strided_slice_op.cc:108 : Invalid argument: Index out of range using input dim 0; input has only 0 dims
```

This then leads to further errors:

```
File "/src/objectdetectiond3mwrapper/objectDetectionD3MWrapper/wrapper.py", line 393, in fit
    max_queue_size = self.max_queue_size
  File "/usr/local/lib/python3.6/dist-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/keras/engine/training.py", line 1732, in fit_generator
    initial_epoch=initial_epoch)
  File "/usr/local/lib/python3.6/dist-packages/keras/engine/training_generator.py", line 220, in fit_generator
    reset_metrics=False)
  File "/usr/local/lib/python3.6/dist-packages/keras/engine/training.py", line 1514, in train_on_batch
    outputs = self.train_function(ins)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/backend.py", line 3580, in __call__
    run_metadata=self.run_metadata)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/client/session.py", line 1472, in __call__
    run_metadata_ptr)
tensorflow.python.framework.errors_impl.InvalidArgumentError: 2 root error(s) found.
  (0) Invalid argument: The first dimension of paddings must be the rank of inputs[4,2] []
         [[{{node padding_conv1/Pad}}]]
         [[loss/Identity_1/_1947]]
  (1) Invalid argument: The first dimension of paddings must be the rank of inputs[4,2] []
         [[{{node padding_conv1/Pad}}]]
0 successful operations.
0 derived errors ignored.
```

I haven't modified the call to `fit_generator()` and `max_queue_size = 10`.

Have you seen this error before? I have not modified the loss function, anything in the `retinanet.py` files, or `generator.py` so it is unclear to me why this error would suddenly come up.

**Comment by deg4uss3r** [comment]
Also seeing an issue similar to this, well their first error: 

`keras/utils/data_utils.py:616: UserWarning: The input 260 could not be retrieved. It could be because a worker has died`

Here is my call line: 
`retinanet-train --multiprocessing --workers 24 --weighted-average --multi-gpu 8 --multi-gpu-force --epochs 100 --steps 1000 --lr .01 --tensorboard-dir ./retinanet_test/ --batch-size 8 --weights ./resnet50_coco_best_v2.1.0.h5 csv /path/to/train.csv`

I have *a lot* of data I'm trying to train on and I'm wondering if it is because of that...

**Comment by hgaiser** [comment]
I haven't seen this error before no, but I am curious to hear what the issue was if you find a fix for it.

**Comment by deg4uss3r** [comment]
For me this appears to have been related to overloading the GPU memory via image size. I chipped the images and used a GPU with more available memory and doesn't seem to error out.

**Comment by hgaiser** [comment]
Alright, thanks for the feedback. Can we close this issue then?

**Comment by deg4uss3r** [comment]
@snamjoshi Did you find a away around the error yourself too? Try smaller images/batch size.

**Comment by snamjoshi** [comment]
@deg4uss3r I'm still looking into it with no luck so far. I thought it might have to do with image corruption but that was not the case. I have tried varying images/batch size and this made no difference. I'm running it on a reasonably beefy Amazon instance and there are not that many images so I don't think that is the problem.

However, I think it might have something to do with TF2 compatibility. I thought RetinaNet was compatible with TF2 but, unless I'm mistaken, this is still a work in progress. Unfortunately, the Docker image I have to use for this is locked in at TF2 so I have to deal with it. I tried messing with the imports and changing it to import `tensorflow.keras` rather than `keras`, much like [#1117](https://github.com/fizyr/keras-retinanet/issues/1117) and this turned out to be somewhat tricky.

I'll update when I have more information, it's basically going to be my whole day today...

**Comment by deg4uss3r** [comment]
@snamjoshi I am using TF2 on my instance and it is working fine with Keras `2.3.1`. I am not running mine in a docker or AWS, but it took a Tesla K80 (11GB of ram) to load 256x256 images which I had to chip from 1024x1024. Just an FYI on how much GPU ram this network uses.

**Comment by snamjoshi** [comment]
@deg4uss3r Well after some testing today it looks like its definitely not TF2 error and it's also not a memory issue! I'm at a loss right now so I've gone back to trying to debug the inputs again. Thanks for your update!

**Comment by snamjoshi** [comment]
I finally figured it out. I made the following changes:

- In `compute_inputs()` which is located in `preprocessing/generator.py`, import tensorflow as tf and then change the return statement to `return tf.constant(image_batch, dtype = tf.float32)`. 
- In `anchor_targets_bbox()` which is located in `utils/anchors.py`, import tensorflow as tf and then change the return statement to `return tf.constant(regression_batch, dtype = tf.float32), tf.constant(labels_batch, dtype = tf.float32)`.

Essentially, you have convert the input and target for the Keras sequence generator to a tensor rather than leave it as a numpy array. In this case, the targets batches are actually computed desperately for the classification and regression heads in `anchors.py` so you have to go in there it change it. It might have something to do with eager execution memory requirements or something else... I'm really not sure.

It seems that others I am working with have had to make similar changes to their could for TF2 compatibility with their own code (not `keras-retinanet`). I don't know if that's a consequence of the environment we are running the wrapped code in or something else but it may not be a `keras-retinanet` problem at all.
