### ISSUE TITLE
How to set --random-transform, True or False or other?

### ISSUE THREAD

**Issue by 2696120622** [fizyr/keras-retinanet#1193]
I want to train the retinanet with python keras_retinanet/bin/train.py ...
However, I do not know how to set the value for --random-transform.
Is there some help?

**Comment by hgaiser** [comment]
Just providing the argument `--random-transform` will enable random transforms :)

**Comment by 2696120622** [comment]
> Just providing the argument `--random-transform` will enable random transforms :)

OK, thanks.
