### ISSUE TITLE
On the input format of tensorflow's non_max_suppression function

### ISSUE THREAD

**Issue by dishofchicken** [fizyr/keras-retinanet#1195]
When I read the document of tensorflow's non_max_suppression function, I found that the format of boxes should be (y1,x1,y2,x2), but what I see in the program is (x1,y1,x2,y2).

**Comment by hgaiser** [comment]
Yes! Very perceptive, you are correct, however does it matter? ^^ Basically it's computing nms on a rotated image. I do agree that a comment to make this point clear would be nice. Feel free to make a PR for that.
