### ISSUE TITLE
load retinanet model

### ISSUE THREAD

**Issue by PEE8** [fizyr/keras-retinanet#1197]
"# adjust this to point to your downloaded/trained model
# models can be downloaded here: https://github.com/fizyr/keras-retinanet/releases
model_path = os.path.join('..', 'snapshots', 'resnet50_coco_best_v2.1.0.h5')

# load retinanet model
model = models.load_model(model_path, backbone_name='resnet50')"

while running the above lines --it shows error as 

 model = models.load_model(model_path, backbone_name='resnet50')

AttributeError: module 'imageai.Detection.keras_retinanet.models' has no attribute 'load_model'

I tried uninstall keras_retinanet it did not work
I tried cloning keras-retinanet it did not work

**Comment by hgaiser** [comment]
Your question is regarding imageai it seems, not keras-retinanet.

**Comment by PEE8** [comment]
it is regarding keras-retinanet only, Not imageai. I have keras-retinanet in imageai already. So it is not considering the keras-retinanet in the folder where my code is present.

**Comment by hgaiser** [comment]
`imageai` has their own copy of keras-retinanet. I don't know what they have or how to help you.

**Comment by PEE8** [comment]
ok!
