### ISSUE TITLE
 import compute_overlap in keras-retinanet

### ISSUE THREAD

**Issue by PEE8** [fizyr/keras-retinanet#1198]
When i run "C:\Users\Desktop\keras_retinanet\utils\anchors.py". I am getting error  import compute_overlap
cimport cython
                 ^
SyntaxError: invalid syntax

I placed compute_overlap in the same folder

If i import compute_overlap into anchors.py then it shows no error.
But is this correct?

**Comment by hgaiser** [comment]
How did you download / install keras-retinanet? Did you compile the plugin?

**Comment by PEE8** [comment]
Yes i downloaded from https://github.com/fizyr/keras-retinanet/

**Comment by hgaiser** [comment]
And you ran `python setup.py build_ext --inplace` ? And then what?

**Comment by PEE8** [comment]
Yes! but this gave error as
[Errors.docx](https://github.com/fizyr/keras-retinanet/files/3910477/Errors.docx)

**Comment by hgaiser** [comment]
Could you post the error using the triple ` tags ?

**Comment by PEE8** [comment]
'''
(base) C:\Users\Prisilla\Desktop\CNN11\Bounding Boxes\Satellite_images\New>pytho
n setup.py build_ext --inplace
running build_ext
cythoning keras_retinanet/utils/compute_overlap.pyx to keras_retinanet/utils\com
pute_overlap.c
creating keras_retinanet
creating keras_retinanet\utils
error: C:\Users\Prisilla\Desktop\CNN11\Bounding Boxes\Satellite_images\New\keras
_retinanet\utils\compute_overlap.pyx '''

**Comment by hgaiser** [comment]
Seems that there is where your issue really is, but it doesn't give any description on what is going wrong. I can't help you though, as I have no experience with using keras-retinanet on Windows.

Small tip, you used the wrong symbol for code tags. Using ` it would look like:

```python
print("Hello World")
```

**Comment by PEE8** [comment]
In the previous comment as i told 
creating keras_retinanet
creating keras_retinanet\utils  ---> it created a dir keras-retinanet and subdir utils in the folder (New) but nothing is present as error is raised.

Regarding """ do you mean i use while i run the command?
I did it and it gives error as 

(base) C:\Users\Prisilla\Desktop\CNN11\Bounding Boxes\Satellite_images\New>"""py
thon setup.py build_ext --inplace"""
'"""python setup.py build_ext --inplace"""' is not recognized as an internal or
external command,
operable program or batch file.

**Comment by PEE8** [comment]
If i placed all the modules under one dir (folder). it raises no error.  Special i put compute_overlap in anchors.py
def compute_overlap(a, b):
    """
    Parameters
    ----------
    a: (N, 4) ndarray of float
    b: (K, 4) ndarray of float
    Returns
    -------
    overlaps: (N, K) ndarray of overlap between boxes and query_boxes
    """
    area = (b[:, 2] - b[:, 0]) * (b[:, 3] - b[:, 1])

    iw = np.minimum(np.expand_dims(a[:, 2], axis=1), b[:, 2]) - np.maximum(np.expand_dims(a[:, 0], 1), b[:, 0])
    ih = np.minimum(np.expand_dims(a[:, 3], axis=1), b[:, 3]) - np.maximum(np.expand_dims(a[:, 1], 1), b[:, 1])

    iw = np.maximum(iw, 0)
    ih = np.maximum(ih, 0)

    ua = np.expand_dims((a[:, 2] - a[:, 0]) * (a[:, 3] - a[:, 1]), axis=1) + area - iw * ih

    ua = np.maximum(ua, np.finfo(float).eps)

    intersection = iw * ih

    return intersection / ua


And when i run the anchors.py there is no error.

**Comment by PEE8** [comment]
https://github.com/fizyr/keras-retinanet/issues/1116#event-2665131854

Is this the same issue
