### ISSUE TITLE
It seems the train data were not augmented

### ISSUE THREAD

**Issue by Kongsea** [fizyr/keras-retinanet#120]
This repository uses the following code to augment the train data:

>  train_image_data_generator = keras.preprocessing.image.ImageDataGenerator(
>       horizontal_flip=True,
>   )
> 
>   train_generator = CSVGenerator(
>       csv_data_file=args.train_path,
>       csv_class_file=args.classes,
>       image_data_generator=train_image_data_generator,
>       batch_size=args.batch_size
>   )

However, I found the train_generator can generate the same images and the same number of images as original every time.

To be sure, I have used the following code to check it:

> for i in tqdm(range(len(train_generator.image_names))):
>     im = train_generator.load_image(i)
>     cv2.imwrite('test/{}.png'.format(i), im)

I run the code many times and got the same images as original every time.
I cannot found the reason, please help me to fix it.
Thank you.

**Comment by hgaiser** [comment]
`load_image` only loads the image, it doesn't augmentation it. `preprocess_group` in the `Generator` class handles the data augmentation.

**Comment by Kongsea** [comment]
OK, thank you for your explanation.

**Comment by Kongsea** [comment]
Then do we need to set `steps_per_epoch=train_generator.size() // args.batch_size` to a larger value to use more original and augmented images in one epoch? Since the current value is (almost) the same as the original image number.

**Comment by hgaiser** [comment]
An epoch isn't really a strictly defined "thing". It is mostly for the user to get a feeling of how many times it has seen the training data, than it really is something the network works with. In the latest COCO training script I changed the `steps_per_epoch` to a static `10000` actually. As long as the training converges, you're fine. Whether the `steps_per_epoch` exactly matches the total number of input images you have, doesn't really matter.

I will close this issue for now.

**Comment by kongqiankun** [comment]
If I double the COCO dataset by myself about the images and annotations, will it conflict with argumentation in source code?
