### ISSUE TITLE
How to train mobilenet with param alpha

### ISSUE THREAD

**Issue by sonfiree** [fizyr/keras-retinanet#1200]
How to set alpha parameter? So what is this?

`backbone_retinanet=  models.backbone('mobilenet224')`
`model = model_with_weights(backbone_retinanet(num_classes, num_anchors=num_anchors, modifier=modifier), weights=weights, skip_mismatch=True)`

**Comment by anshulg03** [comment]
`backbone_retinanet= models.backbone('mobilenet224_1')`
`backbone_retinanet= models.backbone('mobilenet224_0.75')`

You can do it like this.

**Comment by sonfiree** [comment]
What does alpha indicate?
