### ISSUE TITLE
.csv files and .txt files

### ISSUE THREAD

**Issue by PEE8** [fizyr/keras-retinanet#1201]
I find classes-bbox-trainable.txt , classes-description.csv and class-description-boxable.csv. mentioned in open_images.py, but i do not find them.
From where are these passed to this open_images files.
Pascal_voc.file has load_image.jpg file, can i pass any jpg file?
Please suggest

Yes! is this for csv files and annotation files i need to pass
https://github.com/fizyr/keras-retinanet-test-data/tree/214fae74dd4fcb73552ea1b23f6d8f38bd1e327c

**Comment by hgaiser** [comment]
What is it you are trying to do exactly?

**Comment by PEE8** [comment]
I am trying to detect the objects as mentioned in https://arthurdouillard.com/post/nato-challenge/
