### ISSUE TITLE
Is it possible to get class scores for all classes ? 

### ISSUE THREAD

**Issue by dangmanhtruong1995** [fizyr/keras-retinanet#1206]
Hi, Is it possible to get class scores for all classes ? For example we have a dog object. The model predicts that the object is dog, with score 0.9. Is it possible to get scores for other classes, for example: cat - 0.1 ? 
I checked many examples but have not found how to get class scores for all classes ? 
Thank you very much.

**Comment by hgaiser** [comment]
With the current implementation this is not possible. The information is there in the network though, but you would have to start with a non-converted model. The outputs will then be `regression, classification`. You would need to apply the regression values to the anchors to get the predicted bboxes (we use [this](https://github.com/fizyr/keras-retinanet/blob/master/keras_retinanet/layers/_misc.py#L118) to do that) and apply some form of non-maximum suppression on the boxes.

I'm closing this as there is no issue with our code here.
