### ISSUE TITLE
Can someone help me to generate the confusion matrix for the multi-class case?

### ISSUE THREAD

**Issue by vinhbt0301** [fizyr/keras-retinanet#1209]

**Comment by hgaiser** [comment]
This is not an issue with our code. If you wish to discuss theories, please use the Slack channel for that.

**Comment by MaddyThakker** [comment]
@vinhbt0301 were you able to generate the confusion-matrix?

**Comment by sindhura234** [comment]
@vinhbt0301 @MaddyThakker Did you generate confusion-matrix?

**Comment by MaddyThakker** [comment]
It's been more than a year and I honestly don't remember now.
