### ISSUE TITLE
How to convert the wired format of boxes returned by model.predict_on_batch?

### ISSUE THREAD

**Issue by Kongsea** [fizyr/keras-retinanet#121]
After training a model, we can use the following code to predict outputs as mentioned in README.md:

> _, _, detections = model.predict_on_batch(inputs)

However, it ignores the first two returned arguments and only gives the first 300 predicted boxes and its scores.
We can obtained the first two returned variables too:

> boxes, scores, detections = model.predict_on_batch(inputs)

But the boxes coordinates are in a wired format, which I don't know how to convert to the common formats to use. 

The followings are the coordinates obtained from the returned arguments, boxes and detections, respectively.

First one, from detections:

> box1 = np.array([89.41078949,  104.58268738,  111.79120636,  169.3478241], dtype=np.float32)

The corresponding coordinates from boxes:

> box11 = np.array([0.02108106, -0.05322488, -0.24202469,  0.12740892], dtype=np.float32)

Second one, from detections:

> box2 = np.array([200.23431396,  193.16589355,  225.7416687,  276.84066772], dtype=np.float32)

from boxes:

> box22 = np.array([0.01305179,  0.0823493, -0.26798463,  0.12430889], dtype=np.float32)

The image width is 480, and the height is 640. No scale was used on images.

So could anybody give some advice?
Thank you.

**Comment by fangwudi** [comment]
1)  first two returned arguments aren't boxes, scores, actually are regression(not box coordinate) and classification
2) don't understand your purpose, if you want more  predicted box, you can sent max_boxes argument to NonMaximumSuppression()

**Comment by Kongsea** [comment]
Thank you. I have misunderstood it.
Then could you give me some advice to pass max_boxes argument to NonMaximumSuppression(). I cannot find where this function was called and where to pass this argument.
Thanks.

**Comment by hgaiser** [comment]
Those first two values are indeed regression and classification values. They are only used for loss computations. The third output are the resulting boxes and classifications. Per layer configuration is something that is currently not supported. You could pass `nms=False` to skip the non maximum suppression all together. You would then receive all boxes as outputs. You could then also append an NMS layer again, if you want NMS, with your own arguments.

**Comment by Kongsea** [comment]
Thank you.
It's just what I need. Could you please tell me where to pass nms=False argument?

**Comment by hgaiser** [comment]
You can pass `nms=False` to the call to `ResNet50RetinaNet`. I will consider this issue resolved for now.
