### ISSUE TITLE
It looks like that nms is not working.

### ISSUE THREAD

**Issue by 2696120622** [fizyr/keras-retinanet#1215]
I convert my training model to inference model with "python keras_retinanet/bin/convert_model.py snapshots/resnet50_csv_10.h5 inference/resnet50_csv_10.h5"

convert_model.py has code as follows:

              ...
    parser.add_argument('--no-nms', help='Disables non maximum suppression.', dest='nms', action='store_false')  
    parser.add_argument('--no-class-specific-filter', help='Disables class specific filtering.', dest='class_specific_filter', action='store_false') 
              ...
    model = models.convert_model(model, nms=args.nms, class_specific_filter=args.class_specific_filter, anchor_params=anchor_parameters)

I have not passed --no-nms and --no-class-specific-filter. Therefore, both args.nms and args.class_specific_filter are True according to above code. It means that nms and class_specific_filter will be applied.
However, I get some overlap boxes when I use the inference model for detection.

**Comment by tonmoyborah** [comment]
Usually if you don't use nms, then there are hundreds of boxes around the same object. If this is not the case and only one or two overlap occurs, it might mean that the nms threshold needs to be optimized for your data.

**Comment by hgaiser** [comment]
As @tonmoyborah mentioned, you can still get overlapping boxes, they should just be less severe. I believe the IoU is set to 0.5 for NMS, so overlapping boxes should in theory have an IoU of less than 0.5. Since class specific filter is set to true, it also means that detections from different class can have (nearly) identical bounding boxes.

**Comment by VincentDecospan** [comment]
i'm encoutering the same issues tbh. I don't think the .5 overlap is failproof as I have seen two objects from the same class overlap 100% when running detection

**Comment by hgaiser** [comment]
If you find a case where this occurs and dig into why that happens, I would be very interested to hear the results.

**Comment by apatsekin** [comment]
I experienced the same with TF Object Detection API. Since both frameworks use native tf.image.non_max_suppression, it's kind of expected. It clearly outputs boxes of the same class with higher IoU than threshold. I didn't find the reason. If someone knows the answer, would be great!

**Comment by hgaiser** [comment]
> NMS is run on each of FPN outputs separately, and then combined.

That shouldn't be the case, we flatten the outputs of FPN before passing it to NMS.
