### ISSUE TITLE
prediction model after traing

### ISSUE THREAD

**Issue by sonfiree** [fizyr/keras-retinanet#1217]
I teach the grid script 
`https://github.com/fizyr/keras-retinanet/blob/master/keras_retinanet/bin/train.py`
Next, I want to predict here 
`https://github.com/fizyr/keras-retinanet/blob/58e9058585c786612bd42c21d53c5af6e7519316/examples/ResNet50RetinaNet.ipynb`

And getting an error
```
     24 # process image
     25 start = time.time()
---> 26 boxes, scores, labels = model.predict_on_batch(np.expand_dims(image, axis=0))
     27 print("processing time: ", time.time() - start)
     28 

ValueError: not enough values to unpack (expected 3, got 2)
```

How do i call a prediction model?
And why doesn't the callback save the prediction model?

**Comment by BogoK** [comment]
Why did you call this? Got the same issue

**Comment by sonfiree** [comment]
@BogoK need converting model 
https://github.com/fizyr/keras-retinanet#converting-a-training-model-to-inference-model
