### ISSUE TITLE
AttributeError: 'Namespace' object has no attribute 'steps_for_validation'

### ISSUE THREAD

**Issue by sv-youn** [fizyr/keras-retinanet#1223]
File "keras_retinanet/bin/train.py", line 528, in <module>
    main()
  File "keras_retinanet/bin/train.py", line 521, in main
    validation_steps = args.steps_for_validation,
AttributeError: 'Namespace' object has no attribute 'steps_for_validation'

**Comment by ssusie** [comment]
I commented that line out and it worked. But it needs to be fixed.

**Comment by pendex900x** [comment]
same error here

**Comment by china56321** [comment]
> File "keras_retinanet/bin/train.py", line 528, in 
> main()
> File "keras_retinanet/bin/train.py", line 521, in main
> validation_steps = args.steps_for_validation,
> AttributeError: 'Namespace' object has no attribute 'steps_for_validation'

Have you solved this problem?

**Comment by hgaiser** [comment]
Some commits from last week are causing these issues. I just reverted them, can you try again?

**Comment by china56321** [comment]
I commented  that line ,it worked!发自我的华为手机-------- 原始邮件 --------发件人： Hans Gaiser <notifications@github.com>日期： 2019年12月19日周四 17:55收件人： fizyr/keras-retinanet <keras-retinanet@noreply.github.com>抄送： china56321 <china56321@126.com>, Comment <comment@noreply.github.com>主    题： Re: [fizyr/keras-retinanet] AttributeError: 'Namespace' object has no attribute 'steps_for_validation' (#1223)Some commits from last week are causing these issues. I just reverted them, can you try again?

**Comment by alex337** [comment]
hi,did you solved this problem

**Comment by china56321** [comment]
> hi,did you solved this problem

yes,just commented that line

**Comment by alex337** [comment]
> > > hi,did you solved this problem
> > 
> > 
> > yes,just commented that line
> 
> it is not enough to comment the line, if you want to train the network for other classes, You will need that piece of code

The minimum required version of keras must be  2.3.0??

**Comment by china56321** [comment]
> > > hi,did you solved this problem
> > 
> > 
> > yes,just commented that line
> 
> it is not enough to comment the line, if you want to train the network for other classes, You will need that piece of code

So,how should i do to solve the problem ?

**Comment by pendex900x** [comment]
> > > > hi,did you solved this problem
> > > 
> > > 
> > > yes,just commented that line
> > 
> > 
> > it is not enough to comment the line, if you want to train the network for other classes, You will need that piece of code
> 
> So,how should i do to solve the problem ?

I solved running again my program, it appears to be a bug

**Comment by china56321** [comment]
> > > > > hi,did you solved this problem
> > > > 
> > > > 
> > > > yes,just commented that line
> > > 
> > > 
> > > it is not enough to comment the line, if you want to train the network for other classes, You will need that piece of code
> > 
> > 
> > So,how should i do to solve the problem ?
> 
> I solved running again my program, it appears to be a bug

i can't
