### ISSUE TITLE
can we use efficientnet as a feature extractor on high resolution image input(1024x1024)?

### ISSUE THREAD

**Issue by RituYadav92** [fizyr/keras-retinanet#1224]
can we use efficientnet as a feature extractor on high-resolution image input(1024x1024)?
It will affect the accuracy or we should expect similar level results?

Thanks!

**Comment by hgaiser** [comment]
Best way to find out is to try it out: https://github.com/fizyr/keras-retinanet/blob/master/keras_retinanet/models/effnet.py
