### ISSUE TITLE
You can change default **max_detection** in **'/keras_retinanet/layers/filter_detections'**.

### ISSUE THREAD

**Issue by apolanco3225** [fizyr/keras-retinanet#1228]
You can change default **max_detection** in **'/keras_retinanet/layers/filter_detections'**. 
This model sorted the scores to select the detection results with scores and u can use NMS in **‘/keras_retinanet/utils/eval’** instead of scores judgment.

_Originally posted by @yelanyelan in https://github.com/fizyr/keras-retinanet/issues/624#issuecomment-410640294_

Hi ! so I've been struggling with this for days and would really appreciate your help, I go to the following directory:

/home/arturo/anaconda3/envs/retinanet/lib/python3.6/site-packages/keras_retinanet-0.4.1-py3.6-linux-x86_64.egg/keras_retinanet/layers

then in filter_detection.py I modify the variable max_detections to 400, or to 200, it doesn't matter, I always get 300 detections, could you please give me some advice?

**Comment by hgaiser** [comment]
The parameters are baked into the model when you convert. Try re-converting your training model after changing the parameters.
