### ISSUE TITLE
StartAbort Invalid argument: Incompatible shapes: [1,235356] vs. [1,176517]

### ISSUE THREAD

**Issue by milansoliya4210** [fizyr/keras-retinanet#1233]
I am trying to predict image from train model and getting error as below
`2019-12-19 09:54:53.768014: W tensorflow/core/common_runtime/base_collective_executor.cc:216] BaseCollectiveExecutor::StartAbort Invalid argument: Incompatible shapes: [1,235356] vs. [1,176517]
	 [[{{node boxes/mul_1}}]]
	 [[filtered_detections/map/while/body/_1/strided_slice_2/_52]]
2019-12-19 09:54:53.769414: W tensorflow/core/common_runtime/base_collective_executor.cc:216] BaseCollectiveExecutor::StartAbort Invalid argument: Incompatible shapes: [1,235356] vs. [1,176517]
	 [[{{node boxes/mul_1}}]]`

**Comment by hgaiser** [comment]
Did you change anything regarding anchor sizes / ratios?

**Comment by milansoliya4210** [comment]
yes, i add config.ini file as input as below configuration as input as here:

`!python keras_retinanet/bin/train.py \
 --freeze-backbone \
 --random-transform \
 --weights {PRETRAINED_MODEL} \
 --batch-size 1 \
 --steps 500 \
 --epochs 5 \
 --config config.ini \
 csv annotations.csv classes.csv`

And Congiguration is ,
`[anchor_parameters]
sizes   = 16 32 64 128 256
strides = 8 16 32 64 128
ratios  = 0.5 1 2 3
scales  = 1 1.2 1.6
`

**Comment by hgaiser** [comment]
And did you also add the config when you loaded the model for prediction?

**Comment by milansoliya4210** [comment]
No?? How to add??

**Comment by milansoliya4210** [comment]
In Function
`convert_model(model,` nms=True, class_specific_filter=True, anchor_params=None)`
what should be format of anchor_params ??

**Comment by ak4ever87** [comment]
did you solve the problem?
i have the same exact issue?

**Comment by MichaelStevan** [comment]
Running into the same issue here, also due to adding a new 16 anchor size. I did this modifying the code directly without a config file and it didn't solve the issue. Any help is welcomed!

**Comment by MichaelStevan** [comment]
> Running into the same issue here, also due to adding a new 16 anchor size. I did this modifying the code directly without a config file and it didn't solve the issue. Any help is welcomed! Let us know if you fixed it @milansoliya4210!

I managed to solve my issue, figured out changing anchor sizes is not doable without changing the model architecture. Only scales and ratios can be changed if you want to use the library as it's. Also, Retinanet ratios are defined as `height/width`. I hope this helps someone out in the future!

**Comment by GGDRriedel** [comment]
Then how do I add the changed ratios? I am running into the same problem

**Comment by GGDRriedel** [comment]
I solved this for me. 

Custom CSV dataset. 

I trained with a config.ini with custom ratios. 
```python keras_retinanet/bin/train.py --config config.ini csv annotations.csv classmapping.csv  ```

I used the convert_model.py with this line

```python keras_retinanet/bin/convert_model.py --config config.ini ./snapshots\resnet50_csv_34.h5 ./models/first_train.h5```

This results in the "first_train" model, which I can load through the provided Jupyter Notebook.
