### ISSUE TITLE
How to set --config config.ini during Prediction?

### ISSUE THREAD

**Issue by milansoliya4210** [fizyr/keras-retinanet#1237]
I have train model using Changing Anchor size as per below:
`[anchor_parameters]
sizes   = 16 32 64 128 256
strides = 8 16 32 64 128
ratios  = 0.5 1 2 3
scales  = 1 1.2 1.6
`
I have save this config in file config.ini and I put this as input to  training as below:
`!python keras_retinanet/bin/train.py \
 --freeze-backbone \
 --random-transform \
 --weights {PRETRAINED_MODEL} \
 --batch-size 1 \
 --steps 500 \
 --epochs 5 \
 --config config.ini \
 csv annotations.csv classes.csv`

And Training Goes Good but how to use this file during Prediction in given function?
`convert_model(model,nms=True, class_specific_filter=True, anchor_params=None)` 
??

**Comment by travis8719** [comment]
@milansoliya4210 , did you figure out how to send the config file to convert_model? I am in the same boat. Thank you.

**Comment by A-Sassi** [comment]
Use this command:
retinanet-convert-model snapshots_folder/trained_model.h5 name_after_conversion.h5 --config config.ini --backbone backbone_used.
You can also replace "retinanet-convert-model" with "python3 path_to_retinanet_folder/keras_retinanet/bin/convert_model.py"

**Comment by A-Sassi** [comment]
@travis8719 Use this command:
retinanet-convert-model snapshots_folder/trained_model.h5 name_after_conversion.h5 --config config.ini --backbone backbone_used.
You can also replace "retinanet-convert-model" with "python3 path_to_retinanet_folder/keras_retinanet/bin/convert_model.py"
