### ISSUE TITLE
Compute Precision-Recall-Curve

### ISSUE THREAD

**Issue by MarviB16** [fizyr/keras-retinanet#1238]
Hello,

is there a way to compute the Precision-Recall-Curve for a trained model?

Thanks?

**Comment by hgaiser** [comment]
There is some code to compute the precision and recall inside the evaluation functions, but it's not exposed: https://github.com/fizyr/keras-retinanet/blob/master/keras_retinanet/utils/eval.py#L234-L235

**Comment by swathi24prabhu** [comment]
what is the command to get the precision and recall for retinanet?
