### ISSUE TITLE
AttributeError: 'Model' object has no attribute '_get_distribution_strategy' 

### ISSUE THREAD

**Issue by milansoliya4210** [fizyr/keras-retinanet#1239]
I am trying to train model in Google Colab using tensorflow 2.x bundle package for Colab and Getting Error as mention Below:

`AttributeError:'Model' object has no attribute _get_distribution_strategy' `

**Comment by hgaiser** [comment]
https://github.com/tensorflow/tensorflow/pull/34870

you can also remove the tensorboard callback for now.

**Comment by shadow12138** [comment]
> [tensorflow/tensorflow#34870](https://github.com/tensorflow/tensorflow/pull/34870)
> 
> you can also remove the tensorboard callback for now.

Will the training weights be saved if the callback is removed?

**Comment by hgaiser** [comment]
Yes they will be. Only thing you lose is the usage of Tensorboard.

ps. you can also use `--tensorboard-dir ""` on the command line to disable Tensorboard callback.

**Comment by SalahAdDin** [comment]
It is a problem with `keras`, right? I mean, you cannot solve it in this implementation, right?

**Comment by shadow12138** [comment]
> It is a problem with `keras`, right? I mean, you cannot solve it in this implementation, right?

i solved it by `--tensorboard-dir ""`

**Comment by SaltyGlutinousRiceBall** [comment]
> Yes they will be. Only thing you lose is the usage of Tensorboard.
> 
> ps. you can also use `--tensorboard-dir ""` on the command line to disable Tensorboard callback.

'--tensorboard-dir ""' is not an internal or external command, nor is it a runnable program or batch files.

**Comment by hgaiser** [comment]
> It is a problem with `keras`, right? I mean, you cannot solve it in this implementation, right?

It's a problem with keras and tensorflow. Tensorflow made some changes that didn't work when using keras, only works when using tensorflow.keras. https://github.com/tensorflow/tensorflow/pull/34870 got merged so this should be automatically fixed with a new tensorflow release.

**Comment by daryl-user** [comment]
Did you try import from tensorflow.keras instead of tensorflow?

**Comment by ZhangYuef** [comment]
> Did you try import from tensorflow.keras instead of directly from keras?

It's the same for me. Both `tensorflow.keras` and `keras` raise the error.

**Comment by hgaiser** [comment]
Tensorflow just released version 2.2, this should fix this issue.

**Comment by hgaiser** [comment]
Tensorflow just released version 2.2, this should fix this issue.

**Comment by DarthAmk97** [comment]
The issue persists :(

**Comment by SalahAdDin** [comment]
@DarthAmk97  Use the monkeypatch solution ,it works for me.

**Comment by TimNagle-McNaughton** [comment]
@SalahAdDin can you provide a link to or any documentation of that solution?

**Comment by SalahAdDin** [comment]
> > It is a problem with `keras`, right? I mean, you cannot solve it in this implementation, right?
> 
> i solved it by `--tensorboard-dir ""`

@TimNagle-McNaughton This one.

**Comment by TimNagle-McNaughton** [comment]
oh. Sadly that doesn't actually fix the functionality, just removes the functionality and the error. Thanks

**Comment by SalahAdDin** [comment]
@TimNagle-McNaughton it is related to `Tensorflow` library more than this package, unfortunately.
