### ISSUE TITLE
GPU is not used when training

### ISSUE THREAD

**Issue by lx7555** [fizyr/keras-retinanet#1241]
versions:
Tensorflow 1.14.0
anaconda2 py2
ubuntu 16.04
TITAN X (Pascal)
NVIDIA driver 418.67
cuda:10.0
cudnn: 7.4.2
I set the args.gpu='0', and args.multi_gpu = 1.
when the model was trained, I found my gpu work. However,when the model try to get convolution algorithm gpu didn't work. Because loaded runtime CuDNN library: 7.1.2 but source was compiled with: 7.4.2.
I don not know how to set make cudnn work?  In tensorflow, gpu can work. More information please see images. I don not know weather is my anacond2 problem?? or other issue??
Thank you for your help!!
tensorflow-gpu state:true(work)
![1](https://user-images.githubusercontent.com/25916892/71470853-8554d480-2808-11ea-98bb-621bf732427c.png)
cudnn link
![2](https://user-images.githubusercontent.com/25916892/71470873-9dc4ef00-2808-11ea-8470-4498e90144e6.png)
cudnn version
![3](https://user-images.githubusercontent.com/25916892/71470917-b9c89080-2808-11ea-80b0-cd82fb6717be.png)
error
![4](https://user-images.githubusercontent.com/25916892/71470922-bc2aea80-2808-11ea-8d73-c302a8e13a32.png)

**Comment by dageita** [comment]
Same problem, anyone can help?
