### ISSUE TITLE
Retina net architecture

### ISSUE THREAD

**Issue by game-sys** [fizyr/keras-retinanet#1243]
Is it using a two stage object detection and how ?
And why every time I train it say epoch 1 1/10000 what that 10000 mean I change batch size but it is not changing why?

**Comment by Mastemace** [comment]
10000 means the step size set by argument --batch size. The custom value is 10000. It is not affected by the batch size. Generally, you can compute a proper batch size by n/b, where n is a number of samples in your dataset and b is batch size. But of course, you can set batch size lower/higher than the number computed using the formula.

**Comment by hgaiser** [comment]
You can change batch size and step size independently of each other. Regarding your question about the stages, I suggest to read the paper :)
