### ISSUE TITLE
What does the steps argument do in training? 

### ISSUE THREAD

**Issue by sv-youn** [fizyr/keras-retinanet#1245]
I understand how batch-size and epochs work. But I have no idea about the steps argument. 
The following is from bin/train.py. 
parser.add_argument('--steps', help='Number of steps per epoch.', type=int, default=10000)
Can anyone explain about this argument?

**Comment by Mastemace** [comment]
You should google it;) See the explanation, e.g., on https://datascience.stackexchange.com/questions/47405/what-to-set-in-steps-per-epoch-in-keras-fit-generator

**Comment by sv-youn** [comment]
Thanks, Mastemace. That's very helpful. I will close the issue.
