### ISSUE TITLE
anchors in a custom config file

### ISSUE THREAD

**Issue by Mastemace** [fizyr/keras-retinanet#1246]
I'd like to ask about a custom config. You propose to use an extern repository for defining your own config file. It works well, and the network is trained well too. But the problem is the inference: I didn't find a way how the custom config can be passed to the inference model. Can you help me with the solution?

**Comment by tonmoyborah** [comment]
It's is incorporated into the `convert_model` script where you can pass the config file. The inference model generated has the necessary config then.
