### ISSUE TITLE
No Such File or Directory 'Logos/retinanet_classes.csv'

### ISSUE THREAD

**Issue by Mididou** [fizyr/keras-retinanet#1247]
Hello Everyone , i'm trying to train  retinanet on my logo dataset , when i run the following command line 
        `  retinanet-train --batch-size 1 --steps 349 --epochs 50 --weights logos/resnet50_coco_best_v2.1.0.h5  --snapshot-path logos/snapshots  csv logos/retinanet_train.csv logos/retinanet_classes.csv` 

I get the following error :  

![image](https://user-images.githubusercontent.com/48514563/72136157-73d30700-3388-11ea-9b1a-79346e2d9fda.png)

Any Help Would be much appreciated , thank you.

**Comment by SeaBroNoMeal** [comment]
Hi, have you manged to solve this problem? Same problem happened to me :)
