### ISSUE TITLE
too few negative samples?

### ISSUE THREAD

**Issue by lovepan1** [fizyr/keras-retinanet#1248]
i think  the algorithm does not take into the pictures without targets, will it cause too few background classes or negative samples compared two-stage algorithm?  

if (x1, y1, x2, y2, class_name) == ('', '', '', '', ''):
        continue
this code from csv_generator.py , can you give me some advices ?

**Comment by hgaiser** [comment]
The code you are referencing in the `CsvGenerator` skips parsing of the annotations, but before that an entry for this image has already been created. The `CsvGenerator` should definitely use the empty pictures if they are provided in the csv file. Have you tried visualizing your data with `retinanet-debug` to see if it generates empty images?

**Comment by panchengl** [comment]
thank u you reply,  i do not use debug.py,  i will visualizing no annotations pictures, and then reply u .

**Comment by lovepan1** [comment]
thank u you reply, i do not use debug.py, i will visualizing no annotations pictures, and then reply u .

**Comment by lovepan1** [comment]
i had visualizing no annotations images, only pictures,   
if len(annotations['label] >0): 
     the code will visualizing annotations 
in debug.py

but I don't know what role these unlabeled pictures play in the algorithm, if not important , why not del this image? or this unlabeled images is important, where does the code use these pictures？

thank U ！

**Comment by lovepan1** [comment]
@hgaiser

**Comment by alainkaiser** [comment]
@lovepan1 "or this unlabeled images is important, where does the code use these pictures ?"

This is an interesting question. Do you found an answer? Currently, we are also testing with positive images (images with annotations) and negative images (images with no annotations) in our csv file.

If we only use the positive images csv for training, the model training works and also the printed map score is realistic. But if we run the training with the positive and negative images csv file, the map score is 0.0000 for every epoche and the model does not learning anything...

**Comment by lovepan1** [comment]
hey, when i test no annotations imgaes, the net occured misdetection, so i want use this no obj images to train in order to create  more negative samples, but i think the code not deal with no obj images.
you mentioned  different csv files trained different maps, i don't explain the phenomenon,  you can @ author to answer.

**Comment by hgaiser** [comment]
>  if len(annotations['label] >0):

That code only disables drawing of the annotations. It should still visualize images that have no annotations in `debug.py`.

The algorithm tries to classify anchors as having an object or not, in essence it's just a classification net but executed on a grid on an image. Images without annotation will mean all predicted classifications should ideally be zero (as in, no object detected in the grid).
