### ISSUE TITLE
How precision and recall are calculated?

### ISSUE THREAD

**Issue by iskorini** [fizyr/keras-retinanet#1249]
Hi! I can't understand how precision and recall are calculated. 
I would like to plot a P/R curve for different `score_threshold` value, but when I saw the code in `eval.py` I can't understand why FP and TP are calculated this way:
``` python
false_positives = np.cumsum(false_positives)
true_positives  = np.cumsum(true_positives)
```
in particular, I've doubts about np.cumsum(), why it isn't np.sum()?

**Comment by hgaiser** [comment]
I'm not an expert on the evaluation metrics, the logic was copied from [py-faster-rcnn](https://github.com/rbgirshick/py-faster-rcnn/blob/master/lib/datasets/voc_eval.py#L192-L193).

**Comment by SalahAdDin** [comment]
@iskorini I have the same problem, we need to find the F1 score from the trained model, but we couldn't implmenet it correctly.

**Comment by ssusie** [comment]
If you use np.sum that will give you the precision, but you need to calculate Average Precision here. [This](https://towardsdatascience.com/breaking-down-mean-average-precision-map-ae462f623a52) post might be helpful to understand what is AP and mAP.

**Comment by SalahAdDin** [comment]
@ssusie What's about the F1 score?

**Comment by ssusie** [comment]
@SalahAdDin I don't know if there is "mean F1 score". I guess you can define F1 score for each class, then take the mean? F1 score is computed with regular precision and recall of the class, so you need to change the the evaluate function to compute precision and recall and not average precision or recall. Hope this helps.

**Comment by SalahAdDin** [comment]
what's the difference between average precision and recall and regular ones?

**Comment by ssusie** [comment]
Just read the post I mentioned above, that should make it clear.

**Comment by swathi24prabhu** [comment]
> Hi! I can't understand how precision and recall are calculated.
> I would like to plot a P/R curve for different `score_threshold` value, but when I saw the code in `eval.py` I can't understand why FP and TP are calculated this way:
> 
> ```python
> false_positives = np.cumsum(false_positives)
> true_positives  = np.cumsum(true_positives)
> ```
> 
> in particular, I've doubts about np.cumsum(), why it isn't np.sum()?

what is the command to get precision and recall for retinanet?
