### ISSUE TITLE
 UserWarning: The TensorBoard callback `batch_size` argument (for histogram computation) is deprecated with TensorFlow 2.0. It will be ignored.

### ISSUE THREAD

**Issue by SalahAdDin** [fizyr/keras-retinanet#1251]
Hi,

I'm testing this repository again and i found this warning while I'm training the net:
` UserWarning: The TensorBoard callback `batch_size` argument (for histogram computation) is deprecated with TensorFlow 2.0. It will be ignored.`

what is it about?

**Comment by hgaiser** [comment]
Duplicate of https://github.com/fizyr/keras-retinanet/issues/1239

**Comment by SalahAdDin** [comment]
@hgaiser Actually, i put it wrong, i was speaking about the warning, is it related to the same error? because i saw it in this other [issue](https://github.com/fizyr/keras-retinanet/issues/1123).

**Comment by hgaiser** [comment]
Ah I see. I don't know about that, Tensorboard is not working in tensorflow 2.1. How did you get around issue #1239 .

**Comment by SalahAdDin** [comment]
@hgaiser I dissabled it as you recommended.

**Comment by hgaiser** [comment]
But you still see this warning? Curious ... =\

**Comment by SalahAdDin** [comment]
Well, no, i don't get the warning if i use that option.

**Comment by hgaiser** [comment]
Then I'm confused, without that option you can't use `TensorBoard`, how did you get the warning?

**Comment by SalahAdDin** [comment]
i got the warning before to use that option; i tested your advice(using this option) and i don't get this warning anymore.
