### ISSUE TITLE
why it cause segmentation fault(core dumped)

### ISSUE THREAD

**Issue by Niel-shuang** [fizyr/keras-retinanet#1253]
When I run my dataset, I get an error “Segmentation fault (core dumped)
”, I could n’t solve it. I would like to ask what is causing this.

**Comment by Niel-shuang** [comment]
by the way, "core file size" is unlimited.

**Comment by hgaiser** [comment]
Sounds like an issue with tensorflow or some other third party library. How did you install your system and what command are you running?

**Comment by Niel-shuang** [comment]
I run the code by "python keras_retinanet/bin/train.py csv keras_retinanet/CSV/train_annotations.csv keras_retinanet/CSV/classes.csv --val-annotations keras_retinanet/CSV/val_annotations.csv",  It's weird, I haven't changed anything, run it again and it runs successfully.

**Comment by hgaiser** [comment]
Hmm strange. At least it's working now ^^

Segmentation faults are most likely coming from some C/C++ based project. So I would guess some issue with Tensorflow or OpenCV.
