### ISSUE TITLE
Change of code

### ISSUE THREAD

**Issue by aayushbhaskar** [fizyr/keras-retinanet#1256]
In backend/tensorflow_backend.py, please  change [line 68](https://github.com/fizyr/keras-retinanet/blob/232166da6ca5ac579e1a1ef9bed0f74f354f7272/keras_retinanet/backend/tensorflow_backend.py#L68) to return tensorflow.image.resize(images, size, methods[method]).

**Comment by hgaiser** [comment]
Hmm why? They slightly changed their implementation between tensorflow 1 and tensorflow 2. This ensures we are using the same implementation we always used.

**Comment by aayushbhaskar** [comment]
Oh okay!
