### ISSUE TITLE
Using Train and Val files in PASCAL VOC

### ISSUE THREAD

**Issue by SalahAdDin** [fizyr/keras-retinanet#1258]
Hi,

I was looking some things in the code and i found the next: https://github.com/fizyr/keras-retinanet/blob/232166da6ca5ac579e1a1ef9bed0f74f354f7272/keras_retinanet/bin/train.py#L266

If you see the normal `PASCAL VOC` format you will find a train, a validation and a test file, then, why do you use a `trainval` file text instead?

**Comment by hgaiser** [comment]
Pfoe difficult question, that was a long time ago. I vaguely remember the Pascal dataset I had didn't have a train set, just a trainval set.

**Comment by hgaiser** [comment]
I've never heard of these datasets, but I take your word for it that they have those sets. What do you propose to change? Could you check if the original Pascal VOC dataset (2007 and 2012) has them as we would expect?

**Comment by SalahAdDin** [comment]
@hgaiser Ok, i will check it and also i will make a PR to change the values to **train** and **val** splitted.

**Comment by SalahAdDin** [comment]
@hgaiser Look:
![image](https://user-images.githubusercontent.com/5034215/73445391-9d6dc580-436b-11ea-9e4a-defeecbb1234.png)

It is from 2012 and it has training an validation files, also joined in other file too. It is interesting notice there is no testing file.

**Comment by hgaiser** [comment]
Is there no single `train.txt` file?

**Comment by SalahAdDin** [comment]
@hgaiser There is:
![image](https://user-images.githubusercontent.com/5034215/73449226-c2fecd00-4373-11ea-9a82-9255a902cbc0.png)
