### ISSUE TITLE
Support PNG extension to PASCAL VOC

### ISSUE THREAD

**Issue by SalahAdDin** [fizyr/keras-retinanet#1259]
Hi,

I'm working with the **ACFR** dataset and i got a problem: its images are all in **PNG** format, and as far as i can see this RetinaNet implementation use JPEG images.

So, can we add support to PNG or multi-format image? Thanks.

**Comment by hgaiser** [comment]
Yes that would be nice to have. Could you submit a PR to add functionality to change what extension is to be expected for Pascal VOC?

**Comment by SalahAdDin** [comment]
@hgaiser  Should we do it automatically or manually?

**Comment by hgaiser** [comment]
Unfortunately the filenames in the .txt files don't include an extension, otherwise we could just use that ... I would choose for manually, with the default being whatever it is that Pascal VOC has (jpg I believe).

**Comment by SalahAdDin** [comment]
The other way is "walk" along the PASCAL VOC folder and read each file in the folder and pass after as the image, but it could lessen the performance.

**Comment by de-vri-es** [comment]
If the PASCAL VOC dataset has a folder per image, a searching the folder for the right file isn't such a weird idea. Overhead is probably negligible, and it would support datasets with mixed file extensions.

It would even solve incompatibilities with Windows if people wrongly capitalize file extensions.

**Comment by SalahAdDin** [comment]
@de-vri-es  You got a good point: i don't know it is offend possible to find different file's extensions.

@hgaiser What do you think?

**Comment by SalahAdDin** [comment]
@de-vri-es 
There is a problem with walking through the directory: https://github.com/fizyr/keras-retinanet/blob/master/keras_retinanet/preprocessing/pascal_voc.py#L94
```
self.image_names          = [l.strip().split(None, 1)[0] for l in open(os.path.join(data_dir, 'ImageSets', 'Main', set_name + '.txt')).readlines()]
 ```

It is taking the files from the training, testing or validation files, and it is logical because it will be used in different `bin` files; that's why it does not use a walking algorithm.

In this case, i think the best idea is to put the extension manually, while the researchers must be careful about their images' extension.
