### ISSUE TITLE
Lowering GPU usage doesn't seem to work. 

### ISSUE THREAD

**Issue by psi43** [fizyr/keras-retinanet#1261]
Hey, 
for a project I am working on that has several networks constantly running and evaluating at the same time, I need to limit the GPU usage of the Retina Net down to 70-80%, otherwise it complains about lacking Memory and quits. 

Now I've tried the following in the [/bin/evaluate.py](https://github.com/fizyr/keras-retinanet/blob/master/keras_retinanet/bin/evaluate.py):
```
def get_session():
    """ Construct a modified tf session.
    """
    gpu_options = tf.GPUOptions(per_process_gpu_memory_fraction=0.8, allow_growth=True)
    return tf.Session(config=tf.ConfigProto(gpu_options=gpu_options))
```

This is the only place in the project where I can find any mention of the tf.Session, so I assume that this is where I'd pass the gpu_options along. But I also tried to print a log message in the same function and it doesn't print, so maybe this is not the right place to set the memory fraction? 

When I start the other scripts first, the Memory used for the Retina Net seems to adjust automatically, but it still causes my other scripts to run out of memory. 
`GPU:0 with 8620 MB memory) -> physical GPU (device: 0, name: GeForce RTX 2080 Ti, pci bus id: 0000:01:00.0, compute capability: 7.5)`

I also tried turning off allow_growth but it doesn't seem to make a difference. 

Can anyone help me out? 

Thank you! 

EDIT: 
I use the following line to load my model, which is the line that triggers TensorFlow starting up:
`inference_model = models.load_model("/home/neural/RetinaTest/keras-retinanet/snapshots/" + model_name, backbone_name="resnet50")`

**Comment by hgaiser** [comment]
The session code in evaluate.py should be removed, we don't use it anymore since tf 2.0. We now use [this](https://github.com/fizyr/keras-retinanet/blob/master/keras_retinanet/utils/gpu.py#L33-L34).
