### ISSUE TITLE
How to split model between one GPU and the CPU ? Is that possible using multi-gpu feature?

### ISSUE THREAD

**Issue by esperancaleonardo** [fizyr/keras-retinanet#1265]
I have only 6GBs available in my GPU and getting stuck on training with high resolution images all the time giving me OOM errors. Can I use the multi gpu option do split my model between VRAM and RAM so I can train it?

**Comment by hgaiser** [comment]
The multi-gpu functionality in Keras is very limited, it doesn't support splitting one model onto multiple GPUs. You could split up your image in smaller images, run it as a batch and then combine the results again.

**Comment by esperancaleonardo** [comment]
And how do I do that?

**Comment by hgaiser** [comment]
I don't have an implementation of that for you, that will be something you have to develop.
