### ISSUE TITLE
Random_visual_effect_generator is missing

### ISSUE THREAD

**Issue by BogoK** [fizyr/keras-retinanet#1266]
The following import is not possible:` from utils.image import random_visual_effect_generator` since `image` in `utils` doesn't have the function `random_visual_effect_generator`

**Comment by vsuryamurthy** [comment]
random_visual_effect_generator exists in utils/image 

https://github.com/fizyr/keras-retinanet/blob/15814cb669d848e2a8b66b67ad6ba5c81cfc7181/keras_retinanet/utils/image.py#L282

Closing issue.
