### ISSUE TITLE
Training on images without any annotation

### ISSUE THREAD

**Issue by tadbeer** [fizyr/keras-retinanet#1268]
I have trained a model for a specific set of classes; but while testing on a new set of images, with none containing the trained set of classes, the model is detecting an another object class in those new images as one of the trained upon class.
To alleviate this problem, I intend to retrain my model with those new set of images added to the original training images set, such that the model might get an understanding of the falsely detected object class as not being one of the original set of trained classes.
Yet the format in which _csv_ method accepts data, any image without an annotation cannot be included in the training. Is there any way, by which I can work around this?
@hgaiser @yhenon

**Comment by hgaiser** [comment]
This is mentioned in the [README](https://github.com/fizyr/keras-retinanet#annotations-format).

**Comment by tadbeer** [comment]
oh, I apologise for not looking thoroughly?
