### ISSUE TITLE
Testing on my own data

### ISSUE THREAD

**Issue by kawshik8** [fizyr/keras-retinanet#127]
What is the preprocessing(Generators, resizing.....) to be done if I intend to test a model trained on my training data to predict outputs for my testing data?

I noticed you used COCOgenerator in your example for testing images !
Is there a generator that I can use for my test images?

**Comment by hgaiser** [comment]
In general the steps can be followed [here](https://github.com/fizyr/keras-retinanet/blob/master/keras_retinanet/preprocessing/generator.py#L111-L118). The steps in general are:

- Load the image
- Run `preprocess_image`
- (optional) randomly augment the image using `image_data_generator.random_transform`
- Resize the image using `resize_image`

If your testing data also contains annotations, the easiest to do is to create a `Generator` object for your testing data and use the `next` function from `Generator`.

**Comment by hgaiser** [comment]
In addition, if you want to create your own dataset, I recommend using the [CSV generator](https://github.com/fizyr/keras-retinanet/blob/master/keras_retinanet/preprocessing/csv_generator.py). Check the [README.md](https://github.com/fizyr/keras-retinanet#usage) for usage instructions.
