### ISSUE TITLE
AttributeError: module 'tensorflow_core._api.v2.image' has no attribute 'resize_images'

### ISSUE THREAD

**Issue by sudhirsilwal23** [fizyr/keras-retinanet#1271]
I have downgraded  tensorflow and keras version but still the same issue.                          
tensorflow==1.15.0 , Keras==2.2.4

**Comment by chefkoch10** [comment]
@sudhirsilwal23 the following solved the problem for me:
tf.compat.v1.image.resize(
    images,
    size,
    method=ResizeMethodV1.NEAREST,
    align_corners=False,
    preserve_aspect_ratio=False,
    name=None
)

**Comment by hgaiser** [comment]
Does keras 2.3.1 work for you?

**Comment by chefkoch10** [comment]
> Does keras 2.3.1 work for you?

Yes! I have keras 2.3.2 and tensorflow-gpu 2.0.0. Seems like downgrading to tf 2.0 works.

**Comment by Vortalcord** [comment]
Hello, I have keras version 2.3.1 and am experiencing the same issue when I call the keras_retinanet.models.load_model() function:
'AttributeError: module 'tensorflow._api.v2.image' has no attribute 'resize_images' '

**Comment by pikkaay** [comment]
> Hello, I have keras version 2.3.1 and tensorflow version 2.2.0 and am experiencing the same issue when I call the keras_retinanet.models.load_model() function:
> 'AttributeError: module 'tensorflow._api.v2.image' has no attribute 'resize_images' '

I had the same issue.

when I tried retinanet package installation **from repo instead of pip,** it worked.
