### ISSUE TITLE
Questions about image size and anchor

### ISSUE THREAD

**Issue by kknoob** [fizyr/keras-retinanet#1277]
I noticed that the anchor size is fixed.
sizes   = [32, 64, 128, 256, 512],
strides = [8, 16, 32, 64, 128],
ratios  = np.array([0.5, 1, 2], keras.backend.floatx()),
scales  = np.array([2 ** 0, 2 ** (1.0 / 3.0), 2 ** (2.0 / 3.0)], keras.backend.floatx()),
But  the input  image is resized so the smallest side is image-min-side.And it's default number is 800.
I want to know what input image size the anchor is designed for?
Or if I have some square pictures, what is the best input size to match the anchor?

**Comment by hgaiser** [comment]
The sizes are coming from the receptive field of the different pyramid levels in FPN (Feature Pyramid Network). Each feature vector on the first level (P3) has a receptive field of 32x32 on the original image. It doesn't have anything to do with the image sizes itself.
