### ISSUE TITLE
How to install keras-retinanet on a CPU-based mac pro?

### ISSUE THREAD

**Issue by LucyChen0228** [fizyr/keras-retinanet#1281]
Hi there,

Is there any possibility to install keras-retinanet on CPU-based laptop.

Here is one error I met. Btw, my keras = 2.3.1; python = 3.6.4. 

The methods I tried are as follows,

![methods](https://user-images.githubusercontent.com/42339395/74605438-207c7300-5103-11ea-9705-65bc063890a3.jpg)

The error I met is as follows, 

![error1](https://user-images.githubusercontent.com/42339395/74605456-4a359a00-5103-11ea-9063-f6168976b302.jpg)
![error2](https://user-images.githubusercontent.com/42339395/74605477-646f7800-5103-11ea-8cee-d7ef14373bc7.jpg)

Many thanks!

**Comment by hgaiser** [comment]
Seems more likely that there is an issue with your python environment. Can you install other packages the same way ?
