### ISSUE TITLE
Resource exhausted: OOM when allocating tensor with shape[1,94,167,512] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc

### ISSUE THREAD

**Issue by KulunuGeeganage** [fizyr/keras-retinanet#1284]
@hgaiser 

I'm using Anaconda environment with **python 3.6.1** and **tensorflow gpu 1.14.0**
**Graphic NVIDIA Geforce 920M** and running **keras-retinanet**

I'm getting following issue while training my custom data. (note.txt file attached here with)

Could you please help me to train my data set according to above specifications. 

**Input command**  

"python keras_retinanet/bin/train.py --weights resnet50_coco_best_v2.1.0.h5 --steps 400 --epochs 20 --snapshot-path snapshots --tensorboard-dir tensorboard csv dataset/train.csv dataset/classes.cs"

[note.txt](https://github.com/fizyr/keras-retinanet/files/4238948/note.txt)

**Comment by hgaiser** [comment]
Your GPU does not have enough memory to run keras-retinanet. I suggest at least 4gb of memory, yours seems to have 1.5gb.

**Comment by Shubhor05** [comment]
@hgaiser does your issue resolved after using 4GB of memory getting the same issue ?

**Comment by hgaiser** [comment]
4gb is a rough estimation, but with default values it should be enough.
