### ISSUE TITLE
28819 segmentation fault (core dumped) 

### ISSUE THREAD

**Issue by ouening** [fizyr/keras-retinanet#1285]
OS: Ubuntu18.04
keras: 2.3.1
tensofelow: 2.1
GPU: RTX2080 X 2
CUDA:10.1
cudnn: 7.6

Hi, when I use option `--multi-gpu 2 --multi-gpu-force`, I got an error:
`AttributeError: module 'tensorflow_core._api.v2.config' has no attribute 'experimental_list_devices'`

So I changed **line 506** in `keras/backend/tensorflow_backend.py ` to (reference to https://github.com/tensorflow/tensorflow/releases Release 2.1.0):
![image](https://user-images.githubusercontent.com/15122811/75104479-5e6a2180-5644-11ea-895d-d1cc76cd985c.png)

But I got another error:
`28819 segmentation fault (core dumped) `

my command is:
```
 python3 train.py --multi-gpu 2 --multi-gpu-force --backbone resnet50 --batch-size 2 --steps 10000 --snapshot-path snapshots/beverage csv .........
```

**Comment by hgaiser** [comment]
Segfaults are generally caused by libraries that we use. Main culprits are generally opencv or tensorflow. I don't think we can help you there.
