### ISSUE TITLE
ModuleNotFoundError: No module named 'keras_resnet'

### ISSUE THREAD

**Issue by Islam1Samir** [fizyr/keras-retinanet#1287]
I cloned the repository and although I have run python setup.py build_ext --inplace I am still getting 'ModuleNotFoundError: No module named 'keras_resnet'

**Comment by Islam1Samir** [comment]
I cloned the repository and although I have run python setup.py build_ext --inplace I am still getting 'ModuleNotFoundError: No module named 'keras_resnet'

**Comment by ahmedshahin9** [comment]
You should install by doing:
`install . --user`
in the repository folder, to be able to import keras_resnet.
Alternatively, if you want to stick to installing by:
`python setup.py build_ext --inplace`
you should navigate to the repository folder and do
`import keras_resnet`
there, however, this will raise errors if you followed the examples, as they assume you installed using the former approach.

**Comment by hgaiser** [comment]
This has been solved I guess. :+1:
