### ISSUE TITLE
How can I automatically convert model when creating checkpoints?

### ISSUE THREAD

**Issue by zmqp111** [fizyr/keras-retinanet#1289]
Hi, 

I want to automatically convert model when creating checkpoints in my project.

I tried to make a callback function, but i failed.

Did you have idea in my case?

Thanks, 

Regard

**Comment by hgaiser** [comment]
If you change [this](https://github.com/fizyr/keras-retinanet/blob/master/keras_retinanet/bin/train.py#L188) line to redirect to `prediction_model`, then it will save only converted (prediction) models.
