### ISSUE TITLE
model couldent recognize the class when i change min_side and max_side for input pics

### ISSUE THREAD

**Issue by dataman-py** [fizyr/keras-retinanet#1291]
hi

i trained my dataset by resnet50 with image-min-side = 800 and image-max-side = 1333 and have just one class.
i test it with min_side = 800 and max_side = 1333 i get correct answer , but when i change it to min_side = 112 and max_side = 112 , network couldent recognize my class.

plz help me

thx

**Comment by hgaiser** [comment]
There's two problems here, 1) is that the sizes you provided are too small (I wouldn't go much lower than 300x300), 2) training it on one size and testing it on another size gives reduced results.

**Comment by dataman-py** [comment]
@hgaiser  thanks for your answer
