### ISSUE TITLE
The steps based on the number of boxes or the number of images?

### ISSUE THREAD

**Issue by sooyeonshin** [fizyr/keras-retinanet#1293]
The steps based on the number of object(boxes) or the number of images?
example, let's say we have 1000 training images and 2000 objects. 
Should we set step to 1000 or 2000 if we want to include all that data in our training for 1epoch?(batch_size: 1)

**Comment by hgaiser** [comment]
You should do whatever you want ;)

That sounds a bit rude, but epochs don't mean anything to networks. Whether you train for 1 epoch and 500 steps or 2 epochs of 250 steps doesn't matter in the end. The only difference is the frequency of testing your model and how often a snapshot is saved.

That said, if you want to include all the data once per epoch, you should set it to the number of images divided by the batch size.

**Comment by sooyeonshin** [comment]
Thank you for answer my question.
In fact, the epoch or batch_size in the question is just an example, and the real question was whether one step was an image or an object. Based on your answers, it seems that the number of images is a standard, as with other CNN algorithms. Thanks again for the response.
