### ISSUE TITLE
Train on different resolution images 

### ISSUE THREAD

**Issue by Samjith888** [fizyr/keras-retinanet#1295]
I’m training on a dataset , which consist of different resolution images.. ( from 400x300 to 4020x2280

Here i have three questions 

1) Is keras retinanet work with different resolution images ?
2) i have train and text csv files here.. I want to evaluate the model ( to find AP) after every epoch . How to do this ?

**Comment by hgaiser** [comment]
> Is keras retinanet work with different resolution images ?

It does, but by default it will resize all images so that one side is 800px.

> i have train and text csv files here.. I want to evaluate the model ( to find AP) after every epoch . How to do this ?

There's a README for that ;)

**Comment by Samjith888** [comment]
> > Is keras retinanet work with different resolution images ?
> 
> It does, but by default it will resize all images so that one side is 800px.
> 
> > i have train and text csv files here.. I want to evaluate the model ( to find AP) after every epoch . How to do this ?
> 
> There's a README for that ;)

How you implemented tensorboard ? How to plot loss graph ?
