### ISSUE TITLE
tf_serving detection result decrease

### ISSUE THREAD

**Issue by wszph** [fizyr/keras-retinanet#1298]
Hello! I have a question . I can successfully transform keras model into tf_serving model , But in the test, the test results fell by 0.15-0.20 . what should i do ? This is my conversion code :

from keras import backend as K
import tensorflow as tf
from tensorflow.python import saved_model
from tensorflow.python.saved_model.signature_def_utils_impl import (
    build_signature_def, predict_signature_def)

from keras_retinanet import models
import shutil
import os

export_path = 'D:\svn\keras-retinanet-master\keras-retinanet-master\snapshots\\test_model'

# change to your model train num_classes
num_classes = 2
model = models.convert_model(
    model=models.backbone(backbone_name='resnet50').retinanet(num_classes=num_classes),
    nms=True,
    class_specific_filter=True,
    anchor_params=None
)

model.load_weights('D:\svn\keras-retinanet-master\keras-retinanet-master\snapshots\\resnet50_csv_09.h5')
print('Output layers', [o.name[:-2] for o in model.outputs])
print('Input layer', model.inputs[0].name[:-2])

if os.path.isdir(export_path):
    shutil.rmtree(export_path)

builder = saved_model.builder.SavedModelBuilder(export_path)
signature = predict_signature_def(
    inputs={'input': model.input},
    outputs={
        'loc_box': model.outputs[0],
        'hat_pre': model.outputs[1],
        'hat_class': model.outputs[2]})

sess = K.get_session()
builder.add_meta_graph_and_variables(sess=sess,
                                     tags=[saved_model.tag_constants.SERVING],
                                     signature_def_map={'predict': signature})
builder.save()
Thanks!

**Comment by hgaiser** [comment]
@vcarpani do you have an idea?

**Comment by vcarpani** [comment]
Which version of `tensorflow` and `keras` are you using?

**Comment by wszph** [comment]
@vcarpani tensorflow-gpu=1.14.0 keras=2.3.0

**Comment by RafayAK** [comment]
What is your inference code like?

**Comment by vcarpani** [comment]
> @vcarpani What is your inference code like?
@RafayAK 
My inference code is in c++, first i convert the model to tf saved model doing:
```
    outputs = {
        'filtered_detections':   model.outputs[0], # bbox
        'filtered_detections_1': model.outputs[1], # score
        'filtered_detections_2': model.outputs[2], # label
    # convert to tf model
    signature = tf.compat.v1.saved_model.signature_def_utils.predict_signature_def(
        inputs={'input_6': model.input},
        outputs=outputs
    )
    builder = tf.compat.v1.saved_model.builder.SavedModelBuilder(args.model_out)
    builder.add_meta_graph_and_variables(
        sess=keras.backend.get_session(),
        tags=[tf.compat.v1.saved_model.tag_constants.SERVING],
        signature_def_map={
            tf.compat.v1.saved_model.signature_constants.DEFAULT_SERVING_SIGNATURE_DEF_KEY: signature
        }
    )
    builder.save()
```

Then I load it in C++ using the tf saved model API
