### ISSUE TITLE
How do you deal with negative image examples (no annotations)?

### ISSUE THREAD

**Issue by zrachlin** [fizyr/keras-retinanet#130]
Is there a good way to deal with images that don't have any objects in them (negative examples)? I was previously using a bounding box of "0,0,0,0" with a class of 'None', but it seems like your most recent update now considers this an invalid box.

**Comment by hgaiser** [comment]
You can use a bbox of 0, 0, 1, 1. I would advise to use any existing class by the way (so not None) as this also means your network reserves space for this None class.

**Comment by de-vri-es** [comment]
You can also try PR #131.

**Comment by hgaiser** [comment]
Should be fixed by #131 , I will close this issue.
