### ISSUE TITLE
EfficientnetB3 giving lesser mAP compared to resnet50 backbone

### ISSUE THREAD

**Issue by Samjith888** [fizyr/keras-retinanet#1300]
I have trained a model by using resnet50 back bone, the result is following 
![keras-retina50_default_uppt04epch](https://user-images.githubusercontent.com/39676803/76059124-103e1200-5fa4-11ea-83b0-c6f180443959.png)

And then i tried with EfficientnetB3, 
![eff_github](https://user-images.githubusercontent.com/39676803/76059162-2ba91d00-5fa4-11ea-8d84-fcbc8a1e5fbd.png)

But the efficient net mAP coming down after 2nd epoch. In retinanet , the mAP for 2nd epoch was 0.6 , where the mAP in efficientnet is 0.2230 and even after the mAP coming down . In both the cases  i have passed a config.ini file while training .(Got from https://github.com/martinzlocha/anchor-optimization/)

**Comment by hgaiser** [comment]
Unless you can point out an issue in the code, I will close this issue. EfficientNet is a community contribution so I can't help you, plus it's very difficult to debug problems like this.
