### ISSUE TITLE
bounding box issue

### ISSUE THREAD

**Issue by aman1902** [fizyr/keras-retinanet#1303]
I'm trying to work on RSNA Pneumonia detection dataset.
1. I have scaled my input image from (1024 x 1024) to (224 x 224) which is scale(~0.2). After training the model I get a regression loss of 1.7 which is not good I guess. I have used around 10k images. Any suggestions will be very helpful.
2. During prediction, I have converted the model to inference model using convert_model(), but still i am getting bounding boxes of shape (1,300,4) and score of (1,300). 
This is code that I am using from your repo for drawing bounding boxes, with a few changes such as scale according to my image dimensions.

`def img_inference(img_path):
  image = read_image_bgr(img_infer)

  draw = image.copy()
  draw = cv2.cvtColor(draw, cv2.COLOR_BGR2RGB)
  scale=224/1024

  start = time.time()
  boxes, scores, labels = model.predict_on_batch(np.expand_dims(image, axis=0))
  print("processing time: ", time.time() - start)

  boxes*=scale

   for box, score, label in zip(boxes[0], scores[0], labels[0]):
      print(score)
      if score < THRES_SCORE:
          break

     color = label_color(label)

     b = box.astype(int)
     draw_box(draw, b, color=color)

     caption = "{} {:.3f}".format(labels_to_names[0], score)
     draw_caption(draw, b, caption)
  plt.figure(figsize=(5, 5))
  plt.axis('on')
  plt.imshow(draw)
  plt.show()`

<img width="695" alt="Capture" src="https://user-images.githubusercontent.com/29036050/76569252-a5776400-64d8-11ea-9a4a-8302a312fbe7.PNG">
<img width="697" alt="Capture4" src="https://user-images.githubusercontent.com/29036050/76569747-e1f78f80-64d9-11ea-9df4-ad9c37ac130a.PNG">
<img width="898" alt="Capture3" src="https://user-images.githubusercontent.com/29036050/76569303-ca6bd700-64d8-11ea-9299-dc594972b907.PNG">

I'm also attaching the annotations file for the images. If someone can please help me configure a network for the same.

[annotations.txt](https://github.com/fizyr/keras-retinanet/files/4326786/annotations.txt)

**Comment by hgaiser** [comment]
You can try using `retinanet-debug` to visualize your dataset, as described in the README. Since the issues are intended for issues with the code and not for usage questions (there is a slack channel for that), I will close this issue.

**Comment by parthkvv** [comment]
@aman1902 Were you able to find a solution to this issue, am in a similar situation. Running the debug.py file also did not display any bounding boxes.
