### ISSUE TITLE
Unit tests explaination

### ISSUE THREAD

**Issue by tienthegainz** [fizyr/keras-retinanet#1304]
Hi, I'm interested in your unit tests. I rarely see anyone do these kind of things for AI project. Can you tell me a little more details about your tests. And which test common to write? Thank you.

**Comment by hgaiser** [comment]
I don't know what you're referring to exactly; the unit tests?

**Comment by tienthegainz** [comment]
> I don't know what you're referring to exactly; the unit tests?

Yeah, I mean the unit test.

**Comment by hgaiser** [comment]
It should be common practice in a repo to write unit tests for the functions written. I don't know what else to tell you :p
