### ISSUE TITLE
Anchors close to each other

### ISSUE THREAD

**Issue by rvandeghen** [fizyr/keras-retinanet#1305]
Hello,

I would like to know if it is possible to change the stride for the anchors without changing the FPN. 

I use retinanet on satellite images and when objects are close to each other, it detects only one of them, even though those objects have the same shape and the distance between them is the same (like a pattern).

I already changed the size of the anchors s.t. it matches the size of my objects.

Thanks

**Comment by hgaiser** [comment]
You shouldn't change the stride unless you also change the backbone; the stride defines how the backbone is describing the image. Objects too close to each other is a challenging problem. You could try to increase the size of your image, possible cutting it up in multiple subparts?

**Comment by rvandeghen** [comment]
I know that if i change the stride i need to change the backbone. Also I have made huge gain of performances after some debugging on the anchors.
