### ISSUE TITLE
Error converting weights to inference mode

### ISSUE THREAD

**Issue by brunoeducsantos** [fizyr/keras-retinanet#1307]
Hi,
Converted **resnet50_coco_best_v2.1.0.h5** to inference mode using 

`keras_retinanet/bin/convert_model.py /path/to/training/model.h5 /path/to/save/inference/model.h5
`

 
I obtained the following error:

> UserWarning: No training configuration found in save file: the model was *not* compiled. Compile it manually.
>   warnings.warn('No training configuration found in save file:
> 

System setup:
* Python 3.6
* Ubuntu 16.04

Can someone help me?

Thanks,

Bruno

**Comment by hgaiser** [comment]
This is just a warning and can be ignored.
