### ISSUE TITLE
[tensorflow/core/framework/tensor_shape.cc:324] Check failed: size >= 0 (-1655719932 vs. 0)                                                                                                                   | Elapsed Time: 0:00:00 ETA:  --:--:--2020-03-19 18:16:48.267327: F tensorflow/core/framework/tensor_shape.cc:324] Check failed: size >= 0 (-1655719932 vs. 0)

### ISSUE THREAD

**Issue by BradleyBrown19** [fizyr/keras-retinanet#1308]
I am getting this error after an epoch when validation begins. It only happens when providing the --val_annotations flag (obviously something wrong with validation :)
```
Running network: N/A% (0 of 28296) Elapsed Time: 0:00:00 ETA:  --:--:--2020-03-19
```
```
18:16:48.267327:tensorflow/core/framework/tensor_shape.cc:324] Check failed: size >= 0 (-1655719932 vs. 0)
```
I am running tensorflow 1.15.0 on a gcp gpu instance.

Please let me know if anyone has any ideas or further feedback I can give to help resolve this issue. Thanks!

**Comment by CColten** [comment]
@BradleyBrown19  hello , I met the error, did u solve it ?

**Comment by CharlesDuv** [comment]
Hello, I met the same error. Any has ideas?

**Comment by CColten** [comment]
> Hello, I met the same error. Any has idea

you can try. 
https://github.com/triton-inference-server/server/issues/2368

**Comment by CColten** [comment]
> Hello, I met the same error. Any has ideas?

@CharlesDuv you can try.
triton-inference-server/server#2368

**Comment by shreyas-afk** [comment]
F tensorflow/core/framework/tensor_shape.cc:324] Check failed: size >= 0 (-1862366296 vs. 0)
Aborted (core dumped)
 i got a similar version of this error, i found out that this is not a memory/gpu issue as i was checking them while running the validation code.
