### ISSUE TITLE
Performance of optimized model

### ISSUE THREAD

**Issue by pravn** [fizyr/keras-retinanet#1309]
Thank you for the absolutely fantastic work in publishing this code. I was able to run the notebook successfully. That being said, I think it would be good to have some lines in the notebook that print out the timing numbers from the various optimized models. 

Could you tell us what perf improvements (timings) we could expect from running the optimized models?

I am hoping to use this for a real time application, for which we need fast detector performance. My code right now (from the mmdetection suite) gives about 200 ms on my laptop which is far too slow for our task. 

I am wondering if your optimized models (fp16, int8, etc.) can give good fps. Ultimately, we will of course want to port them to an embedded platform.

**Comment by hgaiser** [comment]
Unfortunately we don't have the time to provide these improvement statistics. If you make a project out of this then I can reference it on the main page.
