### ISSUE TITLE
Bad Training results for custom dataset 

### ISSUE THREAD

**Issue by poornimajd** [fizyr/keras-retinanet#1311]
I am trying to do object detection on Indian roads.I have 9 classes and around 20k images.I trained the model with resnet50_coco_best_v2 weights as the initial weights for around 20 epochs. I converted the trained model to inference and used examples/ResNet50RetinaNet.py to test on few new images.There is no detection with a score of above 0.25 ( this was the same case when I had previously trained the model without any pretrained weights just for 10 epochs).I kept number of steps as 20k per epoch and a batch size=1. So in the two trainings, I could not find any difference between the predictions of the models though the method of training is different.
Can someone please help me out on this? Am I going wrong somewhere?

**Comment by hgaiser** [comment]
Please refer to the keras-retinanet slack channel for usage help. The issues are for issues with the code.
