### ISSUE TITLE
ModuleNotFoundError: No module named 'cv2.cv2'

### ISSUE THREAD

**Issue by BieberZhang** [fizyr/keras-retinanet#1312]
when I use 
'python keras_retinanet/bin/train.py csv keras_retinanet/CSV/train_annotations.csv keras_retinanet/CSV/classes.csv --val-annotations keras_retinanet/CSV/val_annotations.csv
'  to train my datesets
and use 'python keras_retinanet/bin/train.py csv keras_retinanet/CSV/train_annotations.csv keras_retinanet/CSV/classes.csv --val-annotations keras_retinanet/CSV/val_annotations.csv
'to check my dataset
I meet the same issue that ModuleNotFoundError: No module named 'cv2.cv2'
I hope get your ansswer, thank you too much

**Comment by hgaiser** [comment]
It seems that your opencv isn't installed properly. Can't help you much there other than that :)
