### ISSUE TITLE
Objectness score

### ISSUE THREAD

**Issue by tpostadjian** [fizyr/keras-retinanet#1314]
Hello !
Is there any way to extract a class-independent objectness score that tells us is one anchor is likely to contain an actual object, no matter what is the actual class of the object ?

From what I understand, anchor filtering relies on a `tf.greater` operation performed on classification scores. I need for my project to make it class independent, as YOLO does with the objectness score that is returned along with coordinates and classification scores.

Thanks !

**Comment by hgaiser** [comment]
The goal of single stage object detectors is that you don't need to detect "objectness" first :package: 

You could take the max of all the classifications, but that "objectness" score will be limited to the classes in your dataset. If you want pure "objectness", then you will have to train it like that, or use a two-stage detector.
