### ISSUE TITLE
ImportError: Building module keras_retinanet.utils.compute_overlap failed

### ISSUE THREAD

**Issue by keersujiade** [fizyr/keras-retinanet#1316]
["distutils.errors.CompileError: command 'x86_64-linux-gnu-gcc' failed with exit status 1\n"]
I've tried every way, but they don't work....

**Comment by hgaiser** [comment]
Is that the complete error?

**Comment by keersujiade** [comment]
I have solve this problem by reinstall numpy, thx ~
