### ISSUE TITLE
How do I save the model and weight in one file

### ISSUE THREAD

**Issue by Programmerwyl** [fizyr/keras-retinanet#1319]
If I want to save the weight and structure of the model in a file, so I don't have to refactor the structure of the model.
```
model = models.load_model(model_path, backbone_name='resnet50')
model.save('D:/data/project_python/retinanet/model/retinanet_resnet50.h5')
```
model = load_model('D:/data/project_python/retinanet/model/retinanet_resnet50.h5')

It raises exception.
TypeError: ('Keyword argument not understood:', 'freeze')

How can I do this . thanks

**Comment by Programmerwyl** [comment]
```
custom_objects = {
    'BatchNormalization': layer_resnet.BatchNormalization,
    'UpsampleLike'     : UpsampleLike,
    'PriorProbability' : PriorProbability,
    'RegressBoxes'     : RegressBoxes,
    'FilterDetections' : FilterDetections,
    'Anchors'          : Anchors,
    'ClipBoxes'        : ClipBoxes,
    '_smooth_l1'       : smooth_l1(),
    '_focal'           : focal(),

}

model = load_model('D:/data/project_python/retinanet/model/retinanet_resnet50.h5',custom_objects=custom_objects)
```
Although I have save the model,the custom layers are not saved.
How can I solve it ?
thanks

**Comment by hgaiser** [comment]
Unfortunately you can't :)

What you listed is the correct way to do this.
