### ISSUE TITLE
Current status of this repo

### ISSUE THREAD

**Issue by haimat** [fizyr/keras-retinanet#1323]
Hi, first of all: Thanks for this repo.
It seems to be very promising!

Recently we have swtiched from native Keras to `tf.keras` and thus got rid of the standalone Keras framework. Now I have seen that you are migrating this repo to a new repo "tf-retinanet". So I am curious: What is the status of this fork/migration, is there any ETA on it? Why can't we just replace all dependencies on the Keras library with calls to `tf.keras` in this original repo?

Also, can I use this repo with TF2.1, or do I have to use TF1.x?

**Comment by vcarpani** [comment]
Hi, this repo can be used with tf2, however we do have a port of this repo, but it is still in experimental phase:
https://github.com/fizyr/tf-retinanet

**Comment by hgaiser** [comment]
The reason it is taking longer than just find replacing `keras` to `tf.keras` is because we wanted to do some refactoring of the code and configuration of the networks. [There](https://github.com/tensorflow/tensorflow/issues/33787) [are](https://github.com/tensorflow/tensorflow/issues/36829) [various](https://github.com/tensorflow/tensorflow/issues/37635) issues in tensorflow that made this pretty difficult and we still don't have a fully functioning package (hence the experimental part).

I could give it a shot to simply replace `keras` with `tf.keras` in this repo and make some backwards compatibility changes, to see if that works. I'll see if I can do that today :+1:

**Comment by haimat** [comment]
@hgaiser Wow, that sounds great, thanks a lot.
I would love to use your code directly with `tf.keras`, thanks guys!

**Comment by vsuryamurthy** [comment]
Closing as this is not an issue :P

**Comment by haimat** [comment]
Of course it's OK that you are closing this thread, as it is not an issue. But would you guys please be so kind and drop me a line here when you have switched to `tf.keras`? Thanks in advance!

**Comment by hgaiser** [comment]
Seems to work for me, can you give it a go?

https://github.com/fizyr/keras-retinanet/tree/tf-keras

To convert an old model to this branch, create a new empty model with the same structure, then call `model.load_weights(path)` and optionally save your model.

**Comment by haimat** [comment]
Wow, awsome, thanks a lot!
I will give it a go over the easter weekend and let you know.

**Comment by haimat** [comment]
> To convert an old model to this branch, create a new empty model with the same structure, then call `model.load_weights(path)` and optionally save your model.

I downloaded your new branch of this repo, compiled it and installed all dependencies. Then I downloaded the pre-trained models from https://github.com/fizyr/keras-retinanet/releases, however, when I try to run your example from the `/examples` sub directory using the `resnet50_coco_best_v2.1.0.h5` pre-trained model I do get the following error:

    Exception has occurred: AttributeError
    'Node' object has no attribute 'output_masks'
      File "/data/Development/Python/Keras-RetinaNet/keras-retinanet/keras_retinanet/models/__init__.py", line 87, in load_model
        return tf.keras.models.load_model(filepath, custom_objects=backbone(backbone_name).custom_objects)
      File "/data/Development/Python/Keras-RetinaNet/first-example.py", line 29, in <module>
        model = models.load_model(model_path, backbone_name="resnet50")`

Is this because of what you mentioned, that I have to create a new empty model first, or is this related to another problem? In the first case, could you please be so kind and elaborate on what you meant by _"create a new empty model with the same structure"_ - i.e. how do I achieve that?

**Comment by hgaiser** [comment]
Written from the top of my head, so this might be slightly incorrect:
```python
import keras_retinanet.models
model = keras_retinanet.models.backbone('resnet50').retinanet(80)
model.load_weights('<path to weights>')
model = keras_retinanet.models.convert_model(model)
model.save('<path to output>')
```
