### ISSUE TITLE
taking too much time when predicting object i have GPU  Quadro P4000, with 8 gb ram why it's taking ?

### ISSUE THREAD

**Issue by DeveloperRachit** [fizyr/keras-retinanet#1335]
taking too much time when predicting object i have GPU  Quadro P4000, with 8 gb ram why it's taking ?

**Comment by de-vri-es** [comment]
There is no way we can answer this question with the provided information.

**Comment by DeveloperRachit** [comment]
what kind of information i need to give you

**Comment by DeveloperRachit** [comment]
i am using pretrained model retinanet_resnet152_500_classes_0.4991.h5
