### ISSUE TITLE
ModuleNotFoundError: No module named 'keras_retinanet.utils.gpu'

### ISSUE THREAD

**Issue by charliewang789** [fizyr/keras-retinanet#1342]
can you help me understand why I got this error?

**Comment by IsaacPatole** [comment]
Hey @charliewang789 did you run this script : python setup.py build_ext --inplace  ?

**Comment by charliewang789** [comment]
Hey @IsaacPatole , yes i have done that and it won't help.  any further sugestion?

**Comment by IsaacPatole** [comment]
@charliewang789 did you install everything in requirements.txt?

**Comment by charliewang789** [comment]
@IsaacPatole yes, the training is working, it is just the detection that has problem. there was an older version that doesn't have SetupGPU, and it works fine for me.

**Comment by IsaacPatole** [comment]
Cool :D

**Comment by DeveloperRachit** [comment]
actually my gpu using memory but it's using 10% when i predicting to my images object using retina_resnet152

**Comment by datasciencemachine** [comment]
I am having the same problem too, can someone suggest me a way to solve it.

**Comment by yfpeng** [comment]
you have to install keras_retinanet==0.5.2.beta0
