### ISSUE TITLE
Filter detections nms not working properly

### ISSUE THREAD

**Issue by madelinehayes** [fizyr/keras-retinanet#1346]
Hi all, 
I have a large dataset that produces many overlapping bounding boxes after running my prediction code. I tried to alter the nms threshold in filter_detections.py and then I reran covert_model.py to convert my training model back to a inference model. Decreasing the nms threshold ended up producing way more overlapping bounding boxes than if I just left it at the default of 0.5. Am I missing something here, or is something wrong in the filter_detections.py script? 
Thanks.

**Comment by hgaiser** [comment]
Are the overlapping boxes of different classes, or the same class? Different classes don't cancel each other out, so they could overlap. You can change this behaviour with [this](https://github.com/fizyr/keras-retinanet/blob/master/keras_retinanet/bin/convert_model.py#L44).

If they're the same class, did you also try increasing the NMS IOU threshold? I agree it should be lower to get less overlaps, but might be worth a try :)

**Comment by madelinehayes** [comment]
> Are the overlapping boxes of different classes, or the same class? Different classes don't cancel each other out, so they could overlap. You can change this behaviour with [this](https://github.com/fizyr/keras-retinanet/blob/master/keras_retinanet/bin/convert_model.py#L44).
> 
> If they're the same class, did you also try increasing the NMS IOU threshold? I agree it should be lower to get less overlaps, but might be worth a try :)

The overlapping boxes are the same class. I've decreased the threshold (I tried 0.4, 0.3, 0.1) and increased the threshold (0.6, 0.7 0.8) - increasing and decreasing the threshold both produces a TON more overlapping boxes.
