### ISSUE TITLE
shear transform matrix bug

### ISSUE THREAD

**Issue by edwardyangxin** [fizyr/keras-retinanet#1348]
the shear matix now is:
![image](https://user-images.githubusercontent.com/13101725/81363374-c4c7f180-9115-11ea-9724-76eef8a272c4.png)

I don't understand why it just scale y axis here.

while on wiki it is:
![image](https://user-images.githubusercontent.com/13101725/81363424-df01cf80-9115-11ea-912a-44d652e3c3e5.png)

**Comment by de-vri-es** [comment]
We copied that pretty much from `keras`, to keep the augmentation the same. No particular reason other than that.
