### ISSUE TITLE
Label Smoothing

### ISSUE THREAD

**Issue by waylonflinn** [fizyr/keras-retinanet#1349]
Suggestions on how to implement label smoothing?

It looks like a modification in `anchor_targets_bbox` may be necessary, but what kind? It looks like this produced a label for each anchor but I don't really understand the format of the labels produced or how they relate to the input classes. Can you speak a bit on that or point me to documentation or other explanation?

Thanks.

**Comment by hgaiser** [comment]
It seems you can already use label smoothing from Keras:

https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/keras/losses.py#L558-L561

Which we use here:

https://github.com/fizyr/keras-retinanet/blob/master/keras_retinanet/losses.py#L58

**Comment by waylonflinn** [comment]
Thanks for the information. I don't currently understand how binary crossentropy is used to handle more than two classes, but this may work.

**Comment by pleaseRedo** [comment]
How can we integrate `keras.losses.binary_crossentropy`  with label_smoothing enabled into our code? 
As you mentioned in 
https://github.com/fizyr/keras-retinanet/blob/master/keras_retinanet/losses.py#L58
it is `keras.backend.binary_crossentropy()` but it does not have arg like `label_smoothing`
`keras.losses.binary_crossentropy()` allows `label_smoothing`, but changing `keras.backend.binary_crossentropy(labels, classification)` to `keras.losses.binary_crossentropy(labels,classification,label_smoothing=0.1)` function causes OOM issues, so I guess I'm using it in the wrong way?

**Comment by waylonflinn** [comment]
A note: this functionality (`label_smoothing`) was added to keras in 2.3.0

**Comment by waylonflinn** [comment]
Thanks for everyone's comments here. I've dug into both the implementation of focal loss in `keras_retinanet` and the implementation of `binary_cross_entropy` in keras and I think I understand both how the current implementation works (for hard targets) and why it won't work for soft targets (including those found in label smoothing).
I'm going to work through all the math to verify and then attempt to formulate a solution. If I manage to solve this issue are you open to a Pull Request?

**Comment by waylonflinn** [comment]
I've implemented a simple fix that allows soft targets (including smoothed labels) to work with the current loss function implementation. 

Even though I still have reservations about using this loss function for multiclass classification, I'll put together a PR later today, after a bit more testing.

**Comment by waylonflinn** [comment]
Here's the code I'm using to do the actual smoothing.

```python
def smooth_batch_labels(batch_labels, factor=0.1):
    """
        Args:
            batch_labels: array of shape [B, A, C+1]
                B: batch size, A: anchor count, C: class count
            factor: factor to smooth by
            
    """
    # remove anchor state
    labels = batch_labels[:, :, :-1] 
    # compute smoothed labels and replace
    batch_labels[:, :, :-1] = smooth_labels(labels, factor)
    
    return batch_labels
        
def smooth_labels(labels, factor=0.1):
	labels *= (1 - factor)
	labels += (factor / labels.shape[2])
	return labels
```

I call this in my pipeline after the call to `compute_targets` https://github.com/fizyr/keras-retinanet/blob/2267d76d36cd4c54dea65b34ca7b7f94048ff605/keras_retinanet/preprocessing/generator.py#L320

The calling code looks something like this:
```python

	Y = compute_targets(image_list, annotations_list, class_count)
    
        # extract labels
	batch_bboxes, batch_encoded_labels = Y
	# apply label smoothing
	batch_encoded_labels = smooth_batch_labels(batch_encoded_labels, factor=0.2)
        # repackage bboxes and labels
        Y = [batch_bboxes, batch_encoded_labels]
        
```

**Comment by AutumnZ-94** [comment]
Hey, I tried your code, 
and put 
your part 2 code after [https://github.com/fizyr/keras-retinanet/blob/2267d76d36cd4c54dea65b34ca7b7f94048ff605/keras_retinanet/preprocessing/generator.py#L360](url)here to call the part 1,  
`targets = self.compute_targets(image_group, annotations_group)
batch_bboxes, batch_encoded_labels = targets
# apply label smoothing
batch_encoded_labels = self.smooth_batch_labels(batch_encoded_labels)
targets = [batch_bboxes, batch_encoded_labels]
return inputs, targets`
then error raised:
`TypeError: list indices must be integers or slices, not tuple
group = self.groups[index]` which is in the __getitem__


Would you mind giving any advice if it works for you? Thanks :)
