### ISSUE TITLE
I get negative values for Bounding Boxes

### ISSUE THREAD

**Issue by HuviX** [fizyr/keras-retinanet#1359]
Hi. Just train your model on 105 class dataset. 
My classification and regression loss decreased really well during the training process. But when I try to .predict or .predict_on_batch my bounding box values are lies between **-1 and 1**. And this happens not only for new data but also on a train data. 
During train my classification_loss decreasing from 2.4 to 0.5 and regression loss from 4 to 0.9.
I also run retinanet-debug before training process to check if my bboxes are right.

Thank you!

**Comment by HuviX** [comment]
Resolved a problem by converting model to inference mode. 
by `retinanet-convert-model /path/to/training/model.h5 /path/to/save/inference/model.h5`. 
My fault (:

**Comment by mansi-aggarwal-2504** [comment]
I am having the same problem but I'm using the converted model only. Don't know what's going wrong :/

**Comment by nguyenquyem99dt** [comment]
I am having the same problem. Can anyone help me? :(((
