### ISSUE TITLE
keras_retinanet.layers.Anchor changes batch size

### ISSUE THREAD

**Issue by wassname** [fizyr/keras-retinanet#136]
My model fails when I used batch size of >1, and this seems to be the reason. No matter what batch size is used, anchors output a batch size of 1. Is this right or have I missed something?

Cheers

```py
import keras.layers
import keras_retinanet.layers
batch_size = 2
f=keras.layers.Input(batch_shape=(batch_size,4,4,256))
output = keras_retinanet.layers.Anchors(
        size=32,
        stride=8,
        ratios=np.array([ 0.5,  1. ,  2. ]),
        scales=np.array([ 1.        ,  1.25992107,  1.58740103]),
        name='anchors_{}'.format(0)
    )(f)
output
# <tf.Tensor 'anchors_0_26/ExpandDims:0' shape=(1, ?, 4) dtype=float32>
# output has batch_size=1, not 2

# it should be
l=keras_retinanet.layers.Anchors(
        size=32,
        stride=8,
        ratios=np.array([ 0.5,  1. ,  2. ]),
        scales=np.array([ 1.        ,  1.25992107,  1.58740103]),
        name='anchors_{}'.format(0)
    )
l.compute_output_shape((batch_size,4,4,256))
# (2, 144, 4)
```

**Comment by wassname** [comment]
Oh it seems like this is intended behavior since there is a [test](https://github.com/fizyr/keras-retinanet/blob/master/tests/layers/test_misc.py#L55) for it that is marked to fail?

**Comment by hgaiser** [comment]
Yes you're correct. It is fixed in https://github.com/fizyr/keras-retinanet/pull/111 but that PR needs a bit more work to be merged.

**Comment by wassname** [comment]
Great! Thanks for all the work on this.
