### ISSUE TITLE
'tensorflow._api.v2.image' has no attribute 'resize_images'

### ISSUE THREAD

**Issue by Vortalcord** [fizyr/keras-retinanet#1368]
Hello, I have keras version 2.3.1 and tensorflow version 2.2.0 and am experiencing the same issue as in the closed post (see below) when I call the keras_retinanet.models.load_model() function:
'AttributeError: module 'tensorflow._api.v2.image' has no attribute 'resize_images' '

_Originally posted by @Vortalcord in https://github.com/fizyr/keras-retinanet/issues/1271#issuecomment-633363438_

**Comment by Arushacked** [comment]
The function has been renamed into resize.
You should change your code like this: 
tf.image.resize(................)
