### ISSUE TITLE
You are using tensorflow version 2.0.0. The minimum required version is 1.14.0 (blacklisted: [(2, 0, 0), (2, 0, 1)]).

### ISSUE THREAD

**Issue by kmanojkkmr** [fizyr/keras-retinanet#1371]
when I execute the train.py using command
!python keras_retinanet/bin/train.py \
--freeze-backbone \
--random-transform --weights {PRETRAINED_MODEL} \
--batch-size 8 --steps 500 --epochs 10 csv train.csv classes.csv

I am getting below error. I want to use tensorflow 2.0 version and don't want to downgrade or upgrade it.

Using TensorFlow backend.
You are using tensorflow version 2.0.0. The minimum required version is 1.14.0 (blacklisted: [(2, 0, 0), (2, 0, 1)]).

Tensorflow - 2.0.0

Can you please help me on this.

**Comment by de-vri-es** [comment]
You must use a version of tensorflow that isn't blacklisted. So upgrade or downgrade :)
