### ISSUE TITLE
No module named keras

### ISSUE THREAD

**Issue by DispooL** [fizyr/keras-retinanet#1372]
Hello everyone!
I tried to train my own detector following this [tutorial](https://github.com/jaspereb/Retinanet-Tutorial) and I've faced a really strange problem. When I try to execute this command inside the repo keras_retinanet/bin/train.py --tensorboard-dir TrainingOutput --snapshot-path snapshots --random-transform --steps 100 pascal dataset I get an error says 'No module named keras'. But keras library is properly installed and I did all of the installation steps but using pip3. I would be really happy if someone will be able to solve my problem.

OS : Ubuntu 20.04
Python 3.7.3
`keras_retinanet/bin/train.py --tensorboard-dir TrainingOutput --snapshot-path snapshots --random-transform --steps 100 pascal dataset
Traceback (most recent call last):
  File "keras_retinanet/bin/train.py", line 24, in <module>
    import keras
ImportError: No module named keras
`

**Comment by maaz-bin-asad** [comment]
Hello , try the command sudo pip install keras in Linux distributions

**Comment by TimNagle-McNaughton** [comment]
Also having this issue when converting training to inference: 

- python 3.7.7
- keras 2.4.0
- tensorflow 2.2.0

`path\keras-retinanet\keras_retinanet\bin>convert_model.pypath\models\train_36.h5 path\TAR_retinanet\models\infer_36.h5
Traceback (most recent call last):
  File "path\keras-retinanet\keras_retinanet\bin\convert_model.py", line 31, in <module>
    from ..utils.config import read_config_file, parse_anchor_parameters
  File "path\keras-retinanet\keras_retinanet\bin\..\..\keras_retinanet\utils\config.py", line 19, in <module>
    import keras
ImportError: No module named keras`
