### ISSUE TITLE
Why copying the image in read_image_bgr()?

### ISSUE THREAD

**Issue by CodeJjang** [fizyr/keras-retinanet#1373]
What's the reason you perform copy in this function?
```
def read_image_bgr(path):
    """ Read an image in BGR format.
    Args
        path: Path to the image.
    """
    # We deliberately don't use cv2.imread here, since it gives no feedback on errors while reading the image.
    image = np.asarray(Image.open(path).convert('RGB'))
    return image[:, :, ::-1].copy()
```
I checked PIL docs, and although PIL performs lazy loading, it doesn't cache or duplicate image instances, so I don't see a reason to call `copy()` every time on every image, this should be very expensive.

**Comment by hgaiser** [comment]
As I remember, it was to create a contiguous array (which is a requirement further down the line), but it seems `ascontiguousarray` makes more sense. Could you make a PR for it?

**Comment by CodeJjang** [comment]
OK, working on it.
