### ISSUE TITLE
How to use pretrained weights which is in .pkl format

### ISSUE THREAD

**Issue by kmanojkkmr** [fizyr/keras-retinanet#1382]
Hello Team,

I have downloaded weights from the below link and it's in .pkl format. Could you please help me how to use it.

https://dl.fbaipublicfiles.com/detectron/ImageNetPretrained/25093814/X-152-32x8d-IN5k.pkl

I am using CPU system.

**Comment by hgaiser** [comment]
It is likely in a pytorch or caffe2 format, so it is not easily ported to keras.
