### ISSUE TITLE
Where does train.py save and can it be stopped early?

### ISSUE THREAD

**Issue by nsgalea** [fizyr/keras-retinanet#1389]
Hi I am just getting started with ML and am running the train.py on a custom dataset as a test to try and figure out how things work.  It's been pretty difficult finding good tutorials on training models, since most of the ones I tried didn't work.  I finally managed to get train.py running on my own dataset using the guide in the readme, but I am still not 100% sure how it works.

It says it is going to run for about 80 hours more.  I am wondering if it is possible to stop early with maybe a less accurately trained model?  Also does it actually save somewhere on my HD when it is done?  I was looking at the code and couldn't figure out if/how it saves.

Sorry for asking here, I don't know if this is the best place since it isn't really an "issue" with keras-retinanet, so much as an issue with my understanding of how it works.

**Comment by Gateway2745** [comment]
You can always stop your model after training for few epochs .The model will be saved in ./snapshots by default after every epoch.
