### ISSUE TITLE
Input Values

### ISSUE THREAD

**Issue by kawshik8** [fizyr/keras-retinanet#139]
If I have multiple bounding boxes for an image.
What is the format of the csv file to be generated?
"image_path,x1,y1,x2,y2,class" is the format for images with one bounding box.
Similarly what should be done for multiple boxes?

**Comment by zrachlin** [comment]
Just make another line in the csv file with the same image path and the new coordinates and class of the second object in the image.

**Comment by yhenon** [comment]
The readme seems quite clear about this, is there something not clear?

> A full example:
>/data/imgs/img_001.jpg,837,346,981,456,cow
>/data/imgs/img_002.jpg,215,312,279,391,cat
>/data/imgs/img_002.jpg,22,5,89,84,bird
>/data/imgs/img_003.jpg,,,,,
>This defines a dataset with 3 images. img_001.jpg contains a cow. img_002.jpg contains a cat and a bird. img_003.jpg contains no interesting objects/animals.

I'm closing this as it not an issue with the codebase.
