### ISSUE TITLE
Converting to saved_model-folder for TF Serving with TF2

### ISSUE THREAD

**Issue by johanneskpp** [fizyr/keras-retinanet#1390]
Hello, i am currently trying to convert a trained model to a saved-model-folder for tf serving. I trained the model with Tensorflow 2.2 and i did not found working code for the conversion. Can anybody help me? The most of the code I found is for TF 1.X and gets Problems while setting the session.

**Comment by metanav** [comment]
I am having the same issue. Has anybody tried to convert keras-retinanet model to Tensorflow 2 SavedModel successfully? Any hints or suggestions are welcome.

**Comment by aginpatrick** [comment]
Same issue for me. Has anybody succeeded to convert or save in the SavedModel format? It's very annoying as TF Serving only accepts that model format.
