### ISSUE TITLE
Use pycocotools new release

### ISSUE THREAD

**Issue by henrykironde** [fizyr/keras-retinanet#1396]
I would suggest to use the new release that is both on `Conda `and `Pypi` for `pycocotools`
git+https://github.com/cocodataset/cocoapi.git#subdirectory=PythonAPI

Unless there is a reason to use the dev branch.

**Comment by hgaiser** [comment]
Isn't that what we're using? https://github.com/fizyr/keras-retinanet/blob/master/requirements.txt
