### ISSUE TITLE
Ap value of each category in COCO dataset

### ISSUE THREAD

**Issue by mary-0830** [fizyr/keras-retinanet#1397]
Hello, I would like to ask, where can I find the code to calculate the ap value of each category?

My data set is similar to coco format, and currently only output such results:
Average Precision (AP)@[ IoU=0. 50: 0. 95 area- all maxDets-=100 ]=0.384
Average Precision (AP)@[ IoU=0. 50area= all maxDets=100]=0.633
Average Precision(AP)@L IoU=0.75 area = all maxDets=100]=0.408
Average Precision (AP)@[ IoU=0.50: 0.95 area= small maxDets=100
Average Precision (AP)@[ IoU=0. 50: 0.95 area=medium maxDets=100]=0.408
Average Precision (AP)@[ IoU=0. 50: 0. 95 area= large max Dets=100]=0.479
Average Recal(AR)@[ IoU=0. 50:0.95 area= all maxDets=1]=0.214
Average Recall (AR)@[ IoU=0. 50:0.95 area= all maxDets-=10]=0.444
Average Recal(AR)@[ IoU=0. 50:0.95 area= all maxDets-=100]=0.543
Average Recall (AR)@[ IoU=0. 50:0.95 area= small maxDets=100]=0.305
Average Recall(AR)@[ IoU=0. 50:0.95 area-medium maxDets=100]=0.596
Average Recall(AR)Iou=0. 50:0.95 area= large maxDets=100]=0.649

I want to generate ap values for each category, please give me pointers. Thanks, looking forward to your reply.

**Comment by Gateway2745** [comment]
It is in utils/eval.py
https://github.com/fizyr/keras-retinanet/blob/d9065ef63ae16c4ef3dac00123ce38c07b8128a0/keras_retinanet/utils/eval.py#L30-L56

**Comment by mary-0830** [comment]
> It is in utils/eval.py
> https://github.com/fizyr/keras-retinanet/blob/d9065ef63ae16c4ef3dac00123ce38c07b8128a0/keras_retinanet/utils/eval.py#L30-L56


my cmd：
python evaluate.py --image-min-side=600 --image-max-side=600 coco /home/zxc/DOTA/DOTA_clip_coco_600/DOTA_clip_coco_600/ ./models/resnet50_coco_06.h5 

I still don’t understand.So what is my order changed?
