### ISSUE TITLE
--random-transform debug.py images are transformed but bounding boxes are oddly transformed

### ISSUE THREAD

**Issue by naruto-raj** [fizyr/keras-retinanet#1399]
Hey, thank you for this excellent repository, ive been trying to retinanet for my custom dataset and got a 0.7 mAp but still on fideling with random transform in debug.py i find that the image and boxes are not transformed equally. any help is hugely appreciated.
![cropped_updated107_debug](https://user-images.githubusercontent.com/22745395/85782324-208d1f00-b744-11ea-9731-f5f232f5eb8a.jpg)
![cropped_updated186_debug](https://user-images.githubusercontent.com/22745395/85782331-2256e280-b744-11ea-97e7-7c17ffe617cf.jpg)
in one example the boxes are proper while in another they are very oddly transformed.(i am using defualt sizes just changed anchor ratios to fit my data)

**Comment by de-vri-es** [comment]
To me that just looks like what happens to axis-aligned bounding boxes when you "rotate" them. They're axis aligned, so they can not really be rotated. Instead, they grow to completely enclose the result of rotating the original bounding box.

I'm afraid there's nothing you can do about that with axis aligned bounding boxes (unless my diagnosis is wrong).

**Comment by naruto-raj** [comment]
Hey @de-vri-es thank you for sharing thing info. i wasnt aware of this fact. would it be correct to say that if i use bounding boxes with all 4 coordinates specified i would be able to do the augmentation better provided the model is built for regressing over 4 coordinates?

**Comment by de-vri-es** [comment]
Possibly, although 4 coordinates aren't even necessarily boxes anymore. However, `keras-retinanet` can't do that for you without a lot of manual modifications (which would be out of scope for this issue tracker).

You may be interested in [keras-maskrcnn](https://github.com/fizyr/keras-maskrcnn) though, which can be trained on masks rather than bounding boxes.

**Comment by naruto-raj** [comment]
Thank you for your valuable Input. :100:
