### ISSUE TITLE
converting your Trained model to an Inference Model

### ISSUE THREAD

**Issue by cavilest** [fizyr/keras-retinanet#1400]
I get the following error when I am trying to convert my trained model to inference model
tensorflow version 1.14.0
keras = 2.3.1
python 3.6

model = models.load_model(args.model_in, backbone_name=args.backbone, convert=True, nms=args.nms)
TypeError: load_model() got an unexpected keyword argument 'convert'

**Comment by Yongju-Jeong** [comment]
check models/__init__.py from your keras_retinanet directory. There is no arguments like 'convert' and 'nms' if you didn't change the codes.
To convert your training model to a inference model, check 'convert_model' function in the same folder. or check bin/convert_model.py

I usually convert my training model to a inference model with kile this.

python keras-retinanet\keras_retinanet\bin\convert_model.py .\RetinanetModels\YourTrainingModel.h5 .\RetinanetModels\YourInferenceModel_i.h5
