### ISSUE TITLE
Keras requires TensorFlow 2.2 or higher

### ISSUE THREAD

**Issue by ChunmianLin** [fizyr/keras-retinanet#1402]
Hi, everyone. I encountered this problem of keras bug as shown in following figure, could you please help me solve it? I checked my keras and tensorflow version, with both 2.x. But the problem is remained. What is the problem?
![Screenshot from 2020-06-30 16-42-44](https://user-images.githubusercontent.com/53289159/86104818-23e02c00-baf1-11ea-9fc4-648e11c014a9.png)

**Comment by hgaiser** [comment]
This is not related to keras-retinanet (the import error comes from Keras itself). Which versions are you using?

**Comment by ChunmianLin** [comment]
> This is not related to keras-retinanet (the import error comes from Keras itself). Which versions are you using?

what do you mean? My keras version is 2.4.3, but I confuse why this problem would occur?
![Screenshot from 2020-06-30 16-48-05](https://user-images.githubusercontent.com/53289159/86105160-92bd8500-baf1-11ea-8eee-77338d1a5f5b.png)

**Comment by hgaiser** [comment]
Hmm 2.4.3 ? I haven't used that version of Keras. You might have better luck with 2.3.1.

**Comment by ChunmianLin** [comment]
> Hmm 2.4.3 ? I haven't used that version of Keras. You might have better luck with 2.3.1.
Lower version would be better? I don't understand the reason behind it. Could you explain for  me in detail?
Thanks in  advance!
