### ISSUE TITLE
'Attempt to free invalid pointer' error while training

### ISSUE THREAD

**Issue by gal-elias** [fizyr/keras-retinanet#1405]
Hello,
Im using Google Colab to train and run a model and sometimes when i try to train the model, it works good and simetimes it stucks on this line:

> Using TensorFlow backend.
> 2020-07-02 08:10:10.564578: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.1

and after lots of times, it crushes and i get this:

> Attempt to free invalid pointer 0xc0b030b0a040a09

and it seems like it stucks on the same line every time because when i interrupt the run, i get those lines:

> Traceback (most recent call last):
>   File "/content/keras-retinanet/keras_retinanet/bin/train.py", line 547, in <module>
>     main()
>   File "/content/keras-retinanet/keras_retinanet/bin/train.py", line 478, in main
>     train_generator, validation_generator = create_generators(args, backbone.preprocess_image)
>   File "/content/keras-retinanet/keras_retinanet/bin/train.py", line 300, in create_generators
>     **common_args
>   File "/content/keras-retinanet/keras_retinanet/bin/../../keras_retinanet/preprocessing/csv_generator.py", line 161, in __init__
>     super(CSVGenerator, self).__init__(**kwargs)
>   File "/content/keras-retinanet/keras_retinanet/bin/../../keras_retinanet/preprocessing/generator.py", line 89, in __init__
>     self.group_images()
>   File "/content/keras-retinanet/keras_retinanet/bin/../../keras_retinanet/preprocessing/generator.py", line 291, in group_images
>     order.sort(key=lambda x: self.image_aspect_ratio(x))
>   File "/content/keras-retinanet/keras_retinanet/bin/../../keras_retinanet/preprocessing/generator.py", line 291, in <lambda>
>     order.sort(key=lambda x: self.image_aspect_ratio(x))
>   File "/content/keras-retinanet/keras_retinanet/bin/../../keras_retinanet/preprocessing/csv_generator.py", line 202, in image_aspect_ratio
>     image = Image.open(self.image_path(image_index))
>   File "/usr/local/lib/python3.6/dist-packages/PIL/Image.py", line 2818, in open
>     prefix = fp.read(16)
> KeyboardInterrupt

Any idea how to solve this?

**Comment by hgaiser** [comment]
I would guess this is a tensorflow issue, not a keras-retinanet issue.
