### ISSUE TITLE
How to execute evaluate.py in retinanet

### ISSUE THREAD

**Issue by mansi2421** [fizyr/keras-retinanet#1407]
\keras_retinanet\bin> python evaluate.py csv "C:\Users\user\Pedestrian-Object-Detection\dataset\test.csv" "C:\Users\user\Pedestrian-Object-Detection\dataset\classes.csv" "C:\Users\user\Pedestrian-Object-Detection\output\Pedestrianinference.h5"
I am using the same command but i amm getting the error
usage: evaluate.py [-h] [--model MODEL] [--backbone BACKBONE] [--gpu GPU]
[--score-threshold SCORE_THRESHOLD]
[--iou-threshold IOU_THRESHOLD]
[--max-detections MAX_DETECTIONS] [--save-path SAVE_PATH]
[--image-min-side IMAGE_MIN_SIDE]
[--image-max-side IMAGE_MAX_SIDE] [--config CONFIG]
{coco,pascal,csv} ...
evaluate.py: error: unrecognized arguments: C:\Users\user\Pedestrian-Object-Detection\output\Pedestrianinference.h5

can anyone please help me

**Comment by GlitchBox** [comment]
@mansi2421 have you managed to run evaluate.py
