### ISSUE TITLE
TypeError: type object got multiple values for keyword argument 'training'

### ISSUE THREAD

**Issue by nayyersaahil28** [fizyr/keras-retinanet#1412]
When I run the command:
retinanet-train csv path/to/annotations.csv path/to/classes.csv

I get this error : 

C:\Users\Saahil Nayyer\AppData\Roaming\Python\Python37\site-packages\keras_resnet\layers\_batch_normalization.py:17 call  *
        return super(BatchNormalization, self).call(training=(not self.freeze), *args, **kwargs)

    TypeError: type object got multiple values for keyword argument 'training'

I looked up the reason for the error and it turns out the first argument in call() should be self perhaps, but that again doesn't really help.

After many failed attempts with Faster-RCNN I have switched to Keras, please help me I'm stuck. Thank you in advance!

**Comment by damasubaie** [comment]
I fixed it by updating Keras
`pip install --upgrade keras==2.3.0`

**Comment by nayyersaahil28** [comment]
> I fixed it by updating Keras
> `pip install --upgrade keras==2.3.0`

Thank you @damasubaie . It worked.
