### ISSUE TITLE
Bounding boxes don't appear on Image

### ISSUE THREAD

**Issue by nayyersaahil28** [fizyr/keras-retinanet#1413]
I have successfully trained the retinanet with ResNet50 backbone consuming a whooping 5 hours. I ran the detection using the following script : https://github.com/fizyr/keras-retinanet/blob/master/examples/ResNet50RetinaNet.py

However, on my test image, no bounding boxes are shown. 

Can someone enlighten me on where the problem might be? 

Also in the log for the aforementioned script, I encounter this warning:

Garbage collection: deallocate free memory regions (i.e., allocations) so that we can re-allocate a larger region to avoid OOM due to memory fragmentation. If you see this message frequently, you are running near the threshold of the available device memory and re-allocation may incur great performance overhead. You may try smaller batch sizes to observe the performance impact. Set TF_ENABLE_GPU_GARBAGE_COLLECTION=false if you'd like to disable this feature.

Is there someway to get rid of this warning?

P.S. I trained the network on Geforce RTX 2080 8GB. 

I've attached the image. In expected case, there should be a bounding box around the 100 speed limit traffic sign. 

![Figure_1](https://user-images.githubusercontent.com/67515565/87051015-a917bf00-c21c-11ea-887a-db38279af15b.png)

All the inputs are highly appreciated. Thank you :)

**Comment by GlitchBox** [comment]
@nayyersaahil28 have you found any solution to this problem?

**Comment by mansi-aggarwal-2504** [comment]
Hi, did you find a solution to this? I raised a [similar issue](https://github.com/fizyr/keras-retinanet/issues/1479#issue-735016166) but if you could help, that'd be great!
