### ISSUE TITLE
Visualization.py

### ISSUE THREAD

**Issue by cavilest** [fizyr/keras-retinanet#1414]
I get this error cv2.putText(image, caption, (b[0], b[1] - 10), cv2.FONT_HERSHEY_PLAIN, 1, (0, 0, 0), 2)
TypeError: Expected Ptr<cv::UMat> for argument 'img' when running Visualization anyone have an idea what could be wrong, I really appreciate the help.

**Comment by ilyanelken** [comment]
I encounter the same exception. I will appreciate any assistance. Thanks, Ilya.

**Comment by ilyanelken** [comment]
@cavilest I think this might solve the issue:
https://answers.opencv.org/question/216152/typeerror-expected-cvumat-for-argument-img/

**Comment by mooratov** [comment]
casting `image` to `np.array` fixed it for me. This should probably be a PR 

```
--- a/keras_retinanet/utils/visualization.py
+++ b/keras_retinanet/utils/visualization.py
@@ -30,7 +30,7 @@ def draw_box(image, box, color, thickness=2):
         thickness : The thickness of the lines to draw a box with.
     """
     b = np.array(box).astype(int)
-    cv2.rectangle(image, (b[0], b[1]), (b[2], b[3]), color, thickness, cv2.LINE_AA)
+    cv2.rectangle(np.array(image), (b[0], b[1]), (b[2], b[3]), color, thickness, cv2.LINE_AA)


 def draw_caption(image, box, caption):
@@ -42,8 +42,8 @@ def draw_caption(image, box, caption):
         caption : String containing the text to draw.
     """
     b = np.array(box).astype(int)
-    cv2.putText(image, caption, (b[0], b[1] - 10), cv2.FONT_HERSHEY_PLAIN, 1, (0, 0, 0), 2)
-    cv2.putText(image, caption, (b[0], b[1] - 10), cv2.FONT_HERSHEY_PLAIN, 1, (255, 255, 255), 1)
+    cv2.putText(np.array(image), caption, (b[0], b[1] - 10), cv2.FONT_HERSHEY_PLAIN, 1, (0, 0, 0), 2)
+    cv2.putText(np.array(image), caption, (b[0], b[1] - 10), cv2.FONT_HERSHEY_PLAIN, 1, (255, 255, 255), 1)


 def draw_boxes(image, boxes, color, thickness=2):
```

**Comment by hgaiser** [comment]
If it wasn't an np.array, then what was it ? =\

**Comment by mooratov** [comment]
I think it was just passed as a list somehow

**Comment by juanmanuellopezcorrea** [comment]
File "keras-retinanet/keras_retinanet/bin/../../keras_retinanet/utils/visualization.py", line 45, in draw_caption
    cv2.putText(image, caption, (b[0], b[1] - 10), cv2.FONT_HERSHEY_PLAIN, 1, (0, 0, 0), 2)
TypeError: Expected Ptr<cv::UMat> for argument 'img'
i got the same error when I run :
keras-retinanet/keras_retinanet/bin/evaluate.py --gpu 0 --score-threshold 0.001 --convert-model --image-min-side 1296 --save-path "/Backup/home/jmlopez/retinanet/prediction"  --image-max-side 3000  csv "/home/jmlopez/RetinaNet/keras-retinanet/train_set.csv" "/home/jmlopez/RetinaNet/keras-retinanet/classes.csv" "/Backup/home/jmlopez/retinanet/snapshots/resnet50_csv_90.h5"  > results/test_90_001.txt
