### ISSUE TITLE
TypeError: type object got multiple values for keyword argument 'training'

### ISSUE THREAD

**Issue by KHBillel** [fizyr/keras-retinanet#1417]
![15950927193458034917207278063537](https://user-images.githubusercontent.com/46976573/87858087-3648cb00-c923-11ea-9a11-cee4f60d66b8.jpg)

**Comment by KHBillel** [comment]
@fizyr, can you help please!

**Comment by shivareddy37** [comment]
@KHBillel install keras 2.3.1 that should fix your issue

**Comment by KHBillel** [comment]
@shivareddy37
 it works!
Thanks a lot!
