### ISSUE TITLE
Why considering duplicate detections as false positives in eval.py?

### ISSUE THREAD

**Issue by prickly-u** [fizyr/keras-retinanet#1418]
Hello.
The issue is about this code fragment:
https://github.com/fizyr/keras-retinanet/blob/c38d54795ee85722104fd005c04b2240d088b1a2/keras_retinanet/utils/eval.py#L207-L217

That looks like a detection d that has overlap larger than iou_threshold, but with already detected annotation, will be considered as false_positive. But is it indeed? It seems to me that it is true positive, just duplicated, and it is better to make it contributing neither to false_positives, nor to true_positives count, like this:

``` python
if max_overlap >= iou_threshold: 
    if assigned_annotation not in detected_annotations:
        false_positives = np.append(false_positives, 0)
        true_positives  = np.append(true_positives, 1)
        detected_annotations.append(assigned_annotation)
    else:
        false_positives = np.append(false_positives, 0)
        true_positives  = np.append(true_positives, 0)       
else:
    false_positives = np.append(false_positives, 1)
    true_positives  = np.append(true_positives, 0)
```

**Comment by hgaiser** [comment]
I know this is a bit of a gray area, do you have any idea what is the "official" ruling for these cases? The current logic is derived from https://github.com/rbgirshick/py-faster-rcnn/blob/master/lib/datasets/voc_eval.py#L153-L189

**Comment by prickly-u** [comment]
@hgaiser To be honest, I do not possess knowledge about right ruling in this case. I suppose it is a gray area just because it doesn't affect many tasks due to bbox filtering by non-maximum supression. However, at our project we are trying to train and predict by cutting image into crops (to preserve hight resolution) that overlap each over. When merging them together in order to evaluate on the whole image, doubled bboxes can appear with much higher probability.

**Comment by hgaiser** [comment]
What I usually advise, but never tried, is applying NMS after merging all the bboxes together. You could even disable NMS from keras-retinanet to optimize computations, seeing as you'd be running it in the end anyway.

**Comment by prickly-u** [comment]
Yes, that can be a useful idea, thanks. Would you suggest adapting and reusing keras_retinanet/layers/filter_detections.py or write/import something else for simplicity in this case?

**Comment by hgaiser** [comment]
I think writing/importing something else will be simpler.

Can we close this issue?

**Comment by prickly-u** [comment]
Yes, it's better to close it. I think we shoud work out this moment in our project internally rather than change uncertan place affecting many people. Thank you!

**Comment by hgaiser** [comment]
:+1:
