### ISSUE TITLE
tensorflow.python.framework.errors_impl.InvalidArgumentError

### ISSUE THREAD

**Issue by VincentDuf** [fizyr/keras-retinanet#1419]
Hi,
I tried to infer on an image using a model I trained (and converted to infer model).
The image I try to infer on has a 1920x1080px shape, is it what's causing the error below ?

Thanks

```
Traceback (most recent call last):
  File "main.py", line 60, in <module>
    boxes, scores, labels = model.predict_on_batch(np.expand_dims(image, axis=0))
  File "/home/nvidia/.virtualenvs/cv/lib/python3.6/site-packages/keras/engine/training.py", line 1580, in predict_on_batch
    outputs = self.predict_function(ins)
  File "/home/nvidia/.virtualenvs/cv/lib/python3.6/site-packages/tensorflow_core/python/keras/backend.py", line 3476, in __call__
    run_metadata=self.run_metadata)
  File "/home/nvidia/.virtualenvs/cv/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1472, in __call__
    run_metadata_ptr)
tensorflow.python.framework.errors_impl.InvalidArgumentError: 2 root error(s) found.
  (0) Invalid argument: Incompatible shapes: [1,251664] vs. [1,188748]
         [[{{node boxes/mul_1}}]]
         [[filtered_detections/map/while/Identity/_1862]]
  (1) Invalid argument: Incompatible shapes: [1,251664] vs. [1,188748]
         [[{{node boxes/mul_1}}]]
0 successful operations.
0 derived errors ignored.
```

**Comment by hgaiser** [comment]
It sounds more likely that you are using an adjusted anchor parameters configuration? You also have to use it during inference / converting.

**Comment by VincentDuf** [comment]
Yes exactly, 
I'm using the juyter notebook script to lauch an inference and save the result image, where should I specify the config file path ? 
Is it in the "predict_on_batch" function ?

Thanks

**Comment by VincentDuf** [comment]
Hey, still waiting to know how to select the configuration file when infering

**Comment by hgaiser** [comment]
Hmm giving it a second thought, inference doesn't need the config, but conversion does. Did you use it [there](https://github.com/fizyr/keras-retinanet/blob/master/keras_retinanet/models/__init__.py#L97)?

**Comment by VincentDuf** [comment]
Hey,
I used the command "retinanet-convert-model" before using the generated inference model in the same main script you provide to do inference.

If I want to make the conversion inside the script I should add as you show the "anchor_params" but I don't get what is the shape or nature of this object ? 
When I use the command I just have to put "--config myconfig.ini" to make it happen, but inside the function I don't get what I should put.

Finally the drawing doesn't work for me, it saves (or shows) the image I draw on but I don't see any rectangle... 

Thanks

**Comment by hgaiser** [comment]
> When I use the command I just have to put "--config myconfig.ini" to make it happen

That is all you need to do.

> Finally the drawing doesn't work for me, it saves (or shows) the image I draw on but I don't see any rectangle...

If it saves the image then the original issue seems resolved. Not showing rectangle seems to be an issue with not having learned how to detect objects; it's difficult for me to help you debug that issue. Seeing as the original issue is resolved I will close this issue.

**Comment by VincentDuf** [comment]
Hey,
you didn't answer my question: if I want to use the "model.model_convert()" function, at the place for the "anchor_parameter" argument, what should I put ?

**Comment by hgaiser** [comment]
If you follow the way the configuration file is loaded and used in the convert script you will see how to use it.
