### ISSUE TITLE
evaluate.py doesn't run, shows error

### ISSUE THREAD

**Issue by GlitchBox** [fizyr/keras-retinanet#1421]
I've entered the command below 
**python3 evaluate.py --gpu 0 --save-path 'folder/' csv '/../dev-split.csv' '/../train-class.csv' 'snapshots/resnet50_csv_01.h5'**

But the following error appears:
**File "evaluate.py", line 199, in <module>
    main()
  File "evaluate.py", line 176, in main
    save_path=args.save_path
  File "../../keras_retinanet/utils/eval.py", line 174, in evaluate
    all_detections, all_inferences = _get_detections(generator, model, score_threshold=score_threshold, max_detections=max_detections, save_path=save_path)
  File "../../keras_retinanet/utils/eval.py", line 87, in _get_detections
    boxes, scores, labels = model.predict_on_batch(np.expand_dims(image, axis=0))[:3]
ValueError: not enough values to unpack (expected 3, got 2)**

**Comment by hgaiser** [comment]
Check  the [FAQ](https://github.com/fizyr/keras-retinanet#faq).
