### ISSUE TITLE
Retinanet-Debug not generating Bounding box

### ISSUE THREAD

**Issue by Sehjbir** [fizyr/keras-retinanet#1431]
I cloned the latest version of the keras-retinanet because i wanted to utilize the pyramid_level functionality added in config file. However I'm not able to get bounding boxes while running retinanet-debug. I was able to get the boxes for older versions of keras-retinanet.

**Comment by sindhura234** [comment]
@Sehjbir Did you manage to solve this issue?

**Comment by parthkvv** [comment]
@Sehjbir I am also facing the same issue, were you able to solve it?
