### ISSUE TITLE
Type object got multiple values for keyword argument 'training' with correct version of Keras

### ISSUE THREAD

**Issue by Sherryhh** [fizyr/keras-retinanet#1438]
I downgraded keras to 2.3.0 as the other posts suggested, but it did not fix my issue =(
What other reasons might cause this error to happen?
<img width="495" alt="Screen Shot 2020-08-12 at 2 22 38 AM" src="https://user-images.githubusercontent.com/38924560/89998674-b3294500-dc42-11ea-9e3e-1a0671b57207.png">

**Comment by Sehjbir** [comment]
pip install keras==2.3.1 solved the issue for me.

**Comment by Sherryhh** [comment]
> pip install keras==2.3.1 solved the issue for me.

I tried this but didn't work for me =(

**Comment by Sherryhh** [comment]
Fixed =)
