### ISSUE TITLE
Invalid box error 

### ISSUE THREAD

**Issue by adithya1111** [fizyr/keras-retinanet#1439]
Hey guys, I am using Keras-retinanet to do some object detection training on my own. I keep running into this
`/home/CONCURASP/kumara/.local/lib/python3.6/site-packages/keras_retinanet/preprocessing/generator.py:181: UserWarning: Image /datascience/adi/image_segmentation_training/prodigy_resized_images/p0013118l3fo_4F34DC007A1135EF8C648556DD18C229.png with id 3043 (shape (1700, 4400, 3)) contains the following invalid boxes: [[  26.   34.  643. 1907.]
 [  22. 2277.  602. 4365.]].`
But the boxes fit well into the image. The image width and height are 1700 4400 respectively. Is this because of the maxinum size restriction. How do we work around to include these boxes as wel ? Any help would be appreciated

**Comment by hansoli68** [comment]
Your image size is `width=4400px`, `height=1700px` but some of y positions are bigger than height (`1907`, `2277`, `4365`).
