### ISSUE TITLE
Fatal crash in the code after the latest commit 83d724a015b88f65a603f83b1be36f556b83135a

### ISSUE THREAD

**Issue by Msnkhosravi** [fizyr/keras-retinanet#1442]
It's not possible to train the code since 2 days ago when the commit 83d724a015b88f65a603f83b1be36f556b83135a was pushed.

ValueError: Tensor-typed variable initializers must either be wrapped in an init_scope or callable (e.g., `tf.Variable(lambda : tf.truncated_normal([10, 40]))`) when building functions. Please file a feature request if this restriction inconveniences you.

**Comment by hansoli68** [comment]
I could train a model with my custom csv dataset without any problems.

Could you check version of your environment? I currently using tensorflow 2.3.0 and keras 2.4.3

**Comment by Msnkhosravi** [comment]
> I could train a model with my custom csv dataset without any problems.
> 
> Could you check version of your environment? I currently using tensorflow 2.3.0 and keras 2.4.3

Thanks, Tensorflow version was the problem and now is fixed.
