### ISSUE TITLE
Annotation file.

### ISSUE THREAD

**Issue by kawshik8** [fizyr/keras-retinanet#145]
does x2,y2 in the annotation file point to top right corner coordinates or the width and the height?

**Comment by de-vri-es** [comment]
The bottom right corner actually. The first point is the top left corner :)

**Comment by kawshik8** [comment]
Why must y2 be greater than y1 then?

**Comment by hgaiser** [comment]
Because otherwise it doesn't define a bottom right corner.

Closing this as it's not an issue. Keep discussions on the slack channel (see the README for directions).
