### ISSUE TITLE
Failed to get convolution algorithm

### ISSUE THREAD

**Issue by BS-98** [fizyr/keras-retinanet#1452]
Hi,

when I start training I get error like this:

` tensorflow.python.framework.errors_impl.UnknownError:  **Failed to get convolution algorithm. This is probably because cuDNN failed to initialize**, so try looking to see if a warning log message was printed above. [[node retinanet/conv1/Conv2D (defined at keras_retinanet/bin/train.py:551) ]] [Op:__inference_train_function_13978]`

but before I get:
`E tensorflow/stream_executor/cuda/cuda_dnn.cc:328] Could not create cudnn handle: CUDNN_STATUS_ALLOC_FAILED`

So, is it a problem with my GPU? I have only 6GB. It could be memory growth issue? Or it is different problem?

I use tensorflow-gpu==2.3.0 and keras==2.4.3

**Comment by irtiza00** [comment]
Have a look at this.
https://medium.com/@JeansPantRushi/fix-for-tensorflow-v2-failed-to-get-convolution-algorithm-b367a088b56e
