### ISSUE TITLE
TypeError: 'InputLayer' object is not iterable

### ISSUE THREAD

**Issue by Msnkhosravi** [fizyr/keras-retinanet#1454]
Hi,

When I use vgg19/vgg16 as backbone and state --no-weights, I'm getting this TypeError: 'InputLayer' object is not iterable.

Any idea what I'm doing wrong here?

**Comment by finncottee** [comment]
Also getting this issue for both vgg16/vgg19 as well as Densenet backbones. Training using Imagenet weights

**Comment by hgaiser** [comment]
Should be fixed with https://github.com/fizyr/keras-retinanet/commit/332b3ebd148b874225ec73744c05fe798098c5ef , can you give that a try?

**Comment by Msnkhosravi** [comment]
> Should be fixed with [332b3eb](https://github.com/fizyr/keras-retinanet/commit/332b3ebd148b874225ec73744c05fe798098c5ef) , can you give that a try?

Seems working, thanks
