### ISSUE TITLE
Training not starting in Colab

### ISSUE THREAD

**Issue by lava18** [fizyr/keras-retinanet#1456]
I am trying to train keras-retinanet on my own dataset using the below command:
`!keras_retinanet/bin/train.py --freeze-backbone --weights {PRETRAINED_MODEL} --steps 50 --epochs 1 csv /content/drive/"My Drive"/dataset/annotations.csv /content/drive/"My Drive"/dataset/classes.csv
`

But the training is not starting. Only one output line is displayed:
`I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
`

Please help!

**Comment by Dawars** [comment]
Maybe drive is very slow, try copying "classes.csv" over the the colab machine
