### ISSUE TITLE
Random_transform

### ISSUE THREAD

**Issue by kawshik8** [fizyr/keras-retinanet#146]
What does random_transform do in generator.py?
Is it very necessary?

**Comment by hgaiser** [comment]
You mean why is it there if it just wraps one function? This way you allow someone to override what happens with `random_transform` in their own generator. The way `keras-retinanet` is set up allows the user to compute other things then class and bounding box regression per anchor, but those things would need to be correctly transformed as well. 

Please keep the GitHub issues for bugs and improvement. If you have questions about the workings of retinanet, check the slack channel (#keras-retinanet).
