### ISSUE TITLE
Have a new release

### ISSUE THREAD

**Issue by dslove** [fizyr/keras-retinanet#1461]
Since 0.5.2 there have been changes. Just wondering if there is a plan to have a new release?

**Comment by hgaiser** [comment]
No concrete plans, tensorflow keeps making things unstable. I believe we're at a stable state now though, not entirely sure.

**Comment by hgaiser** [comment]
A new version has just been released :+1:

**Comment by dslove** [comment]
Wonderful! Thanks~
