### ISSUE TITLE
change to onnx model

### ISSUE THREAD

**Issue by netilovefm1** [fizyr/keras-retinanet#1463]
I tried to change keras model to onnx 

but filter detection's  tf.map_fn not support 

so I tried to remove filter detection layer but now got 

AssertionError: retinanet-bbox/classification_submodel/pyramid_classification/Bi
asAdd/ReadVariableOp/resource:0 is disconnected, check the parsing log for more
details.

this error.. 

can this retina model change to onnx model?

**Comment by hgaiser** [comment]
No clue :) I've only recently started looking into ONNX for a different project. If `map_fn` is not supported, then how are loops created in ONNX ? ONNX should have a Loop operator. You could try to rewrite the `map_fn` to some other structure that allows to convert to ONNX maybe? `map_fn` is by now perhaps a bit of an outdated way to loop.

**Comment by netilovefm1** [comment]
hmm yeah... u said things all right maybe i think so but it's exatly error in filter detection's map_fn so i can't convert to ;;;

so i asked anyway thanks to ur reply 

i hope it will do ;;;

**Comment by Mixelon-tera** [comment]
Now, onnx runtime already supports keras-retinanet in this repo but onnx-tensor-rt not.

**Comment by QuantumLiu** [comment]
> Now, onnx runtime already supports keras-retinanet in this repo but onnx-tensor-rt not.

I'm trying to convert keras-retinanet to onnx too, would you tell me your version of keras-retinanet and onnx please?
And by th way, you can convert it into one output to make it work in tensorRT
