### ISSUE TITLE
How can I initialize network with random weights instead of pretrained imagenet weights

### ISSUE THREAD

**Issue by omeryasar** [fizyr/keras-retinanet#1472]
Hi,
I want to train retinanet from scratch with my dataset. To do that How can I initialize weights randomly  instead of fine-tuned imagenet weights ? 
Thanks in advance

**Comment by hgaiser** [comment]
https://github.com/fizyr/keras-retinanet/blob/master/keras_retinanet/bin/train.py#L426

:)

**Comment by omeryasar** [comment]
> https://github.com/fizyr/keras-retinanet/blob/master/keras_retinanet/bin/train.py#L426
> 
> :)

ah sorry I didn't pay attention enough to arguments. Thanks
