### ISSUE TITLE
When I use '--no-weights' parameter for training ap is 0

### ISSUE THREAD

**Issue by omeryasar** [fizyr/keras-retinanet#1475]
When I want to initialize weights randomly and training the model from scratch I get 0 ap even if I test my training set ? Any reccomendations or predictions why might it happens. Thanks

**Comment by hgaiser** [comment]
Why do you want to train from scratch? This is usually a very bad idea. When possible I would always suggest to start from som pretrained set of weights.

**Comment by omeryasar** [comment]
Experimental reasons. The image resolutions and relative object sizes are too small according to the task that pre-trained models trained on. I wonder what would I get if I train whole model from the very beginning. But as I mentioned something goes wrong and I can't figure out what is it
