### ISSUE TITLE
evaluation-py

### ISSUE THREAD

**Issue by juanmanuellopezcorrea** [fizyr/keras-retinanet#1477]
keras-retinanet/keras_retinanet/bin/evaluate.py --gpu 0 --score-threshold 0.001 --convert-model --image-min-side 1296 --save-path "/Backup/home/jmlopez/retinanet/prediction"  --image-max-side 3000  csv "/home/jmlopez/RetinaNet/keras-retinanet/train_set.csv" "/home/jmlopez/RetinaNet/keras-retinanet/classes.csv" "/Backup/home/jmlopez/retinanet/snapshots/resnet50_csv_90.h5"  > results/test_90_001.txt

I have this error when I want to save the drawn images

File "keras-retinanet/keras_retinanet/bin/../../keras_retinanet/utils/visualization.py", line 45, in draw_caption
    cv2.putText(image, caption, (b[0], b[1] - 10), cv2.FONT_HERSHEY_PLAIN, 1, (0, 0, 0), 2)
TypeError: Expected Ptr<cv::UMat> for argument 'img'

I have this error when I want to save the drawn images
Please someone know what the problem can be?

**Comment by anizeani** [comment]
casting image to np.array fixed it for me. This should probably be a PR

--- a/keras_retinanet/utils/visualization.py
+++ b/keras_retinanet/utils/visualization.py
@@ -30,7 +30,7 @@ def draw_box(image, box, color, thickness=2):
         thickness : The thickness of the lines to draw a box with.
     """
     b = np.array(box).astype(int)
-    cv2.rectangle(image, (b[0], b[1]), (b[2], b[3]), color, thickness, cv2.LINE_AA)
+    cv2.rectangle(np.array(image), (b[0], b[1]), (b[2], b[3]), color, thickness, cv2.LINE_AA)


 def draw_caption(image, box, caption):
@@ -42,8 +42,8 @@ def draw_caption(image, box, caption):
         caption : String containing the text to draw.
     """
     b = np.array(box).astype(int)
-    cv2.putText(image, caption, (b[0], b[1] - 10), cv2.FONT_HERSHEY_PLAIN, 1, (0, 0, 0), 2)
-    cv2.putText(image, caption, (b[0], b[1] - 10), cv2.FONT_HERSHEY_PLAIN, 1, (255, 255, 255), 1)
+    cv2.putText(np.array(image), caption, (b[0], b[1] - 10), cv2.FONT_HERSHEY_PLAIN, 1, (0, 0, 0), 2)
+    cv2.putText(np.array(image), caption, (b[0], b[1] - 10), cv2.FONT_HERSHEY_PLAIN, 1, (255, 255, 255), 1)


 def draw_boxes(image, boxes, color, thickness=2):

the solution is shown here: #1414
