### ISSUE TITLE
ValueError: Dimensions must be equal, but are 200145 and 120087 for '{{node retinanet-bbox/boxes/mul_1}} = Mul[T=DT_FLOAT](retinanet-bbox/boxes/add, retinanet-bbox/boxes/sub)' with input shapes: [1,200145], [1,120087].

### ISSUE THREAD

**Issue by divyanshmishra19** [fizyr/keras-retinanet#1478]
Trying to run the predict_on_batch function on a model I trained using 
`!keras_retinanet/bin/train.py \
 --random-transform \
 --freeze-backbone \
 --weights "/content/drive/My Drive/Colab Notebooks/Models/proteininfinity_06_final.h5" \
 --config "/content/drive/My Drive/Colab Notebooks/configinfinity.ini" \
 --tensorboard-dir tensorboard \
 --compute-val-loss \
 --batch-size 8 \
 --steps 400 \
 --epochs 20 \
 csv "/content/drive/My Drive/Colab Notebooks/annotation_infinity.csv" "/content/drive/My Drive/Colab Notebooks/classes.csv" \
--val-annotations "/content/drive/My Drive/Colab Notebooks/validation_infinity.csv" `

I am using weights from a model I trained prior without a frozen backbone. I then trained a new model using the previous one as a backbone. When I run predict on batch, I get the above error. When I try to use an inference model for the predict_on_batch function, I get the following error:
`Input is not a training model (no 'regression' and 'classification' outputs were found, outputs are: ['filtered_detections', 'filtered_detections_1', 'filtered_detections_2']).`

I have previously been able to use predict_on_batch. Not sure what has changed since then. Any help will be greatly appreciated

**Comment by minhaz109074** [comment]
Hey did you solve the problem?
I also facing same problem.

**Comment by divyanshmishra19** [comment]
My issue resolved with using a set of 3 aspect ratios in the config file
instead of 5. I was running with custom config which was causing the issue.
I hope this helps

**Comment by minhaz109074** [comment]
I also  used custom config with 9 aspect ratio.
so now i have to edit the config file and train again from scratch?

**Comment by divyanshmishra19** [comment]
I guess yeah. That’s what I had to do. Your model is trained on 9 aspect
ratios but there library can only convert models trained on 3 aspect ratios
for predict on batch function. I don’t know why this is and I didn’t try to
fix it since I got decent results.

Another thing to note is that evaluate.py works perfectly with more than 3
aspect ratios.

**Comment by minhaz109074** [comment]
Thanks brother

**Comment by minhaz109074** [comment]
Hey in convert-model.py there is a argument called --config to pass the custom config .I don't pass this argument during converting the model to the inference model. That's why script  uses default config file and the error is occurred.

**Comment by divyanshmishra19** [comment]
That could be it. I used the —config argument but I’m guessing I used two
different config files for training and converting. I was we king with
different datasets and each had different config files. Could have been a
mix up
