### ISSUE TITLE
Unable to load Trained model - `ValueError: Unknown layer: Functional`

### ISSUE THREAD

**Issue by Karthik-U-94** [fizyr/keras-retinanet#1480]
I have trained RetinaNet on my own dataset for 300 epochs, when I tried to load the 300th epoch model I am facing an issue, `ValueError: Unknown layer: Functional` Unable to proceed.
I am running this on Ubuntu 18.04 with 2080Ti GPU.

![Screenshot from 2020-11-03 12-34-53](https://user-images.githubusercontent.com/45176469/97958412-21f5e480-1dd3-11eb-8660-1d6dce23fdc6.png)
![Screenshot from 2020-11-03 12-34-58](https://user-images.githubusercontent.com/45176469/97958419-26220200-1dd3-11eb-94f7-c706d2be1459.png)

**Comment by cbodenst** [comment]
Got the seem error today. For me the issue was that I trained with tf 2.3 but tried to load the model with tf 2.2.
To resolve this update to tensorflow 2.3
