### ISSUE TITLE
evaluate.py: no visualisation of the detections in the saved output folder

### ISSUE THREAD

**Issue by anizeani** [fizyr/keras-retinanet#1490]
i run a .sh with following arguments:

python evaluate.py \
--backbone resnet50\
--gpu 0 \
--save-path $store_path \
--config $path_to_config \
csv $path_to_validations_csv $path_to_classes_csv $model \
--convert-model

with: 
path_to_classes_csv=$base_dir/classnameMapping.csv
path_to_validations_csv=$base_dir/imagesForEvaluation/label_test.csv
model=$base_dir/snapshots/resnet50_csv_06.h5
path_to_config=$base_dir/config.ini
store_path=$base_dir/storedImagesWithDetectionsAfterEvaluation

i get an mAP of 0.88 (great) and the images are stored in the defined folder, but there are no detections are shown... what do I do wrong or how can I visualize the detections?

**Comment by sindhura234** [comment]
@anizeani Did you solve this issue? Please help me out
