### ISSUE TITLE
AttributeError: 'BatchNormalization' object has no attribute '_preserve_input_structure_in_config'

### ISSUE THREAD

**Issue by enesayan** [fizyr/keras-retinanet#1496]
python resnet50_retinanet.py code giving above error 

Keras 2.2.4
Tensorflow 2.4.0

if not layer._preserve_input_structure_in_config:
AttributeError: 'BatchNormalization' object has no attribute '_preserve_input_structure_in_config'

**Comment by 5danalfaro** [comment]
@enesayan it is giving me the same error. Did you fix it?

**Comment by M93Pragya** [comment]
Kindly share the solution for this error

**Comment by abhishekw2021** [comment]
Please share the solution for this error

**Comment by yusufbarisk** [comment]
Same error. May it have something to do with package versions? Appereantly there is nothing reported like this before 2021
