### ISSUE TITLE
getting warning `steps_per_epoch * epochs` and average precision is 0.0000

### ISSUE THREAD

**Issue by dev2y** [fizyr/keras-retinanet#1497]
Hi, I am trying to train plums (PlumsVOC.zip) from this repo. (https://github.com/jaspereb/Retinanet-Tutorial)

I've installed TF2.3.0 and I am getting the following output for the following command. I did try everything said in this issue. https://github.com/fizyr/keras-retinanet/issues/1449.

Please let me know if you have successfully trained pascal VOC. Thank you very much

```
retinanet-train --batch-size 1  --snapshot-path /mnt/data/plums/TrainingOutput/snapshots --random-transform --steps 14 pascal /mnt/data/sy/plums/PlumsVOC

Total params: 36,403,702
Trainable params: 36,297,462
Non-trainable params: 106,240
__________________________________________________________________________________________________
None
WARNING:tensorflow:From /mnt/data/plums/plumenv2/lib/python3.6/site-packages/keras_retinanet/bin/train.py:549: 
Model.fit_generator (from tensorflow.python.keras.engine.training) is deprecated and will be removed in a future version.
Instructions for updating:
Please use Model.fit, which supports generators.

Epoch 1/50
11/14 [======================>.......] - ETA: 17s - loss: 3.9918 - regression_loss: 2.8627 - classification_loss: 1.1291WARNING:tensorflow:Your input ran out of data; interrupting training. 
Make sure that your dataset or generator can generate at least `steps_per_epoch * epochs` batches (in this case, 700 batches). 
You may need to use the repeat() function when building your dataset.

Running network: 100% (4 of 4) |####| Elapsed Time: 0:00:05 Time:  0:00:05
Parsing annotations: 100% (4 of 4) |####| Elapsed Time: 0:00:00 Time:  0:00:00

32 instances of class redPlum with average precision: 0.0000
0 instances of class greenPlum with average precision: 0.0000
mAP: 0.0000

11/14 [======================>.......] - 72s 7s/step - loss: 3.9918 - regression_loss: 2.8627 - classification_loss: 1.1291
<tensorflow.python.keras.callbacks.History object at 0x7f2bb42994e0>


```

**Comment by liuwenhua6666** [comment]
修改--steps ，steps*bachsize = 你的图片总数

**Comment by dev2y** [comment]
@liuwenhua6666 thank you.

I have set --steps 14. As I have 14 images and batchsize =1.

**Comment by hlmhlr** [comment]
> @liuwenhua6666 thank you.
> 
> I have set --steps 14. As I have 14 images and batchsize =1.

Your settings looks correct. Can you confirm that, among 14 images all of these you have set in train.txt file or you have copied some in val.txt file?
If you have total 14 images and you have cut and paste few images in val.txt file, now --steps parameters should be set as per number of images in train.txt file only. Simply, no. of images in train.txt file would be set in --steps arguments. This would rectify your error.

**Comment by dev2y** [comment]
@liuwenhua6666 thank you. That worked. I've had only 11 images in train.txt. I could start training with --steps 11. No errors.

But training started with 50 Epoch but it's failing to complete all 50. I've tried several times. Sometimes after 6 Epoch, sometimes it stops after 11 Epoch. 

Thank you very much for your help.

```
11/11 [==============================] - 67s 6s/step - loss: 3.8142 - regression_loss: 2.7474 - classification_loss: 1.0668
Epoch 5/50
Running network: 100% (4 of 4) |##############| Elapsed Time: 0:00:03 Time:  0:00:03
Parsing annotations: 100% (4 of 4) |############| Elapsed Time: 0:00:00 Time:  0:00:00
32 instances of class redPlum with average precision: 0.0019
0 instances of class greenPlum with average precision: 0.0000
mAP: 0.0019

11/11 [==============================] - 71s 6s/step - loss: 3.7147 - regression_loss: 2.7064 - classification_loss: 1.0083
Epoch 6/50
Running network: 100% (4 of 4) |#################| Elapsed Time: 0:00:04 Time:  0:00:04
Parsing annotations: 100% (4 of 4) |################| Elapsed Time: 0:00:00 Time:  0:00:00
32 instances of class redPlum with average precision: 0.0027
0 instances of class greenPlum with average precision: 0.0000
mAP: 0.0027

11/11 [==============================] - 72s 7s/step - loss: 3.5577 - regression_loss: 2.6566 - classification_loss: 0.9010
<tensorflow.python.keras.callbacks.History object at 0x7ff86036b400>
```

**Comment by hlmhlr** [comment]
@dev2y , look over [here](https://github.com/fizyr/keras-retinanet/issues/1355) for the resolution of stoping training issue after 6 and 11 epochs. 
You have to actually increase the value of patience parameter in the train.py file.

**Comment by dev2y** [comment]
@hlmhlr @jaspereb 
I tried to train the model using plums images (from https://github.com/jaspereb/Retinanet-Tutorial/blob/master/PlumsVOC.zip)but cost is reducing. It's toggling around 2.5, even after 50Epochs. According to @jjaspereb video, cost reduced to below 1.0 by 35 Epoch.

I am using the same images and same command.

retinanet-train 
  --batch-size 1  
  --snapshot-path plums/TrainingOutput/snapshots 
   --random-transform 
   --steps 14 
   pascal plums/PlumsVOC
