### ISSUE TITLE
Using keras-retinanet without FPN

### ISSUE THREAD

**Issue by Kanonck** [fizyr/keras-retinanet#1498]
Hi,
I would like to know whether or not it is possible to train the retinanet model without an FPN? How would I achieve this? I thought about changing the retinanet function in retinanet.py line 257 but it is listed there that this is the minimum model necessary for training.
Thanks in advance!

**Comment by hgaiser** [comment]
Theoretically it is possible, but we don't support it. If you want to do this you'd have to make quite some adjustments to the code.
