### ISSUE TITLE
Inference from debug.py and anchor size usage

### ISSUE THREAD

**Issue by hlmhlr** [fizyr/keras-retinanet#1505]
Hi, 

1. I just run the debug.py code to confirm the correctness of annotations. Instead of getting all the annotations in green (to be used in training) and red (not contributing for training), I observed the annotations in green color only and even just few annotations appeared on the image instead of all annotations when comparing with the original one. Here is the sample annotations in the original image (blue color, right side) and after passing from the debug.py file (green, left side). 
![bbox_mismatch](https://user-images.githubusercontent.com/67587354/104852790-2d9a7700-58fd-11eb-85ee-e1b0701e5d93.png)
2. In few other pics, red boxes also appeared but green boxes are not as same as in the original image as can be seen in this pic. 
![bbox_1](https://user-images.githubusercontent.com/67587354/104853018-6c7cfc80-58fe-11eb-8a9a-00c917d28c08.png)
3. Apart from this, how may i change the anchors sizes? And for changing anchor sizes, do i also need to change the stride, ratio and scale parameters. 

I shall be thankful for genereous response. 

Thanks,

**Comment by hlmhlr** [comment]
Hi, Could someone please help me out in clarifying the above mentioned queries. I shall be thankful. Thanks and Regards,

**Comment by hlmhlr** [comment]
> Hi,
> 
> 1. I just run the debug.py code to confirm the correctness of annotations. Instead of getting all the annotations in green (to be used in training) and red (not contributing for training), I observed the annotations in green color only and even just few annotations appeared on the image instead of all annotations when comparing with the original one. Here is the sample annotations in the original image (blue color, right side) and after passing from the debug.py file (green, left side).
>    ![bbox_mismatch](https://user-images.githubusercontent.com/67587354/104852790-2d9a7700-58fd-11eb-85ee-e1b0701e5d93.png)
> 2. In few other pics, red boxes also appeared but green boxes are not as same as in the original image as can be seen in this pic.
>    ![bbox_1](https://user-images.githubusercontent.com/67587354/104853018-6c7cfc80-58fe-11eb-8a9a-00c917d28c08.png)


Hi all, 
I just managed to resolve this matter by going through the code of generating the .csv file. Now, i have exactly the same bounding boxes in green color as in original image after running the debug.py.  
> 3. Apart from this, how may i change the anchors sizes? And for changing anchor sizes, do i also need to change the stride, ratio and scale parameters.

As for as i understood, By changing the length of aspect ratio and scale values, we change the number of anchors and their sizes. Also, keeping in view the object pixel sizes in the images, we can also change the anchor area (for example 16^2 instead of 32^2) so that mosre number of objects could be covered in an image. 
> 
> I shall be thankful for genereous response.
> 
> Thanks,

**Comment by sindhura234** [comment]
@hlmhlr Hi how did you use debug.py to view annotations? I am seeing the images but bboxes and anchors are missing. I used `python debug.py --anchors --show-annotations csv train.csv classes.csv`
Please help me out

**Comment by hlmhlr** [comment]
> @hlmhlr Hi how did you use debug.py to view annotations? I am seeing the images but bboxes and anchors are missing. I used `python debug.py --anchors --show-annotations csv train.csv classes.csv`
> Please help me out

Dear @sindhura234 , I used exactly the same command line parameters as you have mentioned for yours except "--anchors". So, try without this argument like "`python debug.py --show-annotations csv train.csv ". classes.csv

**Comment by sindhura234** [comment]
@hlmhlr Thanks for the reply...I tried even this, but I see no boxes drawn

**Comment by hlmhlr** [comment]
> @hlmhlr Thanks for the reply...I tried even this, but I see no boxes drawn

Dear @sindhura234 , I would recommend you verify the image path mentioned in the CSV file. Also,  check that you have used the correct format for objects inside the CSV file as mentioned in the fizyr keras retinanet main page. 

If still it doesn't work for you then I can do for you is to check your .CSV file  at my workstation, if so then just send me the CSV files containing the information of one image only and also that image.

**Comment by sindhura234** [comment]
[imgs.zip](https://github.com/fizyr/keras-retinanet/files/6016235/imgs.zip)

Thank you so much. I have attached two images along with CSV file. Please take a look into it. 
My path to the images was properly set in CSV files. I checked it once again. It is displaying the images but not annotations

**Comment by hlmhlr** [comment]
Dear @sindhura234 , 
As per data you provided, its working and showing the annotations on the images. Further, for your clarification i have attached sample test.csv file i used here. 

So, i would suggest you to set the image path inside the .csv as it is mentioned in the snapshot. Also, the sample command 
Apart from this, use the command as: "python .../bin/debug.py --show-annotations csv .../test_file.csv .../classes.csv"

Hope it works for you!



![test_image_1](https://user-images.githubusercontent.com/67587354/108607179-13056300-73bf-11eb-8e3b-1ed237c3d4ff.png)
![test_image_02](https://user-images.githubusercontent.com/67587354/108607182-17318080-73bf-11eb-9409-7abf5429ec35.png)
![test_sample csv](https://user-images.githubusercontent.com/67587354/108607186-1ac50780-73bf-11eb-9f8b-e4df9fd4a208.png)

**Comment by sindhura234** [comment]
@hlmhlr are you using the latest version? I am not getting why I'm not able to get this. I tried all the ways you suggested. I

**Comment by hlmhlr** [comment]
> @hlmhlr are you using the latest version? I am not getting why I'm not able to get this. I tried all the ways you suggested. I

Dear @sindhura234, I am using 1.0.0 version of keras-retinanet, and tensorflow 2.3.0. Have another check:  verify in the debug.py file that draw_annotations commands are not commented.

**Comment by sindhura234** [comment]
@hlmhlr thanks a lot

**Comment by hlmhlr** [comment]
> @hlmhlr thanks a lot

@sindhura234, you are welcome. Also  share that how Did you come up with your issue?

**Comment by parthkvv** [comment]
@cndu234 Were you able to solve the issue, am in similar situation.
As you mentioned, I too tried everything, but I am also seeing no boxes drawn.
Any help would be appreciated @hlmhlr

**Comment by parthkvv** [comment]
@cndu234 Were you able to solve the issue, am in similar situation.
As you mentioned, I too tried everything, but I am also seeing no boxes drawn.
Any help would be appreciated @hlmhlr
