### ISSUE TITLE
Training stopped after 11 steps in PlumsVOC dataset

### ISSUE THREAD

**Issue by lalitha-msu** [fizyr/keras-retinanet#1508]
There are 11 images in the train.txt of the PlumsVOC dataset and training is getting stopped after 11 steps. If I specify --steps 11 --epochs 20, then it is going to the next epoch. If I set steps to any number other than 11 it is saving the model and exiting.

**Comment by hlmhlr** [comment]
@lalitha-msu, look over [here](https://github.com/fizyr/keras-retinanet/issues/1355) to resolve the stop-training issue after few epochs (6, 11, ... epochs).  You have to actually increase the value of patience parameter in the train.py file.

Moreover, # of steps = # of images (set in training file) / batch-size. So, set the --steps argument value as per this formula.

**Comment by dev2y** [comment]
@hlmhlr as you suggested, I modified the value of patience at this line and it worked for me. 
https://github.com/fizyr/keras-retinanet/blob/master/keras_retinanet/bin/train.py#L210

It seems that cmd parameter -reduce-lr-patience should set the patience value but it didn't work for me. So, I updated the script.

**Comment by hlmhlr** [comment]
In general, "patience" value indicates for how many no. of epochs training shall be continued if your mAP value stops improving.   Well, thankyou for your feedback, it worked for you.  Further, how "-reduce-lr-patience" influencing the patience parameter, i am not sure about it.

**Comment by lalitha-msu** [comment]
Thank you all!! I changed -- steps = #of training images and it worked for 20 epochs and stopped training after that. No error, Patience = 5 was set. Are there any other parameters in training or evaluation I need to change? Bounding boxes were drawn on 3 plums out of 10 plums in the image. I changed confidence_cutoff in testDetector.py the bounding boxes were more but not selecting all the plums in the image

**Comment by hlmhlr** [comment]
> Thank you all!! I changed -- steps = #of training images --epochs = 50 and it worked for 20 epochs and stopped training after that. No error, Patience = 5 was set. Are there any other parameters in training or evaluation I need to change? Bounding boxes were drawn on 3 plums out of 10 plums in the image. I changed confidence_cutoff in testDetector.py the bounding boxes were more but not selecting all the plums in the image

@lalitha-msu , kindly insert  patience value equal to no.of epochs. Your training won't stop after 20 epochs and it shall run for the specified number of epochs. 

Moreover, if you want to get rid-off from this issue, remove early stopping call back from training script. Keeping it simple, just follow first point.

**Comment by lalitha-msu** [comment]
Thank you!! It worked by changing the patience value. I trained PlumsVOC dataset, with 11 images in training and 4 images in validation with 11 steps and 50 epochs. My mAP increased but when I ran testDetector.py, it was not detecting all the plums in the image. I tried changing the classification_cutoff in testDetector.py, but not of great use. Am I missing something? Do I need to change any other parameters or do I need to use weights from other models? Please let me know. Thanks!!!

**Comment by hlmhlr** [comment]
@lalitha-msu , weights of coco as suggest are sufficient. As for as no. of detections are concerned in the output image, i also experienced the same, and it is unsolved yet atleast for me. So, if you come up with solution then please do not forget to share your solution, thanks.

**Comment by dev2y** [comment]
I too tried PlumsVOC and it only detected 2 plums.  I think training set is not good enough.

**Comment by dev2y** [comment]
Closing this. 

Modify patience parameter here to continue to train.
https://github.com/fizyr/keras-retinanet/blob/master/keras_retinanet/bin/train.py#L210

ref: https://github.com/fizyr/keras-retinanet/issues/1508

**Comment by hlmhlr** [comment]
> I too tried PlumsVOC and it only detected 2 plums. I think training set is not good enough.

yes this could be.
