### ISSUE TITLE
training with bigger images

### ISSUE THREAD

**Issue by dev2y** [fizyr/keras-retinanet#1509]
Is it possible to train the model with images of size 2000x2000?

**Comment by hlmhlr** [comment]
@dev2y , Please have a look on the following issues related to input image with this retinanet project.
[Issue_157](https://github.com/fizyr/keras-retinanet/issues/157), [Issue_914](https://github.com/fizyr/keras-retinanet/issues/914), [Issue_341](https://github.com/fizyr/keras-retinanet/issues/341),  [Issue_519](https://github.com/fizyr/keras-retinanet/issues/519), [Issue_992](https://github.com/fizyr/keras-retinanet/issues/992). 
As per defalut configuration in current project, resized image size for training network is 1333x750. However, in general and in nutshell, processing of images with higher resolution requires larger gpu memory, batch-size parameter would be smaller, training time would be larger, and also few other related impacts. Further, have a thorough look on above mentioned issues.    
Hope you would get answer from these issues.

**Comment by dev2y** [comment]
Thank you @hlmhlr.
I modified the values in script from 1333x750 to 2000x2000 and tried to train. Cost is not going down and I did get several invalid box warnings.

Will go thru the issues.

**Comment by dev2y** [comment]
https://github.com/fizyr/keras-retinanet/issues/519#issuecomment-398889834

looks like we can avoid image resizing, if we have enough compute and memory.

But it says keras-retinanet can accept only 3D images, with 3 channels. Is it still true? That message was from 2018

thanks @hlmhlr

**Comment by dev2y** [comment]
Closing this. If we have enough computer and memory, we can train with bigger images.
