### ISSUE TITLE
Invalid annotations

### ISSUE THREAD

**Issue by dev2y** [fizyr/keras-retinanet#1511]
I am trying to train a model with bigger images (2000x2000x3). I have enough compute and memory and I am using the following training command

`python train.py --snapshot-path /TrainingOutput/snapshots --image-min-side 2000 --image-max-side 2000 --no-resize --epochs --random-transform --steps 12 pascal /TrainingData/
`

I get the following warning.

`TrainingData/JPEGImages/W09_6.jpg with id 8 (shape (2000, 2000, 3)) contains the following invalid boxes: [[ -1.  65.  44. 107.]].`

I did check my annotation xml file and I don't have this box. Instead I have this.

```
		<bndbox>
			<xmin>785</xmin>
			<ymin>65</ymin>
			<xmax>824</xmax>
			<ymax>94</ymax>
		</bndbox>
```

I am wondering if script is adjusting box to new image size, though I said no-resize.

Thanks\

**Comment by dev2y** [comment]
I reduced the images to 800x800 but I still get the same error. I double checked and I don't see any negative number in xml files. I did try with --no-resize option. 
No luck yet. Please let me know if some one has seen this error and found a solution.

**Comment by hlmhlr** [comment]
Dear @dev2y, how did youmanage to resize the images by maintaing the same sizes of bounding boxes of objects as well? Though this is not the solution towards your problem but i would be grateful if you could help me in any way. 

Thanks,

**Comment by dev2y** [comment]
@hlmhlr, we didn't resize. Instead we cropped smaller images from bigger images. Sorry. I should have been more clearer.
We wrote script to create new annotation files for the cropped images.

**Comment by hlmhlr** [comment]
> @hlmhlr, we didn't resize. Instead we cropped smaller images from bigger images. Sorry. I should have been more clearer.
> We wrote script to create new annotation files for the cropped images.

@dev2y , Ah okay, thanks for your response. I need to look for some other ways.
