### ISSUE TITLE
Width and height order

### ISSUE THREAD

**Issue by aginpatrick** [fizyr/keras-retinanet#1512]
I've noticed that the function that reads an image (`read_image_bgr` in `utils/image.py`) returns the image array in height, width order. For example, I have a 640x480 image that results in image.shape = (480,640,3). Unless I'm wrong this is the order that will be used to feed the model that normally "expects" an image in width,height order. I understand that this is simple convention and this not an issue if the model takes care of the bounding boxes in the same order but I just wanted to be sure if it's normal/desired behavior or not?

**Comment by hgaiser** [comment]
You are correct, it is normal behavior. We and all other implementations that I know of use the matrix convention of dimensions, where the first dimension is the height and the second the width.
