### ISSUE TITLE
AttributeError: module 'tensorflow._api.v2.summary' has no attribute 'scalar'

### ISSUE THREAD

**Issue by sindhura234** [fizyr/keras-retinanet#1514]
I am training on my custom dataset. I followed the documentation and was able to perform training successfully for about 25 epochs. I have seen no issues so far. But then i realised that i have not given the option to perform validation. So I used the following arguments
`python keras_retinanet/bin/train.py --imagenet-weights --batch-size 4 --gpu 2,3 --epochs 25 --steps 3000 --snapshot-path snapshots/ --tensorboard-dir tensorboard_dir/ --no-resize --weighted-average --compute-val-loss csv ../Train.csv ../class_mapping.csv --val-annotations ../Val.csv`
After one epoch at the end, I get the following error. Please let me know how to fix it. Is it because of the different TF versions?

`File "keras_retinanet/bin/../../keras_retinanet/callbacks/common.py", line 31, in on_epoch_end
    self.callback.on_epoch_end(epoch, logs=logs)
  File "keras_retinanet/bin/../../keras_retinanet/callbacks/eval.py", line 90, in on_epoch_end
    tf.summary.scalar("mAP", self.mean_ap, step=epoch)
AttributeError: module 'tensorflow._api.v2.summary' has no attribute 'scalar'`

I used
tensorflow-gpu==2.3.0
keras==2.4.0

**Comment by huberemanuel** [comment]
@sindhura234 any update on this?

**Comment by demongolem-biz** [comment]
I have the same error.  The thing to note is that on one computer this error arises but when I move to another computer it runs successfully.  I have yet to figure out any difference in environments that would cause this, but I need to resolved `tensorflow._api.v2.summary` has no attribute scalar

**Comment by Ben-Epstein** [comment]
for me at least, i needed to have tensorboard installed. I am not sure why though
`pip install tensorboard`

**Comment by TruscaPetre** [comment]
> for me at least, i needed to have tensorboard installed. I am not sure why though `pip install tensorboard`

THANK YOU SIR!

**Comment by Anil0205** [comment]
module 'tensorflow.compat.v2' has no attribute '__internal__'  Iam getting this error please help to sort out
