### ISSUE TITLE
Trained the model on 5000*8000 images. Got MAP=0.56. However while running inference I cannot see the bounding box. I see a random blue line. I have just got 1 class to detect.

### ISSUE THREAD

**Issue by Sehjbir** [fizyr/keras-retinanet#1522]

**Comment by Sehjbir** [comment]
I trained using --no-resize and without this parameter. I ran retinanet-debug and can clearly see annotations in green on all the images. any help ?

**Comment by Sehjbir** [comment]
I'm getting regression loss on train: 1.21 and classification loss on train: 0.15. On val: regression loss: 2.0 and classification loss is 0.46.

**Comment by arci97** [comment]
> I'm getting regression loss on train: 1.21 and classification loss on train: 0.15. On val: regression loss: 2.0 and classification loss is 0.46.



> I trained using --no-resize and without this parameter. I ran retinanet-debug and can clearly see annotations in green on all the images. any help ?

If not using --no-resize what size the images will be scaled?

**Comment by parthkvv** [comment]
@Sehjbir Did you find any solution?

**Comment by parthkvv** [comment]
@Sehjbir Did you find any solution to this? I am facing a similar issue. I really appreciate any help you can provide.

**Comment by parthkvv** [comment]
@Sehjbir  Did you find any solution to this? I am facing a similar issue. I'll really appreciate any help you can provide.
