### ISSUE TITLE
How to convert the generated models to TF servable model? 

### ISSUE THREAD

**Issue by neda60** [fizyr/keras-retinanet#1525]
I am using TF 2.3.1 and Keras-retinanet 1.0, I used [this code](https://github.com/fizyr/keras-retinanet/issues/676#issuecomment-508958949) and got an error `RuntimeError: build_tensor_info is not supported in Eager mode. on output3': model.outputs[2]`
After googling I inserted :
```
if tf.executing_eagerly():
tf.compat.v1.disable_eager_execution()
```

so model was converted but with a very small volume for the .pb file (the .h5 file is 437 MB while the pb file is 465 Bytes) and an empty variable folder. Is is normal???
Also, when tried to load the TF model for prediction `loaded = tf.saved_model.load("./retinanet_savedmodel/")` I get this error:
`KeyError: "The name 'input_1:0' refers to a Tensor that does not exist. The operation, 'input_1', does not exist in the graph."`
It is blocking me. Can anybody help?

**Comment by Mps24-7uk** [comment]
@neda60 did you get the solution?

**Comment by neda60** [comment]
> @neda60 did you get the solution?

Unfortunately not!

**Comment by mateoochoa** [comment]
I have the same problem of now, and I didn't get any solution, can anybody help?, please :)
