### ISSUE TITLE
test model

### ISSUE THREAD

**Issue by levinhhoang16** [fizyr/keras-retinanet#1527]
ImportError: cannot import name 'load_model' from 'keras_retinanet.models' (unknown location)

**Comment by Unice-CS** [comment]
I encountered the same problem, did you solve it?

**Comment by levinhhoang16** [comment]
you need install keras,retinet .lets check your enviroment

**Comment by Unice-CS** [comment]
> you need install keras,retinet .lets check your enviroment

I installed it again and solved the problem. Thanks a lot!!!
