### ISSUE TITLE
is there any restrictions for training images

### ISSUE THREAD

**Issue by SepidehAlassi** [fizyr/keras-retinanet#153]
Hi, 

in my train data I have 71 classes, I am using train_csv

after creation of model, its summary includes:

anchors_4 (Anchors)             (None, None, 4)      0           P7[0][0]                         
__________________________________________________________________________________________________
regression (Concatenate)        (None, None, 4)      0           regression_submodel[1][0]        
                                                                 regression_submodel[2][0]        
                                                                 regression_submodel[3][0]        
                                                                 regression_submodel[4][0]        
                                                                 regression_submodel[5][0]        

and keras throw error below:
  File "Library/Python/2.7/lib/python/site-packages/keras/engine/training.py", line 153, in _standardize_input_data
    str(array.shape))
ValueError: Error when checking target: expected regression to have shape (None, None, 4) but got array with shape (1, 71550, 5)

can you please help me understand this error?

**Comment by hgaiser** [comment]
Are you by any chance running Keras 2.1.0 or 2.1.1? If so, try updating both `keras-retinanet` and `keras`.

**Comment by SepidehAlassi** [comment]
I was running keras 2.1.1, now I updated to 2.1.2. Running with version 2.1.2 solved the issue. Thank you for the hint.
