### ISSUE TITLE
monitor mAP??

### ISSUE THREAD

**Issue by chairiq** [fizyr/keras-retinanet#1533]
How can I monitor the mAP while training, or just to check it at the end of the training?

**Comment by tamasbalassa** [comment]
By looking first through the existing issues, you can find this https://github.com/fizyr/keras-retinanet/issues/1435#issuecomment-703423869 in 15 seconds.

However I was not able to make the validation work during training time, only to evaluate the converted model with the _retinanet-evaluate_ command.
