### ISSUE TITLE
Bug in mAP calculation

### ISSUE THREAD

**Issue by AndreiIonut1** [fizyr/keras-retinanet#1534]
I trained the network to detect faces and faces with masks. In the following image we have 2 persons and we should get 2 predictions with class "face". However we also get a 3rd prediction of "face_mask". 
![0](https://user-images.githubusercontent.com/61600244/118937243-fd6bef00-b955-11eb-9a3f-a83dbf4f88cb.png)

Running the evaluation script on a dataset made only of this image I get the following result:
```
2 instances of class face with average precision: 1.0000
0 instances of class face_mask with average precision: 0.0000
Inference time for 1 images: 3.6936
mAP using the weighted average of precisions among classes: 1.0000
mAP: 1.0000
```
Having precision = 1.0 doesn't seem right because the model produced a false positive(the orange bounding box). Any idea why this happens? Shouldn't the precision be lower since we have a 3rd prediction which is wrong?

**Comment by hgaiser** [comment]
I see what you mean, but the following logic is applied:

- The face masks were all correctly identified so it should have a precision of 1.0. 
- There are no annotations of face_mask, so it gets weight 0 for computed the "weighted average of precisions".

Would be nice if there was an option to disable the "weighted" part of computing the average of precisions, but there currently isn't :).

**Comment by AndreiIonut1** [comment]
This makes sense, but I believe there is more to it. Consider the next image:
![0](https://user-images.githubusercontent.com/61600244/119527904-6ce44300-bd89-11eb-8a13-57663f231378.png)

Again, one correct "face" detection and a few false positives. 
1 instances of class face with average precision: 1.0000
0 instances of class face_mask with average precision: 0.0000
Inference time for 1 images: 4.0214
mAP using the weighted average of precisions among classes: 1.0000
mAP: 1.0000

"1 instances of class face with average precision: 1.0000"
I don't get how "face" can have 100% precision. It looks like the code completely ignores false positives.

**Comment by hgaiser** [comment]
Some weird faces to the right there :p but it sounds like you are correct.
