### ISSUE TITLE
Cant save the model!!! Get TypeError('Not JSON Serializable:', obj) 

### ISSUE THREAD

**Issue by whoisibooo** [fizyr/keras-retinanet#1535]
After first epoch training I can't save the snapshots and I get this error. 

File "/home/rsns01/stud/it/iboeit00/unix/miniconda3/envs/valet-parking/lib/python3.8/site-packages/tensorflow/python/keras/saving/saved_model/json_utils.py", line 143, in get_json_type
    raise TypeError('Not JSON Serializable:', obj)
TypeError: ('Not JSON Serializable:', <tf.Variable 'conv1/kernel:0' shape=(7, 7, 3, 64) dtype=float32, numpy=
array([[[[ 2.82848626e-03, -3.72060202e-02,  9.90435854e-03, ...,
          -1.79686360e-02,  7.66428187e-03, -2.83039510e-02],

and 

TypeError: Layer tf.nn.convolution was passed non-JSON-serializable arguments. Arguments had types: {'filters': <class 'tensorflow.python.ops.resource_variable_ops.ResourceVariable'>, 'strides': [<class 'int'>, <class 'int'>], 'padding': <class 'str'>, 'dilations': [<class 'int'>, <class 'int'>], 'data_format': <class 'str'>, 'name': <class 'str'>}. They cannot be serialized out when saving the model.

Have someone any idea how can I solve this problem ?

**Comment by JulietaAbuin** [comment]
I've been using the library fine but today i got the same error and dont know how to fix it

**Comment by leksandre** [comment]
I also get same problem

**Comment by leksandre** [comment]
great, solved it by 4 commands

  pip3 install tensorflow==2.3.0
  pip3 install tensorflow-gpu==2.3.0
  pip3 install --user git+https://github.com/cocodataset/cocoapi.git#subdirectory=PythonAPI
  pip3 install keras==2.4

**Comment by whoisibooo** [comment]
@leksandre which python version do you use?

**Comment by JulietaAbuin** [comment]
I keep getting the same error but the python version colab is using in my case is Python 3.7.10. How can I change that?

**Comment by leksandre** [comment]
> I am getting this error now: " LOCAL.GENERATED_WITH_V2 = tf.**internal**.tf2.enabled()
> AttributeError: module 'tensorflow.compat.v2' has no attribute '**internal**'"
> but the python version colab is using in my case is Python 3.7.10. How can I change that?

here shows how downgrade python 
https://stackoverflow.com/questions/60775160/install-python-3-8-kernel-in-google-colaboratory
or here 
https://stackoverflow.com/questions/66775948/downgrade-python-version-from-3-7-to-3-6-in-google-colab
it not an easy way

but all of errors like "has no attribute" "or has no method" it only from incompatible version between keras and tensorflow
a you sure made "pip install" like I show earlier?

**Comment by mateoochoa** [comment]
> I am getting this error now: " LOCAL.GENERATED_WITH_V2 = tf.**internal**.tf2.enabled()
> AttributeError: module 'tensorflow.compat.v2' has no attribute '**internal**'"
> but the python version colab is using in my case is Python 3.7.10. How can I change that?

Hi, I'm getting the same problems and change the version of python is not working, not at least for me, because if I downgrade it some libraries does not have the minimum version available. Any idea to solve this problem in google colab?

**Comment by leksandre** [comment]
> > I am getting this error now: " LOCAL.GENERATED_WITH_V2 = tf.**internal**.tf2.enabled()
> > AttributeError: module 'tensorflow.compat.v2' has no attribute '**internal**'"
> > but the python version colab is using in my case is Python 3.7.10. How can I change that?
> 
> Hi, I'm getting the same problems and change the version of python is not working, not at least for me, because if I downgrade it some libraries does not have the minimum version available. Any idea to solve this problem in google colab?

I try repeat yours exception on python 3.7.7 it seems error was here pip3 install `tensorflow-gpu==2.3.0` try this `pip3 uninstall tensorflow-gpu` if it still give  you error, try to clean dirrectory <python-setup-path>/Lib/site-packages from all packages like "tf-*", "tensor*", ""keras*" and resetup this packages  again

**Comment by aleperaltabazas** [comment]
I got the same error as mentioned by @JulietaAbuin . I was able to progress a bit further thanks to the accepted response on the first SO post provided by @leksandre , along with the replies explaining that anaconda should be exported to PATH. For reference, these are the commands I used in Colab to circumvent the tensorflow issue:

```python
# install Anaconda3
!wget -qO ac.sh https://repo.anaconda.com/archive/Anaconda3-2020.07-Linux-x86_64.sh 
!bash ./ac.sh -b

# a fake google.colab library
!ln -s /usr/local/lib/python3.7/dist-packages/google \
       /root/anaconda3/lib/python3.8/site-packages/google

# start jupyterlab, which now has Python3 = 3.8
!nohup /root/anaconda3/bin/jupyter-lab --ip=0.0.0.0&

# access through ngrok, click the link
!pip install pyngrok -q
from pyngrok import ngrok
print(ngrok.connect(8888))

import os
os.environ['PATH'] = '/root/anaconda3/bin:' + os.environ['PATH']
```

However, I then encountered an error with `keras-resnet`, namely, that the module is not found (even though `pip list` says otherwise):
```python
<ipython-input-1-f688cf9e2ee5> in <module>()
     33 get_ipython().system('python3 setup.py build_ext --inplace')
     34 
---> 35 import keras_resnet
     36 import shutil
     37 import zipfile

ModuleNotFoundError: No module named 'keras_resnet'
```

**Comment by whoisibooo** [comment]
i solved this with @leksandre help. But I needed to install tensorflow and gpu version of 2.4.0 because at 2.3.0 my gpu isn't supported. The python version I use is 3.8.10. 

> great, solved it by 4 commands
> 
> pip3 install tensorflow==2.3.0
> pip3 install tensorflow-gpu==2.3.0
> pip3 install keras==2.4

**Comment by whoisibooo** [comment]
> I am getting this error now: " LOCAL.GENERATED_WITH_V2 = tf.**internal**.tf2.enabled()
> AttributeError: module 'tensorflow.compat.v2' has no attribute '**internal**'"
> but the python version colab is using in my case is Python 3.7.10. How can I change that?

just try to uninstall/install all packages or try to create a fresh new environment. it helped for me. @JulietaAbuin @mateoochoa

**Comment by mateoochoa** [comment]
I was able to run all the project, first I had to delete all the packages that can be deleted, literally all, then, I installed the packages just like @leksandre said, and adicionally I had to install ipykernel. It works to read the model with all the parameters, it works to train the model and save it. Thanks all of you for you help.

**Comment by whoisibooo** [comment]
I want to evaluate my model with my test data.  I use the evaluate.py but get the following error. 

!keras_retinanet/bin/evaluate.py \
csv val_annotations.csv classes.csv \
last_trained_model

OSError: SavedModel file does not exist at: last_trained_model/{saved_model.pbtxt|saved_model.pb}

Can anyone help me what the issue is?

**Comment by leksandre** [comment]
> I want to evaluate my model with my test data. I use the evaluate.py but get the following error.
> 
> !keras_retinanet/bin/evaluate.py
> csv val_annotations.csv classes.csv
> last_trained_model
> 
> OSError: SavedModel file does not exist at: last_trained_model/{saved_model.pbtxt|saved_model.pb}
> 
> Can anyone help me what the issue is?

i fix it in file evaluate.py, in code line
![image](https://user-images.githubusercontent.com/44774042/120472501-66744d80-c3bf-11eb-935d-37121a168b9c.png)
![image](https://user-images.githubusercontent.com/44774042/120472587-80159500-c3bf-11eb-8a41-6f0d582ee832.png)

**Comment by whoisibooo** [comment]
> > I want to evaluate my model with my test data. I use the evaluate.py but get the following error.
> > !keras_retinanet/bin/evaluate.py
> > csv val_annotations.csv classes.csv
> > last_trained_model
> > OSError: SavedModel file does not exist at: last_trained_model/{saved_model.pbtxt|saved_model.pb}
> > Can anyone help me what the issue is?
> 
> i fix it in file evaluate.py, in code line
> ![image](https://user-images.githubusercontent.com/44774042/120472501-66744d80-c3bf-11eb-935d-37121a168b9c.png)
> ![image](https://user-images.githubusercontent.com/44774042/120472587-80159500-c3bf-11eb-8a41-6f0d582ee832.png)

I used your solution it solved the issue at the top. but now I get another error: 
    boxes, scores, labels = model.predict_on_batch(np.expand_dims(image, axis=0))[:3]
ValueError: not enough values to unpack (expected 3, got 2)

I can predict with model.predict_on_batch(np.expand_dims(image, axis=0) test data but if I want to evaluate I get this error. 

Any idea ?

**Comment by leksandre** [comment]
> > > I want to evaluate my model with my test data. I use the evaluate.py but get the following error.
> > > !keras_retinanet/bin/evaluate.py
> > > csv val_annotations.csv classes.csv
> > > last_trained_model
> > > OSError: SavedModel file does not exist at: last_trained_model/{saved_model.pbtxt|saved_model.pb}
> > > Can anyone help me what the issue is?
> > 
> > 
> > i fix it in file evaluate.py, in code line
> > ![image](https://user-images.githubusercontent.com/44774042/120472501-66744d80-c3bf-11eb-935d-37121a168b9c.png)
> > ![image](https://user-images.githubusercontent.com/44774042/120472587-80159500-c3bf-11eb-8a41-6f0d582ee832.png)
> 
> I used your solution it solved the issue at the top. but now I get another error:
> Traceback (most recent call last):
> File "keras_retinanet/bin/evaluate.py", line 195, in
> main()
> File "keras_retinanet/bin/evaluate.py", line 166, in main
> average_precisions, inference_time = evaluate(
> File "/.........unix/valet_parking/neural_network/object_detection/retinanet/retinanet_repo/keras_retinanet/bin/../../keras_retinanet/utils/eval.py", line 174, in evaluate
> all_detections, all_inferences = _get_detections(generator, model, score_threshold=score_threshold, max_detections=max_detections, save_path=save_path)
> File "/.........unix/valet_parking/neural_network/object_detection/retinanet/retinanet_repo/keras_retinanet/bin/../../keras_retinanet/utils/eval.py", line 87, in _get_detections
> boxes, scores, labels = model.predict_on_batch(np.expand_dims(image, axis=0))[:3]
> ValueError: not enough values to unpack (expected 3, got 2)
> 
> I can predict with model.predict_on_batch(np.expand_dims(image, axis=0) test data but if I want to evaluate I get this error.
> 
> Any idea ?

you lose important part about process of converting model  https://github.com/fizyr/keras-retinanet#converting-a-training-model-to-inference-model

**Comment by mateoochoa** [comment]
> 
> 
> > > I want to evaluate my model with my test data. I use the evaluate.py but get the following error.
> > > !keras_retinanet/bin/evaluate.py
> > > csv val_annotations.csv classes.csv
> > > last_trained_model
> > > OSError: SavedModel file does not exist at: last_trained_model/{saved_model.pbtxt|saved_model.pb}
> > > Can anyone help me what the issue is?
> > 
> > 
> > i fix it in file evaluate.py, in code line
> > ![image](https://user-images.githubusercontent.com/44774042/120472501-66744d80-c3bf-11eb-935d-37121a168b9c.png)
> > ![image](https://user-images.githubusercontent.com/44774042/120472587-80159500-c3bf-11eb-8a41-6f0d582ee832.png)
> 
> I used your solution it solved the issue at the top. but now I get another error:
> Traceback (most recent call last):
> File "keras_retinanet/bin/evaluate.py", line 195, in
> main()
> File "keras_retinanet/bin/evaluate.py", line 166, in main
> average_precisions, inference_time = evaluate(
> File "/.........unix/valet_parking/neural_network/object_detection/retinanet/retinanet_repo/keras_retinanet/bin/../../keras_retinanet/utils/eval.py", line 174, in evaluate
> all_detections, all_inferences = _get_detections(generator, model, score_threshold=score_threshold, max_detections=max_detections, save_path=save_path)
> File "/.........unix/valet_parking/neural_network/object_detection/retinanet/retinanet_repo/keras_retinanet/bin/../../keras_retinanet/utils/eval.py", line 87, in _get_detections
> boxes, scores, labels = model.predict_on_batch(np.expand_dims(image, axis=0))[:3]
> ValueError: not enough values to unpack (expected 3, got 2)
> 
> I can predict with model.predict_on_batch(np.expand_dims(image, axis=0) test data but if I want to evaluate I get this error.
> 
> Any idea ?

You should convert the model first, https://github.com/fizyr/keras-retinanet#converting-a-training-model-to-inference-model

**Comment by whoisibooo** [comment]
> > > > I want to evaluate my model with my test data. I use the evaluate.py but get the following error.
> > > > !keras_retinanet/bin/evaluate.py
> > > > csv val_annotations.csv classes.csv
> > > > last_trained_model
> > > > OSError: SavedModel file does not exist at: last_trained_model/{saved_model.pbtxt|saved_model.pb}
> > > > Can anyone help me what the issue is?
> > > 
> > > 
> > > i fix it in file evaluate.py, in code line
> > > ![image](https://user-images.githubusercontent.com/44774042/120472501-66744d80-c3bf-11eb-935d-37121a168b9c.png)
> > > ![image](https://user-images.githubusercontent.com/44774042/120472587-80159500-c3bf-11eb-8a41-6f0d582ee832.png)
> > 
> > 
> > I used your solution it solved the issue at the top. but now I get another error:
> > Traceback (most recent call last):
> > File "keras_retinanet/bin/evaluate.py", line 195, in
> > main()
> > File "keras_retinanet/bin/evaluate.py", line 166, in main
> > average_precisions, inference_time = evaluate(
> > File "/.........unix/valet_parking/neural_network/object_detection/retinanet/retinanet_repo/keras_retinanet/bin/../../keras_retinanet/utils/eval.py", line 174, in evaluate
> > all_detections, all_inferences = _get_detections(generator, model, score_threshold=score_threshold, max_detections=max_detections, save_path=save_path)
> > File "/.........unix/valet_parking/neural_network/object_detection/retinanet/retinanet_repo/keras_retinanet/bin/../../keras_retinanet/utils/eval.py", line 87, in _get_detections
> > boxes, scores, labels = model.predict_on_batch(np.expand_dims(image, axis=0))[:3]
> > ValueError: not enough values to unpack (expected 3, got 2)
> > I can predict with model.predict_on_batch(np.expand_dims(image, axis=0) test data but if I want to evaluate I get this error.
> > Any idea ?
> 
> You should convert the model first, https://github.com/fizyr/keras-retinanet#converting-a-training-model-to-inference-model

I tried it but I get the same error as above and when I change the code to the path of the model I get the error 

KeyError: 'inputs'

**Comment by whoisibooo** [comment]
Thanks for the help guys. I solved my problem :)
