### ISSUE TITLE
RESIZING IMAGES

### ISSUE THREAD

**Issue by arci97** [fizyr/keras-retinanet#1536]
Is the model (train.py) resize images as default? Or the size remain the original ones? And how can i set the resize?

**Comment by mahesaAtma** [comment]
Based on file **train.py**, i think you can add some of arguments such as : 
```
parser.add_argument('--image-min-side',   help='Rescale the image so the smallest side is min_side.', type=int, default=800)    parser.add_argument('--image-max-side',   help='Rescale the image if the largest side is larger than max_side.', type=int, default=1333)    
parser.add_argument('--no-resize',        help='Don''t rescale the image.', action='store_true')
```
or you can do some tweaks in **image.py** file, in resize_image function

def resize_image(img, min_side=800, max_side=1333):    """ Resize an image such that the size is constrained to min_side and max_side.    Args        min_side: The image's min side will be equal to min_side after resizing.        max_side: If after resizing the image's max side is above max_side, resize until the max side is equal to max_side.    Returns        A resized image.    """    # compute scale to resize the image    scale = compute_resize_scale(img.shape, min_side=min_side, max_side=max_side)
    # resize the image with the computed scale    img = cv2.resize(img, None, fx=scale, fy=scale)
    return img, scale
