### ISSUE TITLE
"List index of out of range error " during inference (  Show up  this week )

### ISSUE THREAD

**Issue by syln21** [fizyr/keras-retinanet#1537]
Hello, i have been using same notebook on colab for more than 2 months with same weights and dependencies. It started to give me error this week. I didn't change anything. It suprisingly started to give me error. while loading the model. Could you please help me ?

IndexError                                Traceback (most recent call last)
<ipython-input-10-d80d5bc75b82> in <module>()
      3 
      4 # load retinanet model
----> 5 model = models.load_model(model_path, backbone_name='resnet50')
      6 model = models.convert_model(model)
      7 

8 frames
/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/engine/functional.py in process_node(layer, node_data)
   1222           add_unprocessed_node(layer, node_data)
   1223           return
-> 1224         inbound_node = inbound_layer._inbound_nodes[inbound_node_index]
   1225         input_tensors.append(
   1226             nest.flatten(inbound_node.outputs)[inbound_tensor_index])

IndexError: list index out of range

**Comment by AndreiIonut1** [comment]
I believe this is happening because colab upgraded to tensorflow 2.5

**Comment by syln21** [comment]
> I believe this is happening because colab upgraded to tensorflow 2.5

Thanks for your reply, I tried to downgrade tensorflow with pip install tensorflow==2.3.0 but still have the same problem

**Comment by AndreiIonut1** [comment]
The way I managed to get it to work is to install miniconda in google colab and then install tensorflow-gpu 2.4.0.

**Comment by ra024940** [comment]
I'm also facing this issue.

**Comment by syln21** [comment]
> The way I managed to get it to work is to install miniconda in google colab and then install tensorflow-gpu 2.4.0.

It was related to my final project of bachelor degree, thanks to you i completed it. Thank you very much. I appreciate it

**Comment by syln21** [comment]
> I'm also facing this issue.

You should do exactly how @AndreiIonut1 explained. It works ,Good luck

**Comment by AlexandrAstafiev** [comment]
Can I have a piece of code or a link to a working colab?

**Comment by ra024940** [comment]
> Can I have a piece of code or a link to a working colab?

yes, of course. i really appreciate you taking the time to check it.

https://colab.research.google.com/drive/1frDF_8a3CB-EKCe1bRdjzeMaDa8MzlK0?usp=sharing

**Comment by AlexandrAstafiev** [comment]
I am asking for an example of a solution to the problem. I have the same problem.

**Comment by mateoochoa** [comment]
You should check issue #1535, All these problems have the same reason, google colab change the version of its libraries and in some of these broke the support for the RetinaNet.

**Comment by kirthan0899** [comment]
https://github.com/fizyr/keras-retinanet/issues/1538#issuecomment-853652860

**Comment by kirthan0899** [comment]
Issue resolved.
[Check here](https://github.com/fizyr/keras-retinanet/issues/1538#issuecomment-853652860)
