### ISSUE TITLE
continue train

### ISSUE THREAD

**Issue by hoangnhancs** [fizyr/keras-retinanet#1544]
i have train 20 epoch on gg colab. because colab has a limited time for traing each session. when time limited, session will end. so, i want to continue train with my weight at 20-th epoch, how can i do?

**Comment by AndreiIonut1** [comment]
https://github.com/fizyr/keras-retinanet/blob/main/keras_retinanet/bin/train.py#L423

**Comment by hoangnhancs** [comment]
But --snapshot don't work on gg colab. I don't know why ??
