### ISSUE TITLE
Keras 2.4 and retinanet Keras conflict

### ISSUE THREAD

**Issue by Paryavi** [fizyr/keras-retinanet#1547]
Hi, I have installed TensorFlow 2.3 and Keras 2.4 on Python 3.6, and it recognizes the GPU successfully!
Also, I run pip install . --user
 and python setup.py build_ext --inplace from the instructions section.
 
However, when I want to train by running the following code;
 
  /path_of_image&CSVfiles... ...keras_retinanet\bin\train.py --image-min-side 1000 --random-transform --batch-size 1 --epoch 10 --steps 30 --backbone resnet101 csv Train\training_labels.csv Train\classes.csv 
 
I get the following error;
kernel_initializer' : keras.initializers.normal(mean=0.0, stddev=0.01, seed=None),
AttributeError: module 'keras.initializers' has no attribute 'normal'

Any direction on how to solve it? I really appreciate any help you can provide.

**Comment by deduble** [comment]
Yes the written instruction no longer works for clean install with the said instructions. But I had a different error. Have you manage to install this yet?
