### ISSUE TITLE
Where is the root dictionary for the model in Colab?

### ISSUE THREAD

**Issue by wfeng66** [fizyr/keras-retinanet#1557]
I installed the model following Readme, however, it shows "No module named 'keras_retinanet.backend.tensorflow_backend'".

I found some posts that said need to run pip install. --user. It ends up with an error of "Directory '.' is not installable. Neither 'setup.py' nor 'pyproject.toml' found." Which dictionary should I execute that command?

Thanks in advance!

**Comment by tirelesslearner-1901** [comment]
Instead of using pip install . --user , do write pip install .  ; it works fine !
