### ISSUE TITLE
version incompatible?

### ISSUE THREAD

**Issue by wfeng66** [fizyr/keras-retinanet#1558]
I use windows10, python 3.7, tensorflow==1.13.1, keras==2.2.4. When I import keras, it shows No module named tensorflow.compat.v2. I think the keras requires tensorflow higher than 2.0. So, I want to degrade the keras. However, the retinanet requires 2.2.4 or higher.

What's the problem and what can I do?

**Comment by AnimeshGalande** [comment]
yes you are right the tensorflow version is not compatible
