### ISSUE TITLE
continue train on colab

### ISSUE THREAD

**Issue by hoangnhancs** [fizyr/keras-retinanet#1560]
i training my model on gg colab, and GPU on this has limited time for training. i haved used snapshot for continue train but it doén't work. and i don't know how to fix.

**Comment by pratibhashinde** [comment]
Hi,
I am also working with this github repo. Shall we connect through LinkedIn/gmail? I have used snapshot and it works fine. My mail id is: shindepratibha31@gmail.com.

Start the training: python train.py --snapshot "previous trained model.h5" ................
Don't use --weights and --snapshot together.
Hope this helps.
