### ISSUE TITLE
invalid boxes

### ISSUE THREAD

**Issue by juanmanuellopezcorrea** [fizyr/keras-retinanet#1564]
Hello everyone, I have this problem:

!keras_retinanet/bin/train.py --freeze-backbone --tensorboard-dir "/content/drive/MyDrive/TomatoDeep/" --gpu 0 --weights "/content/drive/MyDrive/TomatoDeep/keras-retinanet/snapshots/resnet50_coco_best_v2.1.0.h5" --batch-size 32 --snapshot-path "/content/drive/MyDrive/TomatoDeep/keras-retinanet/snapshots/" --steps 50 --epochs 100 csv '/content/drive/MyDrive/TomatoDeep/train/annotations.csv' '/content/drive/MyDrive/TomatoDeep/train/classes.csv'

The annotations are correct in the csv but I get this error:

keras_retinanet/bin/../../keras_retinanet/preprocessing/generator.py:181: UserWarning: Image /content/drive/MyDrive/TomatoDeep/train/almacen/IMG_4466.JPG with id 532 (shape (3888, 5184, 3)) contains the following invalid boxes: [[3170. 4101. 3589. 4890.]
[2072. 4784. 2458. 5184.]
[3524. 4869. 3888. 5184.]
[ 597. 4912. 1096. 5184.]].
annotations['bboxes'][invalid_indices, :]

You can see Bounding Boxes coordinates are correct with the shape image. I dont know what is the problem

**Comment by hgaiser** [comment]
The shape is printed as `(row, cols, channels)`, the boxes are printed as `(x1, y1, x2, y2)`. Meaning for example the first box has `y1 = 4101` but the height of the image is only `3888`.
