### ISSUE TITLE
No bounding boxes when running evaluate.py

### ISSUE THREAD

**Issue by adavradou** [fizyr/keras-retinanet#1569]
Hello everyone, 

I trained the model for 20 epochs on Colab using a train.csv (I will train for more when I make sure testing works too).
I converted the training model to inference model and then I try to evaluate it on a test.csv using the evaluate.py.

Unfortunately, the saved images contain no bounding boxes, although they are created when I run `model.predict_on_batch` for a specific image. Also, the mAP is above 50%.

I don't know if it is related, but I also get the following warning:
`WARNING:tensorflow:No training configuration found in the save file, so the model was *not* compiled. Compile it manually.
` 

Can anyone help? 
Thank in advance.

**Comment by adavradou** [comment]
Hi, I managed to find the solution. 

Inside `eval.py` I needed to modify the code in order to pass a `.copy()` of my image as an argument in `draw_annotations` and `draw_detections`. Then it worked like a charm and both prediction and annotation are plotted on the output image. 

I modified the code as shown below:
```
if save_path is not None:     
    draw = raw_image.copy()
    draw_annotations(draw, generator.load_annotations(i), label_to_name=generator.label_to_name)
    draw_detections(draw, image_boxes, image_scores, image_labels, label_to_name=generator.label_to_name, score_threshold=score_threshold)
```

**Comment by parthkvv** [comment]
@adavradou Tried the solution, but I'm not able to solve this error. Anything else to try?
