### ISSUE TITLE
ERROR:gpu_init.cc(454)] Passthrough is not supported, GL is disabled, ANGLE is

### ISSUE THREAD

**Issue by icexiaoyou** [fizyr/keras-retinanet#1575]
How can I solve this problem? It occured when I code as following:

(tensorflow) C:\Users\YJZ>"C:\Users\YJZ\Desktop\Tensorflow\keras-retinanet-main\keras_retinanet\bin\train.py" pascal "C:\Users\YJZ\Desktop\Tensorflow\workspace\dataset_version_voc\train"

Windows 11, annconda-latest, Python 3.9.12, tensowflow-GPU 2.8 

This was the entire report:
[main 2022-05-23T10:59:48.926Z] window#load: attempt to load window (id: 1)
[main 2022-05-23T10:59:49.010Z] update#setState idle
[main 2022-05-23T10:59:49.047Z] ExtensionHostStarterWorker created
[main 2022-05-23T10:59:50.293Z] window#load: window reported ready (id: 1)
[main 2022-05-23T10:59:50.478Z] Starting extension host with pid 22296 (fork() took 18 ms).
[main 2022-05-23T10:59:50.478Z] ExtensionHostStarterWorker.start() took 20 ms.
[main 2022-05-23T11:00:19.019Z] update#setState checking for updates
[main 2022-05-23T11:00:19.124Z] update#setState idle
[18180:0523/190150.056:ERROR:gpu_init.cc(454)] Passthrough is not supported, GL is disabled, ANGLE is

Loonking for your help, thanks!

**Comment by evilalmus** [comment]
I am getting the same error on Win11 and Keybase is not fully starting up (stuck on "Starting up Keybase")
