### ISSUE TITLE
resnet50_csv_final.h5 file

### ISSUE THREAD

**Issue by Tracyxzh** [fizyr/keras-retinanet#159]
i want to run a demo,so i what kow how can i get your resnet50_csv_final.h5 file

**Comment by alexiskattan** [comment]
For resnet50_csv_final.h5 will be weights you train based on the CSV dataset you provide.

On the otherhand, if you're looking for the COCO weights, see https://github.com/fizyr/keras-retinanet/issues/124.

**Comment by hgaiser** [comment]
What @alexiskattan said.

**Comment by Tracyxzh** [comment]
i want to konw how many pics do i need to train this model. And i have 400 pics right now.

**Comment by hgaiser** [comment]
@Tracyxzh that is a really vague question, and an unanswerable one. My advice: try it on the 400 pictures you have and see if the results are satisfying enough.
