### ISSUE TITLE
Attribute Error - keras

### ISSUE THREAD

**Issue by nealzGu** [fizyr/keras-retinanet#160]
Hi, just cloned and installed this repo for the second time, different machine.

Experiencing this error: AttributeError: 'module' object has no attribute 'models'
when I want to compile a model. I think it's because something with the keras-resnet installation went wrong. I installed it with 
pip install --user --upgrade git+https://github.com/broadinstitute/keras-resnet
from inside ~/keras-retinanet.

Any ideas what I did wrong?! Thanks!

**Comment by hgaiser** [comment]
Can you post the complete error?

**Comment by nealzGu** [comment]
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-2-9d125d75209e> in <module>()
      1 image_input = keras.layers.Input((None, None, 3))
      2 # model = keras_retinanet.models.ResNet50RetinaNet(image_input, num_classes=20, weights='imagenet')
----> 3 model = keras_retinanet.models.ResNet50RetinaNet(image_input, num_classes=3, nms=True, weights='/home/ivision/keras-retinanet/snapshots/resnet50_voc_best_VISIONACCESS.h5')
      4 
      5 # compile model

AttributeError: 'module' object has no attribute 'models

**Comment by nealzGu** [comment]
maybe the error lies deeper. I cant run tensorflow on gpu. I have cuda 9 and I think that causes problems. I will install cuda 8 + cudnn accordingly and go through the installation process again, hoping that this is the root cause ...

**Comment by hgaiser** [comment]
Did you import `keras_retinanet.models` in this code ?

**Comment by nealzGu** [comment]
that might have been it ;)
tensorflow is also throwing an error, I will get report after installing cuda 8... 
Thanks!

**Comment by hgaiser** [comment]
Alright :) I'll close this issue then.
