### ISSUE TITLE
AttributeError: 'module' object has no attribute 'ResNet50RetinaNet'

### ISSUE THREAD

**Issue by nealzGu** [fizyr/keras-retinanet#162]
hi again,

tensorflow is now running on gpu. I import keras_retinanet.models and am now getting this error:

ResNet50RetinaNet is defined in the files, I don't understand why its not getting it... any help will be appreciated!

error message:
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-3-7e9499b68f3f> in <module>()
      3 image_input = keras.layers.Input((None, None, 3))
      4 # model = keras_retinanet.models.ResNet50RetinaNet(image_input, num_classes=20, weights='imagenet')
----> 5 model = keras_retinanet.models.ResNet50RetinaNet(image_input, num_classes=3, nms=True, weights='/home/ivision/keras-retinanet/snapshots/resnet50_voc_best_VISIONACCESS.h5')
      6 
      7 # compile model

AttributeError: 'module' object has no attribute 'ResNet50RetinaNet'

**Comment by hgaiser** [comment]
`ResNet50RetinaNet` is in the submodule `resnet`, so:

```
keras_retinanet.models.resnet.ResNet50RetinaNet
```

**Comment by nealzGu** [comment]
hm, now its showing 'module' object has no attribute 'resnet'

it worked before with the branch I installed like two weeks ago. I followed the installation instructions, is there anything I am missing?! Like shouldnt the python files in "models" be compiled at some stage?

thanks for your help!

**Comment by nealzGu** [comment]
nevermind! works! different error:

ValueError: Layer #1 (named "conv1") expects 1 weight(s), but the saved weights have 2 element(s).

the weights are trained on a previous branch. does this causes the error?

**Comment by hgaiser** [comment]
You then need to do:
```
import keras_retinanet.models.resnet
```

Some things changed and were moved around. You can always check the existing training script to see how it is currently done.

Active development on a repository has both positive and negative sides :)

**Comment by hgaiser** [comment]
> the weights are trained on a previous branch. does this causes the error?

Yes, old models used to have a bias in the conv layers but the original ResNet implementation didn't. This changed a while back. I'm afraid it's better to retrain from imagenet.

**Comment by nealzGu** [comment]
ok :D 
then let's start with training before the inference part :) thanks!
