### ISSUE TITLE
Reshape problem with multi-gpu > 1 & batch-size = 1

### ISSUE THREAD

**Issue by awilliamson** [fizyr/keras-retinanet#166]
```
InvalidArgumentError (see above for traceback): Reshape cannot infer the missing input size for an empty tensor unless all specified input sizes are non-zero
         [[Node: replica_4/retinanet-bbox/classification_submodel_2/pyramid_classification_reshape/Reshape = Reshape[T=DT_FLOAT, Tshape=DT_INT32, _device="/job:localhost/replica:0/task:0/device:GPU:4"](replica_4/retinanet-bbox/classification_submodel_2/pyramid_classification/BiasAdd, replica_4/retinanet-bbox/classification_submodel_2/pyramid_classification_reshape/Reshape/shape)]]
```

The full error is rather long. It errors within Keras library. I imagine because multi_gpu_model splits the batch into mini-batches to distribute amongst GPUs that with Gpu > 1, and batch_size = 1, it fails to split the batch.
We should probably be checking for batch_size when creating models, but that method doesn't accept parsed args. We can then check for batch_size > 1 in order to continue, otherwise raise an Exception to prevent underlying library erroring out.
Thoughts?

EDIT: It appears that reshape errors will occur if `num_gpus < batch_size`. Ran a `batch=4` and it errored. With num_gpus = batch_size, everything seems to work fine.

**Comment by hgaiser** [comment]
This issue is resolved then?
