### ISSUE TITLE
printed loss inconsistency with the loss in the callbacks

### ISSUE THREAD

**Issue by aminshabani** [fizyr/keras-retinanet#168]
Hi, I tried to plot the live loss using the following callback:

```
   def on_batch_end(self, batch, logs={}):
        self.logs.append(logs)
        self.x.append(self.i)
        self.losses.append(logs.get('loss'))
        self.i += 1
        clear_output(wait=True)
        plt.plot(self.x, self.losses, label="loss")
        plt.legend()
        plt.ion()
        plt.pause(0.05)
```

But I get a different loss in here in comparison with the default printed loss. I searched but I can't understand why. Do you know what is the problem?

**Comment by hgaiser** [comment]
This is keras related though, but perhaps the printed loss is an average loss and the loss from the callback isn't?

Either way, it's a keras issue, so closing this.
