### ISSUE TITLE
Moving train.py into /scripts folder breaking some imports

### ISSUE THREAD

**Issue by Akshai** [fizyr/keras-retinanet#169]

**Comment by hgaiser** [comment]
Can you give more information?

**Comment by awilliamson** [comment]
No import issues from me apart from `keras-retinanet`. Ensure running from root project folder, and that pythonpath is set appropriately.
Eg `env PYTHONPATH=./ python scripts/main.py ...`
Hope this helps @Akshai, if this is not the case, please provide more information about your running environment.

**Comment by Akshai** [comment]
@awilliamson Thanks.. That fixed it
