### ISSUE TITLE
bbox_transform formula

### ISSUE THREAD

**Issue by Cre1th** [fizyr/keras-retinanet#171]
Hey, I was wondering why 1.0 is added to the widths and heights in [bbox_transform](https://github.com/fizyr/keras-retinanet/blob/master/keras_retinanet/utils/anchors.py).

```
anchor_widths  = anchors[:, 2] - anchors[:, 0] + 1.0
anchor_heights = anchors[:, 3] - anchors[:, 1] + 1.0
anchor_ctr_x   = anchors[:, 0] + 0.5 * anchor_widths
anchor_ctr_y   = anchors[:, 1] + 0.5 * anchor_heights
```
...
```
targets_dx = (gt_ctr_x - anchor_ctr_x) / anchor_widths
targets_dy = (gt_ctr_y - anchor_ctr_y) / anchor_heights
targets_dw = np.log(gt_widths / anchor_widths)
targets_dh = np.log(gt_heights / anchor_heights)
```

It seems to me the purpose is to avoid division by zero. But I think, taking the maximum(1, anchor_widths/anchor_heights) is better suited for this task.
Especially because I think this introduces a slight error. Let's say the center offset in `x` is `10` then `target_dx = 10 / (anchors[:, 2] - anchors[:, 0] + 1.0)`. This is the value we want our regressor to have.
Using now [inv_bbox_transform](https://github.com/fizyr/keras-retinanet/blob/master/keras_retinanet/backend/common.py) even with this target regression results in
`pred_ctr_x = ctr_x + target_dx * widths` which does not yield the result we want of `ctr_x + 10`. This is because `target_dw * widths` is slightly less then 10 as in [inv_bbox_transform](https://github.com/fizyr/keras-retinanet/blob/master/keras_retinanet/backend/common.py) the + 1.0 is not taken into account see `widths  = boxes[:, :, 2] - boxes[:, :, 0]`.

So my question is: Does this +1.0 serve any other purpose?

**Comment by hgaiser** [comment]
Good question! The short and boring answer is, that's how it is implemented in [py-faster-rcnn](https://github.com/rbgirshick/py-faster-rcnn/blob/master/lib/fast_rcnn/bbox_transform.py). However in their inverse transformation they also use `+ 1`'s.

I think I removed them when implementing the tensorflow implementation of the inverse transformation but never checked this part. In my opinion, x2 and y2 are not inclusive so the width is simply `x2 - x1`.

That being said, I think you're right! Thanks for bringing this to my attention, I'll see about fixing that.

**Comment by hgaiser** [comment]
I feel the `+ 1` indeed was incorrect, but I'll hold off changing it until I upload a new COCO model. Until then I'll keep this open, but thanks for bringing it to our attention!

**Comment by philvdm** [comment]
There is the same +1 issue in compute_overlap even though the division by zero is properly taken care of

**Comment by hgaiser** [comment]
Fixed in https://github.com/fizyr/keras-retinanet/pull/311 .
