### ISSUE TITLE
Running Multi-gpu model for data parallelism

### ISSUE THREAD

**Issue by nbansal90** [fizyr/keras-retinanet#173]
I was trying out the following code using multi_gpu on keras following your code in callback section. But I am getting this error.

model = resnet_model.Resnet_model.build_model_v2(input_shape, num_class,depth)
parallel_model = multi_gpu_model(model, gpus=2)
parallel_model.compile(loss='categorical_crossentropy',optimizer=Adam(lr=lr_schedule(0)),metrics=['accuracy'])

"""Callbacks Used"""

csv_log=CSVLogger(filename, separator=',', append=False)
checkpoint = ModelCheckpoint(filepath=filepath, monitor='val_acc',verbose=1,
                                save_best_only=True)
lr_scheduler = LearningRateScheduler(lr_schedule)
lr_reducer = ReduceLROnPlateau(factor=np.sqrt(0.1), cooldown=0,
                                patience=5, min_lr=0.5e-6)

"""New Callback called used the original model"""
callbacks_l = [csv_log, checkpoint, lr_scheduler, lr_reducer]
cbk = MyCallBack(callbacks_l,model)

"""New Class Defined"""

class MyCallBack(keras.callbacks.Callback):

        def __init__(self, callbacks,model):
                super().__init__()
                callbacks = callbacks
                self.callbacks = [c for c in callbacks]
                self.model = model

        def on_epoch_begin(self,epoch,logs=None):
                for callback in self.callbacks:
                        callback.on_epoch_begin(epoch, logs=logs)

        def on_epoch_end(self,epoch,logs=None):
                for callback in self.callbacks:
                        callback.on_epoch_end(epoch, logs=logs)

        def on_batch_end(self, batch, logs=None):
                for callback in self.callbacks:
                        callback.on_batch_end(batch, logs=logs)

        def on_batch_begin(self, batch, logs=None):
                for callback in self.callbacks:
                        callback.on_batch_begin(batch, logs=logs)

        def on_train_begin(self, logs=None):
                for callback in self.callbacks:
                        callback.set_model(self.model)
                        callback.on_train_begin(logs=logs)

        def on_train_end(self, logs=None):
                for callback in self.callbacks:
                        callback.on_train_end(logs=logs)

"""Getting similar Error"""
Epoch 1/100
1562/1563 [============================>.] - ETA: 0s - loss: 2.3793 - acc: 0.4827Epoch 00001: val_acc improved from -inf to 0.55510, saving model to /home/bansa01/resnet_final/gpu_dir/saved_models/cifar10_v1_model.001.h5
Traceback (most recent call last):
  File "resnet_cifar10.py", line 187, in <module>
    callbacks=[cbk])
  File "/usr/local/keras-python3/lib/python3.5/site-packages/keras/legacy/interfaces.py", line 87, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/keras-python3/lib/python3.5/site-packages/keras/engine/training.py", line 2187, in fit_generator
    callbacks.on_epoch_end(epoch, epoch_logs)
  File "/usr/local/keras-python3/lib/python3.5/site-packages/keras/callbacks.py", line 73, in on_epoch_end
    callback.on_epoch_end(epoch, logs)
  File "/home/bansa01/resnet_final/gpu_dir/resnet_model.py", line 182, in on_epoch_end
    callback.on_epoch_end(epoch, logs=logs)

**Comment by hgaiser** [comment]
This doesn't sound `keras-retinanet` related? Perhaps you have better luck asking on Slack for help with this issue.

Also, it looks like this isn't the full traceback. The actual error appears to be missing.
