### ISSUE TITLE
training error about multi-gpu model 

### ISSUE THREAD

**Issue by huangcong77** [fizyr/keras-retinanet#175]
hey guys,sorry to bother you again.
I modified the train.py as below：
“parser.add_argument('--batch-size', help='Size of the batches.', default=16, type=int)
    parser.add_argument('--gpu', help='Id of the GPU to use (as reported by nvidia-smi).',default='0,1')
    parser.add_argument('--multi-gpu', help='Number of GPUs to use for parallel processing.', type=int, default=2)
”
after that, I want to train this model on 2007,but got error as :
"
Traceback (most recent call last):
  File "scripts/train.py", line 255, in <module>
    train_generator, validation_generator = create_generators(args)
  File "scripts/train.py", line 168, in create_generators
    batch_size=args.batch_size
  File "build/bdist.linux-x86_64/egg/keras_retinanet/preprocessing/pascal_voc.py", line 84, in __init__
TypeError: split() takes no keyword arguments
"
Btw,training this model on signal  gpu  is fine with no error,which is a little slow

**Comment by hgaiser** [comment]
Seems that `split` doesn't take named arguments in python 2. I assume you're running python 2 at least?

@de-vri-es : https://stackoverflow.com/questions/11716687/why-does-str-split-not-take-keyword-arguments

**Comment by huangcong77** [comment]
thank you！ It fixed my problem

**Comment by de-vri-es** [comment]
Fixed in dd687b5d0b97a1ce67876d930bd1669ace1225f4
