### ISSUE TITLE
Does it make sense to train/predict on high resolution?

### ISSUE THREAD

**Issue by loringao** [fizyr/keras-retinanet#178]
Hi All,

I have tried retrain my own dataset sucessfully by train_csv script. I found some intresting result during the test.

My case is detect some irregular block object and irregular line object. I train the net by 500+ images(resolution 800*800)

1. Predict test data on 416x416, block can be detected better than 1024x1024.
2. Predict test data on 1024x1024,  line can be detected better than 416x416.

Seems that model get good understand on high resolution for line object, better resulte on low resoltuion for block object.

My question is:
1. Does it make sense to train on high resolution? I expect that model will get better result if i train it with 1024*1024, but as my knowlege on resnet, the input is fixed resolution.

2. Does it make sense to do additional argument data ? I saw the gernerate already do some argument(bounding box ajust is too hard to me).

Thank!

**Comment by hgaiser** [comment]
> Does it make sense to train on high resolution? I expect that model will get better result if i train it with 1024*1024, but as my knowlege on resnet, the input is fixed resolution.

It is true that ResNet is trained on `224x224` images of ImageNet, but this is not a restriction in RetinaNet and similar networks.

> Does it make sense to do additional argument data ? I saw the gernerate already do some argument(bounding box ajust is too hard to me).

Are you referring to data augmentation? In that case, data augmentation is almost a good idea. You will simply get more data that way and more data is preferable.

As for your question on what resolution to train on, I would say try it out. Test it on multiple different resolutions and compare the results. Note that the [`Generator`](https://github.com/fizyr/keras-retinanet/blob/master/keras_retinanet/preprocessing/generator.py#L36-L37) will resize your images such that its smallest side is equal to `image_min_side`. If the largest side is then above `image_max_side` it will rescale it down further.

**Comment by loringao** [comment]
@hgaiser , thanks for you clarify, I'll test it and post the result.

**Comment by loringao** [comment]
Close it and update more test result later.
