### ISSUE TITLE
Minor bug in example code

### ISSUE THREAD

**Issue by mhwilder** [fizyr/keras-retinanet#179]
In https://github.com/fizyr/keras-retinanet/blob/master/examples/ResNet50RetinaNet%20-%20COCO%202017.ipynb

I believe this line of code:

```
# correct for image scale
detections[:, :4] /= scale
```
Should read:
```
# correct for image scale
detections[0, :, :4] /= scale
```

**Comment by awilliamson** [comment]
I believe the Python Notebook is a little outdated. Did you pull that detections line from coco_eval by any chance?
Likewise it is missing clipping the bbox detections to the image region, alongside reformating the latter bbox coords to bring them in line with COCO spec of `(x, y, w, h)` as the internal representation is `(x1,y1,x2,y2)`.

**Comment by mhwilder** [comment]
coco_eval does do the right thing (i.e., it uses the lower line above). Clipping to the image probably makes sense as well in this example but converting to (x,y,w,h) probably not since the coordinates are used for creating a display of the boxes in the next step.

I had used the example code as reference when implementing a process_folder function that runs detection on all images in a folder and creates visualizations for them. This bug was causing only the first 4 boxes to be scaled correctly. When there were more than 4 detections, some boxes showing up in weird places. It took me a while to figure out the issue which is why I thought it was worth it to post here.

**Comment by hgaiser** [comment]
> This bug was causing only the first 4 boxes to be scaled correctly.

I bet it was fun finding out that this was the issue ? :) It was for me when I had the same issue in the COCO evaluation script ... runs fine, but gives way off results.

Anyway thanks for reporting it. Could you make a PR to fix this issue?

**Comment by LaurensHagendoorn** [comment]
I also had this issue! (remember me asking why it only every draws 4 boxes?)
Awesome, all the new changes to retinanet are causing me a whole lot of other issues though, but this one is now fixed! ;P

**Comment by mhwilder** [comment]
Added PR for this.

**Comment by hgaiser** [comment]
Merged, so I'll close this issue. Thanks for the PR!
