### ISSUE TITLE
I find an error in train.py

### ISSUE THREAD

**Issue by hnsywangxin** [fizyr/keras-retinanet#183]
hello @awilliamson @hgaiser @de-vri-es @mihaimorariu @ @wassname 
I find an error in "train.py" ,the line is  "raise ValueError('Invalid data type received: {}'.format(dataset_type))"
I think it should be raise ValueError('Invalid data type received: {}'.format(args.dataset_type))

thanks

**Comment by awilliamson** [comment]
@hnsywangxin Good spot! I agree, I believe it should be `args.dataset_type` too. https://github.com/fizyr/keras-retinanet/blob/master/scripts/train.py#L158

**Comment by de-vri-es** [comment]
@hnsywangxin: Do you want to send a pull request?

**Comment by hnsywangxin** [comment]
I had send a pull request,thanks all

**Comment by de-vri-es** [comment]
#185 merged. Closing this issue. Thanks again!
