### ISSUE TITLE
Where do I point logdir for tensorboard?

### ISSUE THREAD

**Issue by taewookim** [fizyr/keras-retinanet#187]
I don't see event.* files in the training directory. Where do I point tensorboard logdir?

**Comment by de-vri-es** [comment]
I have no clue what your question is about. Are you having an issue with `keras-retinanet` in specific?

If your issue is more general with `keras` or `tensorflow`, please use the appropriate support channels for those.

**Comment by Patrick-M** [comment]
You have to add a callback in your model.fit

keras.callbacks.TensorBoard(log_dir='./logs', histogram_freq=0, write_graph=True, write_images=True),

**Comment by de-vri-es** [comment]
Since this does not seem related to `keras-retinanet` itself, I'm closing this issue. If it is related to `keras-retinanet`, feel free to comment and I'll re-open it.
