### ISSUE TITLE
Custom dataset and CSV Generator - segmentation fault (core dumped)

### ISSUE THREAD

**Issue by Cibale** [fizyr/keras-retinanet#188]
I am trying to use Retinanet (currently just scripts/train.py) on a custom dataset [1] on my local machine*, but when I try to train a model, somehow I always finish up (after ~1 sec) with a segmentation fault (core dumped). I've tried with --batch-size=1/10/100/1000 but always the same result .. . 

Using the "print" statemetns, I figured out that the error pops out before the first line in main method is executed. 

Actually, if I have  _from keras_retinanet.preprocessing.csv_generator import CSVGenerator_ , then the program crashes before that very first line ("print" line) in a main is executed. **Therefore, I conclude that import of that generator crashes the program.**

However, if I don't import it, then the first line of main is executed, but a program crashes when it needs to create a new CSVGenerator of course.

More specifically, this is what I get (when import CSVGenerator line exists):

Using Theano backend.
WARNING (theano.tensor.blas): Using NumPy C-API based implementation for BLAS functions.
[1]    21385 segmentation fault (core dumped)  python scripts/train.py csv  

* using CPU on my local machine (Ubuntu 16.04/8GB/i5)
[1] http://www.robots.ox.ac.uk/~vgg/data/hands/ (Data set is ~7k images (every image is <1MB))

**Comment by hgaiser** [comment]
A segmentation fault would indicate to me that c++ code is crashing. Since `keras-retinanet` does not contain c++ code I would guess it is one of the dependencies that is crashing for you. Can you try a keras mnist tutorial or something like that?

**Comment by Cibale** [comment]
I tried keras mnist tutorial and it works smoothly.

Do you have any idea how I could solve my issue?

**Comment by hgaiser** [comment]
Try importing the modules that the generator imports. I'm assuming one of
them will be the culprit.

**Comment by hgaiser** [comment]
Ah right! We currently only support tensorflow backend (feel free to add
theano functions to support theano :) ).

**Comment by Cibale** [comment]
How can I switch that? :D

I guess [this line](https://github.com/fizyr/keras-retinanet/blob/master/scripts/train.py#L215) sets the backend? I didn't change a line in a `train.py` so I guess it should be tensorflow?

**Comment by hgaiser** [comment]
You need tensorflow in case you don't have that. If you do, try running it
with KERAS_BACKEND=tensorflow python scripts/train.py ...

**Comment by Cibale** [comment]
Thanks for the help guys. However, even when I run it with the tensorflow backend, I still get the sig fault.
Now, I tried as @hgaiser said, importing line by line to figure out what's wrong and it turns out that I have problem with some library:

```
from keras_retinanet.utils.image import preprocess_image
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/mmatak/RetinaNet/keras-retinanet/keras_retinanet/utils/image.py", line 21, in <module>
    import cv2
ImportError: /lib/x86_64-linux-gnu/libz.so.1: version `ZLIB_1.2.9' not found (required by /home/mmatak/anaconda2/lib/libpng16.so.16)
```
I am not sure how and why is anaconda2 linked at all? (I am using venv for this whole project) 
I guess that's the source of the problem.
