### ISSUE TITLE
Session object after training is 'NoneType' ?

### ISSUE THREAD

**Issue by Cibale** [fizyr/keras-retinanet#192]
After all epochs in training are finished, I get this exception:

```
Exception ignored in: <bound method BaseSession.__del__ of <tensorflow.python.client.session.Session object at 0x7f4dd15d3d30>>
Traceback (most recent call last):
  File "path/RetinaNet/venv/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 696, in __del__
TypeError: 'NoneType' object is not callable

```

Although models are saved in `snapshots` directory.

What is this exception saying actually? Is this allowed exception?

Could this maybe be the reason why I can't get any prediction with more than 0.009 score? :/ 
I even tried with overfitting (**5 epochs, 15 steps -- only 2 images in dataset**), but still. Is that even enough for training for only 2 images?

EDIT: Somehow error is not reproducible, I get it "here and there" o.O

**Comment by de-vri-es** [comment]
There's not a lot to go on for us in that error message. It seems to happen in cleaning up the tensorflow session. Python ignores any exceptions thrown in `__del__` member functions, and my guess is that that is what you're seeing.

It is possible that something in `keras-retinanet` is triggering it, but it seems more likely that it is an issue with your tensorflow installation/configuration. I would recommend trying their support channel too, to see if someone there knows what this error is about.

One thing you can always try is to update tensorflow, if you're not on the latest version already. If you have local configuration you could try to selectively disable it to figure out what is causing the problem.

**Comment by Cibale** [comment]
Okay, will do.

btw. what do you think, why I can't get good results? I am trying to make network work on my local pc so I take 5 epochs, 15 steps -- with only 2 images in dataset. When I try to label something on these same two images, there is no score which is > 0.1. 

I guess these parameters are enough to overfit on two images (~500x500) and problem could be somewhere else?

Or am I wrong?

**Comment by de-vri-es** [comment]
Thanks for the update. Note that if you find out what is causing the original issue, I would be interested to hear about it :)
