### ISSUE TITLE
generator.next() - model.predict

### ISSUE THREAD

**Issue by peterdudfield** [fizyr/keras-retinanet#198]
This may be a silly question, but 
I set up my train_generator as in the example but using a CSV generator. 
when I run x, y = train_generator.next(), y list of length 2. 
However when I run y= model.predict(....) i get a list of length 3. 
I expected y to be the similar.

Can anyone help?

Thanks in advance (apologizes if this is not the correct place to put this)

**Comment by mhwilder** [comment]
model predict generates 3 outputs: regression outputs for the bounding boxes, classification output for the boxes, and detections. The detections are derived from the regression and classification outputs and are there for convenience to access the final bounding box and class predictions. They are not used in training. As such, the training data only contains values for the first 2 outputs.

**Comment by peterdudfield** [comment]
That make sense, thank you

**Comment by yhenon** [comment]
This question is better suited to the keras-retinanet slack channel (see the Readme for instructions on connecting) as it is not an issue in the code.
