### ISSUE TITLE
Accuracy from examples/ResNet50RetinaNet - COCO 2017.ipynb

### ISSUE THREAD

**Issue by taewookim** [fizyr/keras-retinanet#199]
Wasn't sure if this was an issue, so here goes

I ran the [example notebook ](https://github.com/fizyr/keras-retinanet/blob/master/examples/ResNet50RetinaNet%20-%20COCO%202017.ipynb) using the MS COCO weights (download link on the README of the repo), but using COCO 2014 . Didn't think it mattered too much, but what's detected (vs. detected with annotated) has huge discrepancy. 

Shouldn't the number of bounding boxes from 1st picture be closer to the 2nd? Do other RCNN based detection models  miss this many?

Detections:

<img src="https://s10.postimg.org/nv4eq6jyx/detected-min.jpg" />

Detections + Annotations:

<img src="https://s10.postimg.org/xfo1d21l5/annotated-min.jpg" />

**Comment by mhwilder** [comment]
You might want to try lowering the score threshold to something below 0.5. I suspect you'll get more detections then. The coco metrics incorporate a sweep across all thresholds so the MAP scores in the results take into account boxes not visible in your view. According to the coco metrics, this model should be performing similarly or slightly better than other RCNN models.

**Comment by yhenon** [comment]
Indeed. The current mAP is 0.325, so fully accurate predictions should not be expected. COCO is a hard dataset.

I am closing this currently as it is not a specific issue in the code base.

**Comment by taewookim** [comment]
@mhwilder  You were right. I set it to 0.1. Much closer from my random tests. Is there some kinda stat on what threshold i should be using given a dataset? Some kind of intuitive range?

**Comment by mhwilder** [comment]
@taewookim What threshold you use really depends on your specific problem domain and what level of false positives is acceptable. Best way is to try different values and pick what feels right.
