### ISSUE TITLE
load saved model error

### ISSUE THREAD

**Issue by sevenseablue** [fizyr/keras-retinanet#20]
`model = keras.models.load_model('snapshots_voc/resnet50_voc_best.h5', keras_retinanet.custom_objects)`

error as follows:

#####################################
TypeError                                 Traceback (most recent call last)
<ipython-input-3-91c498d1d0ba> in <module>()
      1 
----> 2 model = keras.models.load_model('snapshots_voc/resnet50_voc_best.h5', keras_retinanet.custom_objects)
      3 
      4 #model = keras_retinanet.models.ResNet50RetinaNet(image_input, num_classes=21, weights='imagenet')
      5 

/home/q/seven.wang/anaconda2/lib/python2.7/site-packages/keras/models.pyc in load_model(filepath, custom_objects, compile)
    237             raise ValueError('No model found in config file.')
    238         model_config = json.loads(model_config.decode('utf-8'))
--> 239         model = model_from_config(model_config, custom_objects=custom_objects)
    240 
    241         # set weights

/home/q/seven.wang/anaconda2/lib/python2.7/site-packages/keras/models.pyc in model_from_config(config, custom_objects)
    311                         'Maybe you meant to use '
    312                         '`Sequential.from_config(config)`?')
--> 313     return layer_module.deserialize(config, custom_objects=custom_objects)
    314 
    315 

/home/q/seven.wang/anaconda2/lib/python2.7/site-packages/keras/layers/__init__.pyc in deserialize(config, custom_objects)
     52                                     module_objects=globs,
     53                                     custom_objects=custom_objects,
---> 54                                     printable_module_name='layer')

/home/q/seven.wang/anaconda2/lib/python2.7/site-packages/keras/utils/generic_utils.pyc in deserialize_keras_object(identifier, module_objects, custom_objects, printable_module_name)
    137                 return cls.from_config(config['config'],
    138                                        custom_objects=dict(list(_GLOBAL_CUSTOM_OBJECTS.items()) +
--> 139                                                            list(custom_objects.items())))
    140             with CustomObjectScope(custom_objects):
    141                 return cls.from_config(config['config'])

/home/q/seven.wang/anaconda2/lib/python2.7/site-packages/keras/engine/topology.pyc in from_config(cls, config, custom_objects)
   2495                 if layer in unprocessed_nodes:
   2496                     for node_data in unprocessed_nodes.pop(layer):
-> 2497                         process_node(layer, node_data)
   2498 
   2499         name = config.get('name')

/home/q/seven.wang/anaconda2/lib/python2.7/site-packages/keras/engine/topology.pyc in process_node(layer, node_data)
   2452             if input_tensors:
   2453                 if len(input_tensors) == 1:
-> 2454                     layer(input_tensors[0], **kwargs)
   2455                 else:
   2456                     layer(input_tensors, **kwargs)

/home/q/seven.wang/anaconda2/lib/python2.7/site-packages/keras/engine/topology.pyc in __call__(self, inputs, **kwargs)
    600 
    601             # Actually call the layer, collecting output(s), mask(s), and shape(s).
--> 602             output = self.call(inputs, **kwargs)
    603             output_mask = self.compute_mask(inputs, previous_mask)
    604 

/home/q/seven.wang/anaconda2/lib/python2.7/site-packages/keras_retinanet-0.0.1-py2.7.egg/keras_retinanet/layers/_misc.pyc in call(self, inputs, **kwargs)
     19 
     20         # generate proposals from bbox deltas and shifted anchors
---> 21         anchors = keras_retinanet.backend.anchors(base_size=self.anchor_size, ratios=self.anchor_ratios, scales=self.anchor_scales)
     22         anchors = keras_retinanet.backend.shift(features_shape, self.anchor_stride, anchors)
     23         anchors = keras.backend.expand_dims(anchors, axis=0)

/home/q/seven.wang/anaconda2/lib/python2.7/site-packages/keras_retinanet-0.0.1-py2.7.egg/keras_retinanet/backend/common.pyc in anchors(base_size, ratios, scales)
     71     base_anchor = keras.backend.expand_dims(base_anchor, 0)
     72 
---> 73     ratio_anchors = _ratio_enum(base_anchor, ratios)
     74     anchors = _scale_enum(ratio_anchors, scales)
     75 

/home/q/seven.wang/anaconda2/lib/python2.7/site-packages/keras_retinanet-0.0.1-py2.7.egg/keras_retinanet/backend/common.pyc in _ratio_enum(anchor, ratios)
     98     w, h, x_ctr, y_ctr = _whctrs(anchor)
     99     size = w * h
--> 100     size_ratios = size / ratios
    101     ws = keras.backend.round(keras.backend.sqrt(size_ratios))
    102     hs = keras.backend.round(ws * ratios)

/home/q/seven.wang/anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/math_ops.pyc in binary_op_wrapper(x, y)
    854       if not isinstance(y, sparse_tensor.SparseTensor):
    855         try:
--> 856           y = ops.convert_to_tensor(y, dtype=x.dtype.base_dtype, name="y")
    857         except TypeError:
    858           # If the RHS is not a tensor, it might be a tensor aware object

/home/q/seven.wang/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/ops.pyc in convert_to_tensor(value, dtype, name, preferred_dtype)
    609       name=name,
    610       preferred_dtype=preferred_dtype,
--> 611       as_ref=False)
    612 
    613 

/home/q/seven.wang/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/ops.pyc in internal_convert_to_tensor(value, dtype, name, as_ref, preferred_dtype)
    674 
    675         if ret is None:
--> 676           ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
    677 
    678         if ret is NotImplemented:

/home/q/seven.wang/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/constant_op.pyc in _constant_tensor_conversion_function(v, dtype, name, as_ref)
    119                                          as_ref=False):
    120   _ = as_ref
--> 121   return constant(v, dtype=dtype, name=name)
    122 
    123 

/home/q/seven.wang/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/constant_op.pyc in constant(value, dtype, shape, name, verify_shape)
    100   tensor_value = attr_value_pb2.AttrValue()
    101   tensor_value.tensor.CopyFrom(
--> 102       tensor_util.make_tensor_proto(value, dtype=dtype, shape=shape, verify_shape=verify_shape))
    103   dtype_value = attr_value_pb2.AttrValue(type=tensor_value.tensor.dtype)
    104   const_tensor = g.create_op(

/home/q/seven.wang/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/tensor_util.pyc in make_tensor_proto(values, dtype, shape, verify_shape)
    374       nparray = np.empty(shape, dtype=np_dt)
    375     else:
--> 376       _AssertCompatible(values, dtype)
    377       nparray = np.array(values, dtype=np_dt)
    378       # check to them.

/home/q/seven.wang/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/tensor_util.pyc in _AssertCompatible(values, dtype)
    300     else:
    301       raise TypeError("Expected %s, got %s of type '%s' instead." %
--> 302                       (dtype.name, repr(mismatch), type(mismatch).__name__))
    303 
    304 

TypeError: Expected float32, got {u'type': u'ndarray', u'value': [0.5, 1.0, 2.0]} of type 'dict' instead.

#####################################

**Comment by hgaiser** [comment]
Model loading is currently broken. I'll try to look into this soon. In the meantime you can load models by first creating an identical model (or loading the model definition from the `<model>.h5` file) and then calling `model.load_weights`. That should work until this is fixed.

**Comment by hgaiser** [comment]
Reopening since this is an issue that still needs to be addressed.

**Comment by jwnsu** [comment]
model.load_weights () requires the file to be saved with model.save_weight(), right? 

Tried load_weights from save_model file, got an error:"ValueError: Dimension 3 in both shapes must be equal, but are 180 and 324 for 'Assign_346' (op: 'Assign') with input shapes: [3,3,256,180], [3,3,256,324]."

**Comment by hgaiser** [comment]
Either `save_weights` or `save` should work (I usually just do `save`). From when is this model you're trying to load? Since this repository is under active development the architecture changes some times. It sounds like your saved model is from an older architecture.

**Comment by jwnsu** [comment]
It's from latest codes, the model was saved hours ago.

**Comment by hgaiser** [comment]
Could it then be that the number of classes changed in between saving and loading? Looks like one of your models has 5 classes whereas the other has 9 classes, does that make sense? Or depending on which layer is going wrong, it could also be 20 classes vs 36 classes.

**Comment by jwnsu** [comment]
You are right, forgot to change num_classes when constructed the model from saved file. Thanks --figured out this particular issue on my own, but much appreciation to your efforts on the project.

**Comment by hgaiser** [comment]
This issue is addressed in PR https://github.com/fizyr/keras-retinanet/pull/48.
