### ISSUE TITLE
Anchors modifying

### ISSUE THREAD

**Issue by wyy1106** [fizyr/keras-retinanet#205]
Hi~Thanks so much for your work first of all.If I want to increase the dimention of anchors,for example,from (9,4) to (27,8).Is the weights file 'ResNet-50-model.keras.h5' still avaliable?I encounter some issues,looking forward to your reply.

**Comment by hgaiser** [comment]
If you mean if it's still applicable, then yeah. That weights file doesn't
include regression parameters so there shouldn't be a mismatch. If you want
to transfer parameters from a model that has regression parameters already
included (for example the pretrained COCO model) you could load weights
using : https://github.com/keras-team/keras/pull/8462

**Comment by hgaiser** [comment]
Small update, the PR for loading models with mismatches between shapes has been merged into Keras. It should be available from Keras 2.1.3 (unreleased at time of writing).

I'll close this issue then.
