### ISSUE TITLE
testing the csv data

### ISSUE THREAD

**Issue by icoicqico** [fizyr/keras-retinanet#206]
Hello, I want to ask about using csv as input on opencv instead of coco, how do I modify the example to load the csv data, thanks a lot.

**Comment by hgaiser** [comment]
The README should be pretty self explanatory. What is unclear to you?

**Comment by icoicqico** [comment]
I have already train a data, but don't know how to load it into a detection program with opencv.

**Comment by de-vri-es** [comment]
This is not really related to CSV data. Once you got a trained model, the source of the training date is no longer relevant.

You can have a look at the example notebook on how to load the model and run detection on an image. I'm not 100% sure if it is up to date, but it should help you get started.

**Comment by hgaiser** [comment]
Is there still an issue to be resolved here? I'd like to close it otherwise.
