### ISSUE TITLE
Modifying Anchor Boxes

### ISSUE THREAD

**Issue by chaitons** [fizyr/keras-retinanet#208]
How do we modify the anchor boxes, and the model architecture?

**Comment by de-vri-es** [comment]
Modifying the anchors currently requires modifying the source. See also #205. This is still planned to be exposed properly through the API.

Using a different model than resnet is supported without modifying the source.  You can call `keras_retinanet.models.retinanet.retinanet` and pass in a custom submodel. If the submodel output is compatible, you can also use `retinanet_bbox`. For an example, you can check `models/resnet.py` which creates a retinanet model with resnet as backend.

**Comment by hgaiser** [comment]
Closing this in favour of https://github.com/fizyr/keras-retinanet/issues/324 .
