### ISSUE TITLE
Image preprocessing and scales

### ISSUE THREAD

**Issue by allgrom** [fizyr/keras-retinanet#209]
Hello!
I've several questions about image preprocessing.

- BGR or RGB image?
- Is it necessary to apply mean substraction?
- Is it necessary to apply normalization (divide by 255 or smth else)?

Does this repo support several scales for one image like girshick py-faster-rcnn?

**Comment by hgaiser** [comment]
- The network processes BGR images.
- There is an ImageNet mean subtraction (see [here](https://github.com/fizyr/keras-retinanet/blob/master/keras_retinanet/utils/image.py#L30)).
- No normalization is applied (for the reason that the original resnet implementation did not do this either).

Does this resolve your questions?

**Comment by allgrom** [comment]
One question)

> Does this repo supports several scales for one image like girshick py-faster-rcnn?

**Comment by hgaiser** [comment]
> Does this repo support several scales for one image like girshick py-faster-rcnn?

What do you mean exactly? As far as I remember, `py-faster-rcnn` scales the image such that the smallest side is 600px and then processes that image. `keras-retinanet` follows this same procedure. Other sizes of images can be configured in the data generator, but the default follows the procedure of `py-faster-rcnn`.

**Comment by allgrom** [comment]
I mean that `py-faster-rccn` can forward one image with several scales (e.g 600 and 100) and join outputs from scale 600 and scale 1000.

**Comment by de-vri-es** [comment]
This is not currently implemented in `keras-retinanet` itself.

Of course, you can feed the network multiple scaled images and combine the results yourself. It may make sense to perform non-maximum suppression *after* merging the results in that case. I'm not sure if this is something we want to support in `keras-retinanet` itself or if it makes more sense to keep it as a separate tool.

**Comment by allgrom** [comment]
Thank you!
