### ISSUE TITLE
predict on batch

### ISSUE THREAD

**Issue by peterdudfield** [fizyr/keras-retinanet#211]
I am using the mode.predict function. 
a, b, c= model.predict(image_batch)
a is the box deltas, b is the probabilities and c is the most probable predictions. 
I see that c is shape (batch_size,300,4+n_classes) but it seems to be repeated for the different images in the batch ( for example c[0] =c[1])

Also for a, b, c= model.predict_on_batch(image_batch). See c is of size (1,300,4+n_classes). 

Is this correct?

**Comment by hgaiser** [comment]
That depends on whether you enabled non-maximum suppression. If you enabled that, `batch_size > 1` is not possible (the NMS layer is not capable of handling this). If you have NMS disabled you can have `batch_size > 1` if you like, but you'd need to do your own NMS afterwards probably.

> I see that c is shape (batch_size,300,4+n_classes) but it seems to be repeated for the different images in the batch ( for example c[0] =c[1])

Why do you think this? They are most likely different for the different images in the batch.

**Comment by peterdudfield** [comment]
Thanks for the response. I think this make sense. Basically the NMS layer limits the batch size to 1 for predictions.

**Comment by hgaiser** [comment]
Exactly. I trust this solves your issue, so I'll close this.

**Comment by moyan007** [comment]
Hello sir, could you tell me that 300 means for what please?
