### ISSUE TITLE
Many similar regions detected as same object, how to merge them?

### ISSUE THREAD

**Issue by junyongyou** [fizyr/keras-retinanet#215]
Hi, I have used VOC2012 training data to train a model, and then tested it on new images. The results are very good. However, see my result image, it looks many similar regions are proposed and detected as the same object. How can we eliminate this or merge them? Thanks a lot.
![test_output](https://user-images.githubusercontent.com/13484072/34665165-79d198ca-f45f-11e7-861b-8f4d2c3f36b8.jpg)

**Comment by yhenon** [comment]
It looks like you are not applying non-maximum suppression properly. The easiest way to apply NMS correctly and then use:
```
classes, regressions, bboxes = prediction_model.predict(xxx)
```
Then `bboxes` will contain predictions with NMS applied.

**Comment by yhenon** [comment]
Closing as this is not an issue with the repo. Feel free to use the slack channel (see readme) for further questions.
