### ISSUE TITLE
I can't add keras-retinanet in Pycharm

### ISSUE THREAD

**Issue by hoanghoa213** [fizyr/keras-retinanet#217]

**Comment by hgaiser** [comment]
I've never worked with pycharm so I can't really help you there. What's the problem you're facing? Is it perhaps a pycharm related issue, not a keras-retinanet issue?

**Comment by mkocabas** [comment]
Hi @hoanghoa213, I'm working with Pycharm. If you select the interpreter as the same that keras-retinanet was installed, Pycharm can recognize it.

**Comment by hoanghoa213** [comment]
@mkocabas can you help me? i have so many problem. What config do you use in PyCharm? what environment do you use?

**Comment by mkocabas** [comment]
Can you be more specific? What do you mean by config in Pycharm?

**Comment by de-vri-es** [comment]
This does not sound like a problem with keras-retinanet. Feel free to discuss here further, but I'll close the issue though, since this is most likely a problem with your environment.
