### ISSUE TITLE
How i can use this with tensorflow-cpu version?

### ISSUE THREAD

**Issue by hoanghoa213** [fizyr/keras-retinanet#222]

**Comment by de-vri-es** [comment]
Just install the CPU version of tensorflow. It will be used by keras automatically if your environment is set up correctly.

**Comment by hoanghoa213** [comment]
But i have an error . ImportError: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.22' not found (required by /home/hoang/anaconda2/envs/tensorflow/lib/python2.7/site-packages/../../libopencv_objdetect.so.3.3)

**Comment by de-vri-es** [comment]
It looks like the tensorflow you're using has been compiled against a different libc version than what you have.

This is not an issue with `keras-retinanet` but with your installation environment. If you have trouble installing `tensorflow` with `anaconda`, your best bet is trying an `anaconda` help channel.

Closing this issue as it is not related to `keras-retinanet` itself.
