### ISSUE TITLE
validation in train.py 'csv' 

### ISSUE THREAD

**Issue by Weixing-Zhang** [fizyr/keras-retinanet#225]
In keras-retinanet/keras_retinanet/bin/train.py (branch: master), I found Line 206 (csv_parser.add_argument('--val-annotations' ... ) won't be executed if the dataset_type isn't 'coco' (Line 97-106). Am I missing something here?

**Comment by de-vri-es** [comment]
I think it should work as intended:

https://github.com/fizyr/keras-retinanet/blob/master/keras_retinanet/bin/train.py#L201

https://github.com/fizyr/keras-retinanet/blob/8f22f359949cf8cbf0886adaa61abd84fcd24d89/keras_retinanet/bin/train.py#L145-L160

Or am I the one missing something ?

**Comment by Weixing-Zhang** [comment]
@de-vri-es 
That's right. train.py creates generator for validation. But I meant was, in callbacks = create_callbacks (Line 246), passed validation_generator only happens in the if statement (Line 97-103).

**Comment by de-vri-es** [comment]
hmm, yeah, it looks like you're right. I'm not sure that there is a proper callback we can use for evaluating with a CSV generator though.

**Comment by de-vri-es** [comment]
I don't really know. I'd recommend just looking at the COCO dataset and see from there.

I do know that @hgaiser is working on an evaluation script on the `evaluation` branch. Maybe work from there can be used to make a validation callback for the training process as well. Ideally one that doesn't care which data generator is used.

**Comment by hgaiser** [comment]
As @de-vri-es said, there isn't a callback for anything other than COCO at the moment. Indeed the `evaluation` branch could (should?) include a callback for any dataset type.

For now I'll consider this issue resolved.

**Comment by Weixing-Zhang** [comment]
Thanks you all!

**Comment by de-vri-es** [comment]
For the archives: this should now be fixed by #231.
