### ISSUE TITLE
ReTrain resnet50_coco_best on another dataset

### ISSUE THREAD

**Issue by smehida** [fizyr/keras-retinanet#226]
Hi,
Is there anyway to train the model with resnet50_coco_best weights initialization, but with different class numbers and names? in other words how can I load the weights except top of the model?

**Comment by hgaiser** [comment]
Yes you can, but only using Keras 2.1.3 (at the time of writing, 2.1.3 is released 4 hours ago and I have not yet tested it with keras-retinanet).

If you add the flag `skip_mismatch=True` to `load_model` it should print warnings when layers cannot be copied, rather than throwing an error.

**Comment by smehida** [comment]
Actually I works, but it doesn't display any warning on the screen.

**Comment by coldgemini** [comment]
can you point out exactly where to put this skip_mismatch flag? I couldn't find flag like that in keras documents,

thanks

**Comment by smehida** [comment]
In models/resnet.py you can find a line which consists model.loadweights, you should just add this flag there.
Model.loadweights(..., skip_mismatch=True)

**Comment by hgaiser** [comment]
For future reference, the `skip_mismatch` flag got added in https://github.com/keras-team/keras/pull/8462 on [this](https://github.com/keras-team/keras/commit/0611d80cd05c1c199f4c41aae523bf8b988adf24#diff-fe3ca734e8421a17729d0b0ea4c800baR2600) line.

Which can be added [here](https://github.com/fizyr/keras-retinanet/blob/82a1ec66ce70d44fcb05309c7c5980aceb035b81/keras_retinanet/models/resnet.py#L83).

In addition, PR https://github.com/fizyr/keras-retinanet/pull/232 changes the default behaviour of `keras-retinanet` weight loading such that it should skip mismatching layers (and therefore allow something like COCO weights to be loaded for PascalVOC training).
