### ISSUE TITLE
How i can replace with my model?

### ISSUE THREAD

**Issue by hoanghoa213** [fizyr/keras-retinanet#230]
model = keras.models.load_model('snapshots/resnet50_coco_best.h5', custom_objects=custom_objects) . How i can replace resnet50_coco_best.h5?

**Comment by hgaiser** [comment]
This is not a lot of information to go on, but I'm assuming you have trained your own model then? If not, the README describes how you can train your own model. Once you have that, you get a `.h5` file as output. Replace the path `'snapshots/resnet50_coco_best.h5'` to your path and it should work.
