### ISSUE TITLE
How to train with TOW class "'motorbike'   : 13,     'person'      : 14,"

### ISSUE THREAD

**Issue by phuongpreo** [fizyr/keras-retinanet#236]
Hi,
I just training 2 class
```
 voc_classes = {'motorbike'   : 13,
    'person'      : 14}
```
But 👎 erros: 
```
ValueError: invalid annotations file: 005406.xml: could not parse object #0: class name 'aeroplane' not found in classes: ['motorbike', 'person']
```
How to train with TOW class ?!!
my english not bad ✌️ 
thak

**Comment by hgaiser** [comment]
The error seems pretty self-explanatory, you have an annotation of class aeroplane, but it is not defined in your classes list. Either add aeroplane to your list of classes, or remove that annotation from your list of annotations.

**Comment by phuongpreo** [comment]
Thank , and so
How to ignore the object not belonging to the my class (ex ignore obj name 'car' in file xml ) :)
ex
```
        if class_name not in self.classes:
            raise 'Do WHAT i Should ???'
```
thank you :)

**Comment by de-vri-es** [comment]
You should prepare a dataset that only contains annotations of classes that you want to train on. The data generator can not ignore annotations with unknown classes. Allowing that would hide errors from the user.

**Comment by hgaiser** [comment]
> You should prepare a dataset that only contains annotations of classes that you want to train on. The data generator can not ignore annotations with unknown classes. Allowing that would hide errors from the user.

I agree. I will assume this resolves your issue. If you have further questions on usage, feel free to join the Slack channel.

**Comment by phuongpreo** [comment]
Thank you so much :V i will try
