### ISSUE TITLE
Suitable Input size of Image

### ISSUE THREAD

**Issue by smehida** [fizyr/keras-retinanet#237]
Hi,
My trained model is very sensitive to scale of the image. I want to know is there any optimized input size for the network? In the training procedure what does exactly model do for the scaling of images?

**Comment by hgaiser** [comment]
Theres no straightforward answer to this question. The most important thing is that the anchors that are being generated, currently optimized for COCO dataset, fit your dataset. If your objects are too small or too big, they will not be detected.

The images are rescaled (by default) such that the smallest side equals 600px. If the largest side is then still larger than 1024 pixels, it is scaled down further such that the largest side is equal to 1024 pixels. These are settings that [can be adjusted](https://github.com/fizyr/keras-retinanet/blob/master/keras_retinanet/preprocessing/generator.py#L43-L44).

For further questions / discussions, I invite you to join the Slack channel.
