### ISSUE TITLE
coco issue

### ISSUE THREAD

**Issue by bughunter99** [fizyr/keras-retinanet#238]
Hi,

I tried to run the code on my pc that has python 3.6.
But because of below issue, it couldn't run.

from pycocotools.coco import COCO
ModuleNotFoundError: No module named 'pycocotools'

And I found it is impossible to use pycoco on python 3.x in below.

http://coco.lri.fr/COCOdoc/installation.html

Is retinanet only possible to run on python 2.x?
Thanks.

**Comment by hgaiser** [comment]
`keras-retinanet` should work fine on both python2 and python3. Did you follow the README? It explains how to install pycocotools. If this doesn't work for you, can you share the error you get when trying to install pycocotools?

**Comment by bughunter99** [comment]
Thanks. I had tried to do it on windows.
And I found cocodataset could not support windows for some reasons.

https://github.com/cocodataset/cocoapi/issues/51

I'll give up ^^;

**Comment by hgaiser** [comment]
Ah I see. You can try to use PascalVOC instead, or make your own CSV dataset (or install a real OS ;p).

I'll close this issue then.

**Comment by bughunter99** [comment]
Ok, I checked PascalVOC runned on my pc. Thanks.

**Comment by Chunde** [comment]
hi @bughunter99  You can replace extra_compile_args=['-Wno-cpp', '-Wno-unused-function', '-std=c99'] with extra_compile_args={'gcc': ['/Qstd=c99']} in ./libs/datasets/pycocotools/setup.py. maybe help

ref: https://github.com/CharlesShang/FastMaskRCNN/issues/173
