### ISSUE TITLE
Where i can run this script?

### ISSUE THREAD

**Issue by hoanghoa213** [fizyr/keras-retinanet#251]
# Using the installed script:
retinanet-train pascal <path to VOCdevkit/VOC2007>

**Comment by de-vri-es** [comment]
I'm not sure what the question is. If you install `keras-retinanet` you can run that command from a terminal.

**Comment by hoanghoa213** [comment]
I am doing train in PyCharm and i don't know how to import and how to use dataset ...

**Comment by hgaiser** [comment]
You can either choose to install `keras-retinanet` or choose to run the scripts from `keras_retinanet/bin/`, they are the same. For further support, please join the Slack channel.
