### ISSUE TITLE
pascal voc test ?

### ISSUE THREAD

**Issue by zhang92** [fizyr/keras-retinanet#252]
Can I use pascal voc to test? How use it? thanks very much

**Comment by yrluo** [comment]
It supports Pascal VOC naturally.
Just use command args to set the directory of the Pascal VOC Dataset.

The command may look like this:
`keras_retinanet/bin/train.py pascal <path to VOCdevkit/VOC2007>`

**Comment by zhang92** [comment]
yes,I have trained the module for Pascal VOC Dataset.
but i don't know  how to use the module to test an image or Pascal VOC Dataset.

**Comment by yrluo** [comment]
That's easy. Run `evaluate.py` in `bin/` and pass through the following args:
`Pascal
Pascal Path
Module Path (the module you trained before)`
And the program will run prediction and draw the Bbox of each image.

**Comment by zhang92** [comment]
python evaluate.py pascal '/home/zhangliyuan/RetinaNet/pascal/test' '/home/zhangliyuan/RetinaNet/snapshots/resnet50_pascal_05.h5' 

Traceback (most recent call last):
  File "evaluate.py", line 140, in <module>
    main()
  File "evaluate.py", line 115, in main
    generator = create_generator(args)
  File "evaluate.py", line 58, in create_generator
    'test',
TypeError: __init__() missing 1 required positional argument: 'image_data_generator'

**Comment by zhang92** [comment]
thanks very much

**Comment by hgaiser** [comment]
It seems you're running an outdated version of `keras-retinanet`. Please update to the latest version, retrain your network (unfortunately required due to some bugs in past few revisions) and try again.

If you have any more questions, feel free to join the Slack channel for support (directions are in the README).
