### ISSUE TITLE
Pretrained ResNet50RetinaNet model

### ISSUE THREAD

**Issue by AmitaiPerlstein** [fizyr/keras-retinanet#254]
There are few requests in this repository for pre-trained model to put in "_retinanet/snapshots_".
All threads lead to depracated pages.
Where can I find a pre-trained model that will work for the _ResNet50RetinaNet.ipynb_ notebook in "retinanet/examples" folder?

**Comment by hgaiser** [comment]
There is a link to the model in the [README](https://github.com/fizyr/keras-retinanet#ms-coco).
