### ISSUE TITLE
train_csv.py 

### ISSUE THREAD

**Issue by hoanghoa213** [fizyr/keras-retinanet#257]
parser.add_argument('--gpu', help='Id of the GPU to use (as reported by nvidia-smi).') 
What i can insert in ID when i don't have GPU?

**Comment by hgaiser** [comment]
It is an optional argument, allowing you to force a certain GPU. If you have no GPU, don't use the argument. Assuming you have installed the CPU version of tensorflow, it should use that by default.

**Comment by hoanghoa213** [comment]
Thank for your quick answer. But i don't understand this... can you suggest me? 
`parser = argparse.ArgumentParser(description='Simple training script for object detection from a CSV file.')
    parser.add_argument('csv_path', '/home/hoang/datasets/coco')
    parser.add_argument('--weights', 'imagenet')
    parser.add_argument('--batch-size', 1)`
