### ISSUE TITLE
Training on own data

### ISSUE THREAD

**Issue by Maxfashko** [fizyr/keras-retinanet#265]
Hey. I use my own data to teach this model. I use aerial photographs on which there are cars. This is how the markup file looks like:
```
<annotation>
<folder> </folder>
<filename>57.JPG</filename>
<source> </source>
<owner> </owner>
<size><width>1024</width>
<height>600</height>
<depth>3</depth></size>
<segmented>0</segmented>
<object><name>truck_trail</name>
<truncated>0</truncated>
<difficult>0</difficult>
<bndbox><xmin>939</xmin>
<ymin>345</ymin>
<xmax>1024</xmax>
<ymax>403</ymax>
</bndbox></object>
```

When an object is on the border of the image, an error occurs:

```
File "train.py", line 276, in <module>
    main()
  File "train.py", line 272, in main
    callbacks=callbacks,
  File "/usr/local/lib/python3.5/dist-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/keras/engine/training.py", line 2145, in fit_generator
    generator_output = next(output_generator)
  File "/usr/local/lib/python3.5/dist-packages/keras/utils/data_utils.py", line 770, in get
    six.reraise(value.__class__, value, value.__traceback__)
  File "/usr/local/lib/python3.5/dist-packages/six.py", line 693, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/keras/utils/data_utils.py", line 635, in _data_generator_task
    generator_output = next(self._generator)
  File "../../keras_retinanet/preprocessing/generator.py", line 246, in __next__
    return self.next()
  File "../../keras_retinanet/preprocessing/generator.py", line 257, in next
    return self.compute_input_output(group)
  File "../../keras_retinanet/preprocessing/generator.py", line 241, in compute_input_output
    targets = self.compute_targets(image_group, annotations_group)
  File "../../keras_retinanet/preprocessing/generator.py", line 206, in compute_targets
    labels_group[index], regression_group[index] = self.anchor_targets(max_shape, annotations, self.num_classes(), mask_shape=image.shape)
  File "../../keras_retinanet/preprocessing/generator.py", line 192, in anchor_targets
    return anchor_targets_bbox(image_shape, boxes, num_classes, mask_shape, negative_overlap, positive_overlap, **kwargs)
  File "../../keras_retinanet/utils/anchors.py", line 67, in anchor_targets_bbox
    labels[positive_indices, boxes[positive_indices, 4].astype(int)] = 1
IndexError: index 7 is out of bounds for axis 1 with size 7
Exception ignored in: <bound method BaseSession.__del__ of <tensorflow.python.client.session.Session object at 0x7f9e07378278>>
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 696, in __del__
TypeError: 'NoneType' object is not callable
```

I understand that the error is due to the fact that the bounding rectangles somehow change during the augmentation process. How to solve this?
![57](https://user-images.githubusercontent.com/11171626/35682964-143916ac-0795-11e8-8c5c-dae761a34991.jpg)

**Comment by hgaiser** [comment]
Are you sure you correctly initialized your generator ? Did you fill in the [classes](https://github.com/fizyr/keras-retinanet/blob/master/keras_retinanet/preprocessing/pascal_voc.py#L74) appropriately? Could you share how you initialized?

**Comment by Maxfashko** [comment]
I did not quite understand what is meant by initialization, but I did this:
There is a directory structure that is identical to PASCAL VOC2007.
Inside the directory there are annotation and image files.
I started the training as follows:
`python3 train.py pascal /path_to_data/VOC2007`
I just changed the following file:
`https://github.com/fizyr/keras-retinanet/blob/master/keras_retinanet/preprocessing/pascal_voc.py#L74`

```
voc_classes = {
    "truck"         :0,
    'car'           :1,
    'car'           :2,
    'dashed_line'   :3,
    'bus'           :4,
    'truck'         :5,
    'car_trail'     :6,
    'truck_trail'   :7,
    'van_trail'     :8
}
```

**Comment by Maxfashko** [comment]
The fact is that objects that are not located on the border of the image do not display an error
```
<object><name>car</name><truncated>0</truncated><difficult>0</difficult><bndbox><xmin>408</xmin><ymin>20</ymin><xmax>464</xmax><ymax>49</ymax></bndbox></object>
```

![52](https://user-images.githubusercontent.com/11171626/35683995-1f91c2ee-0798-11e8-8be8-d2b6e5863779.jpg)

**Comment by hgaiser** [comment]
I think there's something wrong with your classes. From your first post I see:
```
  File "../../keras_retinanet/utils/anchors.py", line 67, in anchor_targets_bbox
    labels[positive_indices, boxes[positive_indices, 4].astype(int)] = 1
IndexError: index 7 is out of bounds for axis 1 with size 7
```
That sounds like it is trying to access index 7 but the length of labels is 7.

If it's easy to do, I advice to make your data in the CSV structure. It's easier to make and easier to debug.

**Comment by Maxfashko** [comment]
Thank you! I twice announced a car and a truck
```
voc_classes = {
    "truck"         :0,
    'car'           :1,
    'car'           :2,
    'dashed_line'   :3,
    'bus'           :4,
    'truck'         :5,
    'car_trail'     :6,
    'truck_trail'   :7,
    'van_trail'     :8
}
```

**Comment by de-vri-es** [comment]
Glad to see the problem was found :)

I'm assuming the issue is fixed. If not, feel free to reply here.

**Comment by fastlater** [comment]
@Maxfashko  did you get good accuracy using aerial photographs as input?

**Comment by Maxfashko** [comment]
@fastlater 0.83 with mobilenet0_5 (224 size input).

**Comment by sshuair** [comment]
I am more curious what dataset you are using?

**Comment by sshuair** [comment]
@Maxfashko I am more curious what dataset you are using?

**Comment by ashishmokalkar** [comment]
@Maxfashko What does your directory structure look like?

**Comment by Maxfashko** [comment]
@ashishmokalkar, It`s depends on the generator. If you using pascal - look pascal voc directory structure
