### ISSUE TITLE
How can I re-train only the CLASS subnet while keeping the model's pre-trained weights of backbone and box subnets?

### ISSUE THREAD

**Issue by AmitaiPerlstein** [fizyr/keras-retinanet#268]

**Comment by awilliamson** [comment]
I believe this would involve recompiling the model. You would have to explicitly cycle through layers you wish to freeze, and similar to how we freeze the backbone ( See #243 ), you would set the trainable property to False.

This should then be confirmed in the summary output, that the number of trainable parameters is significantly decreased.

**Comment by hgaiser** [comment]
I'm not sure if you're talking about freezing everything except the classification subnet, or about transferring weights from a trained network to a fresh network, where only the number of classes differ. If it's the first, @awilliamson answer would be correct. If it's the second, it should work out of the box?

Either way, let's take this discussion to Slack (directions are in the README).
