### ISSUE TITLE
How to load snapshots?

### ISSUE THREAD

**Issue by mattignal** [fizyr/keras-retinanet#269]
Hi there,

I've tried to load my existing snapshots, but each time it says 'Creating Model..' instead of Loading Model. What do I input on the command line to load my snapshot?

Thanks!

**Comment by hgaiser** [comment]
Let's start with what the command is that you're executing?

**Comment by mattignal** [comment]
I've tried a few things, such as specifying path, but generally (working from memory here):

`keras_retinanet/bin/train.py --snapshot resnet50_data_04.h5 csv annotations.csv classes.csv`

**Comment by hgaiser** [comment]
Try printing the value of `args.snapshot` on [this](https://github.com/fizyr/keras-retinanet/blob/master/keras_retinanet/bin/train.py#L247) line.

It seems to work for me at least.

**Comment by JaosonMa** [comment]
i use this too ,
CUDA_VISIBLE_DEVICES=3 keras_retinanet/bin/train.py \
    --snapshot-path /home/jasonma/dev_sdb/models/keras-retinanet/20180920-detect \
    --tensorboard-dir /home/jasonma/dev_sdb/models/keras-retinanet/20180920-detect \
    --snapshot /home/jasonma/dev_sdb/models/keras-retinanet/20180920-detect/resnet50_pascal_05.h5 \
    --batch-size=2 \
    --gpu=3 \
    pascal /home/jasonma/dev_sdb/data/keras-retinanet-data/

resnet50_pascal_05.h5
but it start 
Epoch 1/50
   94/10000 [..............................
was not continue from epoch 05, 
how should i set it ?
@mattignal @hgaiser

**Comment by hgaiser** [comment]
It will start from epoch 1, but with the state of your snapshot.

**Comment by lakshmipriya04** [comment]
Incase my training gets stopped at some particular epoch (say 5). Is there any way to restart the training from same epoch 5 ?
TIA

**Comment by hgaiser** [comment]
You can use the --snapshot argument.

**Comment by rawat123** [comment]
@hgaiser so do we need to use --snapshot with --weights

**Comment by hgaiser** [comment]
> @hgaiser so do we need to use --snapshot with --weights

Nope you use one or the other.
