### ISSUE TITLE
AttributeError: module 'keras_resnet' has no attribute 'custom_objects'

### ISSUE THREAD

**Issue by blackxer** [fizyr/keras-retinanet#270]
When executing the train.py script,the below error is occured.
Traceback (most recent call last):
  keras-retinanet-master/keras_retinanet/bin/train.py", line 43, in <module>
    from ..models.resnet import resnet50_retinanet
  keras-retinanet-master/keras_retinanet/bin/../../keras_retinanet/models/resnet.py", line 28, in <module>
    custom_objects.update(keras_resnet.custom_objects)
AttributeError: module 'keras_resnet' has no attribute 'custom_objects'

**Comment by hgaiser** [comment]
Did you install the latest (`master`) version of keras_resnet? 

https://github.com/fizyr/keras-retinanet#installation

**Comment by blackxer** [comment]
yes,my version is 0.0.8.

**Comment by hgaiser** [comment]
That is different from the master version. Could you try the command in the
README ?

**Comment by blackxer** [comment]
I have tried the command according to the README  . It have solved my problem. Thank you !

**Comment by muhammetp** [comment]
i have implemented pip install --user --upgrade keras-retinanet that command but i still get the error ImportError: cannot import name custom_objects. i have used the macos and python 2.7. here is what written when i execute the command

pip install --user --upgrade keras-retinanet
Requirement already up-to-date: keras-retinanet in /Users/muhammet.pakyurek/Library/Python/2.7/lib/python/site-packages (0.4.1)
Requirement already satisfied, skipping upgrade: keras-resnet in /Users/muhammet.pakyurek/Library/Python/2.7/lib/python/site-packages (from keras-retinanet) (0.1.0)
Requirement already satisfied, skipping upgrade: six in /usr/local/lib/python2.7/site-packages (from keras-retinanet) (1.11.0)
Requirement already satisfied, skipping upgrade: cython in /Users/muhammet.pakyurek/Library/Python/2.7/lib/python/site-packages (from keras-retinanet) (0.28.4)
Requirement already satisfied, skipping upgrade: keras in /usr/local/lib/python2.7/site-packages (from keras-retinanet) (2.2.2)
Requirement already satisfied, skipping upgrade: scipy in /usr/local/lib/python2.7/site-packages (from keras-retinanet) (1.1.0)
Requirement already satisfied, skipping upgrade: numpy>=1.9.1 in /usr/local/lib/python2.7/site-packages (from keras->keras-retinanet) (1.15.0)
Requirement already satisfied, skipping upgrade: keras-preprocessing==1.0.2 in /usr/local/lib/python2.7/site-packages (from keras->keras-retinanet) (1.0.2)
Requirement already satisfied, skipping upgrade: h5py in /usr/local/lib/python2.7/site-packages (from keras->keras-retinanet) (2.8.0)
Requirement already satisfied, skipping upgrade: keras-applications==1.0.4 in /usr/local/lib/python2.7/site-packages (from keras->keras-retinanet) (1.0.4)
Requirement already satisfied, skipping upgrade: pyyaml in /usr/local/lib/python2.7/site-packages (from keras->keras-retinanet) (3.13)

**Comment by hgaiser** [comment]
@muhammetp what is the command / code that you're trying to execute?

**Comment by muhammetp** [comment]
pip install --user --upgrade keras-retinanet

**Comment by muhammetp** [comment]
i still get the error ImportError: cannot import name custom_objects.

**Comment by hgaiser** [comment]
> pip install --user --upgrade keras-retinanet

I doubt that command gives the ImportError. Also, please refrain from spamming your error over multiple issues.

**Comment by muhammetp** [comment]
nope. it deosnt give the error. when i run demo.py which includes
import keras

# import keras_retinanet
from keras_retinanet.models.resnet import custom_objects
from keras_retinanet.utils.image import read_image_bgr, preprocess_image, resize_image
from keras_retinanet.utils.visualization import draw_box, draw_caption
from keras_retinanet.utils.colors import label_color

i got the error. then i checked that whether keras-retinanet upgraded when i used  pip install --user --upgrade keras-retinanet

 yeah in order to get reply as soon as possible

**Comment by hgaiser** [comment]
I'm not sure where you got that `demo.py` from but it seems wrong. Try using the https://github.com/fizyr/keras-retinanet/blob/master/examples/ResNet50RetinaNet.ipynb as an example.

> yeah in order to get reply as soon as possible

Remember that we don't have to help you. These kind of comments make me less likely to really help you. A bit of patience and gratitude goes a long way.

**Comment by muhammetp** [comment]
apologies i dont want you to be offended.  what you have done is always valueable. it s not related to why i was intended to do.  my demo code is exactly the same to ResNet50RetinaNet.ipynb . it s a version which run on python directly.

**Comment by hgaiser** [comment]
Alright then. Your demo.py seems to import `from keras_retinanet.models.resnet import custom_objects` but that got removed a while back. The new method is to import `from keras_retinanet import models` and load your model using `model = models.load_model(model_path, backbone_name='resnet50')`. Your code might be exactly the same as the old ResNet50RetinaNet.ipynb, but not the same as the current ResNet50RetinaNet.ipynb.

**Comment by muhammetp** [comment]
thank you so much  for reply.

i was managed to run demo py.

boxes, scores, detections = model.predict_on_batch(np.expand_dims(image, axis=0))
print("processing time: ", time.time() - start)
print(detections.shape)
print(detections)
below is response of above code.
('processing time: ', 6.3751139640808105)
(1, 300)
[[ 0  0  0 27 60 56 56 56  0 56 78 60 56 60 13 60 67  0 39 56 41 56 27 56
  60  0 75  0 57 60 60 56  0 60 60 57 57 45 27 60 65 56 56 16 39 62 41 74
   0 56 56 60 57 26  0 27 13 13  9 67 28 13 60 62 27 60 15 60 13 13 56 56
  26  0 56 60 56 58 15 56 65 13 13 59 38  8 25 25  6 64 60 13 56 59 27 57
  12 65 75 71 28 73 57 65 37 57 73 59 67 59 13 45 24 56 25 20 26 59 14 78
  56 70  0  0  0 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1
  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1
  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1
  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1
  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1
  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1
  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1
  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1]]

in thsi case there is a problem at the line of 
predicted_labels = np.argmax(detections[0, :, 4:], axis=1) which is IndexError: too many indices for array.

2 question. 

1- what must be dimension of detections
2- what is the meaning of values in detection whose response is written above

**Comment by hgaiser** [comment]
Check the new example notebook, it is slightly different than what you're trying to do.

**Comment by muhammetp** [comment]
where the new example

**Comment by muhammetp** [comment]
any do you have a small size of data to understand training part?
