### ISSUE TITLE
ValueError: invalid option string 'train_path': must start with a character '-'

### ISSUE THREAD

**Issue by hoanghoa213** [fizyr/keras-retinanet#271]

**Comment by hgaiser** [comment]
Please provide more information, I have no idea where this is coming from at the moment.

**Comment by hoanghoa213** [comment]
Sorry, i am doing train_csv and i add path like below:
`    parser.add_argument('train_path', '/media/hoang/a76b38d1-d1c3-4c0d-8a70-24fba0a0f140/datasets/coco/images', help='Path to CSV file for training (required)')

And this show the error. 
`

**Comment by hgaiser** [comment]
You're executing a script called `train_csv` from the repository? If so, you need to update your repository.

Also, that is now how arguments are supposed to be filled in .. they are command line arguments.

As we don't define any `train_path` anywhere I'll go ahead and close this issue.

**Comment by navodathathsara** [comment]
ValueError: invalid option string 'f': must start with a character '-'

**Comment by hgaiser** [comment]
@navodathathsara please open a new issue and post more information than this.
