### ISSUE TITLE
Middle term contributions

### ISSUE THREAD

**Issue by lvaleriu** [fizyr/keras-retinanet#272]
What kind of contributions are you looking for in the middle term futur? New datasets, new weights, speed improvements?

**Comment by hgaiser** [comment]
There are a couple of things on my to-do list that I haven't gotten the time for yet:

- Closer comparison to the recently released Detectron implementation
- Find out more about per layer loss weight (did the original implementation use this and what are the weights) and how to apply it in Keras (seems impossible at the moment)
- Check why `batch_size > 1` seems to give lesser results
- Some better form of configuration (image sizes, anchors, thresholds, etc.)
- Other nets, including imagenet weights (mobilenet, resnext, ...)

I haven't gotten started on these yet and deadlines are taking up most of my time. Feel free to get started on any of them, but let me know ;)

Also, perhaps it's better to have this discussion on Slack, as this isn't really an issue.
