### ISSUE TITLE
example test error 

### ISSUE THREAD

**Issue by zilesazoyi2** [fizyr/keras-retinanet#283]
-when i try to run    ResNet50RetinaNet .ipynb  in Jupyter Notebook  seems errors !
could you give me some advice ? thank you a lot!
 

--------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-4-3c18969a06fa> in <module>()
     10 
     11 # import keras_retinanet
---> 12 from keras_retinanet.models.resnet import custom_objects
     13 from keras_retinanet.utils.image import read_image_bgr, preprocess_image, resize_image
     14 

ImportError: No module named 'keras_retinanet'

**Comment by yhenon** [comment]
Closing, this is a basic usage issue. See https://stackoverflow.com/questions/338768/python-error-importerror-no-module-named

**Comment by andongchen** [comment]
when i run ResNet50RetinaNet exemple i have other errors?Could help me ? thanks

super(NonMaximumSuppression, self).__init__(*args, **kwargs)
 
 File "/home/chenandong/.local/lib/python3.6/site-packages/keras/engine/topology.py", line 292, in __init__
    raise TypeError('Keyword argument not understood:', kwarg)
TypeError: ('Keyword argument not understood:', 'top_k')
