### ISSUE TITLE
ModuleNotFoundError: No module named 'keras_resnet'

### ISSUE THREAD

**Issue by Tejus-T** [fizyr/keras-retinanet#292]
Running the _ResNet50RetinaNet.ipynb_ file gave the following error. 
```python
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-2-3c18969a06fa> in <module>()
     10 
     11 # import keras_retinanet
---> 12 from keras_retinanet.models.resnet import custom_objects
     13 from keras_retinanet.utils.image import read_image_bgr, preprocess_image, resize_image
     14 

~/Documents/keras-retinanet/keras_retinanet/models/resnet.py in <module>()
     18 
     19 import keras
---> 20 import keras_resnet
     21 import keras_resnet.models
     22 from ..models import retinanet

ModuleNotFoundError: No module named 'keras_resnet'
```

I followed the Installation steps as written in the README.md file. Any help in this regard?

**Comment by de-vri-es** [comment]
```
ModuleNotFoundError: No module named 'keras_resnet'
```

`keras_restnet` is not installed properly, or your environment is not set up correctly to find it. Please make sure you actually followed all steps from the README.

**Comment by Tejus-T** [comment]
I cloned the Repo again, and followed the instruction mentioned on this post:

https://stackoverflow.com/questions/48741213/module-not-found-error-on-google-collaboratory

When running the file `examples/Resnet50RetinaNet.ipynb` we encountered the error:

`ModuleNotFoundError: No module named 'keras_retinanet'`

So I moved the file outside the Folder, and updated the `model_path` variable, and it worked!

Thanks for your help!
