### ISSUE TITLE
Evaluation required arguments error

### ISSUE THREAD

**Issue by isaacmg** [fizyr/keras-retinanet#299]
When trying to evaluate my model I get the following error 
`evaluate.py csv: error: the following arguments are required: classes`

Even though I'm passing the required parameters.
`keras-retinanet/keras_retinanet/bin/evaluate.py --model=snapshots/resnet50_csv_30.h5 csv test.csv class_labels.csv`

Could someone tell me what I'm doing wrong? The csv command worked fines during training by supplying `keras-retinanet/keras_retinanet/bin/train.py csv train.csv class_labels.csv` I don't understand why it doesn't work with evaluate as well. Thanks.

**Comment by hgaiser** [comment]
The model argument is not an optional argument (and it should be provided at the end of the command). I assume that is what is causing your problem.

**Comment by de-vri-es** [comment]
Hmm.. the error message should point at the right argument though. I'll pick this up soon.

**Comment by isaacmg** [comment]
Got it working by doing `keras-retinanet/keras_retinanet/bin/evaluate.py  csv test.csv class_labels.csv snapshots/resnet50_csv_30.h5`  I had to move it to the end and get rid of the --model tag. Agree though the error message definitely confused me.

**Comment by hgaiser** [comment]
Alright, at least your issue is resolved then. I propose to keep this open until @de-vri-es has checked it.

**Comment by hgaiser** [comment]
@de-vri-es, any update on this?

**Comment by de-vri-es** [comment]
Not really, except that I completely want to change the way arguments are parsed and get rid of the unnamed subparsers. When I do that this problem should dissapear too.

**Comment by hgaiser** [comment]
Closing this

**Comment by mansi2421** [comment]
\keras_retinanet\bin> python evaluate.py csv "C:\Users\user\Pedestrian-Object-Detection\dataset\test.csv" "C:\Users\user\Pedestrian-Object-Detection\dataset\classes.csv" "C:\Users\user\Pedestrian-Object-Detection\output\Pedestrianinference.h5"
I am using the same command but i amm getting the error
usage: evaluate.py [-h] [--model MODEL] [--backbone BACKBONE] [--gpu GPU]
                   [--score-threshold SCORE_THRESHOLD]
                   [--iou-threshold IOU_THRESHOLD]
                   [--max-detections MAX_DETECTIONS] [--save-path SAVE_PATH]
                   [--image-min-side IMAGE_MIN_SIDE]
                   [--image-max-side IMAGE_MAX_SIDE] [--config CONFIG]
                   {coco,pascal,csv} ...
evaluate.py: error: unrecognized arguments: C:\Users\user\Pedestrian-Object-Detection\output\Pedestrianinference.h5

can you please help me
