### ISSUE TITLE
what is the detections'  format in testing ?

### ISSUE THREAD

**Issue by dongxuemin666** [fizyr/keras-retinanet#304]
Hello,I am so confused about the format of predicted 'detections' ,could you please explain it for me.
Thanks

**Comment by hgaiser** [comment]
`detections` is a matrix of size `(batch_size, N, 4 + num_classes)`. The first dimension indexes the batch (though I recommend sticking  to a size of 1 for now). The first 4 values for each row are the box in image coordinates (`(x1,y1,x2,y2)`). The rest of the row is the score for each class in your dataset in the range of `[0, 1]`. 

Does this answer your question?

**Comment by dongxuemin666** [comment]
It helped a lot
      So much thanks
