### ISSUE TITLE
imagenet-weights parse args superfluous

### ISSUE THREAD

**Issue by awilliamson** [fizyr/keras-retinanet#306]
We have `--imagenet-weights`, `--no-weights`, and `--weights`. If `--imagenet-weights` is `default=True`, then it shouldn't really need to be explicitly stated. The other weight command line arguments cover other eventualities such as not loading with a pre-trained backbone, or loading your own model.

I would propose that this can be removed as an argument. Unless I'm missing something?

**Comment by de-vri-es** [comment]
It's true that using it doesn't change the behaviour, but it currently does serve the purpose of documenting the default behaviour. Currently that is its main purpose.

**Comment by de-vri-es** [comment]
The weights arguments are grouped in a mutually exclusive group. Using two or more together should already trigger an error.

I don't really see a problem here. We have one more flag, true, but it also means its easy to see that the default is to use pretrained imagenet weights. Personally I mainly scan command line flags when reading man pages or `--help` output, and right now the `--imagenet-weights` flag will quickly draw attention if you're looking for weight initialization options.

**Comment by hgaiser** [comment]
I'm leaning towards removing it and add a comment in the help section for the other arguments to notify about the default behaviour. That would seem more logical to me.

**Comment by de-vri-es** [comment]
I'd stick the comment only on `--no-weights` in that case. However, it feels ugly to have an option that doesn't include 'imagenet' in the name control (in this case disable) loading of imagenet weights.

To me `--no-weights` seems like a more logical default (it would be cleaner to implement with argparse for one). Though from a practical standpoint I suppose using imagenet weights is a more useful default.

I don't feel very strongly about it, but I don't have a problem with a vestigial flag for documentation purposes.

**Comment by hgaiser** [comment]
> I'd stick the comment only on --no-weights in that case. However, it feels ugly to have an option that doesn't include 'imagenet' in the name control (in this case disable) loading of imagenet weights.

I see what you mean. Having a redundant option however is also ugly, so it's really a choice between two ugly solutions.

**Comment by de-vri-es** [comment]
If anyone wants to resolve this, I'd say open a PR. I won't block it. But then this issue can be closed. If nobody wants to solve it, I'd also like to close the issue.

**Comment by de-vri-es** [comment]
Feel free to open a PR to fix this.
