### ISSUE TITLE
No .xml files exporting from csv_generator.py

### ISSUE THREAD

**Issue by jlarochewpi** [fizyr/keras-retinanet#309]
When I run the csv_generator.py file in the terminal, it completes with no signs of error or success. I cannot find the .xml file exported.
The .csv files are structured appropriately, so I'm not sure what is wrong.

Just to be sure, the setup for the .csv files are
Bounding Boxes:
VOC2007/000003.jpg,1183,450,1961,272,eye
etc.

and

Class:
eye,0

(there is only one class for this application)

file names are class_name.csv (class list) and eye.csv (for the bounding boxes)

Thanks in advance

**Comment by hgaiser** [comment]
Please follow the `README` more closely, there is nowhere stated an XML file will be exported, nor does it say you should run `csv_geneeator.py`.
