### ISSUE TITLE
after setup, train the voc2007 data, but can't download the  ResNet-50-model.keras.h5

### ISSUE THREAD

**Issue by JaosonMa** [fizyr/keras-retinanet#313]
![image](https://user-images.githubusercontent.com/23551774/36956949-13af70ce-206c-11e8-9b1f-04998d0b33b9.png)
ResNet-50-model.keras.h5
https://github.com/fizyr/keras-models/releases/download/v0.0.1/ResNet-50-model.keras.h5
Downloading data from https://github.com/fizyr/keras-models/releases/download/v0.0.1/ResNet-50-model.keras.h5
Traceback (most recent call last):
  File "train.py", line 367, in <module>
    main()
  File "train.py", line 340, in main
    weights = download_imagenet(args.backbone)
  File "../../keras_retinanet/models/resnet.py", line 52, in download_imagenet
    md5_hash=checksum
  File "/usr/lib64/python2.7/site-packages/keras/utils/data_utils.py", line 224, in get_file
    raise Exception(error_msg.format(origin, e.errno, e.reason))
Exception: URL fetch failure on https://github.com/fizyr/keras-models/releases/download/v0.0.1/ResNet-50-model.keras.h5: None -- [Errno 110] Connection timed out

how should i do with this ?

**Comment by JaosonMa** [comment]
i can download the ResNet-50-model.keras.h5 on my windows compter, but i don.t know where should i put the file in?  if it works right, where the file will be download to ? 
我不知道这个文件下载到哪里？ 我现在可以已经有这个文件了，但是我不知道Linux下自动下载的时候这个文件会被放在那里？

**Comment by panda9095** [comment]
You can use the argument **--weights** to specify where the h5 file is.

**Comment by JaosonMa** [comment]
you mean  this? @panda9095 
![image](https://user-images.githubusercontent.com/23551774/36959106-418b1f84-207b-11e8-9bd0-4df9a171c5d3.png)

**Comment by xieenze** [comment]
if you are in china , you need to set vpn open  and paste the url to brower to download the model.

**Comment by xieenze** [comment]
model should be moved to ~/.keras/models, good luck

**Comment by de-vri-es** [comment]
> you mean this? @panda9095

You should not modify the default value of the flag. You should pass the desired value on the command line.

**Comment by JaosonMa** [comment]
@de-vri-es 
![image](https://user-images.githubusercontent.com/23551774/36968446-79d89598-209d-11e8-8bd0-61e7dbb60173.png)

![image](https://user-images.githubusercontent.com/23551774/36968457-83a52f1e-209d-11e8-9c49-16d9be9ab6e6.png)

**Comment by JaosonMa** [comment]
@de-vri-es  i try this way , but  at last  this error 
Creating model, this may take a second...
/home/jansonm/keras-retinanet/data/keras_models/ResNet-50-model.keras.h5
Traceback (most recent call last):
  File "train.py", line 368, in <module>
    main()
  File "train.py", line 344, in main
    model, training_model, prediction_model = create_models(backbone_retinanet=retinanet, backbone=args.backbone, num_classes=train_generator.num_classes(), weights=weights, multi_gpu=args.multi_gpu)
  File "train.py", line 76, in create_models
    model            = model_with_weights(backbone_retinanet(num_classes, backbone=backbone, nms=True), weights=weights, skip_mismatch=True)
  File "train.py", line 55, in model_with_weights
    model.load_weights(weights, by_name=True, skip_mismatch=skip_mismatch)
  File "/usr/lib64/python2.7/site-packages/keras/engine/topology.py", line 2642, in load_weights
    raise ImportError('`load_weights` requires h5py.')
ImportError: `load_weights` requires h5py

**Comment by de-vri-es** [comment]
![image](https://user-images.githubusercontent.com/786213/36969198-25178470-2065-11e8-878e-bf7c6df78d16.png)

**Comment by JaosonMa** [comment]
@de-vri-es  what  does it mean?  the type is wrong?

**Comment by de-vri-es** [comment]
`load_weights` requires h5py

**Comment by JaosonMa** [comment]
@all specal @de-vri-es    thanks a lot!!!
![image](https://user-images.githubusercontent.com/23551774/36969851-99ffa358-20a1-11e8-8e8e-abfb77dcc8a9.png)

**Comment by de-vri-es** [comment]
Glad to see it's solved.

**Comment by ahuizxc** [comment]
@JaosonMa  我直接魔改的keras源码 里面有个data_utils.py我直接把cache改成我桌面了 hhhhh

**Comment by de-vri-es** [comment]
Please limit communication on the issue tracker to English. We have no idea what's being said otherwise.

Or at the very least try to provide an English translation.
