### ISSUE TITLE
Training slows down

### ISSUE THREAD

**Issue by lvaleriu** [fizyr/keras-retinanet#322]
I'm training mobilenet on coco with default parameters (batch_size=1, etc, etc, as specified here: https://github.com/fizyr/keras-retinanet/issues/300).

I've seen that from time to time (every 2, 3 epochs) an epoch takes much more time and i dont understand why. 

Normal epoch speed: 2939s 294ms/step
Slow epoch speed: 28566s 3s/step 

I've tried to stop the training and restart it as soon as i see this and then the speed goes normal.
I've also tried to benchmark the generator when the training speed gets low but there was no disk IO reading speed issue.

It is like after 2, 3 epochs the training is slowed down by something and dont know what...

**Comment by hgaiser** [comment]
Hmm I've seen something similar the other day, but it was with resnet50. I was testing a different training schedule and got a similar problem. I didn't look further into it and I have no explanation for it really... strange.

**Comment by de-vri-es** [comment]
If it happens again be sure to check the CPU and memory usage of the process, as well as the total CPU and memory usage of the system (both regular memory and GPU memory). It might give some clues.

**Comment by lvaleriu** [comment]
![image](https://user-images.githubusercontent.com/927999/37218218-14f94ca0-23c0-11e8-830e-3e43a3717586.png)

GPU usage is very low in those moments since it seems not many batches come to it.
CPU usage seems normal too. Ram stays around 14 gb.

I've also seen that sometimes, if i'm patient, the training speed becomes normal again. But sometimes only. The other times i have to stop the training, load the last model snapshot and start again the training.

**Comment by de-vri-es** [comment]
Whats the total memory capacity of your system? If it's 16 you *might* be seeing the effects of swapping. Even though 14 GB seems safely below 16. Can you check if anything is going into swap space when it happens?

**Comment by lvaleriu** [comment]
I have 32 gb of RAM.

**Comment by de-vri-es** [comment]
Ah, swapping seems out of the question then. Hmm...

**Comment by lvaleriu** [comment]
![image](https://user-images.githubusercontent.com/927999/37233841-2f39c092-23f5-11e8-98c2-ee53fc3089f7.png)

At the moment, it takes 3, 4 seconds for one batch to be processed (batch_size = 1).

**Comment by lvaleriu** [comment]
![image](https://user-images.githubusercontent.com/927999/37233904-70d65718-23f5-11e8-928f-b51fa4ade234.png)

GPU is sleeping ...

**Comment by lvaleriu** [comment]
This is very strange. The training was currently sleeping for at least 30 minutes. So i've launched a new python script where I iterate the CocoGenerator and this unblocks the training.

> 

```
from tqdm import tqdm

from keras_retinanet.preprocessing.coco import CocoGenerator
from keras_retinanet.utils.transform import random_transform_generator

transform_generator = random_transform_generator(flip_x_chance=0.5)

train_generator = CocoGenerator(data_dir='/media/work/image/coco', 
   set_name='train2017', transform_generator=transform_generator, batch_size=1)

def benchmark_gen():
    while True:
        a = train_generator.next()
        if a is None:
            break
        yield a

for _ in tqdm(benchmark_gen()):
    pass
```

**Comment by de-vri-es** [comment]
Hmm, I'd start to suspect bad power management on the nvidia card by now...

**Comment by lvaleriu** [comment]
I'm running this inside a docker container. And it happens only on coco (I'm training on coco for the first time since i want to contribute with some weights for mobilenet)

Otherwise, for the other datasets, i let the network for 1, 2 days and i dont have such issue.
I'm using pretrained retina_resnet50 and training on detection datasets with 1 - 4 classes.

I'll try to benchmark the coco_generator for a longer time to see if there is something that blocks/slows the iteration.

**Comment by aurotripathy** [comment]
Same here, I'm training VOC. I'm on Ubuntu 14.04 and CUDNN 7 and CUDA 8. 
During the first epoch, all my GPU were busy averaging 80% utilizations (`nvidia-smi -l`). 
At the start of the second epoch, the processing switched to CPU and the GPUs are idling. 
Needless to say, this has slowed everything.

**Comment by hgaiser** [comment]
I also have the feeling it's being switched back to CPU somehow.. what Keras are you guys running? Can you try rolling back to Keras 2.1.3 to see if that makes a difference?

**Comment by aurotripathy** [comment]
I've added the flag` --no-evaluation` (during training) and now the GPUs are being utilized fully in every epoch.

**Comment by lvaleriu** [comment]
Hmm... So this might happen because of the coco evaluation. This could explain why I dont have such issues when training on OID or other csv-like datasets. I’ll try to explore this direction.

**Comment by lvaleriu** [comment]
@hgaiser. I’m using keras 2.1.5. I’ll try to see if switching to 2.1.3 will make coco evaluation work again (if this is the issue, how I suspect it to be)

**Comment by aurotripathy** [comment]
@lvaleriu @hgaiser Thanks for looking into this. I'm training on the VOC dataset with the `--no-evaluation` flag (because I think, during the eval phase, the training switches to CPU mode). So you can replicate the issues with the following command:

`keras_retinanet/bin/train.py --multi-gpu=3 --batch-size=3 --no-evaluation --steps=10000 pascal <path/ti/pascal/dataset`

**Comment by ronyuzhang** [comment]
@aurotripathy  why is batch-size set 3? how to calculate it ?

**Comment by lvaleriu** [comment]
Removed coco evaluation after each epoch. At the 7th epoch the training slows down again ...

**Comment by allgrom** [comment]
Same here. I'm training retina resnet 50 on my own dataset and i'm using my own generator. 
![2018-03-20_09-59-41](https://user-images.githubusercontent.com/17882065/37640206-92fb0b76-2c25-11e8-9f98-85ce09f3424f.png)

**Comment by aurotripathy** [comment]
@ronyuzhang batch-size is set to 3 since multi-gpu is 3 

`--multi-gpu=3 --batch-size=3`

Hoping this is correct. Each gpu is handling one image.

**Comment by Devin147** [comment]
@aurotripathy Any update on this?

**Comment by yhenon** [comment]
I had a similar issue, and had some success increasing process priority, as so: https://askubuntu.com/questions/48708/change-niceness-priority-of-a-running-process

For example, try launching your job, then find the process ID, and do `renice -n -19 -p job_id`

**Comment by hgaiser** [comment]
I must say I haven't seen this error anymore. Maybe it was a driver / library / kernel / combination issue?

For reference,
OS: Arch Linux
kernel: 4.15.14-1
nvidia driver: 390.48-2
cuda: 9.1.85.2-1
cudnn: 7.1.2-1
tensorflow: 1.7.0-1
keras: 2.1.5

**Comment by lvaleriu** [comment]
I'll run a new training on coco today and keep you informed.

**Comment by lvaleriu** [comment]
Training mobilenet224_1.0 with the latest keras-retinanet takes more than 5, 6 hours (i'll give you the exact duration when one single epoch will finish) per epoch with batch_size = 1, 1 Titan X Gpu.
So there is something that slows down the process. At least on my machine...

**Comment by hgaiser** [comment]
What about the other libs and kernel? How does it compare to your versions?

**Comment by lvaleriu** [comment]
OS: ubuntu 16.04.3 LTS
kernel: 4.4.0-119-generic
tensorflow: 1.6.0
keras: 2.1.5
cuda: 9.0.176
cudnn: 7.0.5.15

I'm updating right now the libs and drivers and try again.

**Comment by hgaiser** [comment]
What nvidia driver are you running? I think that one is the most likely candidate for such an issue as this.

**Comment by lvaleriu** [comment]
I've just updated only the driver and runned with the old container. The epoch duration seems to take a few hours again (instead of less than one hour). I'll update the docker image with the latest cudnn, etc and tell you.

**Comment by hgaiser** [comment]
Alright. I'm assuming you rebooted after updating the driver?

Also, I never tested mobilenet yet (intend to do so soon), do you only see this slowdown on mobilenet ?

**Comment by lvaleriu** [comment]
Training for 9 epochs with mobilenet128_1.0 and each epoch lasts around 3100 seconds.
So this issue seems to be solved. If everyone is ok I'll close this.

Small remark: I had to install tensorflow1.8.0rc1 for compatibility with the CUDNN 7.1.3.16. Seems that TF 1.7.0 isnt compatible yet (at least the version from pip on ubuntu 16.04).
