### ISSUE TITLE
Separation of data generators.

### ISSUE THREAD

**Issue by hgaiser** [fizyr/keras-retinanet#326]
Currently the `Generator` class is the abstract version of a generator, but more levels can be distinguished. The `Generator` class handles both really abstract concepts (such as its `size` method) as well as `bbox` specific concepts. @de-vri-es had the suggestion of splitting the `bbox` functionality of the `Generator` to another class which inherits from `Generator`. That opens the door for other types of generators to be made (mask generator for instance?).

@de-vri-es do you have anything to add?

**Comment by de-vri-es** [comment]
I wasn't actually proposing to use inheritance, but wrapping. Inheritance would force a single inheritance chain (or tree) whereas wrapping can be done in any order with any base generator.
