### ISSUE TITLE
evaluation.py is returning 44 classes for PascalVOC from the trained model

### ISSUE THREAD

**Issue by aurotripathy** [fizyr/keras-retinanet#331]
Hi, need help. I've trained the PascalVOC dataset w/keras-retinanet and now, during the evaluation,  detections gives me 44 classes (instead of 20 classes). So the  label_to_name conversion is also failing. Grateful for pointers.

```
# Training
keras_retinanet/bin/train.py --multi-gpu=3 --batch-size=3 --no-evaluation --steps=10000 pascal /media/tempuser/RAID\ 5/data/VOCdevkit/VOC2012/

# Evaluation
./evaluate.py --gpu 0 pascal /media/tempuser/RAID\ 5/data/VOCdevkit/VOC2012/ ../../snapshots/resnet50_pascal_50.h5
```

**Comment by aurotripathy** [comment]
OK, I found a solution. Turns out, my training was using three GPUs and the detections output (during inference) returns three things; boxes, classifications and detections (would like to know why). So I'm just using the boxes and the classes.

**Comment by hgaiser** [comment]
So the network returns three things by default: regression, classification and detections.

The first two are outputs required for training and can be ignored. The last one, detections, is the final output of the network. The shape of detections is `(batch_size, num_anchors, 4 + num_classes)`. For PascalVOC this means 24 values per anchor. The first 4 values are a box in image coordinates (x1, y1, x2, y2), the rest are the different class scores.

Does this answer your question?

**Comment by aurotripathy** [comment]
Yes, it does. Thank you. I have no way to verify this as I lost my models in the snapshot folder as soon as I started another training session :-(.  
You can close this and I'll get back to it when I get time to rebuild the VOC models.

**Comment by hgaiser** [comment]
Alright :+1: , for future issues, you can close them yourself if they're resolved ;)
