### ISSUE TITLE
Shape of Detections for PascalVOC (48 instead of 24)

### ISSUE THREAD

**Issue by aurotripathy** [fizyr/keras-retinanet#336]
This also references issue #331.
 
I get 48 values instead of 24.
 
```
>>> detections.shape                                                                                                 
(1, 160956, 48)      
```

I notice that the _first_ 24 values have the regressed bounding box (size 4) and the classes (size 20). They look fine.

The _second_ 24 have the same information _but have have not been non-maximum supressed_ . So there are tens of instances of overlapping bounding-boxes.

My question is ...Should I use just the first 24? Just checking.

My pdb window below.

![screenshot from 2018-03-16 10 46 15](https://user-images.githubusercontent.com/1825684/37536464-dcea6540-2907-11e8-9683-269aad3ec46e.png)

**Comment by hgaiser** [comment]
Hmm really strange, for VOC it should definitely return `(1, num_anchors, 24)` in detections, not 48. What python are you using? Could you try running it on python3 to see if that makes a difference?

**Comment by hgaiser** [comment]
Strange. Can you test the following:

```python
from keras_retinanet.models.resnet import resnet50_retinanet
import numpy as np

image = np.zeros((512, 512, 3))
model = resnet50_retinanet(20)
_, _, detections = model.predict(np.expand_dims(image, axis=0))
print(detections.shape)
```

If I run this I get:
```
(1, 49104, 24)
```

**Comment by hgaiser** [comment]
Any update on this?
