### ISSUE TITLE
MobileNet and ResNet need different preprocessing

### ISSUE THREAD

**Issue by jonla1** [fizyr/keras-retinanet#340]
The models from keras.applications are using different preprocessing stategies. ResNet50 uses BGR and zero centered data. Whereas MobileNet uses RGB and scaled pixel values from -1 to 1. See keras.applications.mobilenet.preprocess_input. Both use keras.applications.imagenet.preprocess_input but different modes: Mobilenet uses 'tf' and Resnet 'caffee'.

I recommend replacing the custom load image and zero centering with the keras functions to avoid confusions.

**Comment by hgaiser** [comment]
Ah interesting. How should we add this knowledge to the generator... Preferably the generator knows nothing about the backbone that is used, but the backbone dictates what kind of preprocessing to perform. @de-vri-es?

**Comment by de-vri-es** [comment]
Any way to tackle this would be easier if we split the generator into smaller bits. The code for instantiating the models could then also be given a generator to wrap with the correct preprocessing function.

**Comment by hgaiser** [comment]
> Any way to tackle this would be easier if we split the generator into smaller bits. The code for instantiating the models could then also be given a generator to wrap with the correct preprocessing function.

Is there a more short-term solution? Refactoring the generators is quite a task I imagine.

**Comment by de-vri-es** [comment]
well... the generator could take a function to load an image from a string as constructor parameter. Then the script can fill in the right function based on the selected backbone.

But maintaining backwards API compatibility for that will be annoying when we do split the generators. Then again, if we split the generators their API will probably change drastically anyway.

**Comment by hgaiser** [comment]
I'm working on this ... the first step is https://github.com/fizyr/keras-retinanet/pull/417

**Comment by hgaiser** [comment]
Should be fixed with https://github.com/fizyr/keras-retinanet/pull/538
