### ISSUE TITLE
Invalid CSV annotations file

### ISSUE THREAD

**Issue by elhammoumi** [fizyr/keras-retinanet#347]
I created the annotations and the classes files here are the files

- Annotations
kdef_sorted\disgust\BM35DIS.JPG,84,228,388,388,disgust
kdef_sorted\fear\AF01AFHL.JPG,33,246,344,344,fear
kdef_sorted\fear\AF01AFHR.JPG,113,226,392,392,fear

- Classes
neutral,0
anger,1
disgust,2
fear,3
happy,4
sadness,5
surprise,6

I did not change anything in the code.
here is the command I used : 
`python keras_retinanet/bin/train.py csv annotations.csv classes.csv`

and this is the error I got:
`Using TensorFlow backend.
Traceback (most recent call last):
  File "keras_retinanet/bin/train.py", line 400, in <module>
    main()
  File "keras_retinanet/bin/train.py", line 347, in main
    train_generator, validation_generator = create_generators(args)
  File "keras_retinanet/bin/train.py", line 189, in create_generators
    batch_size=args.batch_size
  File "keras_retinanet/bin\..\..\keras_retinanet\preprocessing\csv_generator.py", line 138, in __init__
    raise_from(ValueError('invalid CSV annotations file: {}: {}'.format(csv_data_file, e)), None)
  File "<string>", line 3, in raise_from
ValueError: invalid CSV annotations file: annotations.csv: line 6: x2 (138) must be higher than x1 (317)`

Please help, thank you.

**Comment by beerboaa** [comment]
Hello, how did you solve this problem?

**Comment by JinwenJay** [comment]
change \ to /
e.g.  kdef_sorted\disgust\BM35DIS.JPG,84,228,388,388,disgust
to kdef_sorted/disgust/BM35DIS.JPG,84,228,388,388,disgust
