### ISSUE TITLE
Error in Image from PIL package import

### ISSUE THREAD

**Issue by DiegoAgher** [fizyr/keras-retinanet#349]
With the newest `pillow` version, `5.0.0` importing the module directly, `import PIL` doesnt work when using `PIL.Image`.

Importing the submodule directly, fixes this issue: `from PIL import Image`

Proposed fix in the following [PR](https://github.com/fizyr/keras-retinanet/pull/348).

Greetings.

**Comment by de-vri-es** [comment]
Fixed by #348. Thanks for your contribution!
