### ISSUE TITLE
Can't train on kitti dataset

### ISSUE THREAD

**Issue by FilipaRamos** [fizyr/keras-retinanet#351]
Hello!
First of all, thanks a lot for your work on this model. I cloned the repo and was trying to train the model on the kitti dataset which I exported using the digits extraction script. However, once I run ```python keras_retinanet/bin/train.py kitti /path/to/KITTI``` I get the following error:
```Traceback (most recent call last):
   File "keras_retinanet/bin/train.py", line 428, in <module>
      main()
   File "keras_retinanet/bin/train.py", line 366, in main
      train_generator, validation_generator = create_generator(args)
   File "keras_retinanet/bin/train.py", line 246, in create_generators
      if args.val_annotations:
AttributeError: 'Namespace' object has no attribute 'val_annotations'
```

Am I doing something wrong?
Thanks for the help in advance.

**Comment by hgaiser** [comment]
Apparently those arguments shouldn't be used for OID and KITTI. I just removed them in https://github.com/fizyr/keras-retinanet/commit/e3879cdbad5e517d1b904d93b2f08de79e4c292b , could you give that a shot?

Fair warning: I'm only working on the COCO dataset. Other datasets rely on community contribution to work.

**Comment by lvaleriu** [comment]
Yes, those arguments were unused (I got confused about their purpose in the csv_generator).

I can try to assist you with training on OID and Kitti if you still encounter issues.

**Comment by FilipaRamos** [comment]
Thanks a lot for the help! For now it's training, I'll report back in case something happens
