### ISSUE TITLE
Some questions about keras-retinanet

### ISSUE THREAD

**Issue by FilipaRamos** [fizyr/keras-retinanet#355]
Hello!
I am currently reading through the original paper however I have some doubts about the specific usage of this repository.
+ Is it possible to resume training from one previous training session's saved model?
+ How is the map calculated?
+ What is considered a good training time, I mean, how many epochs are generally necessary to achieve good results? I know it depends on the situation, but I just wanted to have a general perception.
+ The ETA shows ms/step after an epoch. What is considered a step?
Sorry if these are newbie questions, I'm just diving into this now! Thanks in advance.

**Comment by hgaiser** [comment]
> Is it possible to resume training from one previous training session's saved model?

Yep, theres a `--snapshot` argument in the training script.

> How is the map calculated?

For COCO or other datasets? For COCO it is using the pycoco repository for evaluation. For other datasets it is based on the evaluation code from `py-faster-rcnn`.

> What is considered a good training time, I mean, how many epochs are generally necessary to achieve good results? I know it depends on the situation, but I just wanted to have a general perception.

As you said, highly depends on the situation. To give you a ballpark, COCO required somewhere near 150 epochs (don't remember exactly). A custom dataset of nearly 2k images took around 30 epochs to reach its maximum.

> The ETA shows ms/step after an epoch. What is considered a step?

A step is one batch of image(s). Currently batch_size > 1 is broken so in that case one step corresponds to one image.

**Comment by FilipaRamos** [comment]
I am working on the kitti dataset and my question comes from my doubts as to how I should interpret the map I see after each epoch during training. Thanks a lot for all the help! I got everything else

**Comment by jpxrc** [comment]
> Yep, theres a --snapshot argument in the training script. This resumes the state of training from when it was saved. You can also load in the weights only using --weights. The difference is that the latter will start with a "clean" optimizer.

Hi, could you elaborate on what the benefit of starting with a 'clean' optimizer would be over not using one for training?
