### ISSUE TITLE
Errors when evaluating

### ISSUE THREAD

**Issue by pedroconceicao** [fizyr/keras-retinanet#356]
Hello guys,

I trained my network without any problem. However when I want to evaluate some images I get some errors:

- In visualization.py, is line 78 right? I'm gettin an error saying an argument is missing. There is no image when calling that function.  "def draw_box(image, box, color, thickness=2)"

- In eval.py, line 37, I get an error because I expect 4 outputs ( _, _, boxes, classification = model.predict_on_batch) and I only get 3. Is the correct way "boxes, regression, classification = model.predict_on_batch()" ? I tried several different ways without success.

Thank you in advance and keep the good work!

**Comment by de-vri-es** [comment]
> In visualization.py, is line 78 right? I'm gettin an error saying an argument is missing. There is no image when calling that function. "def draw_box(image, box, color, thickness=2)"

You appear to be right. The image should be passed to `draw_box` there too. Do you want to submit a PR?

> In eval.py, line 37, I get an error because I expect 4 outputs ( _, _, boxes, classification = model.predict_on_batch) and I only get 3. Is the correct way "boxes, regression, classification = model.predict_on_batch()" ? I tried several different ways without success.

The output of the model changed with #338. If you got a version from before that (it was merged today), the boxes and classification are together in one blob.

I'd recommend updating to the current master, but you can also see the old README here: https://github.com/fizyr/keras-retinanet/blob/be03c247e0c9567b61c5fa886fb39783357c34ca/README.md

**Comment by pedroconceicao** [comment]
> You appear to be right. The image should be passed to draw_box there too. Do you want to submit a PR?

Sure.

> The output of the model changed with #338. If you got a version from before that (it was merged today), the boxes and classification are together in one blob.

I actually updated today and already trained a new model. I tested it and I still get the error. I believe previous trained models won't work, right?

**Comment by hgaiser** [comment]
Previously trained models indeed won't work (out of the box). You can "update" a model by creating a model using the new code and then calling `model.load_weights(weights_path, by_name=True)`.

With the new code you can only get 3 outputs if you disable NMS (the fourth output is the classification after NMS).

**Comment by pedroconceicao** [comment]
I still don't get the outputs. In retinanet.py from line 363 to 368 you have (basically):

` outputs = [regression, classification] + other + [boxes]`
` if nms: outputs += [nms]`

So when I'm evaluating and I want, let's say, the bouning boxes coordinates what should I do? If I don't apply NMS will this be right?
` _, _, boxes = model.predict_on_batch`

And considering NMN will it be `regression, classficiation, boxes, nms = model.predict_on_batch` for example?

**Comment by pedroconceicao** [comment]
When I try to predict an image I get this error

`  File "..\..\keras_retinanet\utils\visualization.py", line 34, in draw_box` 
    ` cv2.rectangle(image, (b[0], b[1]), (b[2], b[3]), color, thickness, cv2.LINE_AA)` 
` IndexError: index 1 is out of bounds for axis 0 with size 1`

And the shapes of the regression, classification and boxes variables are, respectively, (1, 120087, 4), (1, 120087, 1), (1, 120087, 1). Could you explain the outputs and its order a bit better please?

**Comment by hgaiser** [comment]
Are you sure your boxes output is shaped `(1, 120087, 1)` ? It should have 4 columns, for x1, y1, x2, y2. Regardless, your assumptions are correct, but the output of boxes is a bit weird. Also you're only using 1 class I guess ?

**Comment by pedroconceicao** [comment]
Yes, I'm pretty sure and I found it strange. Maybe I can change the order of the outputs to get the desired shape/array for each variable. However there are two variables with the same array shape and I don't know which of the two arrays is the regression and the classification.

Yes, I'm in the beggining of my work so, for now, I'm keeping things as simple as I can.

**Comment by pedroconceicao** [comment]
I already got it working fine. I completely uninstalled retinan-net and installed it again from scratch. 

Thank you for the attention!
