### ISSUE TITLE
Input image size

### ISSUE THREAD

**Issue by franksRsrch** [fizyr/keras-retinanet#360]
In the paper it reports that the input size is 600x600. Am I right in thinking that this parameter is set in generator.py and that the default is set to 1333x800?

**Comment by yhenon** [comment]
>the paper it reports that the input size is 600x600

It does not say that. It says ` input image scale (defined by the shorter image side).` So the scale is the shorter side of the image, such that aspect ratio is preserved. The paper uses 600px for ablation studies, while the main results are reported at 800px.

>Am I right in thinking that this parameter is set in generator.py and that the default is set to 1333x800?

No. The minimum for the shorted image side is 800px preserving aspect ratio (to match the paer), with an additional constraint that the larger size is not larger than 1366px.
