### ISSUE TITLE
Why is group method ratio even when default batch_size is 1

### ISSUE THREAD

**Issue by adityapatadia** [fizyr/keras-retinanet#362]
https://github.com/fizyr/keras-retinanet/blob/99f1e96af98092aeaaff8c5a8475ee6c8795c2c1/keras_retinanet/preprocessing/generator.py#L41

Can we set to 'random'? It increases speed drastically.

**Comment by yhenon** [comment]
There should be no issue doing that, it would even make sense to make that the default. I'm surprised to hear it `increases speed drastically` ? The grouping is only performed once, at the start. Is your dataset large/ HDD slow?

**Comment by adityapatadia** [comment]
Yes big database and slow HDD both.

**Comment by adityapatadia** [comment]
Apart from that what is your take on larger batch size? Can we train this with barch_size > 1?

**Comment by yhenon** [comment]
>Can we train this with barch_size > 1

Currently doing that will result in less good mAP, so I recommend batch_size=1. I am actively looking into it though, and I think I am getting closer.
