### ISSUE TITLE
pre-trained weights for custom networks

### ISSUE THREAD

**Issue by rodrigo2019** [fizyr/keras-retinanet#364]
Hello, first of all, congratulations for this code, really well structured and easy to understand.
I'm testing some custom networks focused on speed, like TinyDarkNet.
I would like to know if has some method to speed up the time for converge in a good results, I'm training on a 1070 ti that takes around 4000s per epoch, I tried to train a Autoencoder before (for around 8hours), but I noticied that doesnt helped, so I would like to know if has some method that help me to start with better weights which can save some time.

![image](https://user-images.githubusercontent.com/8016520/38165455-f305f8c4-34e9-11e8-978a-683c3df344e2.png)

Doing some tests I saw that TinyDarkNet take almost same time to predict as ResNet50, around 160ms per image. It should be really different times, right?

Thank you

**Comment by hgaiser** [comment]
You could initialize with the pretrained COCO weights, that should help speed up the training time for your network. That does mean you're limited to ResNet50 though.

**Comment by rodrigo2019** [comment]
thank you @hgaiser, another option is the VGG that also has pre trained weights
