### ISSUE TITLE
More efficient interference

### ISSUE THREAD

**Issue by jonla1** [fizyr/keras-retinanet#365]
From what I read is that channels_first mode seems to be faster when executed on a GPU. Are there plans to support both modes?

**Comment by hgaiser** [comment]
I wouldn't mind having that support, but it's definitely not planned. I've read that too that it should be faster. Do you have any measurements that supports how much it differs?

**Comment by jonla1** [comment]
Thanks for the info. I am currently trying to get it to work in my R-FCN setup, I will give an update on slack (maybe better place to discuss this, as it is not really an issue) when the first training is finished.
