### ISSUE TITLE
Not able to use --val-annotations on custom CSV dataset

### ISSUE THREAD

**Issue by SarveshRedkar** [fizyr/keras-retinanet#366]
Hi there,

I'm trying to get evaluations result after each epoch on a model for the custom CSV dataset using the resnet50 backbone. I'm trying to train a model on ubuntu server 16.04, with Tesla K80 GPU having 12GB memory. I was able to train the model without errors initially, but when i try it using the --val-annotations argument as given in the following command:

`keras_retinanet/bin/train.py --steps=1000 --epochs=50 csv ./annotations-train.csv ./classes.csv --val-annotations ./annotations-val.csv`
or
`keras_retinanet/bin/train.py --steps=1000 --epochs=50 csv ./annotations-train.csv ./classes.csv --val-annotations=./annotations-val.csv`

I get the following error when I run the training with --val-annotations flag provided:

> Traceback (most recent call last):
>  File "keras_retinanet/bin/train.py", line 426, in <module>
>    main()
>  File "keras_retinanet/bin/train.py", line 422, in main
>    callbacks=callbacks,
>  File "/home/ubuntu/.local/lib/python2.7/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
>    return func(*args, **kwargs)
>  File "/home/ubuntu/.local/lib/python2.7/site-packages/keras/engine/training.py", line 2262, in fit_generator
>    callbacks.on_epoch_end(epoch, epoch_logs)
>  File "/home/ubuntu/.local/lib/python2.7/site-packages/keras/callbacks.py", line 77, in on_epoch_end
>    callback.on_epoch_end(epoch, logs)
>  File "keras_retinanet/bin/../../keras_retinanet/callbacks/common.py", line 30, in on_epoch_end
>    self.callback.on_epoch_end(epoch, logs=logs)
>  File "keras_retinanet/bin/../../keras_retinanet/callbacks/eval.py", line 67, in on_epoch_end
>    print(self.generator.label_to_name(label), '{:.4f}'.format(average_precision))
>  File "keras_retinanet/bin/../../keras_retinanet/preprocessing/csv_generator.py", line 153, in label_to_name
>    return self.labels[label]
> KeyError: 0

Any help would be greatly appreciated.
Thank you in advance!

**Comment by yhenon** [comment]
Can you share your `classes.csv` ? It looks like you didn't begin your class list at 0, which the evaluation code assumes.

**Comment by SarveshRedkar** [comment]
@yhenon Thanks for the help. My class list began at 1. After changing the Classes.csv it worked for me.
