### ISSUE TITLE
Using generated H5 file leads to zero output in another machine.

### ISSUE THREAD

**Issue by Doodleshr** [fizyr/keras-retinanet#379]
Hi guys,

I trained a model and it was all good until I copied the generated weights (like resnet50_csv_50.h5) to another machine  : the model is giving zero output, while if I test the model using provided ResNet50RetinaNet.ipynb on the machine where I did the training I could get good and reasonable output.
If I print the model summary on the training machine and the testing machine, the last layer differs as shown below:
`nms (NonMaximumSuppression)     (None, None, 9)      0           regress_boxes_1[0][0]            
                                                                 classification[0][0]  `
`nms (NonMaximumSuppression)     (None, None, 5)      0           regress_boxes_1[0][0]            
                                                                 classification[0][0]  `

So I am wondering if I am doing it right, copying generated weights from the training machine to the testing machine and specify its location in ResNet50RetinaNet.ipynb.  How come the same h5 file could lead to different model summaries?

Thanks in advance for any help,
shr

**Comment by hgaiser** [comment]
Are you sure both machines are using the same version of keras-retinanet? It sounds like there is a difference there. Also check to make sure Keras is on the same version, though I suspect this isn't the problem.

In general, what you're doing should be possible (we're doing it too).

**Comment by Doodleshr** [comment]
@hgaiser Oh right, I am not using the same version of retinanet, thanks for your kind help.
