### ISSUE TITLE
Any examples for training on custom data set?

### ISSUE THREAD

**Issue by taewookim** [fizyr/keras-retinanet#38]
particularly, im interested in merging some classes from COCO, widerface, and imagenet.

any tutorials you can point me to?

**Comment by hgaiser** [comment]
I'm afraid you're on your own here. The plan is to add a "custom" dataset generator which assumes a certain dataset syntax, but even then you'll need to supply the dataset yourself. Merging datasets isn't really the concern of this repository.

**Comment by taewookim** [comment]
sorry, i wasn't asking about merging those 3 datasets ( i would merge whatever is necessary myself)

my question was  if i had my own dataset (csv w/path, classname, xmin,xmax, ymin, ymax), how would i go about training keras retinanet on it.

this repo was referred to by [keras frcnn](https://github.com/yhenon/keras-frcnn) and that repo had explicit instructions on how to do so. I assumed the maintainer of that repo was also on here

**Comment by hgaiser** [comment]
Ah I see, I misunderstood then. He's actually the one who suggested that style of "custom dataset" generator, which sounds like a good idea. I haven't had time to add that yet though.

**Comment by yhenon** [comment]
I am the maintainer of the keras-frcnn repo, and I am indeed here! A custom dataset loader is in the works.

**Comment by taewookim** [comment]
I'll take a stab at it. Doesn't seem too hard

BTW, do you have any accuracy benchmarks? (i.e. mAP ) Would be nice to compare to other architectures

**Comment by taewookim** [comment]
Oh oops.. @yhenon, sorry, you replied as I replied.

Awesome!. Looking forward to seeing it

**Comment by hgaiser** [comment]
This issue is addressed in PR https://github.com/fizyr/keras-retinanet/pull/51. I will close this when that gets merged.

**Comment by hgaiser** [comment]
This issue is addressed in PR https://github.com/fizyr/keras-retinanet/pull/48.
