### ISSUE TITLE
Evaluation problem

### ISSUE THREAD

**Issue by huxianxian** [fizyr/keras-retinanet#384]
Hello , Thanks for your amazing work. 
However , I find that the result automatically evaluated by the callbacks function after training finished is little lower than the result evaluated by running `/bin/evaluate.py` .  The following is my experiment result :
I train the model with the parameters: `--epochs 1 --steps 1000 --batch-size 1`, 
when the training is done, I got the following results:
```
 991/1000 [============================>.] - ETA: 2s - loss: 2.7543 - regression_loss: 2.3785 - classification_loss: 0.3757
 992/1000 [============================>.] - ETA: 1s - loss: 2.7531 - regression_loss: 2.3777 - classification_loss: 0.3755
 993/1000 [============================>.] - ETA: 1s - loss: 2.7522 - regression_loss: 2.3769 - classification_loss: 0.3752
 994/1000 [============================>.] - ETA: 1s - loss: 2.7510 - regression_loss: 2.3760 - classification_loss: 0.3750
 995/1000 [============================>.] - ETA: 1s - loss: 2.7496 - regression_loss: 2.3749 - classification_loss: 0.3747
 996/1000 [============================>.] - ETA: 0s - loss: 2.7497 - regression_loss: 2.3750 - classification_loss: 0.3747
 997/1000 [============================>.] - ETA: 0s - loss: 2.7489 - regression_loss: 2.3744 - classification_loss: 0.3745
 998/1000 [============================>.] - ETA: 0s - loss: 2.7473 - regression_loss: 2.3731 - classification_loss: 0.3742
 999/1000 [============================>.] - ETA: 0s - loss: 2.7459 - regression_loss: 2.3719 - classification_loss: 0.3740
1000/1000 [==============================] - 246s 246ms/step - loss: 2.7454 - regression_loss: 2.3716 - classification_loss: 0.3738

Epoch 00001: saving model to ./snapshots/resnet50_csv_01.h5
airplane 0.4378
mAP: 0.4378
```

Then I ran the  `/bin/evaluate.py` to evaluate the trained model  `./snapshots/resnet50_csv_01.h5`.  Well, I got the following results:
```
==================================================================================================
Total params: 36,382,957
Trainable params: 36,276,717
Non-trainable params: 106,240
__________________________________________________________________________________________________
None
airplane 0.4085
mAP: 0.4085
```

Obviously, the latter is  approximately 0.03 lower than the former. So why did it happen ?I have been  bothered a lot . Give me a hand please.

**Comment by rsingla92** [comment]
Are you asking what your test dataset (evaluation dataset) achieved a lower mAP than when you were training?

**Comment by hgaiser** [comment]
Hmm that's strange, they should execute exactly the same code on the same model. You're sure you haven't changed the evaluation args somewhere?

**Comment by hgaiser** [comment]
I just tried to replicate your issue using the COCO dataset (had to modify the train code a bit to use the non-COCO evaluation callback), but I didn't see the issue you're reporting. Can you verify if it is still a problem, otherwise I'm going to close this.
