### ISSUE TITLE
"Bus error (core dumped)" error after running training script

### ISSUE THREAD

**Issue by ravikrn** [fizyr/keras-retinanet#389]
I created csv dataset as per instructions and ran below query 
           
           keras_retinanet/bin/train.py csv /path/to/csv/file/containing/annotations /path/to/csv/file/containing/classes

But I got "Bus error (core dumped)" error

**Comment by hgaiser** [comment]
It sounds like your problem is elsewhere. Could you try running a Keras or Tensorflow tutorial (like MNIST) ?

**Comment by ravikrn** [comment]
I think it was issue with tensrboard. I commented tensorboard callback code. It worked
