### ISSUE TITLE
TypeError: pad() got an unexpected keyword argument 'constant_values'

### ISSUE THREAD

**Issue by a6225301** [fizyr/keras-retinanet#390]
https://github.com/fizyr/keras-retinanet/blob/fbf46ad7941dfaa7dd5c607086c4c940f34467f9/keras_retinanet/layers/filter_detections.py#L89

hi, when i update my code and train the model on my own dataset, it seems to appear that issue. Any good advices? 
TypeError: pad() got an unexpected keyword argument 'constant_values'
 
![1523638959](https://user-images.githubusercontent.com/22911232/38748098-9da24e64-3f7f-11e8-8496-1854bd7a2c50.jpg)

**Comment by rsingla92** [comment]
Odd! At a glance, backend.pad(...) is really tf.pad(...), which should adhere to the documentation found here: 
https://www.tensorflow.org/api_docs/python/tf/pad


```
tf.pad(
    tensor,
    paddings,
    mode='CONSTANT',
    name=None,
    constant_values=0
)
```

So at a glance things seem like they should be ok.

What version of Keras and tensorflow? What command did you run?

**Comment by hgaiser** [comment]
I'm also wondering what your tensorflow version is. I'm guessing it's out
of date.

**Comment by a6225301** [comment]
My tensorflow version is 1.2.1 , is there a basic version to run the model ?

**Comment by hgaiser** [comment]
I don't know to be honest, but 1.2.1 sounds quite old. Could you try
updating?

**Comment by a6225301** [comment]
Well, i'll  try to update my tensorflow version.
 By the way , during the training, is there an 'early_stopping' setting to monitor the 'val-loss' or some other metric to prevent the model being over-fitting ?

**Comment by rsingla92** [comment]
It is likely your tensorflow version.

See documentation for tensorflow r1.2 here: https://www.tensorflow.org/versions/r1.2/api_docs/python/tf/pad

which does not include 'constant_values' as a parameter. 

`pad(
    tensor,
    paddings,
    mode='CONSTANT',
    name=None
)`

Please update your tensorflow version. 

If you wanted to contribute back, you could always try the different versions (1.3 through 1.8 and the master) and report back on which errors out. The documentation for r1.3 indicates that it has introduced the `constant_values` arg to the tf.pad(...) function.

Hope this helps.

**Comment by rsingla92** [comment]
@a6225301 re: 'early_stopping' parameter - I would advise raising a separate issue for this.

**Comment by hgaiser** [comment]
I'm assuming updating tf will fix your issue.

**Comment by bw4sz** [comment]
anyone else wandering to this page. Tensorflow 1.1 (which is default in conda install tensorflow) yields the pad error above. Changing to 

```conda install -c conda-forge tensorflow``` gets tensorflow 1.8 and clears this up. Tested on OSX.

**Comment by handsomefengfeng** [comment]
I also encountered the question when i followed the instuctions described in the project.
My tensorflow is also 1.2.0 version.
I'm wondering what version you updated your tensorflow to solve the probolm

**Comment by hgaiser** [comment]
I would simply update to the latest version, currently that's 1.13.

**Comment by handsomefengfeng** [comment]
For the fact that I'm sharing the GPU with my classmates that I conld't update the cuda/cudnn privately, could you please tell me how to check the appropriate version of Tensorflow-GPU that contains the pad() function in which the 'constant_value' exists.
My CUDA Version 8.0.44 and CUDNN_MAJOR   5.
Thanks~!! :)

**Comment by handsomefengfeng** [comment]
Tensorflow Version above 1.3 is equipped wtih the wanted pad() function.
pad(
    tensor,
    paddings,
    mode='CONSTANT',
    name=None,
    constant_values=0
)
