### ISSUE TITLE
ValueError: need more than 2 values to unpack

### ISSUE THREAD

**Issue by a6225301** [fizyr/keras-retinanet#399]
Hi, i trained a detection model and the model was saved as '**.h5' , however, when i reload the model to test my data, it occurs with the error 'ValueError: need more than 2 values to unpack'. It's confusing that my model loads successfully but when it predicts the data it crashed. 
![_20180416213531](https://user-images.githubusercontent.com/22911232/38812302-886f2670-41be-11e8-932e-c9206295d754.png)

**Comment by hgaiser** [comment]
You still need to convert your training model to an inference model. You can check in the README how to do this.

We should probably add a utility function to wrap loading so that the conversion is done automatically..
