### ISSUE TITLE
Can anyone please help me on how to use evaluate for pascal data

### ISSUE THREAD

**Issue by rgsl888** [fizyr/keras-retinanet#400]
Hi I am trying to evaluate model, but I am not able to figure out how can I provide dataset path and model path, every time I am getting errors while running evaluate.py.

**Comment by hgaiser** [comment]
It would help if you could share the command you're running and the errors
you're getting..

**Comment by rgsl888** [comment]
I am trying something like this 
./keras_retinanet/bin/evaluate.py pascal ../data/RTTS model snapshots/resnet50_coco_best_v2.0.3.h5 

and error is as follows,
 
Using TensorFlow backend.
usage: evaluate.py [-h] [--gpu GPU] [--score-threshold SCORE_THRESHOLD]
                   [--iou-threshold IOU_THRESHOLD]
                   [--max-detections MAX_DETECTIONS] [--save-path SAVE_PATH]
                   {coco,pascal,csv} ... model
evaluate.py: error: unrecognized arguments: model

**Comment by rgsl888** [comment]
Its fin, I found it. Thank you

For others who might be seeking how to do it:

./keras_retinanet/bin/evaluate.py pascal {data-set path} {model_path}

eg:
./keras_retinanet/bin/evaluate.py pascal ../data/RTTS/ snapshots/resnet50_coco_best_v2.0.3.h5

**Comment by rgsl888** [comment]
But I have one more question,
         I am trying to use evaluate.py for Pascal data-set. I just gave single image in the test case but evaluate.py didn't find anything, but when I loaded same model on ipynb file for testing it detected all the objects. Can you please let me know if I am doing something wrong or misinterpretation. 

./keras_retinanet/bin/evaluate.py pascal ../data/RTTS/ snapshots/resnet50_coco_best_v2.0.3.h5

I am executing the command as shown above.

**Comment by hgaiser** [comment]
The pretrained model is trained on the COCO dataset, hence the mapping from classes to Pascal classes is incorrect for that model.

**Comment by rgsl888** [comment]
Do, you have any model trained for pascal data-set?

**Comment by hgaiser** [comment]
Nope, only COCO with resnet50.

**Comment by rgsl888** [comment]
Is there a way that I can change the mapping?

And can you please explain bit briefly on how this mapping works

**Comment by hgaiser** [comment]
The easiest way is to retrain for a bit using the COCO model as starting point, ie.:
```python
python keras_retinanet/bin/train.py --weights /path/to/coco/model.h5 pascal /path/to/pascal
```

About the mapping, COCO and Pascal encode classes differently. For Pascal, check [here](https://github.com/fizyr/keras-retinanet/blob/master/keras_retinanet/preprocessing/pascal_voc.py#L30-L51). For COCO you can see the mapping in the [example](https://github.com/fizyr/keras-retinanet/blob/master/examples/ResNet50RetinaNet.ipynb). I don't think you should change the mapping, they're simply two different datasets.

**Comment by Priyanka154** [comment]
python: can't open file 'keras_retinanet/bin/train.py': [Errno 2] No such file or directory
it giving me error

**Comment by SwordSam** [comment]
Thought top post for future reference This is how I evaluated my model on csv, I think for pascal you just need to change the csv to pascal and of course your annotation and classes files:

This is from repository, and I am using the GPU with ID 1 as I have two GPUs

`python keras_retinanet\bin\evaluate.py --gpu 1  csv annotations.csv classes.csv  ./snapshots/inference/resnet50_csv_100.h5`

**Comment by samomidi** [comment]
Thought to post for future reference. This is how I evaluated my model on csv, I think for pascal you just need to change the csv to pascal and of course your annotation and classes files:

This is from repository, and I am using the GPU with ID 1 as I have two GPUs

`python keras_retinanet\bin\evaluate.py --gpu 1 csv annotations.csv classes.csv ./snapshots/inference/resnet50_csv_100.h5`
