### ISSUE TITLE
example issue

### ISSUE THREAD

**Issue by gwspotex** [fizyr/keras-retinanet#403]
Today i try this keras-retinanet

but issue happen like picture

Anyone can answer me T_T

ps.why the (model.) has no list...........error

![image](https://user-images.githubusercontent.com/32533059/38884682-ea896700-42a2-11e8-8006-a38143533db3.png)

**Comment by mikemanski** [comment]
It's because there is no model to load in that location. It looks like this distribution used to have "resnet50_coco_best_v2.0.3.h5" bundled with it (in the snapshots directory), but currently it does not. 
I am not sure how to generate that model from scratch.

**Comment by hgaiser** [comment]
You can find it under releases. There's also a link for it in the README.
If you change the example to point to the releases page in a comment and
make a PR for it, that'd be nice.

**Comment by gwspotex** [comment]
![image](https://user-images.githubusercontent.com/32533059/38910303-4859a7e8-42fb-11e8-9634-2795a91bb139.png)

but my folder certainly have download the "resnet50_coco_best_v2.0.3" (h5)

spyder3.5+keras2.1.5+tensorflow-gpu1.7+win10

sorry i'm noob , some problem issue must be detail..

**Comment by gwspotex** [comment]
![image](https://user-images.githubusercontent.com/32533059/38913177-f4703596-430b-11e8-854a-b19587773dc6.png)
I try compile code 1 to 36 ,just load model and print model.summary

and u can see there some layer be define , that's mean i already load the 'resnet50_coco_best_v2.0.3'?

debug model by step find error is happen  on code "model.predict_on_batch" makes spyder system broken

that's i try my best to describe my question and debug

**Comment by hgaiser** [comment]
> I try compile code 1 to 36 ,just load model and print model.summary
> 
> and u can see there some layer be define , that's mean i already load the 'resnet50_coco_best_v2.0.3'?
> 
> debug model by step find error is happen on code "model.predict_on_batch" makes spyder system broken
> 
> that's i try my best to describe my question and debug

What is the error you're getting when running `predict_on_batch`? The screenshot from your first post doesn't show the complete error.

**Comment by gwspotex** [comment]
I try debug step on model.predict_on_batch have error

and i also find the model.() have't list

those are my error message 
C:\Users\gary\AppData\Local\Continuum\anaconda3\envs\tensorflow-gpu\lib\site-packages\keras\models.py:255: UserWarning: No training configuration found in save file: the model was *not* compiled. Compile it manually.
  warnings.warn('No training configuration found in save file: '
-----------------------------------------------------------------------------------------------------------------
2018󈚨󈚶 23:51:36.467801: I T:\src\github\tensorflow\tensorflow\core\platform\cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
2018󈚨󈚶 23:51:36.776977: I T:\src\github\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:1344] Found device 0 with properties: 
name: GeForce GTX 1080 Ti major: 6 minor: 1 memoryClockRate(GHz): 1.683
pciBusID: 0000:01:00.0
totalMemory: 11.00GiB freeMemory: 9.08GiB
2018󈚨󈚶 23:51:36.779076: I T:\src\github\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:1423] Adding visible gpu devices: 0
2018󈚨󈚶 23:51:37.990841: I T:\src\github\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:911] Device interconnect StreamExecutor with strength 1 edge matrix:
2018󈚨󈚶 23:51:37.991165: I T:\src\github\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:917] 0 
2018󈚨󈚶 23:51:37.991381: I T:\src\github\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:930] 0: N 
2018󈚨󈚶 23:51:37.991671: I T:\src\github\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:1041] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 8794 MB memory) ‑> physical GPU (device: 0, name: GeForce GTX 1080 Ti, pci bus id: 0000:01:00.0, compute capability: 6.1)
2018󈚨󈚶 23:51:45.400235: E T:\src\github\tensorflow\tensorflow\stream_executor\cuda\cuda_dnn.cc:396] Loaded runtime CuDNN library: 7103 (compatibility version 7100) but source was compiled with 7003 (compatibility version 7000). If using a binary install, upgrade your CuDNN library to match. If building from sources, make sure the library loaded at runtime matches a compatible version specified during compile configuration.
2018󈚨󈚶 23:51:45.402207: F T:\src\github\tensorflow\tensorflow\core\kernels\conv_ops.cc:712] Check failed: stream‑>parent()‑>GetConvolveAlgorithms( conv_parameters.ShouldIncludeWinogradNonfusedAlgo(), &algorithms)

**Comment by hgaiser** [comment]
I see no error there?

**Comment by YefeiGao** [comment]
seems like a runtime error with a dismatch  of cudnn version, try to change cudnn version to the same with ur tensorflow was compiled.

**Comment by hgaiser** [comment]
> seems like a runtime error with a dismatch of cudnn version, try to change cudnn version to the same with ur tensorflow was compiled.

Oh missed that, thought it was just tensorflow spamming stuff. But I agree, seems like a cuDNN incompatibility issue.

I'm closing this as it is not related to keras-retinanet.
