### ISSUE TITLE
Evaluating for the test set using evaluate.py

### ISSUE THREAD

**Issue by rgsl888** [fizyr/keras-retinanet#404]
evaluate.py has been designed to find mAP when the test data has all the object classes, if we have only few class of objects the mAP being calculated is wrong.

sum(average_precisions.values()) / len(average_precisions)

As we can see above, even though thereare know object to be identified as person in test data, still while calculating the mAP (the length), takes person class in consideration which improper.

I just thought, it would be better if I raise error for this so others don't have to search the coder.

If possible, please address this issue.

**Comment by rsingla92** [comment]
I'm not 100% clear on what the problem here is. Are you saying that if you were to test on a dataset that doesn't have "person" in it, but include "person" as one of your classes, it is improper to compute mAP as state?

If so, why would you include "person" in the classes arg passed to `evaluate.py`? 

If no, can you work through another example?

**Comment by rgsl888** [comment]
> I'm not 100% clear on what the problem here is. Are you saying that if you were to test on a dataset that doesn't have "person" in it, but include "person" as one of your classes, it is improper to compute mAP as state?
Yes, as per the calculation being carried out in this [file](https://github.com/fizyr/keras-retinanet/blob/master/keras_retinanet/bin/evaluate.pyl)
print('mAP: {:.4f}'.format(sum(average_precisions.values()) / len(average_precisions)))

The length of average_precision would be number of the classes defined in the, it doesn't check dynamically from json file for number of classes defined in the data-set.

The user might not know what classes are there in the data-set.

Now I have manually checked what all classes are present in the data set and calculated mAP, but checking classes for every  new data-set would be hazzle.

Please correct me if I am wrong.

**Comment by YefeiGao** [comment]
In practice, u should prepare ur owned dataset and annotation file without that situation i think ...

**Comment by hgaiser** [comment]
I'm closing this as it's not really an issue with the code base, that's just how the mAP is calculated for multiple classes.
