### ISSUE TITLE
Problem on ResNet50RetinaNet.ipynb

### ISSUE THREAD

**Issue by afifai** [fizyr/keras-retinanet#406]
Hello guys,
i don't know is this a right place to ask a question, but i wanna ask a question. 
I've train retinanet on my own dataset, but, when i want to predict using sample using sample script on jupyter notebook, it return :

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-5-39a6a7e590ec> in <module>()
     12 # process image
     13 start = time.time()
---> 14 boxes, scores, labels = model.predict_on_batch(np.expand_dims(image, axis=0))
     15 print("processing time: ", time.time() - start)
     16 

ValueError: not enough values to unpack (expected 3, got 2)
```

so i change this :

`boxes, scores, labels = model.predict_on_batch(np.expand_dims(image, axis=0))`

become

```
(boxes, nmsClassification) = model.predict_on_batch(np.expand_dims(image, axis=0))
labels = np.argmax(nmsClassification[0, :, :], axis=1)
scores = nmsClassification[0,np.arange(0, nmsClassification.shape[1]), labels]

```
it return no error,
but, i don't get any bounding boxes, when i print my `box` variable (before cast it into `int`) `[ 0.4144543   0.75406075 -0.02865006 -0.48030004]`. And when i cast it to int with function `astype(int)`, it return `[0,0,0,0]`how to get bounding boxes correctly ?

i'm using `keras 2.1.5` anyway

**Comment by hgaiser** [comment]
https://github.com/fizyr/keras-retinanet#converting-a-training-model-to-inference-model

**Comment by Tangzixia** [comment]
I got the same question

**Comment by Tangzixia** [comment]
can you tell me how you fix this problem?

**Comment by Deeperss** [comment]
> can you tell me how you fix this problem?
Look at the https://github.com/fizyr/keras-retinanet#converting-a-training-model-to-inference-model  ,in the test part ,convert the model that can address the isses
