### ISSUE TITLE
negative data mining

### ISSUE THREAD

**Issue by HuangBo-Terraloupe** [fizyr/keras-retinanet#410]
Few mouth ago I asked a question about the negative data mining.
How can we train the model with negative samples(the image does not contain any object, just background).
The solution you give me is make fake bounding box for these images, like [0, 0, 1, 1].
So in the evaluation part, these images might get every low classification scores and we can filter the bounding box by the classification score.
Is there any update of negative mining in this repo? Is there a better way to do it? Because I found this make the training get 0 loss. It is exactly what focus loss do...

**Comment by rodrigo2019** [comment]
From [readme](https://github.com/fizyr/keras-retinanet/blob/master/README.md) it says:

> The CSV file with annotations should contain one annotation per line. Images with multiple bounding boxes should use one row per bounding box. Note that indexing for pixel values starts at 0. The expected format of each line is:
> 
> path/to/image.jpg,x1,y1,x2,y2,class_name
> Some images may not contain any labeled objects. To add these images to the dataset as negative examples, add an annotation where x1, y1, x2, y2 and class_name are all empty:
> 
> `path/to/image.jpg,,,,,`
> A full example:
> 
>```
>/data/imgs/img_001.jpg,837,346,981,456,cow
> /data/imgs/img_002.jpg,215,312,279,391,cat
> /data/imgs/img_002.jpg,22,5,89,84,bird
> /data/imgs/img_003.jpg,,,,,
>```
> This defines a dataset with 3 images. img_001.jpg contains a cow. img_002.jpg contains a cat and a bird. img_003.jpg contains no interesting objects/animals.

**Comment by yhenon** [comment]
Indeed, this is fully supported now. Closing this.
