### ISSUE TITLE
What's the inference time of Retina-net?

### ISSUE THREAD

**Issue by YJHMITWEB** [fizyr/keras-retinanet#413]
Using a well-trained retina-net model, how much time does it need for inference per image?
Also, how long does it take to train the model from scratch? (and how many GPUs used?)
Thanks a lot.

**Comment by yhenon** [comment]
Please keep this page for issues only, this is better suited to slack. Feel free to join the #keras-retinanet Keras Slack channel (see readme).

In general, this depends on your GPU, image size, backbone, CUDA version, cudnn version and more. Execution time on NVIDIA Pascal Titan X is roughly 75msec for an image of shape 1000x800x3, about 50ms for an image of size 800x600 on a Titan X.
