### ISSUE TITLE
train.py: error: unrecognized arguments: --snapshot ./keras_retinanet/snapshots/resnet50_csv_44.h5

### ISSUE THREAD

**Issue by a6225301** [fizyr/keras-retinanet#414]
Hi，when i try to train the model from a snapshot model, it comes with the error 'train.py: error: unrecognized arguments: --snapshot' 
My training command line is 'python ./keras_retinanet/bin/train.py csv ./Process_zxy/annotation0to9.csv ./Process_zxy/class_mapping.csv --snapshot  ./keras_retinanet/snapshots/resnet50_csv_44.h5'
Any help? 
![image](https://user-images.githubusercontent.com/22911232/39027443-7638d60e-4484-11e8-8853-370cd12b25f6.png)

**Comment by YefeiGao** [comment]
Does this has help for u? #387

**Comment by a6225301** [comment]
@YefeiGao  Well, it works . 
So another question, how can i train the model on multi-gpu devices ?
command : --multi-gpu 2 ?     
i have two gpus and i want to parallel the model.

**Comment by YefeiGao** [comment]
According to the source code, command like this should work:
`keras_retinanet/bin/train.py --multi-gpu-force --multi-gpu 2 --batch-size 2 --weights ResNet-50-model.keras.h5 coco /data/coco/`
but i have not test yet...

**Comment by ramadevsaiteja** [comment]
Nope. I am also using two GPU's and I mentioned --multi-gpu-force --multi-gpu 2 but it's giving following error,
![screenshot from 2018-09-07 12-29-01](https://user-images.githubusercontent.com/25078260/45203425-b9029880-b26b-11e8-9212-c81f0bb77e59.png)

**Comment by de-vri-es** [comment]
Please include the full command line that is triggering the error. There's no way we can help otherwise. It is highly likely that #387 is exactly your issue.
