### ISSUE TITLE
coordinate？

### ISSUE THREAD

**Issue by zhang92** [fizyr/keras-retinanet#415]
I want to output the coordinates, 
xmin=boxes[0,0,0]?
ymin=boxes[0,0,1]?
xmax=boxes[0,0,2]?
ymax=boxes[0,0,3]?
It doesn't seem to be right，
Can you help me see what the coordinates are？
thank you very much

**Comment by YefeiGao** [comment]
Can you put more details about your trouble??? About voc detection result? or something else?

**Comment by zhang92** [comment]
yes，voc detection result‘coordinates. I want to output the voc detection result‘coordinates. I see it in eval.py. image_boxes      = boxes[0, indices[0][scores_sort], :]. But I don't know how to express the coordinates。

**Comment by hgaiser** [comment]
The coordinates are encoded as you said, x1/y1/x2/y2.

[README.md](https://github.com/fizyr/keras-retinanet#testing)

**Comment by zhang92** [comment]
yes,it's OK. Thank you very much
