### ISSUE TITLE
Keras hangs on predit

### ISSUE THREAD

**Issue by lukeb88** [fizyr/keras-retinanet#423]
After some days of test on this project, i'm facing a problem.
I'm using the pre-trained `resnet50_coco_best_v2.0.3.h5` and tensorflow **without** GPU.
My goal is similar to the notebook in /exsamples, but in real time.
I had modified the code of the notebook and (even if it was too slow for real-time) it worked. 

Today trying the code,  I raealized that there was some problem. And it seems to be Keras that hangs on predict (it successfully load the model).

In the beginning I thought that could be some modification that I made, but I have now the same problem with the original notebook.

**Comment by hgaiser** [comment]
Do other Keras models work properly for you? I'm not sure if this is related to the code from this repository.

**Comment by lukeb88** [comment]
For answer your question, i've tried this simple example:
[](https://machinelearningmastery.com/tutorial-first-neural-network-python-keras/)
in which I made a small change, I've saved the model and then loaded it to predict the result. And it works.

I'm also working with `nn4.small2.v1.h5` for face-recognition, but in this case I create a model and the only load the weigths, it works even in this case, but maybe the case it's a bit different.

(sorry, but as you have surely understood, I am new with Keras)

**Comment by hgaiser** [comment]
> Today trying the code, I raealized that there was some problem.

Did you mean with this that you updated the repository? If so, you could try older versions to see if the issue doesn't occur for you there.

**Comment by lukeb88** [comment]
> Did you mean with this that you updated the repository? If so, you could try older versions to see if the issue doesn't occur for you there.

I have modified my code that I obtained from this repository. But like I said, to check if I had made wrong changes, I tried again the original notebook and it does not work either.

**Comment by hgaiser** [comment]
I meant to ask what changed between the time that it worked and now? Did you update anything?

**Comment by lukeb88** [comment]
> I meant to ask what changed between the time that it worked and now? Did you update anything?

Sorry, no no, nothing that is related with this repository. I just tried keras for other projects but without change the installation or the version (same for tensorflow).

**Comment by mpcuter** [comment]
When I run a retinanet on cpu it also fails. It consumes all my systems memory and hangs. This happens when I run on inference model. 

I used to be able to run models trained in January on my cpu with no issue. 

I can still run these models on a Jetson in GPU mode.

**Comment by touchdown** [comment]
same here with tensorflow on py 3.6, not sure what the exact issue was, but was able to get around it on docker tensorflow which is on py 3.5

**Comment by hgaiser** [comment]
Is it possible it is simply using up all of your systems memory? I have no experience running keras-retinanet in cpu mode.

**Comment by lukeb88** [comment]
Guys, i was stuck on this problem for a few days.. i have spent a few days triyng to understand sere the problem was... This evening i managed to find the solution ... simply uninstalling keras and tensorflow and then reinstalling them at the same version..

**Comment by mpcuter** [comment]
Thanks Luke that fixed it for me too. Thanks!

**Comment by de-vri-es** [comment]
How exactly do you mean, the same version? Tensorflow is at 1.7 and Keras is at 2.1.6.

**Comment by hgaiser** [comment]
> How exactly do you mean, the same version? Tensorflow is at 1.7 and Keras is at 2.1.6.

I imagine he means installing the same versions he had.

I'll close this since it seems resolved.
