### ISSUE TITLE
Meet the error when predicting or continue training using the model train on my datasets with only one class

### ISSUE THREAD

**Issue by Tristacheng** [fizyr/keras-retinanet#430]
Hi,  I met the error like blow when I tried to evalute my model which trained on my dataset, I made my dataset the same  as VOC, it has only one class. It trains well from scratch, but it report error when tests or resumes training using saved weight.  model.predict_on_batch should return three values but it only has two, and I don't know why it happens.

![default](https://user-images.githubusercontent.com/12381965/39356334-58376300-4a42-11e8-8917-78380671d6dd.png)

![default](https://user-images.githubusercontent.com/12381965/39356518-c4afcd4c-4a42-11e8-939f-3cbf5837bd0d.png)

Can anyone help me? Thank you!

**Comment by hgaiser** [comment]
I think this will help you:

https://github.com/fizyr/keras-retinanet/blob/master/README.md#converting-a-training-model-to-inference-model

**Comment by Tristacheng** [comment]
@hgaiser thank you, you help me a lot
