### ISSUE TITLE
Missing "self" causes crash

### ISSUE THREAD

**Issue by pderian** [fizyr/keras-retinanet#431]
Error in `ResNetBackbone.download_imagenet()`:
https://github.com/fizyr/keras-retinanet/blob/afad72216a5d68c01ac9e6e487120656ce589950/keras_retinanet/models/resnet.py#L41
which produces the following:
```NameError: global name 'backbone' is not defined```

Proposed fix: replace `backbone` by `self.backbone`

Sorry, I won't be able to make a PR before long, so I thought I would better mention it here.
Keep on with the awesome work!

**Comment by lvaleriu** [comment]
I've made a PR for this: https://github.com/fizyr/keras-retinanet/pull/432

**Comment by hgaiser** [comment]
#432 is merged, so this should be resolved.
