### ISSUE TITLE
Can we load the snapshots of the model in the ResNet50RetinaNet.ipynb ?

### ISSUE THREAD

**Issue by rgsl888** [fizyr/keras-retinanet#435]
Hi,
          I tried to load the snapshot saved while training the model in the "ResNet50RetinaNet.ipynb", but I was getting error while predicting. The model that I printed had different outputs in pre-trained model and the snapshot model. I have attached the, for reference.
This snapshot, which was saved while training,
![snapshot](https://user-images.githubusercontent.com/33406337/39392223-efdbc202-4a77-11e8-8fa4-7bd69f53fcba.png)
This is pre-trained model
![pre-trained](https://user-images.githubusercontent.com/33406337/39392233-088cb428-4a78-11e8-8b1b-c1e2e94744a5.png)

**Comment by hgaiser** [comment]
What is the error you're getting?

**Comment by hgaiser** [comment]
https://github.com/fizyr/keras-retinanet/blob/master/README.md#converting-a-training-model-to-inference-model

**Comment by rgsl888** [comment]
Thank you, that solves my problem.
