### ISSUE TITLE
About per_process_gpu_memory_fraction and multi gpu.

### ISSUE THREAD

**Issue by wzjiang** [fizyr/keras-retinanet#436]
Hi，I have som problems when I train the model in the multi gpu way. Just like that 
ValueError: To call `multi_gpu_model` with `gpus=2`, we expect the following devices to be available: ['/cpu:0', '/gpu:0', '/gpu:1']. However this machine only has: [u'/cpu:0']. Try reducing `gpus`.
But I can train the model in one gpu. And the memory of gpu just cost 105MB, no matter how can i modified the batchsize from 8 to 128. Could you give me some help? Thank you very much.

**Comment by wzjiang** [comment]
Thank you for your reply. I have solved this problem. But there are some new problem with the master branch just like：
######################################################################
Traceback (most recent call last):
  File "keras_retinanet/bin/train.py", line 438, in <module>
    main()
  File "keras_retinanet/bin/train.py", line 406, in main
    freeze_backbone=args.freeze_backbone
  File "keras_retinanet/bin/train.py", line 90, in create_models
    prediction_model = retinanet_bbox(model=model)
  File "keras_retinanet/bin/../../keras_retinanet/models/retinanet.py", line 348, in retinanet_bbox
    detections = layers.FilterDetections(nms=nms, name='filtered_detections')([boxes, classification] + other)
  File "/home/wzjiang/.local/lib/python2.7/site-packages/keras/engine/topology.py", line 619, in __call__
    output = self.call(inputs, **kwargs)
  File "keras_retinanet/bin/../../keras_retinanet/layers/filter_detections.py", line 154, in call
    parallel_iterations=self.parallel_iterations
  File "keras_retinanet/bin/../../keras_retinanet/backend/tensorflow_backend.py", line 22, in map_fn
    return tensorflow.map_fn(*args, **kwargs)
  File "/home/wzjiang/anaconda/lib/python2.7/site-packages/tensorflow/python/ops/functional_ops.py", line 389, in map_fn
    swap_memory=swap_memory)
  File "/home/wzjiang/anaconda/lib/python2.7/site-packages/tensorflow/python/ops/control_flow_ops.py", line 2770, in while_loop
    result = context.BuildLoop(cond, body, loop_vars, shape_invariants)
  File "/home/wzjiang/anaconda/lib/python2.7/site-packages/tensorflow/python/ops/control_flow_ops.py", line 2599, in BuildLoop
    pred, body, original_loop_vars, loop_vars, shape_invariants)
  File "/home/wzjiang/anaconda/lib/python2.7/site-packages/tensorflow/python/ops/control_flow_ops.py", line 2549, in _BuildLoop
    body_result = body(*packed_vars_for_body)
  File "/home/wzjiang/anaconda/lib/python2.7/site-packages/tensorflow/python/ops/functional_ops.py", line 379, in compute
    packed_fn_values = fn(packed_values)
  File "keras_retinanet/bin/../../keras_retinanet/layers/filter_detections.py", line 146, in _filter_detections
    nms_threshold=self.nms_threshold,
  File "keras_retinanet/bin/../../keras_retinanet/layers/filter_detections.py", line 81, in filter_detections
    boxes    = backend.pad(boxes, [[0, pad_size], [0, 0]], constant_values=-1)
  File "keras_retinanet/bin/../../keras_retinanet/backend/tensorflow_backend.py", line 26, in pad
    return tensorflow.pad(*args, **kwargs)
TypeError: pad() got an unexpected keyword argument 'constant_values'
##############################################################################
but the old version have no problem. Could you give me some help. Thanks you very much and you great work.

**Comment by hgaiser** [comment]
Please search the issues first:
https://github.com/fizyr/keras-retinanet/issues/390

**Comment by wzjiang** [comment]
Thanks! Which version of your tensorflow is？My tensorflow is 1.2.0.

**Comment by hgaiser** [comment]
I'm running 1.7.

**Comment by wzjiang** [comment]
Thank you very much.

**Comment by yiwenxin518** [comment]
Please ,How do you solve the  first problem?Thanks.

**Comment by yiwenxin518** [comment]
Excuse me. How do you solve your first prooblem? Thanks very much.

ValueError: To call multi_gpu_model with gpus=2, we expect the following devices to be available: ['/cpu:0', '/gpu:0', '/gpu:1']. However this machine only has: [u'/cpu:0']. Try reducing gpus.

**Comment by Kittywyk** [comment]
> Thank you for your reply. I have solved this problem. But there are some new problem with the master branch just like： ###################################################################### Traceback (most recent call last): File "keras_retinanet/bin/train.py", line 438, in main() File "keras_retinanet/bin/train.py", line 406, in main freeze_backbone=args.freeze_backbone File "keras_retinanet/bin/train.py", line 90, in create_models prediction_model = retinanet_bbox(model=model) File "keras_retinanet/bin/../../keras_retinanet/models/retinanet.py", line 348, in retinanet_bbox detections = layers.FilterDetections(nms=nms, name='filtered_detections')([boxes, classification] + other) File "/home/wzjiang/.local/lib/python2.7/site-packages/keras/engine/topology.py", line 619, in **call** output = self.call(inputs, **kwargs) File "keras_retinanet/bin/../../keras_retinanet/layers/filter_detections.py", line 154, in call parallel_iterations=self.parallel_iterations File "keras_retinanet/bin/../../keras_retinanet/backend/tensorflow_backend.py", line 22, in map_fn return tensorflow.map_fn(*args, **kwargs) File "/home/wzjiang/anaconda/lib/python2.7/site-packages/tensorflow/python/ops/functional_ops.py", line 389, in map_fn swap_memory=swap_memory) File "/home/wzjiang/anaconda/lib/python2.7/site-packages/tensorflow/python/ops/control_flow_ops.py", line 2770, in while_loop result = context.BuildLoop(cond, body, loop_vars, shape_invariants) File "/home/wzjiang/anaconda/lib/python2.7/site-packages/tensorflow/python/ops/control_flow_ops.py", line 2599, in BuildLoop pred, body, original_loop_vars, loop_vars, shape_invariants) File "/home/wzjiang/anaconda/lib/python2.7/site-packages/tensorflow/python/ops/control_flow_ops.py", line 2549, in _BuildLoop body_result = body(*packed_vars_for_body) File "/home/wzjiang/anaconda/lib/python2.7/site-packages/tensorflow/python/ops/functional_ops.py", line 379, in compute packed_fn_values = fn(packed_values) File "keras_retinanet/bin/../../keras_retinanet/layers/filter_detections.py", line 146, in _filter_detections nms_threshold=self.nms_threshold, File "keras_retinanet/bin/../../keras_retinanet/layers/filter_detections.py", line 81, in filter_detections boxes = backend.pad(boxes, [[0, pad_size], [0, 0]], constant_values=-1) File "keras_retinanet/bin/../../keras_retinanet/backend/tensorflow_backend.py", line 26, in pad return tensorflow.pad(*args, **kwargs) TypeError: pad() got an unexpected keyword argument 'constant_values' ############################################################################## but the old version have no problem. Could you give me some help. Thanks you very much and you great work.

Hi, how did you solve it? Could u pls tell me? Thanks.

**Comment by HeiBoWang** [comment]
fuck you
