### ISSUE TITLE
Invalid annotations message

### ISSUE THREAD

**Issue by suchiek** [fizyr/keras-retinanet#437]
Hi,

I am getting an error message while running train.py and checked my annotations file. It appears that I have the layout needed:
pathname to image, xmin, ymin, xmax, ymax, classname.

Here is the message:
ValueError: invalid CSV annotations file: /home/mdsskv/keras-retinanet/all_new_train1.csv: line 5912: x2 (51) must be higher than x1 (51) 

I thought this meant that my xmax value was less than my xmin value. 

However, my annotation values are:
288 | 52 | 398 | 636

Please let me know how to resolve this.

thanks!

**Comment by suchiek** [comment]
[Sample_records.xlsx](https://github.com/fizyr/keras-retinanet/files/1958765/Sample_records.xlsx)

Hi, 

Thank you for your response. I am attaching a snippet from the file that contains the record that was causing the problem. It is the same set of values that I pasted in my original message. The entire file has over 18,000 records and I did not want to post it.

I tried deleting that record and running train.py without it and then I got the same message about the previous record.

**Comment by de-vri-es** [comment]
Could you share a csv file instead of an xlsx? Also, does that snippet cause the same problem? If not we can't really use it to debug.

**Comment by suchiek** [comment]
Hi,

I did try and upload a csv file and got a message: " we don't support that file type. Try again with a GIF, JPEG....,  TXT, XLSX file. 

The records in the attached file are where I am getting problems.

Please let me know if a tab delimited TXT file would work?

thanks!

**Comment by de-vri-es** [comment]
How about a comma delimited TXT file? ;)

**Comment by suchiek** [comment]
[Annotations_error_message.txt](https://github.com/fizyr/keras-retinanet/files/1958989/Annotations_error_message.txt)

Hi, 

I am attaching a comma separated txt file and I used this exact file for training and got the following error message:

**Traceback (most recent call last):
  File "keras_retinanet/bin/train.py", line 440, in <module>
    main()
  File "keras_retinanet/bin/train.py", line 385, in main
    train_generator, validation_generator = create_generators(args)
  File "keras_retinanet/bin/train.py", line 224, in create_generators
    image_max_side=args.image_max_side
  File "keras_retinanet/bin/../../keras_retinanet/preprocessing/csv_generator.py", line 138, in __init__
    raise_from(ValueError('invalid CSV annotations file: {}: {}'.format(csv_data_file, e)), None)
  File "<string>", line 3, in raise_from
ValueError: invalid CSV annotations file: /home/mdsskv/keras-retinanet/Annotations_error_message.csv: line 13: x2 (51) must be higher than x1 (51)**

thanks!

**Comment by de-vri-es** [comment]
It seems like there is a off-by-one in the line number, but the annotation on line 14 is invalid. x1 and x2 are both 51.

**Comment by suchiek** [comment]
Thanks so much. Feel really silly about not catching that one.
