### ISSUE TITLE
Get error when running testing

### ISSUE THREAD

**Issue by hoangminhtoan** [fizyr/keras-retinanet#438]
I used to use the older version of retinanet and there was no problem. But after I updated the latest version of retinanet I can not run the test file although there was no problem during training.

![screenshot from 2018-04-29 22-56-06](https://user-images.githubusercontent.com/1559257/39407487-d06b4b1e-4c01-11e8-9668-bb8972cda7ab.png)

**Comment by hgaiser** [comment]
I think you're trying to run inference on a train model:

https://github.com/fizyr/keras-retinanet/blob/master/README.md#converting-a-training-model-to-inference-model
