### ISSUE TITLE
Regarding the lesser annotations, more object detection and its effect on mAP 

### ISSUE THREAD

**Issue by rgsl888** [fizyr/keras-retinanet#446]
I had question regarding the evaluation,

For an example, as per annotation we should get 5 objects detected, but the model was able to detect more objects and all of them are correctly tagged. Will this additional detection reduce the mAP as the evaluation might consider them as false positive as there is no annotation for those ?

**Comment by hgaiser** [comment]
Yeah, it could (depends on the scores).

If we take a small example of 2 objects in one image, one of them is annotated the other isn't. If the non-annotated object has a higher score than the annotated object, the evaluation code will see this as a mistake. The best (highest scoring) detection would be wrong and the second highest scoring object would be correct. I believe this will yield an mAP score of 0.5 then. If it happens to be the other way around, the annotated object gets a higher detection score, then the mAP is 1.0. mAP doesn't penalize for detecting too much, only for detecting things in the wrong order.

Please ask questions like this on the Slack channel, as they don't affect the code in this repository..

**Comment by rgsl888** [comment]
Thank you for the information

**Comment by rgsl888** [comment]
Is there any way that we can eliminate/ discard that non-annotated detection ? 

What the link for slack?
