### ISSUE TITLE
No module named keras_resnet

### ISSUE THREAD

**Issue by XRDai** [fizyr/keras-retinanet#455]
Hello,
When it runs at resnet.py.:
ImportError: No module named keras_resnet

Thanks in advance for the help !

**Comment by hgaiser** [comment]
https://github.com/fizyr/keras-retinanet#installation

**Comment by XRDai** [comment]
Ok,Thanks

**Comment by jashshopin** [comment]
I'm trying to run this from the notebook titled `ResNet50RetinaNet` and I still run into this error: `ImportError: No module named 'keras_resnet'`.

Note: I have run the first two steps in the installation mentioned here: https://github.com/fizyr/keras-retinanet#installation
