### ISSUE TITLE
model.predict_on_batch gives ValueError: too many values to unpack (expected 3) 

### ISSUE THREAD

**Issue by ravikrn** [fizyr/keras-retinanet#456]
Below is my code
     
       ```
       model_path = os.path.join('snapshots/resnet50_csv_05.h5')
       model = keras.models.load_model(model_path, custom_objects=custom_objects)
       image = read_image_bgr(img_path)
       image = preprocess_image(image)
       image, scale = resize_image(image)

       boxes, scores, labels = model.predict_on_batch(np.expand_dims(image, axis=0))
```

Apparently model.predict_on_batch has 4 outputs But [https://github.com/fizyr/keras-retinanet/blob/master/examples/ResNet50RetinaNet.ipynb](sample example) has just 3 outputs

**Comment by hgaiser** [comment]
I think you'll need to retrain your model with an updated version of this repository. The number (and meaning) of the outputs has changed not so long ago.

**Comment by hgaiser** [comment]
I'm assuming this fixes your issue, if not, feel free to re-open.
