### ISSUE TITLE
Parameter settings to train on large resolution image with small objects 

### ISSUE THREAD

**Issue by JudyMRSD** [fizyr/keras-retinanet#457]
Hello, thank you for making this awesome github repo! may I ask if the current version can train/inference using large input images with small objects? I have 3840x2160 sized images, each image have around 20 objects of size 40x100. There is only one class in the dataset. Is there other things need to be changed besides change the input size in the following code? https://github.com/fizyr/keras-retinanet/blob/afad72216a5d68c01ac9e6e487120656ce589950/keras_retinanet/bin/train.py#L232                             One of the github issues page also said that `the anchors that are being generated, currently optimized for COCO dataset, fit your dataset. If your objects are too small or too big, they will not be detected. The images are rescaled (by default) such that the smallest side equals 600px. If the largest side is then still larger than 1024 pixels, it is scaled down further such that the largest side is equal to 1024 pixels. ` Does this mean I need to change the parameters for anchor boxes?   Thanks a lot for helping!

**Comment by hgaiser** [comment]
In general, large images and small objects don't go well together. I'm not sure about your time constraints, but IMO your best bet is to use large images. Perhaps 40x100 is already enough, but by default (as you mentioned), images are resized prior to inference to avoid the network requiring too much memory. You could try cutting up your images in smaller parts (perhaps with a bit of overlap between them) and perform the object detection on each image separately.

Your other option is to modify the anchor shapes for smaller objects, but this is not natively supported in keras-retinanet (it is a to-do). For more info on this, check [here](https://github.com/fizyr/keras-retinanet#faq).
