### ISSUE TITLE
IOError: [Errno 2] No such file or directory: 'VOCdevkit/VOC2012/ImageSets/Main/train.txt

### ISSUE THREAD

**Issue by swloo618** [fizyr/keras-retinanet#459]
I try to run the script python build/darknet/x64/data/voc/voc_label.py in GitBash.  But i get the error as below
 image_ids = open('VOCdevkit/VOC%s/ImageSets/Main/%s.txt'%(year, image_set)).read().strip().split()
IOError: [Errno 2] No such file or directory: 'VOCdevkit/VOC2012/ImageSets/Main/train.txt'

I check the train.txt and it is appear in the mentioned folder.  May I know what the problem?  Please guide me.
Thanks

**Comment by RuiRickyZhang** [comment]
Have you ever tried to use VOC2007 instead? I used VOC2007 and this problem seems not exist. As the readme profile mentioned VOc 2007 so I think there would be risks in using VOC2012.

**Comment by RuiRickyZhang** [comment]
Hi, I used to try on VOC 2007 and there's no problem on it. But today I tried VOC2012 and found the same problem like yours. But I found that I forgot to install  VOC2012 test dataset. Then I installed it.

`wget http://pjreddie.com/media/files/VOC2012test.tar`
`tar tar -xvf VOC2012test.tar`

Afterwards there would be no problem for me. Wish this would help :)

**Comment by hgaiser** [comment]
darknet? I think you're on the wrong repository ;)

**Comment by freedom9393** [comment]
Probably your forgot to unzip files and trying to run your code without unzipping? :)
Make sure you run:
```
tar -xvf VOCtrainval_11-May-2012.tar
tar -xvf VOCtrainval_06-Nov-2007.tar
tar -xvf VOCtest_06-Nov-2007.tar
```
Then run voc_label.py

**Comment by martianvenusian** [comment]
I have the same issue. `VOCtest_06-Nov-2007.tar` hadn't been extracted even though i did exactly same as tutorials taught. So i did extract it by manually and got `test.txt` file in **VOCdevkit/VOC2007/ImageSets/Main/**.

Just review your things.
