### ISSUE TITLE
Transposed convolution instead of bilinear upsampling

### ISSUE THREAD

**Issue by msokoloff1** [fizyr/keras-retinanet#46]
I'm wondering if using transposed convolution instead of bilinear up-sampling for the feature pyramid would be advantageous. Any thoughts?

**Comment by hgaiser** [comment]
Actually it used to be Deconv but then I changed it to upsampling. The disadvantage of Deconv is that it can only upsample in factors of 2. If an image is shaped 5x5, it's downsampled version is 2x2. With Deconv this would be upsampled to 4x4 whereas with upsampling it can be upsampled back to 5x5.

In addition [this](https://distill.pub/2016/deconv-checkerboard/) blogpost claims it is better to do upsampling followed by a convolution.

**Comment by hgaiser** [comment]
Does this answer your question?

**Comment by msokoloff1** [comment]
Yes, thank you for the response.
