### ISSUE TITLE
I change anchors sizes,error happend

### ISSUE THREAD

**Issue by zhangtao22** [fizyr/keras-retinanet#462]
in train.py file, I change anchors_for_shape like this: 
    if sizes is None:
        # sizes = [2 ** (x + 2) for x in pyramid_levels]
        sizes = [2 ** x for x in pyramid_levels]
    if ratios is None:
        ratios = np.array([1])

in retinanet.py file，I change
AnchorParameters.default = AnchorParameters(
    sizes   = [8,16,32, 64, 128],
    strides = [8, 16, 32, 64, 128],
    ratios  = np.array([1], keras.backend.floatx()),
    scales  = np.array([2 ** 0, 2 ** (1.0 / 3.0), 2 ** (2.0 / 3.0)], keras.backend.floatx()),
    # scales  = np.array([2 , 3, 5, 7], keras.backend.floatx()),
)
after 1 epoch，it print these errors
File "keras_retinanet/bin/../../keras_retinanet/callbacks/eval.py", line 52, in on_epoch_end
10587     save_path=self.save_path
10588   File "keras_retinanet/bin/../../keras_retinanet/utils/eval.py", line 163, in evaluate
10589     all_detections     = _get_detections(generator, model, score_threshold=score_threshold, max_detections=max_detections, save_path=save_path)
10590   File "keras_retinanet/bin/../../keras_retinanet/utils/eval.py", line 81, in _get_detections
10591     boxes, scores, labels = model.predict_on_batch(np.expand_dims(image, axis=0))
10592   File "/home/zhangtao/.local/lib/python2.7/site-packages/keras/engine/training.py", line 1945, in predict_on_batch
10593     outputs = self.predict_function(ins)
10594   File "/home/zhangtao/.local/lib/python2.7/site-packages/keras/backend/tensorflow_backend.py", line 2482, in __call__
10595     **self.session_kwargs)
10596   File "/home/zhangtao/.local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 895, in run
10597     run_metadata_ptr)
10598   File "/home/zhangtao/.local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1124, in _run
10599     feed_dict_tensor, options, run_metadata)
10600   File "/home/zhangtao/.local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1321, in _do_run
10601     options, run_metadata)
10602   File "/home/zhangtao/.local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1340, in _do_call
10603     raise type(e)(node_def, op, message)
10604 tensorflow.python.framework.errors_impl.InvalidArgumentError: Incompatible shapes: [1,181503] vs. [1,60501]
10605          [[Node: boxes/mul_6 = Mul[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/gpu:0"](boxes/add_2, boxes/sub)]]
10606          [[Node: filtered_detections/map/TensorArrayStack/TensorArrayGatherV3/_3683 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/cpu:      0", send_device="/job:localhost/replica:0/task:0/gpu:0", send_device_incarnation=1, tensor_name="edge_3365_filtered_detections/map/TensorArrayStack/TensorArrayGatherV      3", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"]()]]
10607
10608 Caused by op u'boxes/mul_6', defined at:
10609   File "keras_retinanet/bin/train.py", line 454, in <module>
10610     main()
10611   File "keras_retinanet/bin/train.py", line 422, in main
10612     freeze_backbone=args.freeze_backbone
10613   File "keras_retinanet/bin/train.py", line 90, in create_models
10614     prediction_model = retinanet_bbox(model=model)
10615   File "keras_retinanet/bin/../../keras_retinanet/models/retinanet.py", line 352, in retinanet_bbox
10616     boxes = layers.RegressBoxes(name='boxes')([anchors, regression])
10617   File "/home/zhangtao/.local/lib/python2.7/site-packages/keras/engine/topology.py", line 619, in __call__
10618     output = self.call(inputs, **kwargs)
10619   File "keras_retinanet/bin/../../keras_retinanet/layers/_misc.py", line 111, in call
10620     return backend.bbox_transform_inv(anchors, regression, mean=self.mean, std=self.std)
10621   File "keras_retinanet/bin/../../keras_retinanet/backend/common.py", line 39, in bbox_transform_inv
10622     pred_ctr_x = ctr_x + dx * widths
10623   File "/home/zhangtao/.local/lib/python2.7/site-packages/tensorflow/python/ops/math_ops.py", line 865, in binary_op_wrapper
10624     return func(x, y, name=name)
10625   File "/home/zhangtao/.local/lib/python2.7/site-packages/tensorflow/python/ops/math_ops.py", line 1088, in _mul_dispatch
10626     return gen_math_ops._mul(x, y, name=name)
10627   File "/home/zhangtao/.local/lib/python2.7/site-packages/tensorflow/python/ops/gen_math_ops.py", line 1449, in _mul
10628     result = _op_def_lib.apply_op("Mul", x=x, y=y, name=name)
10629   File "/home/zhangtao/.local/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 767, in apply_op
10630     op_def=op_def)
10631   File "/home/zhangtao/.local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2630, in create_op
10632     original_op=self._default_original_op, op_def=op_def)
10633   File "/home/zhangtao/.local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1204, in __init__
10634     self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access
10635
10636 InvalidArgumentError (see above for traceback): Incompatible shapes: [1,181503] vs. [1,60501]
10637          [[Node: boxes/mul_6 = Mul[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/gpu:0"](boxes/add_2, boxes/sub)]]
10638          [[Node: filtered_detections/map/TensorArrayStack/TensorArrayGatherV3/_3683 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/cpu:      0", send_device="/job:localhost/replica:0/task:0/gpu:0", send_device_incarnation=1, tensor_name="edge_3365_filtered_detections/map/TensorArrayStack/TensorArrayGatherV      3", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"]()]]

**Comment by hgaiser** [comment]
Changing anchors is not (yet) a supported feature of keras-retinanet. Other than the [faq](https://github.com/fizyr/keras-retinanet#faq) I can't help you much. Closing this since it is covered by https://github.com/fizyr/keras-retinanet/issues/324 .
