### ISSUE TITLE
Adding arbitrary head structure support

### ISSUE THREAD

**Issue by Ori226** [fizyr/keras-retinanet#469]
I see the need to play with the "head" of the model: changing the number of pyramid and their configuration. I have created theses changes in my private repository and I wonder whether this repository is the right place to put them in for two reasons:
1. Make this changes configurable may be quite complicated
2. This is a RetinaNet repository. Making this changes will turn the code into a general single shot detector.

Any thoughts?

**Comment by yhenon** [comment]
It sounds like a private repo is the right place for your experiments with the network head. If you want to submit a PR down the line with your changes you could certainly do that.
