### ISSUE TITLE
Coordinate beyound limit

### ISSUE THREAD

**Issue by Jerry3062** [fizyr/keras-retinanet#470]
Hi!
     My dataset annotation is formated  as x,y,w,h, and i calculate it to x1,y1,x2,y2. But some object is on the edge of the map,then the x1,y1,x2,y2 coordinate maybe out of the edge,like -50,100,200,300. Should i change it to 0,100,200,300,or other.

**Comment by hgaiser** [comment]
But that should be regardless of the box encoding right? Either methods
would place your box beyond the image bounds. Yeah it's better to clip it
to the image bounds I would say.
