### ISSUE TITLE
Standalone model?

### ISSUE THREAD

**Issue by aqader** [fizyr/keras-retinanet#477]
Is there a way to turn a keras-retinanet inference model into a standalone model that works with the PyPi version of Keras? The load_model() function (for example) has the backbone_name argument which isn't native to Keras.

**Comment by hgaiser** [comment]
You can use the load_model from keras-retinanet?

**Comment by aqader** [comment]
I guess I mean is there a way to remove the keras_retinanet library dependency?

________________________________

**Comment by hgaiser** [comment]
Keras is going to need the layer definitions to load the model, so no. You
could minimise the dependency by making a module containing only the layers.

**Comment by aqader** [comment]
Got it, thanks!
