### ISSUE TITLE
Score threshold in draw_detections

### ISSUE THREAD

**Issue by pedroconceicao** [fizyr/keras-retinanet#480]
Hi all!

In evaluate.py the score_threshold is, by default, 0.05. You use that value everywhere except in draw_detections() where it is 0.5 by default.

In [line 87](https://github.com/fizyr/keras-retinanet/blob/448f01fead22be40a2f4040192b236d0e50a1bf5/keras_retinanet/utils/eval.py#L87) of eval.py you choose only the "indices which have a score above the threshold" which is 0.05. However, when you call draw_detections() you don't pass this argument. 

Since the default threshold_score in draw_detections() is 0.5 it will only draw boxes with a score higher than that because it again compares (in [line 74](https://github.com/fizyr/keras-retinanet/blob/448f01fead22be40a2f4040192b236d0e50a1bf5/keras_retinanet/utils/visualization.py#L74) of visualization.py ) the detections with this new threshold score. 

Why don't you use always the same value? And why do you compare the score two times?

**Comment by hgaiser** [comment]
Drawing detections with a threshold of 0.05 would be really hard to inspect. There are many boxes that are above that threshold. The reason for the 0.05 is because that is what appears to be used by other systems as well, such as faster rcnn and Detectron.

**Comment by yhenon** [comment]
>The reason for the 0.05 is because that is what appears to be used by other systems as well, such as faster rcnn and Detectron
I'll add that when computing metrics such as mAP, you want to include lower confidence detections, since doing so gives you a fuller picture of your system's trade-offs between precision and recall.
