### ISSUE TITLE
How to get output_node_names  (question)

### ISSUE THREAD

**Issue by Programmerwyl** [fizyr/keras-retinanet#482]
I want to convert .h5 files to tensoflow pb files.
The code are  listed as follow:

output_node_names= ''
models_dir = 'F:/project/RetinaNet/keras-retinanet-master/train_data/'
model_filename = 'retinanet.pb'
path = 'F:/project/RetinaNet/keras-retinanetmaster/keras_retinanet/bin/snapshots/resnet50_None_01.h5'
model = models.load_model(path,backbone_name='resnet50')
K.set_learning_phase(0)
sess = K.get_session()
saver = saver_lib.Saver(write_version=saver_pb2.SaverDef.V2)
checkpoint_path = saver.save(sess, 'F:/project/RetinaNet/keras-retinanet-master/train_data/saved_ckpt', global_step=0, latest_filename='checkpoint_state')
graph_io.write_graph(sess.graph, '.', 'tmp1.pb')
print('ok')
freeze_graph.freeze_graph('./tmp.pb', '',
                        False, checkpoint_path, output_node_names,
                        "save/restore_all", "save/Const:0",
                        models_dir+model_filename, False, "")

How can I get output_node_names ?
If anyone have any ideas ,please tell me .
Thanks

**Comment by nguyeho7** [comment]
You can simply do model.outputs which is a list of outputs. Use their names in the tensorflow graph afterwards

**Comment by Programmerwyl** [comment]
Ok,thanks for your advices.
I have tried it,but it does not work.

**Comment by Programmerwyl** [comment]
Firstly I use convert_model.py  to convert 'RetinaNet/keras-retinanetmaster/keras_retinanet/bin/snapshots/resnet50_None_01.h5'  to 'model_first.h5'

Secondly ,model = models.load_model('model_first.h5',backbone_name='resnet50')
for i in range(len(model.outputs)):
    print（model.outputs[i].name)

what I get output_node_names  are out_names = ['filtered_detections/map/TensorArrayStack/TensorArrayGatherV3:0','filtered_detections/map/TensorArrayStack_1/TensorArrayGatherV3:0','filtered_detections/map/TensorArrayStack_2/TensorArrayGatherV3:0']

Finally I get the error ' filtered_detections/map/TensorArrayStack/TensorArrayGatherV3:0 is not in graph'



![code](https://user-images.githubusercontent.com/22095854/40965788-49a0b7d4-68e1-11e8-9cdd-df1736376945.png)
![error](https://user-images.githubusercontent.com/22095854/40965792-4e51fef0-68e1-11e8-8ce7-24564c8a963e.png)
![out_node](https://user-images.githubusercontent.com/22095854/40965801-548e81b2-68e1-11e8-8d37-ca81c6b9ba32.png)

**Comment by Programmerwyl** [comment]
Ok I  have solved this question.
The codes are listed as follows:
out_node_name = []
for i in range(len(net_model.outputs)):
    output_name = net_model.outputs[i].name.split(':')[0]
    tf.identity(net_model.outputs[i],output_name)
    out_node_name.append(output_name)
print(out_node_name)
The key is that we need to run 'tf.identity'
Thanks

**Comment by hgaiser** [comment]
Alright I'll close this issue then.

**Comment by XdpAreKid** [comment]
@Programmerwyl Hello, can i get your all code to convert the h5 file to pb file, i run my code it said TypeError:('Keyword argument not understood:','freeze')
