### ISSUE TITLE
output rotated bounding box 

### ISSUE THREAD

**Issue by JudyMRSD** [fizyr/keras-retinanet#484]
Would that be possible to make the network output rotated bounding box instead of the current format of vertical/horizontal bounding box? For example, if there is a a ship with center axis 45 degrees to horizontal, would that be possible to make some changes to the network to output a rotated bounding box? Is this just change the label format or need some complicated changes somewhere in the model architecture? Thanks a lot!

**Comment by hgaiser** [comment]
It's possible, but you'd need some rigorous changes to the architecture. You'd first of all need the data labeled with rotation included, then make or change the generator to generate boxes with 5 values and change the architecture accordingly. It won't be trivial to generate anchor boxes which include rotation I'd guess, but it should be possible.

Alternatively, it might be wiser to look at https://github.com/fizyr/keras-maskrcnn for segmentation. Using the segmentation output you can also compute a rotated box.
