### ISSUE TITLE
Trained model produces diffetent tesults on diffent envs

### ISSUE THREAD

**Issue by snarb** [fizyr/keras-retinanet#491]
Hi! I am observing very strange isue . On my env trained model works good. I have zipped repository with code, training code, saved model and validation images on other env(laptop windows 10 without gpu). And the same model produces terrible results. Maybe because of CPU onstead of GPU? Do I need to convert model or something like this? How to fix this?  Thanks!

**Comment by mgwizdala** [comment]
Are you sure you are using same version of retinanet in both enviroments ? Also please check if your tensorflow, keras and h5py version are matching.

**Comment by snarb** [comment]
The issue was in different installed versions of retinanet. Bad that there is no any version checking if it is so sensitive

**Comment by de-vri-es** [comment]
@snarb: If you're aware of a good method to store version information in snapshots created by keras, please let us know.
