### ISSUE TITLE
How to use tensorRT to improve the speed of inference

### ISSUE THREAD

**Issue by Programmerwyl** [fizyr/keras-retinanet#492]
If anyone have tried it or have any ideas ,please tell me .
Thanks

**Comment by hgaiser** [comment]
This is a good question to ask on the slack channel. In fact, I think it has been asked before and the answer was that it was possible, but that you'd have to write some Cuda kernels since not every layer we use is covered in TensorRT.

**Comment by CHONGCHUANSHENG** [comment]
how can i use tensorrt  to achieve speeding up the inference?
