### ISSUE TITLE
AttributeError: 'module' object has no attribute 'imagenet_utils'

### ISSUE THREAD

**Issue by Lakshya-Kejriwal** [fizyr/keras-retinanet#494]
Hi,

I am training using csv files on a custom dataset and when I start training I am getting the following error:

`Traceback (most recent call last):`
 `File "keras_retinanet/bin/train.py", line 442, in <module>`
 `   main()`
`  File "keras_retinanet/bin/train.py", line 401, in main`
`    weights = backbone.download_imagenet()`
`  File "keras_retinanet/bin/../../keras_retinanet/models/resnet.py", line 50, in download_imagenet`
`    return keras.applications.imagenet_utils.get_file(`
`AttributeError: 'module' object has no attribute 'imagenet_utils'`

**Comment by hgaiser** [comment]
Hmm what Keras version are you using? Can you check if your Keras contains
this file:
https://github.com/keras-team/keras/blob/master/keras/applications/imagenet_utils.py

**Comment by Lakshya-Kejriwal** [comment]
My keras version is 2.2.0

**Comment by Lakshya-Kejriwal** [comment]
It had that file. I solved it by first importing the module `imagenet_utils` in `resnet.py`. No idea why it behaved in such a way

**Comment by foofybuster** [comment]
Have you ever seen "IndexError: list index out of range" problem after solved your problem?
