### ISSUE TITLE
retinanet() got an unexpected keyword argument 'weights'

### ISSUE THREAD

**Issue by magda1428** [fizyr/keras-retinanet#502]
Hi, 

thank your work. I have been using this solution since January. 

I used transfer learning approach to train a model using:

```
#Create empty model with your number of classes
num_classes = 15
image = keras.layers.Input((None, None, 3))
model = resnet50_retinanet(num_classes, weights='imagenet', nms=True)

#Load weights, skipping incompatible sections
model.load_weights('resnet50_coco_best_v1.2.2.h5', skip_mismatch=True, by_name=True)

```
Unfortunately, after your updates, while running the command resnet50_retinanet, I came across following issue:

retinanet() got an unexpected keyword argument 'weights'

I've tried to install keras-resnet cloning some github repositories (which I found among issues here) as well as by using pip install keras-resnet command, but with no success.
After that I attemted to use the method resnet50_retinanet without _weights_ and _nms_ parameters. It created model but I can not compile it because of
```
model.compile(
        loss={
            'regression'    : losses.smooth_l1(),
            'classification': losses.focal()
            
        },
        optimizer=keras.optimizers.adam(lr=1e-4, clipnorm=0.001),
    metrics = ['accuracy']
    ) 
```
which gives me error:
ValueError: Unknown entry in loss dictionary: "_smooth_l1". Only expected the following keys: ['filtered_detections', 'filtered_detections', 'filtered_detections'] 

I am using _Keras 2.1.5_
Right now I have also following versions of packages:
_keras-resnet==0.0.8
keras-retinanet==0.3.1_

**Comment by hgaiser** [comment]
The weights argument has indeed been removed and you should now load weights separately using `model.load_weights`. In theory, this should work:

```python
from keras_retinanet.models.resnet import ResNetBackbone
model = ResNetBackbone('resnet50').retinanet(num_classes)
model.load_weights(weights_path, by_name=True, skip_mismatch=True)
```

**Comment by magda1428** [comment]
Thanks a lot. The solution you sent is working.
