### ISSUE TITLE
Strange problems with argument parsing

### ISSUE THREAD

**Issue by netw0rkf10w** [fizyr/keras-retinanet#505]
Hello,

I have realized something very strange in the argument parsing. I executed the following command:

`keras_retinanet/bin/train.py --backbone resnet101 --snapshot-path ./snapshots/tiny csv train_tiny.csv names_tiny.csv --val-annotations val_tiny.csv`

then I tried printing out the arguments by inserting a print command in the `main()` function of `keras_retinanet/bin/train.py`:

```
    args = parse_args(args)
    print(args)
```
The obtained results:

> Namespace(annotations='train_tiny.csv', backbone='resnet101', batch_size=1, classes='names_tiny.csv', dataset_type='csv', epochs=50, evaluation=True, freeze_backbone=False, gpu=None, image_max_side=1333, image_min_side=800, imagenet_weights=True, multi_gpu=0, multi_gpu_force=False, random_transform=False, snapshot=None, snapshot_path='./snapshots/tiny', snapshots=True, steps=10000, tensorboard_dir='./logs', val_annotations='val_tiny.csv', weights=None)

The problem lies in the following values:

```
freeze_backbone=False,
random_transform=False,
```

In the code their default values are True for both:

```
parser.add_argument('--freeze-backbone', help='Freeze training of backbone layers.', action='store_true')
parser.add_argument('--random-transform', help='Randomly transform image and annotations.', action='store_true')
```

So maybe there is a bug?

**Comment by de-vri-es** [comment]
The default for these values is actually `False`. `store_true` means that if the argument is found in the command line, the associated value will be set to true.

See also: https://docs.python.org/3/library/argparse.html#action

I'm assuming this resolved your issue. Feel free to comment if not.

**Comment by netw0rkf10w** [comment]
@de-vri-es My bad! Thanks a lot!
