### ISSUE TITLE
What is the AnchorParameters configuration if the min_input_size=x and max_input_size=y?

### ISSUE THREAD

**Issue by YJHMITWEB** [fizyr/keras-retinanet#506]
Is there a function to automatically set AnchorsParameters according to the max and min input size?
For example, in your repo, the min and max input size are 800 and 1333, and your anchors parameters are
`sizes=[32, 64, 128, 256, 512],
strides=[8, 16, 32, 64, 128],
ratios  = np.array([0.5, 1, 2], keras.backend.floatx()),
scales  = np.array([2 ** 0, 2 ** (1.0 / 3.0), 2 ** (2.0 / 3.0)], keras.backend.floatx()),`.
What if the min and max input size are 400 and 512, how to set the anchors parameters?
Thank you!!

**Comment by Programmerwyl** [comment]
@hgaiser  @YJHMITWEB  Is it necessary to set the anchors parameters？how to set it 
Thanks
