### ISSUE TITLE
Few questions about the --save-path parameter in evaluate.py

### ISSUE THREAD

**Issue by nehalmamgain** [fizyr/keras-retinanet#507]
Hi,

Thank you for this marvelous implementation of RetinaNet.

Could you please answer the following two questions?
1) What bounding boxes does the save-path parameter in evaluate.py save (the ground truth or the predictions or both)?
2) If the answer is "both" to above, are green-colored boxes the ground truth and other-colored boxes (blue, orange, purple, magenta etc) the predictions? If not, could you please tell what the different colors of the bounding boxes signify?

**Comment by hgaiser** [comment]
> What bounding boxes does the save-path parameter in evaluate.py save (the ground truth or the predictions or both)?

Both.

> If the answer is "both" to above, are green-colored boxes the ground truth and other-colored boxes (blue, orange, purple, magenta etc) the predictions? If not, could you please tell what the different colors of the bounding boxes signify?

Your assumption is correct. Maybe not as intuitive now as how it used to be (detections were always drawn in blue). If you have a suggestion to make it more intuitive, I'm all ears.
