### ISSUE TITLE
the difference training on windows and linux 

### ISSUE THREAD

**Issue by mooncakehe** [fizyr/keras-retinanet#516]
when i train on windows. The model can converge.
But i use the same parameters trianed on linux. the model can not converge.
is there some erros?
any suggestion?
my dataset is 5000 pictures, classify area has cars.  # self.classes = {'car': 0}
lr = 1e-5 the same as primeval code.
windows has 6G GPU. linux has 16G GPU

**Comment by mooncakehe** [comment]
my keras is 2.2.0. 
thx!

**Comment by hgaiser** [comment]
keras-retinanet doesn't (yet) work on keras 2.2.0. I have never trained on windows before, so I cannot say anything about that, but on linux it is working for me. Are you sure you didn't make some changes on linux that you don't have on windows? Other versions of software?

**Comment by mooncakehe** [comment]
I solve the problem when i change the keras version to 2.1.3.
It may be the version mismatch between keras and tensorflow.
I downgrade the version of keras and the problem soloved!
thx!
