### ISSUE TITLE
TypeError: softmax() got an unexpected keyword argument 'axis'

### ISSUE THREAD

**Issue by madingx** [fizyr/keras-retinanet#525]
Hello,I am honored to be able to use your code of RetinaNet, but I have got an error when I try to train it. Do you know why it happens?How can I fix it?Looking forward to your reply.

  File "keras_retinanet/bin/train.py", line 485, in <module>
    main()
  File "keras_retinanet/bin/train.py", line 437, in main
    model            = models.load_model(args.snapshot, backbone_name=args.backb
one)
  File "keras_retinanet/bin\..\..\keras_retinanet\models\__init__.py", line 76,
in load_model
    model = keras.models.load_model(filepath, custom_objects=backbone(backbone_n
ame).custom_objects)
  ...
  File "C:\Program Files\Anaconda3\lib\site-packages\keras\activations.py", line
 29, in softmax
    return K.softmax(x)
  File "C:\Program Files\Anaconda3\lib\site-packages\keras\backend\tensorflow_ba
ckend.py", line 2963, in softmax
    return tf.nn.softmax(x, axis=axis)
TypeError: softmax() got an unexpected keyword argument 'axis'

**Comment by hgaiser** [comment]
What version of tensorflow and Keras are you using? I would guess tensorflow is out of date.

**Comment by yhenon** [comment]
This is a Keras issue encountered by many users, see here: https://github.com/keras-team/keras/issues/9621

You may need to change your keras/tensorflow version.

**Comment by LiuWenzhang** [comment]
Modify the code in this way: tf.nn.softmax(x, **axis**=axis) -> tf.nn.softmax(x, **dim**=axis)

**Comment by itsnageshv** [comment]
I got the same problem. Gave the following command and installed keras tensorflow. It worked for me

pip install -U keras tensorflow

**Comment by RAMIREDDYDEVARAM** [comment]
just do it.

pip install --upgrade tensorflow      # for Python 2.7

pip3 install --upgrade tensorflow     # for Python 3.n
