### ISSUE TITLE
not enough values to unpack (expected 3, got 2)

### ISSUE THREAD

**Issue by yelanyelan** [fizyr/keras-retinanet#531]
I used KITTI data to train retinanet with default backbone_name='resnet50'.
train.py kitti /path/to/kitti
And after I completed and load it to test:

model_path = os.path.join('snapshots', 'resnet50_coco_best_v2.1.0.h5')
model = models.load_model(model_path, backbone_name='resnet50')
and:
boxes, scores, labels = model.predict_on_batch(np.expand_dims(image, axis=0))

Then I got problem:
ValueError: not enough values to unpack (expected 3, got 2)

But I would not get this problem when I load the pretrain mode from
https://github.com/fizyr/keras-retinanet/releases
Is there any different between MS COCO and KITTI that I used to train?

**Comment by hgaiser** [comment]
Check the faq:

https://github.com/fizyr/keras-retinanet/blob/master/README.md#faq

**Comment by yelanyelan** [comment]
thank u a lot
