### ISSUE TITLE
Inference speed improvement

### ISSUE THREAD

**Issue by hxlee309** [fizyr/keras-retinanet#532]
Is there any way to improve the inference speed without affecting the accuracy too much by modifying the code? Since we plan to use this model for real-time prediction in driving, so the speed requirement is very important. Any help will be appreciated.

**Comment by hgaiser** [comment]
It's better to have these discussions on the Slack channel (see the README). To shortly answer your question, the easiest solution is to reduce the resolution of the images. There are other options (examining which parts of the network are not doing much or anything at all, and pruning them), but they require more investigation and work.
