### ISSUE TITLE
Coding style that prohibits auto-formatting

### ISSUE THREAD

**Issue by apacha** [fizyr/keras-retinanet#533]
This issue is not related to the implementation, but rather to the style of your source-code. Have you ever questioned your coding style? It currently looks like this:

```
    def load_annotations(self, image_index):
        """ Load annotations for an image_index.
        """
        path   = self.image_names[image_index]
        annots = self.image_data[path]
        boxes  = np.zeros((len(annots), 5))

        ....
```

which might look ok, but has a big issue: It assumes that you are manually correcting all indentations in the entire file and that you do not use any tools to automatically fix indentation (e.g. PyCharm). Any decent IDE would automatically transform this code into the following:

```
    def load_annotations(self, image_index):
        """ Load annotations for an image_index.
        """
        path = self.image_names[image_index]
        annots = self.image_data[path]
        boxes = np.zeros((len(annots), 5))

        ....
```

Now there are two things that I would like to point out with the current style:

- It forbids the use of automatic code formatting, because that would "destroy" your manual indentations - and create a lot of undesired edits, when just changing a few lines.
- Adding another variable (that has a longer name) without breaking the style can only be done if you _manually_ change the indentations for all other variables.

I've seen this several times in the code base and I keep on getting merge conflicts, because of different indentations in my fork (I'm using auto-formatting for all files, that I work in). I would suggest, that we auto-format all files once, and from then follow the [standard Python indentation guidelines](https://www.python.org/dev/peps/pep-0008/?#pet-peeves).

**Comment by de-vri-es** [comment]
We prefer the code to be easy to read over having tools that can automatically format code. Also, what is a decent IDE is very subjective. I would say that any decent text editor can align code on assignments or similar marks.

So, thank you for your concern, but we won't be changing this.

**Comment by apacha** [comment]
You just blatantly ignored every single argument that I made. You can use whatever IDE you want, but ignoring the Python guidelines is just ignorant - they've been written with very good reasons.

And why should code be any more "readable", just because it is indented upon the equal sign? Please reconsider this issue, before you prematurely close it.

**Comment by de-vri-es** [comment]
Yes, in the end this is our repository and we can enforce the code style we want. I'm sorry if you disagree with that style, but different people prefer different styles.

**Comment by apacha** [comment]
Sure you can. But does it make sense? You're not actually enforcing this code style (see https://github.com/fizyr/keras-retinanet/blob/master/keras_retinanet/callbacks/eval.py#L72) for just one of many "violations". I simply don't understand why anyone would actively stand against cleaning up the code automatically. It just makes developers lifes harder...

![2018-06-27 15_02_17-keras-retinanet c__users_alex_repositories_keras-retinanet - _keras_retinan](https://user-images.githubusercontent.com/594497/41975519-3b0c5f0c-7a1b-11e8-9d4a-6f41aabe3151.png)

**Comment by de-vri-es** [comment]
That is your opinion, we have a different opinion. Please respect our choice on code style and lets this issue drop.
