### ISSUE TITLE
NoOutput of images and code stoped at evaluation step.

### ISSUE THREAD

**Issue by DongxiaW** [fizyr/keras-retinanet#535]
Hi fizyr,
I am running the model and it stops at this line

`boxes, scores, labels = model.predict_on_batch(np.expand_dims(image, axis=0)) `

Here is the error information,

```
2018-06-27 18:23:09.491536: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
2018-06-27 18:23:09.938498: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1030] Found device 0 with properties:
name: GeForce GTX 1080 major: 6 minor: 1 memoryClockRate(GHz): 1.7335
pciBusID: 0000:05:00.0
totalMemory: 7.92GiB freeMemory: 7.81GiB
```

I am new to Deep learning, and is this because the weights file is too large to be used?

Thank you!

**Comment by DongxiaW** [comment]
It is the actual error message.

**Comment by hgaiser** [comment]
> It is the actual error message.

The `I` in those messages means it is just information. These are not error messages.

**Comment by hgaiser** [comment]
I'm not sure what script you're running, but `model` is not initialized there.

Closing this as it is not an issue of this repository. For further questions on how to use `keras-retinanet`, please join the Slack channel (check the README for how to join the channel).

**Comment by DongxiaW** [comment]
Sure.
Thanks for your help.
