### ISSUE TITLE
boxes, scores, labels = model.predict_on_batch(np.expand_dims(image, axis=0))  ValueError: need more than 2 values to unpack

### ISSUE THREAD

**Issue by Tangzixia** [fizyr/keras-retinanet#536]
I have met this issue, and more, the boxes size seem to be illegal? Can you help me to fix this issue?

**Comment by zqdeepbluesky** [comment]
hi,how do you solve this problem,can you please help me,thanks a lot?

**Comment by hgaiser** [comment]
Check the FAQ in the README.
