### ISSUE TITLE
import error 

### ISSUE THREAD

**Issue by raeony** [fizyr/keras-retinanet#541]
hello, hgaiser
Thanks for your open source code, but when I run the jupyter file ResNet50RetinaNet.ipynb, an import error 
  " name 'keras_resnet' is not defined " happened. Then, when I locate the file where the error happened, exactly there was no module named "keras_resnet". therefore, I just want to ask where  I can find this module or it just missed for some reasons.
This image shows a jupyter notebook example used for testing
![resnet50retinanet](https://user-images.githubusercontent.com/34431912/42080719-291e8314-7bb6-11e8-8006-b1981d80999e.png)

This image shows where the module "keras_resnet" be imported and resulted an error
![image](https://user-images.githubusercontent.com/34431912/42080861-8fcec77c-7bb6-11e8-8a24-18153f6f20cf.png)

**Comment by hgaiser** [comment]
Did you follow the README? You can install it with `pip install keras-resnet`.

**Comment by raeony** [comment]
thanks very much,  I have solved it.
