### ISSUE TITLE
Could someone tell me how much  memory need to run this file?

### ISSUE THREAD

**Issue by xfxmu** [fizyr/keras-retinanet#55]
I  always get OOM when run train_pascal.py, so I wonder how much memory should be provided to run this file.

**Comment by dasolyn** [comment]
I have no problems in the my enviroment.
(Train with Titan Xp 12GB VRAM, predict with GTX 1050 2GB VRAM)

**Comment by xfxmu** [comment]
Thanks for your reaction. I have found the problem and solved it!

**Comment by Jo-RedClouds** [comment]
@xfxmu What was your solution? Because I also keep getting OOM errors, with a 12GB GTX 1080TI and a 6GB GTX 980TI

**Comment by kapil-varshney** [comment]
@xfxmu Can you please share the solution that worked for you. It could be of help. Thanks.
