### ISSUE TITLE
What is the difference between score threshold and Iou Threshold ?

### ISSUE THREAD

**Issue by ahmedbendebba1** [fizyr/keras-retinanet#550]
Hello,
What is the difference between score threshold and Iou Threshold ? 
And how the score Threshold is used in detection ?
Thank you.

**Comment by yhenon** [comment]
The code is documented quite well here:  https://github.com/fizyr/keras-retinanet/blob/master/keras_retinanet/layers/filter_detections.py#L33

Closing as this is not anissue, please take further usage questions to the keras-retinanet slack (see readme).
