### ISSUE TITLE
What is the AnchorParameters configuration if the min_input_size=x and max_input_size=y?

### ISSUE THREAD

**Issue by Programmerwyl** [fizyr/keras-retinanet#553]
In your repo, the min and max input size are 800 and 1333, and your anchors parameters are
sizes=[32, 64, 128, 256, 512], strides=[8, 16, 32, 64, 128], ratios = np.array([0.5, 1, 2], keras.backend.floatx()), scales = np.array([2 ** 0, 2 ** (1.0 / 3.0), 2 ** (2.0 / 3.0)], keras.backend.floatx()),.
What if the min and max input size are 400 and 512, how to set the anchors parameters?
or  it is not necessary to set it.
Besides if I change the  min and max input size in training, how to change utils/image/resize_image  the min and max input size.
Thanks

**Comment by hgaiser** [comment]
`sizes` and `strides` should never really be changed. They reflect how the network is built up and unless you change that, they don't need to be changed.

You can theoretically change the scales and ratios, but if it is not necessary, I wouldn't bother. You can check using debug.py to see if the anchors find your annotations (check the README).


> Besides if I change the min and max input size in training, how to change utils/image/resize_image the min and max input size.

What do you mean? The documentation for `resize_image` is quite clear.

I'm closing this as it is not an issue with the code. Please use Slack for these questions.
