### ISSUE TITLE
No module named 'keras_retinanet.utils.compute_overlap'

### ISSUE THREAD

**Issue by fancyke** [fizyr/keras-retinanet#554]
i have find the folder of utils and found not the file compute_overlap.py only found the file of compute_overlap.pyx。so i run it get some  errors No module named 'keras_retinanet.utils.compute_overlap' .who can privode the file of compute_overlap.py

**Comment by hgaiser** [comment]
https://github.com/fizyr/keras-retinanet#faq

**Comment by yerzhik** [comment]
it didn't work for me. the script in faq finished correctly. but the error remains.

**Comment by ganav** [comment]
does not work to me too

**Comment by mariaculman18** [comment]
Hi @yerzhik, @ganav 

Did you manage to make it work? I have the same problem but the `python setup.py build_ext --inplace` solution does not work for me :(

Thank you in advance for your help.

**Comment by yerzhik** [comment]
> Hi @yerzhik, @ganav
> 
> Did you manage to make it work? I have the same problem but the `python setup.py build_ext --inplace` solution does not work for me :(
> 
> Thank you in advance for your help.

Could you please remind me what script y ou are running when this appears. I have code changes but don't remember the source of error (where it was coming from)

**Comment by mariaculman18** [comment]
Hi @yerzhik,

It is a problem when installing keras-retinanet. I managed to resolve the problem following the steps:

- clone the repo
- install prophet with `conda install -c conda-forge fbprophet`
- install keras retinanet by running `pip install .` within the cloned repo folder

From this closed [issue](https://github.com/fizyr/keras-retinanet/issues/990). It seems to be a problem with `gcc`.

Thank you for responding.

**Comment by ganeshmanikanta** [comment]
> * conda install -c conda-forge fbprophet

I have followed the directions given by @mariaculman18 and than used command 
"python setup.py build_ext --inplace" and it works great for me

After completion of instruction given by @mariaculman18 , run the command("python setup.py build_ext --inplace") in the location where this setup.py file is located.It will run the python code to generate the .c files (even with out visual studio installation). 
To find the setup.py, check in the repo keras_retinanet (https://github.com/fizyr/keras-retinanet)

**Comment by sunshinesjw1** [comment]
> Im workin on windows 10, And the solution does not work for me too..it generates C file instead of py file and does not work with the C file.

Hello,  I run the command("python setup.py build_ext --inplace") in the location where this setup.py file is located.It will run the python code to generate the .c files. But the question of ImportError: No module named 'keras_retinanet.utils.compute_overlap still exits. And I also work in win10, please tell me how you solve this question? Thanks.

**Comment by binhduong0908** [comment]
> 
> 
> > * conda install -c conda-forge fbprophet
> 
> I have followed the directions given by @mariaculman18 and than used command
> "python setup.py build_ext --inplace" and it works great for me
> 
> After completion of instruction given by @mariaculman18 , run the command("python setup.py build_ext --inplace") in the location where this setup.py file is located.It will run the python code to generate the .c files (even with out visual studio installation).
> To find the setup.py, check in the repo keras_retinanet (https://github.com/fizyr/keras-retinanet)

That works for me! Thanks!!!!!
