### ISSUE TITLE
 UserWarning: Image with id 17 (shape (920, 1906, 3)) contains the following invalid boxes: 

### ISSUE THREAD

**Issue by jetjodh** [fizyr/keras-retinanet#556]
UserWarning: Image with id 17 (shape (920, 1906, 3)) contains the following invalid boxes: [array([ 190.,  313., 1166., 1560.,    0.]), array([ 16.,  72., 940., 982.,   0.]), array([  25.,   70., 1146., 1184.,    0.])].
  [annotations[invalid_index, :] for invalid_index in invalid_indices]

What does this error mean? The training is still going on and I dont know if it is really training or not.
The losses seem to be going down though.

**Comment by mgwizdala** [comment]
This mean that your annotations are placed partially outside of the image. These annotation are not supported for now.  Everything will work fine but you should consider these annotations will not be used.

**Comment by yhenon** [comment]
That is correct. Annotations must be fully contained within the image.

**Comment by jetjodh** [comment]
When initially running the script, I got an error that y1 cannot be greater than y2, so I swapped all the greater values from y2 to y1. Do you think this might have caused this?
