### ISSUE TITLE
Not Getting the Same result as displayed using the example notebook

### ISSUE THREAD

**Issue by sumeetssaurav** [fizyr/keras-retinanet#557]
I am trying to run the example notebook code but not getting satisfactory result using the same pre-trained model that I downloaded and the same test image. I mean I am running the notebook code without any change but the output result is not detecting the tie and there are many bounding boxes.

**Comment by hgaiser** [comment]
Can you share the image you're getting?

It could be the result isn't identical, the network was updated frequently and we don't always update the example with it.

**Comment by sumeetssaurav** [comment]
Here is the out image I am getting.
![output](https://user-images.githubusercontent.com/13672595/42467512-bb82b1b4-83cf-11e8-90aa-d29484940020.png)

**Comment by hgaiser** [comment]
That is quite a strange result. For reference, using the latest version of keras-retinanet I'm getting:
![index](https://user-images.githubusercontent.com/716138/42619704-0cb295dc-85b9-11e8-8343-5fd5618a0044.png)

Are you using the latest version of keras-retinanet? Also, what versions of Keras / tensorflow are you using?

**Comment by hgaiser** [comment]
Was this issue resolved?

**Comment by hgaiser** [comment]
Closing this, I'm assuming that keras-retinanet was outdated. Feel free to open if it is still an issue.
