### ISSUE TITLE
No such file or directory: 'VOCdevkit/VOC2012/Annotations/2008_000001

### ISSUE THREAD

**Issue by Programmerwyl** [fizyr/keras-retinanet#558]
validation_generator = PascalVocGenerator(
            "D:/TF_train_data/voctest/VOCdevkit/VOC2012",
            'test',
            **common_args
        )

The test  PascalVoc data set does not have the 2008_000001 annotation file.
When the program runs an iteration（10000 times）, an error is reported

**Comment by hgaiser** [comment]
I'm not sure what VOC you've downloaded, but the text '2008_000001' doesn't seem to appear in VOC2012.

I think there's an issue with your dataset. Try redownloading the 2012 dataset.

**Comment by Programmerwyl** [comment]
@hgaiser  Thank you very much for your reply
The ‘test’ tag indicates that the file test.txt is used, and in the first line of the test.tex file, the "
" image is required for evaluation.
There is no 2008_000001 annotation file in voc2012test data set.
thanks

**Comment by hgaiser** [comment]
So the issue is resolved then?

**Comment by Programmerwyl** [comment]
@hgaiser 
There's no problem with my data set.
It is downloaded from the official website . http://host.robots.ox.ac.uk:8080/

**Comment by hgaiser** [comment]
> I don't know why you use test.tx for validation data？

Good question. A PR to change it would be welcome.

The test set of VOC2012 doesn't contain annotations, hence it cannot find it. Could you submit a PR to fix it to use the val set instead?

**Comment by Programmerwyl** [comment]
Thank you very much for your kindness. I am not as good at programming as you are.
Thanks  for your reply.

**Comment by Nusrat12** [comment]
./data/VOC0712/create_list.sh
Create list for VOC2007 trainval...
cp: cannot stat '/home/tasnim/data/VOCdevkit//VOC2007/ImageSets/Main/trainval.txt': No such file or directory
sed: can't read /home/tasnim/caffe/data/VOC0712/trainval_img.txt: No such file or directory
sed: can't read /home/tasnim/caffe/data/VOC0712/trainval_img.txt: No such file or directory
cp: cannot stat '/home/tasnim/data/VOCdevkit//VOC2007/ImageSets/Main/trainval.txt': No such file or directory
sed: can't read /home/tasnim/caffe/data/VOC0712/trainval_label.txt: No such file or directory
sed: can't read /home/tasnim/caffe/data/VOC0712/trainval_label.txt: No such file or directory
paste: /home/tasnim/caffe/data/VOC0712/trainval_img.txt: No such file or directory
Create list for VOC2012 trainval...
cp: cannot stat '/home/tasnim/data/VOCdevkit//VOC2012/ImageSets/Main/trainval.txt': No such file or directory
sed: can't read /home/tasnim/caffe/data/VOC0712/trainval_img.txt: No such file or directory
sed: can't read /home/tasnim/caffe/data/VOC0712/trainval_img.txt: No such file or directory
cp: cannot stat '/home/tasnim/data/VOCdevkit//VOC2012/ImageSets/Main/trainval.txt': No such file or directory
sed: can't read /home/tasnim/caffe/data/VOC0712/trainval_label.txt: No such file or directory
sed: can't read /home/tasnim/caffe/data/VOC0712/trainval_label.txt: No such file or directory
paste: /home/tasnim/caffe/data/VOC0712/trainval_img.txt: No such file or directory
Create list for VOC2007 test...
cp: cannot stat '/home/tasnim/data/VOCdevkit//VOC2007/ImageSets/Main/test.txt': No such file or directory
sed: can't read /home/tasnim/caffe/data/VOC0712/test_img.txt: No such file or directory
sed: can't read /home/tasnim/caffe/data/VOC0712/test_img.txt: No such file or directory
cp: cannot stat '/home/tasnim/data/VOCdevkit//VOC2007/ImageSets/Main/test.txt': No such file or directory
sed: can't read /home/tasnim/caffe/data/VOC0712/test_label.txt: No such file or directory
sed: can't read /home/tasnim/caffe/data/VOC0712/test_label.txt: No such file or directory
paste: /home/tasnim/caffe/data/VOC0712/test_img.txt: No such file or directory
I0815 20:30:05.013586 12002 get_image_size.cpp:61] A total of 0 images.
 I am using https://github.com/weiliu89/caffe/tree/ssd this site.

**Comment by hgaiser** [comment]
I suggest to make an issue on that repository then. The script is theirs, we cannot help you with that.
