### ISSUE TITLE
How to use my trained weight to predict picture

### ISSUE THREAD

**Issue by yuyijie1995** [fizyr/keras-retinanet#559]
![image](https://user-images.githubusercontent.com/30818917/42455146-03730ade-83c4-11e8-877a-67e841b4c82c.png)
I already trained KITTI and  got a weight ,but I don not how to use it to predict a picture,I can't find the predict.py file.Can you help me? Thanks a lot

**Comment by sumeetssaurav** [comment]
You could use the example notebook given in the folder for making prediction. Before that you may need to convert the model  to an inference model.

**Comment by hgaiser** [comment]
Seems it's been answered :)
