### ISSUE TITLE
Get an error in ResNet50(... freeze_bn=True)

### ISSUE THREAD

**Issue by hengshanji** [fizyr/keras-retinanet#56]
I find the definition of ResNet50 in  keras_resnet/models/_2d.py 
def ResNet50(inputs, blocks=None, include_top=True, classes=1000, *args, **kwargs)
There is not the "freeze_bn"  parameter.

**Comment by hgaiser** [comment]
Check the [README](https://github.com/fizyr/keras-retinanet/blob/master/README.md#installation) for installation instructions.

**Comment by zccoder** [comment]
@hengshanji You should download the correct resnet github project.
