### ISSUE TITLE
Using other custom resnet models with retinanet

### ISSUE THREAD

**Issue by fabihansen** [fizyr/keras-retinanet#563]
Hello,

I would first like to congratulate you for the excellent work done!

I was wondering if it's possible to use the code also with custom resnet models.
We created our own model and saved in .h5 format.

When we try to load it in retinanet, with the function load_model, the following error occurs:

TypeError: __init__() missing 1 required positional argument: 'freeze'

Do we have to save in the .h5 file also a field named "freeze" or do we have to add some other keyarg to the function load_model?

Thanks for your help,

Fabio

**Comment by hgaiser** [comment]
Where does this ResNet model come from? From `keras.applications`? If so, these are not compatible with keras-resnet (so it's not possible). You could make your own backbone for keras.applicationsbut honestly I wouldn't bother with that and retrain with keras-resnet implementation.

**Comment by hgaiser** [comment]
Closing as this is not an issue with the code base.
