### ISSUE TITLE
Getting an error Unable to find vcvarsall.bat 

### ISSUE THREAD

**Issue by mgoundge11** [fizyr/keras-retinanet#568]
Hi ,
I am getting and error Unable to find vcvarsall.bat  while runnung set.py can anyone pls help me on this ?

**Comment by hgaiser** [comment]
I'm guessing this is an issue with your installation of python.

https://blogs.msdn.microsoft.com/pythonengineering/2016/04/11/unable-to-find-vcvarsall-bat/
