### ISSUE TITLE
 ('Keyword argument not understood:', 'class_specific_filter')

### ISSUE THREAD

**Issue by sumeetssaurav** [fizyr/keras-retinanet#569]
I have generated a trained model using my custom dataset and while testing I am getting this error.

**Comment by hgaiser** [comment]
The system where you're loading the trained model on seems to have an outdated keras-retinanet. Could you try updating it?

**Comment by hgaiser** [comment]
Is this resolved?

**Comment by akhaloo** [comment]
I have trained keras-retinanet with MobileNet224 backbone on COCO dataset. I am getting the same error while running the inference model "TypeError: ('Keyword argument not understood:', 'class_specific_filter')". Your help will be much appreciated

**Comment by hgaiser** [comment]
I think you should try updating your network:

- Create a new identical model
- Load your old weights using `model.load_weights(path, by_name=True)`
- Save the new model

**Comment by akhaloo** [comment]
I have just trained keras-retinanet with ResNet101 backbone on COCO. Still getting the same error when I am running the inference model.

**Comment by hgaiser** [comment]
Possibly you have two versions of keras-retinanet, one installed and one cloned ? Make sure you update or delete the installed version as well.
