### ISSUE TITLE
Can it separate some modules to become a classification model?

### ISSUE THREAD

**Issue by zccoder** [fizyr/keras-retinanet#57]
I wonder whether this github project can be changed to a classification model. For example, I separate the regression module. Can it be ok?

**Comment by hgaiser** [comment]
Do you mean you want to only do anchor classification, no regression? If so, yes that is possible. If you mean classification as in ImageNet classification then no, that is not possible ;)

**Comment by hgaiser** [comment]
Did that answer your question?
