### ISSUE TITLE
AttributeError: module 'keras.applications' has no attribute 'imagenet_utils'

### ISSUE THREAD

**Issue by KwanjaiKJ** [fizyr/keras-retinanet#570]
Traceback (most recent call last):
  File "keras_retinanet/bin/train.py", line 483, in <module>
    main()
  File "keras_retinanet/bin/train.py", line 442, in main
    weights = backbone.download_imagenet()
  File "keras_retinanet/bin/../../keras_retinanet/models/resnet.py", line 55, in download_imagenet
    return keras.applications.imagenet_utils.get_file(
AttributeError: module 'keras.applications' has no attribute 'imagenet_utils'

**Comment by hgaiser** [comment]
I think you need to update keras-retinanet.

**Comment by KwanjaiKJ** [comment]
what's version? now I'm use keras-retinanet version 0.3.1

**Comment by hgaiser** [comment]
0.3.1 isn't keras 2.2.0 compatible. My advice is to use `master`.

**Comment by KwanjaiKJ** [comment]
Keras               2.2.0    
Keras-Applications  1.0.2    
Keras-Preprocessing 1.0.1    
keras-resnet        0.1.0    
keras-retinanet     0.3.1    

I'm use keras 2.2.0

**Comment by KwanjaiKJ** [comment]
Traceback (most recent call last):
  File "keras_retinanet/bin/train.py", line 484, in <module>
    main()
  File "keras_retinanet/bin/train.py", line 443, in main
    weights = backbone.download_imagenet()
  File "keras_retinanet/bin/../../keras_retinanet/models/resnet.py", line 57, in download_imagenet
    return keras.applications.imagenet_utils.get_file(
AttributeError: module 'keras.applications.imagenet_utils' has no attribute 'get_file'

**Comment by KwanjaiKJ** [comment]
another error

**Comment by KwanjaiKJ** [comment]
AttributeError: module 'keras.applications' has no attribute 'imagenet_utils'
this error, I can do it already. 
I'm put from keras.application import imagenet_utils on resnet.py

**Comment by hgaiser** [comment]
Is this resolved?

**Comment by KwanjaiKJ** [comment]
yes! thnak a lot.

**Comment by nosa999** [comment]
I have this error too

![image](https://user-images.githubusercontent.com/40929193/51243481-eab50a00-1997-11e9-87ad-51112c7a134b.png)

**Comment by Anesthesic** [comment]
> I have this error too
> 
> ![image](https://user-images.githubusercontent.com/40929193/51243481-eab50a00-1997-11e9-87ad-51112c7a134b.png)

exactly the same here, too bad he did not mention what to do in order to avoid that AttributeError
