### ISSUE TITLE
Import  compute_overlap .. cannot found

### ISSUE THREAD

**Issue by luvWY** [fizyr/keras-retinanet#571]
I fix it with code:
"import pyximport
pyximport.install() "
But it still has error:::
ImportError: Building module keras_retinanet.utils.compute_overlap failed: ["distutils.errors.CompileError: command 'x86_64-linux-gnu-gcc' failed with exit status 1\n"]
I dont know how to fix it

**Comment by hgaiser** [comment]
Did you run `python setup.py build_ext --inplace` ? You shouldn't need the fix you mentioned then.

**Comment by luvWY** [comment]
thx... I missed it

**Comment by Crispinli** [comment]
When I run `python setup.py build_ext --inplace`, there is no any response...

**Comment by Crispinli** [comment]
> When I run `python setup.py build_ext --inplace`, there is no any response...

Do you know how to solve it?

**Comment by luvWY** [comment]
Try to "pip install . --user" first in order to make sure your running environment.

**Comment by hgaiser** [comment]
> Do you know how to solve it?

If there is no feedback, then it probably works.
