### ISSUE TITLE
The images are upside down when using random-transform

### ISSUE THREAD

**Issue by netw0rkf10w** [fizyr/keras-retinanet#572]
Hi,

I used `debug.py` (which is a great tool, thanks!) to visualize the bounding boxes and realized that when enabling `--random-transform`, the transformed images are upside down. If no `--random-transform` then no problem.

Could you please check?
Thank you very much in advance!

**Comment by hejiaget** [comment]
>     # create random transform generator for augmenting training data
>     if args.random_transform:
>         transform_generator = random_transform_generator(
>             min_rotation=-0.1,
>             max_rotation=0.1,
>             min_translation=(-0.1, -0.1),
>             max_translation=(0.1, 0.1),
>             min_shear=-0.1,
>             max_shear=0.1,
>             min_scaling=(0.9, 0.9),
>             max_scaling=(1.1, 1.1),
>             flip_x_chance=0.5,
>             #flip_y_chance=0.5,

Comment out the last line.

**Comment by hgaiser** [comment]
Seems this has been solved.

**Comment by netw0rkf10w** [comment]
Oh no, I.AM.SO.STUPID.
Thanks a lot, @hgaiser!
