### ISSUE TITLE
testing error: 'boxes, scores, labels ' not enough values to unpack (expected 3, got 2)

### ISSUE THREAD

**Issue by luvWY** [fizyr/keras-retinanet#575]
boxes, scores, labels = model.predict_on_batch(np.expand_dims(image, axis=0))

ValueError: not enough values to unpack (expected 3, got 2)

I dont why...can somebody solve it?

**Comment by luvWY** [comment]
run "# Running directly from the repository:
keras_retinanet/bin/convert_model.py /path/to/training/model.h5 /path/to/save/inference/model.h5"

but the h5 file has error : load_model() got an unexpected keyword argument 'convert_model'
I dont know why

**Comment by luvWY** [comment]
I fixed

**Comment by hejiaget** [comment]
@luvWY I met the same probelm, could you please you how to solve it?

```
> boxes, scores, labels = model.predict_on_batch(np.expand_dims(image, axis=0))

ValueError: not enough values to unpack (expected 3, got 2)
```

**Comment by luvWY** [comment]
convert your model into a inference model

**Comment by Wulingtian** [comment]
@luvWY convert your model into a inference model,
TypeError: ('Keyword argument not understood:', u'class_specific_filter')

**Comment by PhilippMarquardt** [comment]
The problem is that the parameter of the load_model function is called `convert `and not `convert_model`. Load the inference model like this (Just my example...you need to change the path obv): `model = models.load_model('snapshots/resnet50_pascal_03.h5', backbone_name='resnet50', convert=True)`

**Comment by hgaiser** [comment]
Has this been resolved?

**Comment by PhilippMarquardt** [comment]
I guess so.  If you take a look at the `load_model` function (https://github.com/fizyr/keras-retinanet/blob/master/keras_retinanet/models/__init__.py) you can see that the parameter to convert the model is defined as `convert` and not `convert_model` like in the function call in the example notebook (https://github.com/fizyr/keras-retinanet/blob/master/examples/ResNet50RetinaNet.ipynb). 

Everyone who uses the example notebook will have this problem. I made a PR.

**Comment by hgaiser** [comment]
Since the PR (#580) is merged, I will close this. Thanks @PhilippMarquardt !
