### ISSUE TITLE
ImportError: No module named 'keras_retinanet.utils.compute_overlap'

### ISSUE THREAD

**Issue by mgoundge11** [fizyr/keras-retinanet#576]
Hi @hgaiser  I'm getting an ImportError: No module named 'keras_retinanet.utils.compute_overlap' when I run keras_retinanet/bin/train.py . I ran the setup.py and executed successfully. I'm working on windows 7,python 3.5

**Comment by lvaleriu** [comment]
**I get the error ModuleNotFoundError: No module named 'keras_retinanet.utils.compute_overlap', how do I fix this?** Most likely you are running the code from the cloned repository. This is fine, but you need to compile some extensions for this to work (python setup.py build_ext --inplace).

**Comment by PEE8** [comment]
When i run "C:\Users\Desktop\keras_retinanet\utils\anchors.py". I am getting error  import compute_overlap
cimport cython
                 ^
SyntaxError: invalid syntax

I placed compute_overlap in the same folder
