### ISSUE TITLE
Add blur and vary light conditions when augmentation is done in transform.py

### ISSUE THREAD

**Issue by chaitanyarit** [fizyr/keras-retinanet#577]
I want to use blur and change the emulate varying lighting conditions by varying hue and saturation in my images when it transforms the images in transform.py. But transform.py has only  rotation, translation, scaling, shearing and flips. How do I add blur and add vary light conditions?

**Comment by lvaleriu** [comment]
Use a project like this: https://github.com/aleju/imgaug

**Comment by hgaiser** [comment]
Blur and lighting is not something that is currently supported, nor is there a plan to add this. I'll close this issue since we won't be adding it. As @lvaleriu said, you could use other tools to handle augmentation if you need blurring / lighting augmentation.

**Comment by liminghuiv** [comment]
Hi, @chaitanyarit, @lvaleriu @hgaiser, do you have an example on adding additional augmentation methods, i.e. using imgaug?  I browsed through the keras-retinanet code, it is not so straightforward.
Thanks a lot.
Liming
