### ISSUE TITLE
Where does the project save its model?

### ISSUE THREAD

**Issue by qewtqwqqq** [fizyr/keras-retinanet#578]
I am new to keras, and I don't know during it's training where does the project save the weights it results with? Also in what interval does it save them?
Do I have to specify it? Or is there a default dir?
I've search this for a long time and didn't get answer, guess I'm searching it wrong.

**Comment by PhilippMarquardt** [comment]
The models will be saved _after_ each epoch in the snapshots directory.

**Comment by qewtqwqqq** [comment]
@PhilippMarquardt Thanks!
