### ISSUE TITLE
How to test the inference model on test images?

### ISSUE THREAD

**Issue by mgoundge11** [fizyr/keras-retinanet#579]
I have done the training using my own dataset and able create the inference model for the same ?
But when I checked evaluate.py file it as asking for test images annotations data as one of the input parameter. Why it is required?

**Comment by hgaiser** [comment]
Please use Slack for questions about usage.

evaluate.py computes an mAP score for your model and dataset, so it requires the annotations. Check out the example notebook, I think that is what you're looking for.

**Comment by mgoundge11** [comment]
Thank you.
