### ISSUE TITLE
No training configuration found in save file: the model was *not* compiled.

### ISSUE THREAD

**Issue by yelanyelan** [fizyr/keras-retinanet#582]
Thank you for the great work! But I got some problem.

I download the resnet50_coco pretrain model form [here](https://github.com/fizyr/keras-retinanet/releases) and loading it as prediction_model.
but I get the problem as:

No training configuration found in save file

Although it said that is a safe warning, but I cant load the pretrain model with problem:  **IndexError: list index out of range**.  And I find that if I print 
`print('step2',classification.shape)`
that will call twice of the `filter_detections` and the classification will get strange shape when it was called twice:

> step1 (?, 80)
> step2 (?, 80)
> /home/XXX/workspace/tensorflow/lib/python3.5/site-packages/keras/models.py:255: UserWarning: No training configuration found in save file: the model was *not* compiled. Compile it manually.
>   warnings.warn('No training configuration found in save file: '
> step1 (300,)
> step2 (300,)
>     ................
>   File "/home/XXX/.local/lib/python3.5/site-packages/keras_retinanet/layers/filter_detections.py", line 45, in filter_detections
>     for c in range(int(classification.shape[1])):
>   File "/home/XXX/workspace/tensorflow/lib/python3.5/site-packages/tensorflow/python/framework/tensor_shape.py", line 521, in __getitem__
>     return self._dims[key]
> IndexError: list index out of range

When I conver this pretrain model, this problem raise again. All of those problem will absent when I use a csv train model.

**Comment by hgaiser** [comment]
Are you converting the COCO pretrained model? It is already converted, converting it again will probably give this issue.

**Comment by yelanyelan** [comment]
Sry, It happen again. It has the same problem when I use `retinanet-convert-model` to convert it. 

> step1 (300,)
> step2 (300,)
> Traceback (most recent call last):
>  ..........
>   File "/home/XXX/.local/lib/python3.5/site-packages/keras_retinanet/layers/filter_detections.py", line 45, in filter_detections
>     for c in range(int(classification.shape[1])):
>   File "/home/XXX/workspace/tensorflow/lib/python3.5/site-packages/tensorflow/python/framework/tensor_shape.py", line 521, in __getitem__
>     return self._dims[key]

**Comment by hgaiser** [comment]
Did this fix your issue? If so, please close this issue.

**Comment by yelanyelan** [comment]
No, It still here, but thank u a lot. 
I cant still use the --snapshot to load the model 
But I think that I use --weight to load the weight and fine tuning again can make the same.

**Comment by oluwayetty** [comment]
Well, I am currently having this same issue; **IndexError: list index out of range**
What's going on? why was this even closed when there wasn't any solution to it anyway?

**Comment by yelanyelan** [comment]
Please use `--weight` to load the pretrain model instead of `--snapshot`.
