### ISSUE TITLE
RGB or BGR after preprocess_image?

### ISSUE THREAD

**Issue by andyguo007** [fizyr/keras-retinanet#586]
Hi,

Thanks for the great work. 
I was reading ResNet50RetinaNet.ipynb and found the following code a bit confusing:

image = read_image_bgr('000000008021.jpg')

# copy to draw on
draw = image.copy()
draw = cv2.cvtColor(draw, cv2.COLOR_BGR2RGB)

# preprocess image for network
image = preprocess_image(image)

So before preprocess_image, the image is RGB. However in the function preprocess_image it says 
"except for converting RGB -> BGR since we assume BGR already". So we are supposed to input BGR into preprocess_image, right?

and, are the imagenet weights under https://github.com/fizyr/keras-models/releases trained based on the images (first converted to BGR and then input into preprocess_image for normalization)?

Thanks,
Andy

**Comment by hgaiser** [comment]
All images are always BGR for keras-retinanet, in every step of the pipeline.

Trusting this answers your question I'll close this issue (also, use Slack for implementation questions).

**Comment by shahsahilj** [comment]
The read_img_bgr() function actually calls     

image = np.asarray(Image.open(path).convert('RGB'))

so how will it be BGR at all steps?

**Comment by hgaiser** [comment]
The return of that functions swaps the channels to bgr :)
