### ISSUE TITLE
ImportError: cannot import name load_model

### ISSUE THREAD

**Issue by KwanjaiKJ** [fizyr/keras-retinanet#587]
from keras_retinanet import load_model
model = load_model('widerface_model.h5', backbone_name='resnet50')

Traceback (most recent call last):
  File "ResNet50Retinanet.py", line 13, in <module>
    from keras_retinanet import load_model
ImportError: cannot import name load_model

**Comment by hgaiser** [comment]
`load_model` comes from `keras_retinanet.models`.
