### ISSUE TITLE
[bug report]Using VGG19 as backbone

### ISSUE THREAD

**Issue by ycui123** [fizyr/keras-retinanet#588]
Hi,

I want to use VGG19 as backbone. But I encountered the issue "AttributeError: module 'keras.applications.vgg19' has no attribute 'WEIGHTS_PATH_NO_TOP'.

Any ideas? Thanks a lot

**Comment by ycui123** [comment]
Update: Just realize that I don't want a pretrained model. So I add '--no-weights' in the command line to make it work. But still have no idea what to do if pretrained model is needed.

**Comment by alexFilin** [comment]
Hi, we've found solution for this issue.

Instead of running 
`resource = keras.applications.vgg19.WEIGHTS_PATH_NO_TOP`
[here](https://github.com/fizyr/keras-retinanet/blob/master/keras_retinanet/models/vgg.py#L43) we use
`import keras_applications`
`resource = keras_applications.vgg19.WEIGHTS_PATH_NO_TOP`

Also the same works for VGG16.

**Comment by ycui123** [comment]
Hi @alexFilin ,

Thank you for the reply. The problem was solved. Please see my updates.

**Comment by hgaiser** [comment]
Could you make a PR with the fix?

**Comment by ycui123** [comment]
@hgaiser , there are several places need to be modified.
In train.py, line 105 and 108. change it to 

"model = model_with_weights(backbone_retinanet(num_classes, weights, modifier=modifier), weights=weights, skip_mismatch=True)"

In vgg.py line 69, add weights into args.
Same function line 86 and 88, change it to

"vgg = keras.applications.VGG16(input_tensor=inputs, include_top=False, weights=weights)"
"vgg = keras.applications.VGG19(input_tensor=inputs, include_top=False, weights=weights)"

This only works for vgg backbone tho, if other models are needed, please modify the corresponding py file in ./keras_retinanet/models directory. I haven't looked into other backbones.

**Comment by ycui123** [comment]
Yes, @alexFilin. You are absolutely right!

**Comment by LCorleone** [comment]
@ycui123 @hgaiser 
Hi, I think the following code should be modified in bin/train.py
```
    if args.snapshot is not None:
        print('Loading model, this may take a second...')
        model = models.load_model(args.snapshot, backbone_name=args.backbone)
        training_model = model
        prediction_model = retinanet_bbox(model=model)
    else:
        weights = args.weights
        # default to imagenet if nothing else is specified
        if weights is None and args.imagenet_weights:
            weights = backbone.download_imagenet()

        print('Creating model, this may take a second...')
        model, training_model, prediction_model = create_models(
            backbone_retinanet=backbone.retinanet,
            num_classes=train_generator.num_classes(),
            weights=weights,
            multi_gpu=args.multi_gpu,
            freeze_backbone=args.freeze_backbone
        )
```
for the else section, maybe it should be modified like this:
    else:
        weights = args.weights
        # default to imagenet if nothing else is specified
        if weights is None and args.imagenet-weights:
            weights = backbone.download_imagenet()
        if args.no-weights:
            weights = None

what's more, the dest name is imagenet_weights in "no-weights" argument is confusing with the argument imagenet-weights! Please check it out. thank you.
```
    group.add_argument('--snapshot', help='Resume training from a snapshot.')
    group.add_argument('--imagenet-weights', help='Initialize the model with pretrained imagenet weights. This is the default behaviour.', action='store_const', const=True, default=True)
    group.add_argument('--weights', help='Initialize the model with weights from a file.')
    group.add_argument('--no-weights', help='Don\'t initialize the model with any weights.', dest='imagenet_weights', action='store_const', const=False)
```
This is my understanding, am I right?

**Comment by hgaiser** [comment]
@LCorleone I think the code is still correct. If `--weights` is given, those are used. If no weights are given, then imagenet weights are used. If `--no-weights` is used, then `weights is None`.

@de-vri-es correct me if I'm wrong.

Regarding the VGG errors with imagenet weights, can someone make a PR to fix it ?

**Comment by de-vri-es** [comment]
> @LCorleone I think the code is still correct. If --weights is given, those are used. If no weights are given, then imagenet weights are used. If --no-weights is used, then weights is None.
> 
> @de-vri-es correct me if I'm wrong.

That is correct.

**Comment by hgaiser** [comment]
Fixed by https://github.com/fizyr/keras-retinanet/commit/582b6bc453d9b32dcdc37814e101a387e84b8634
