### ISSUE TITLE
How to train backbone separately?

### ISSUE THREAD

**Issue by NeuronCrossroads** [fizyr/keras-retinanet#591]
How can I train a backbone separately from the retinanet?

**Comment by hgaiser** [comment]
You can train a backbone as a classification network and then load the weights using `--weights`. There's no utilities in keras-retinanet to do this, you need to make your own training. Do note that the backbones need to correspond to the ones used in keras-retinanet. In particular, the resnet we use comes from keras-resnet, if you train the resnet in keras.aplications it won't be compatible.
