### ISSUE TITLE
train.py oid /path/to/OID commands specify directory of what?

### ISSUE THREAD

**Issue by deep-diver** [fizyr/keras-retinanet#593]
What files should be listed in the /path/to/OID directory?

Since OID is for object localization problem, I guess CSV file whose format is "path/to/image.jpg,x1,y1,x2,y2,class_name" ?

**Comment by hgaiser** [comment]
@lvaleriu can you answer this?

**Comment by daodao316** [comment]
Just read keras-retinanet-master/keras_retinanet/preprocessing/open_images.py

**Comment by deep-diver** [comment]
Thanks @daodao316 and @hgaiser!

<img src="https://image.ibb.co/egCvzJ/image.png"/>

so, the screenshot above shows all the files that I need. I was confused between V4 and Challenge 2018.

**Comment by lvaleriu** [comment]
If this can bring some more clarification: 

![image](https://user-images.githubusercontent.com/927999/42932463-9702299e-8b42-11e8-8bdc-21d10109578f.png)


![image](https://user-images.githubusercontent.com/927999/42932480-aa487eae-8b42-11e8-9d7b-8a3ae96da4ee.png)

**Comment by lvaleriu** [comment]
But yes, the best way is to let the code(at keras-retinanet-master/keras_retinanet/preprocessing/open_images.py) guide you.
