### ISSUE TITLE
Is it possible to stop training and resume later?

### ISSUE THREAD

**Issue by deep-diver** [fizyr/keras-retinanet#594]
I am trying to use "train.py oid /path/to/OID" command.

Since this is a huge dataset, and I have somewhat poor GPU power, I want to train some portions of the whole dataset like 10% and continue training for the next 10% of the data.

Is it possible to do so? Or should I split the meta-file into 10 pieces and train on each one day by day?

Thank you!

**Comment by hgaiser** [comment]
Please ask these questions on Slack, Github Issues are not the place for these questions.

(also, check the args for train.py)

**Comment by deep-diver** [comment]
I am sorry
