### ISSUE TITLE
mobilenet inference model

### ISSUE THREAD

**Issue by migom6** [fizyr/keras-retinanet#598]
**Where can I find a mobilenet inference model. All I could find was resnet50. I need speed and to detect person only.
BTW this library works like a breeze unlike many other object detection libraries. 
Cheers!!**

Please make sure that the boxes below are checked before you submit your issue. Only use GitHub issues for issues with the implementation, not for issues with specific datasets or general questions about functionality. If your issue is an implementation question, please ask your question on the [#keras-retinanet Slack channel](https://github.com/fizyr/keras-retinanet#discussions) and ask there instead of filing a GitHub issue.

Thank you!

- [ x] Check that you are up-to-date with the master branch of keras-retinanet.

- [x ] Check that you are up-to-date with the latest version of [Keras](https://github.com/keras-team/keras). 

- [x ] Check that you are up-to-date with the latest version of TensorFlow. The installation instructions can be found [here](https://www.tensorflow.org/get_started/os_setup).

- [ ] Check that you have read the entire [README.md](https://github.com/fizyr/keras-retinanet/README.md). Most noticably the [FAQ](https://github.com/fizyr/keras-retinanet#faq) section shows common issues.

- [ ] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

**Comment by hgaiser** [comment]
There's only a ResNet pretrained model available due to limited resources on our side. If you train a mobilenet model on COCO we'd be happy to host it on GitHub as well.

**Comment by alejodosr** [comment]
Any news about this topic? :)

Do you think it is possible to train a 1-class object detector with the pretrained Imagenet weights? Thank you in advance.
