### ISSUE TITLE
error: Microsoft Visual C++ 14.0 is required

### ISSUE THREAD

**Issue by Nemasery** [fizyr/keras-retinanet#606]
running build_ext
skipping 'keras_retinanet/utils\compute_overlap.c' Cython extension (up-to-date)
building 'keras_retinanet.utils.compute_overlap' extension
error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": http://landinghub.visualstudio.com/visual-cpp-build-tools
whilie "https://landinghub.visualstudio.com/visual-cpp-build-tools" is not found

**Comment by hgaiser** [comment]
Ah great, that's a useful error code ;p

You could follow [this](https://www.scivision.co/python-windows-visual-c++-14-required/) page, but to be honest I don't have experience with windows and python.

**Comment by Nemasery** [comment]
ok，thank you！

**Comment by scivision** [comment]
Yes Python on Windows requires VS Build Tools for building C/C++ extension modules. The URL recently changed as you noted.

**Comment by hgaiser** [comment]
Assuming this fixed your issue, I'll close this.
