### ISSUE TITLE
How to make the pretrained model？

### ISSUE THREAD

**Issue by laidy3** [fizyr/keras-retinanet#607]
Is just a classification model which trained on imagenet？
Thanks for your answers.

**Comment by hgaiser** [comment]
I don't get the question? You want to make a pretrained model? Of what?

**Comment by laidy3** [comment]
@hgaiser yes, I want to make a pretrained model, what should i do?

**Comment by hgaiser** [comment]
Of what?

**Comment by laidy3** [comment]
Xception or Resnet50?

**Comment by hgaiser** [comment]
We don't have a backbone for Xception, we do for ResNet. For ResNet50 we supply a pretrained model (check the README). If you want to train your own model, follow the instructions in the README to get you started.

Please ask further questions on Slack (also check the README for directions).

Basically it's all in the README :p

**Comment by laidy3** [comment]
I am very sorry, I know there is a resnet50 pretrained model, is it initialized with imagenet pretrained?
I just want to know what should i do if i want to make a backbone.
