### ISSUE TITLE
PIL/Image.py:844: ResourceWarning: unclosed file <_io.BufferedReader ...

### ISSUE THREAD

**Issue by deep-diver** [fizyr/keras-retinanet#609]
for pascal_voc.py, it loads image names like 

>  self.image_names = [l.strip().split(None, 1)[0] for l in open(os.path.join(data_dir, 'ImageSets', 'Main', set_name + '.txt')).readlines()]

then, this line of code produces warning like

> PIL/Image.py:844: ResourceWarning: unclosed file <_io.BufferedReader ...

I think the code should be changed to use `with open(...) as file` since it is a recommended way

**Comment by hgaiser** [comment]
Hmm interesting, I've never seen these warnings before. Can you share some information on your system, what OS and what version of libraries you're using?

**Comment by deep-diver** [comment]
OS: macOS (High Sierra 10.13.6)
Python: 3.6.0
TensorFlow: 1.6.0rc0
Keras: 2.2.0
Pillow: 4.0.0

**Comment by hgaiser** [comment]
Are you sure the warning comes from that line? The line you mentioned isn't using and PIL related stuff.

**Comment by deep-diver** [comment]
sorry it was my mistake.
