### ISSUE TITLE
accurate performance on object detection but poor classification

### ISSUE THREAD

**Issue by Shiying99** [fizyr/keras-retinanet#611]
Hello

Thank you so much for sharing this repository. 

I am currently using this network to train a model to calculate the confidence score for a detected object in 2 classes. The position of the object are detected very well, but the confidence score is very low. The confidence score for the right class is often slightly lower than the wrong class. (backbone model is resnet50)

Do you have any advises what I could change to improve the classification performance and their score?
I would appreciate for any suggestion. Thank you very much.

Best greetings
Lisha

**Comment by deep-diver** [comment]
gathering more data?

**Comment by hgaiser** [comment]
As this is not an issue with the code I will close it.

You could try the keras-retinanet Slack channel for tips and tricks.
