### ISSUE TITLE
Real-time object detection

### ISSUE THREAD

**Issue by hxlee309** [fizyr/keras-retinanet#620]
Hi,

Is retinanet suitable for real-time objection detection task (i.e. self-driving car)? Since I notice that the inference speed is about 0.9 second per frame (640 x 480) using a GTX 1050 GPU. 

Thanks

**Comment by hgaiser** [comment]
0.9s is quite slow, but then again, a GTX 1050 is also quite slow. You could try updating to the latest tensorflow / cuda / cudnn / keras and see if that makes a difference. If not, then your best bet is to update your GPU.

You could also try to use tcmalloc for memory allocation. If you prepend your inference script with `LD_PRELOAD=/usr/lib/libtcmalloc.so` you might gain a little bit of speed (I got near 10% increase in speed). You might need to install `gperf` for this.

For reference, on a 1080ti it runs in approx. 80msec on a 1000x800 image.

Closing as this is not an issue with the code.
