### ISSUE TITLE
why are always 300 detections results in run ResNet50RetinaNet.ipynb test,the output of boxes are always 300.At the same time ,there is no operations of NMS in the prediction of ResNet50RetinaNet.ipynb test.

### ISSUE THREAD

**Issue by hu5tao** [fizyr/keras-retinanet#624]
why are always 300 detections results in run ResNet50RetinaNet.ipynb test,the output of boxes are always 300.At the same time ,there is no operations of NMS in the prediction of ResNet50RetinaNet.ipynb test.And how to change  NMS in the prediction of ResNet50RetinaNet.ipynb

**Comment by yelanyelan** [comment]
You can change default **max_detection** in **'/keras_retinanet/layers/filter_detections'**. 
This model sorted the scores to select the detection results with scores and u can use NMS in **/keras_retinanet/utils/eval** instead of scores judgment

**Comment by hu5tao** [comment]
@yelanyelan  OK! Thanks , I understand.And another a question is: How to batch test on a path ?

**Comment by yelanyelan** [comment]
I dont really understand ur question. But if u meat that u want to test ur dataset under a path, u can organize ur dataset as a csv file and test with csv.

**Comment by hu5tao** [comment]
OK、that's no problem，I understand. A problem again ，when i train it in my dataset,epoch=25,and loss will be 0.23，no decresed obviously again, and regression loss is 0.18,but classfication loss is lower than regression.
And that's  normal？

**Comment by hgaiser** [comment]
Yeah that's normal.

I'll close this since it seems resolved.

**Comment by hu5tao** [comment]
@hgaiser @yelanyelan  OK,thanks. I want to ask a quetions again,  RetinaNet attaches two subnetworks, one for classifying anchor boxes. Were that two subnetworks shared all the parameters ? Or different features layer including [P3,P4,P5,P6,P7] ，all of thems have two subnetworks . Thanks!
