### ISSUE TITLE
How to extract features from region of interest?

### ISSUE THREAD

**Issue by paulcx** [fizyr/keras-retinanet#627]
Unlike Faster RCNN, we can extract ROI features from layers before fully connected layer. As an one-shot object detector, is that possible and how?

**Comment by hgaiser** [comment]
Extracting ROI features and classifying based on that is basically the second stage in two stage detectors. Retinanet is a one stage detector, so it doesn't compute ROI features. You could have a look here: https://github.com/fizyr/keras-maskrcnn

**Comment by paulcx** [comment]
@hgaiser Thanks. You mean keras-maskrcnn can work as a location detector instead of predicting the mask by removing output?
