### ISSUE TITLE
Why the saved train model is about 400M while the saved prediction model is only about 140M?

### ISSUE THREAD

**Issue by BearVic** [fizyr/keras-retinanet#628]
Is the size of the saved prediction model (.h5) supposed to be larger than the size of the saved train model, as the prediction model including the train model?

**Comment by BearVic** [comment]
It seems I made a mistake. The train model is a multi-gpu version. While the base model is the true train model which is only 140M too. Sorry for that I did not read the codes very carefully.

**Comment by hgaiser** [comment]
Actually the answer is slightly different. The train model also contains
the solver state, which apparently takes up a lot of space. In terms of
weights, the train and inference model are identical. The inference model
is slightly larger in number of layers, but these additional layers don't
contain any weights (think NMS for instance). Hence it is only adding a
little bit in terms of layer configurations. The main difference comes from
the solver state.
