### ISSUE TITLE
model.predict_on_batch return only one value

### ISSUE THREAD

**Issue by benjisympa** [fizyr/keras-retinanet#629]
Hello,

Thank you for your work.
I try to run your code, it works but the line 'boxes, scores, labels = model.predict_on_batch(inputs)' return only one value, the softmax distribution for all the objects.
So I have this error : 

ValueError           Traceback (most recent call last)
<ipython-input-49-c7fbae3d8b72> in <module>()
     21     print(len(img),len(img[0]),len(img[0][0]),len(img[0][0][0]))
     22     print(img.shape)
---> 23     boxes, scores, labels = model.predict_on_batch(img)
     24     plop = model.predict_on_batch(img)
     25     print(plop)

ValueError: not enough values to unpack (expected 3, got 1)

I haven't the boxes and the labels.
I don't understand why, can you help me pls ?
Thanks.

**Comment by benjisympa** [comment]
Ow ok I understand, I need to train the network with the script.
It's not possible to train it on my own dataset ?
I need to modify the script right ?
Thanks.

**Comment by hgaiser** [comment]
It's possible to freeze the backbone, not all except for the last 4. Well, it's possible, but not exposed. You'll have to make that change yourself.

Closing this as it appears to be resolved.

**Comment by benjisympa** [comment]
Ok thanks, I will modify the code so.
