### ISSUE TITLE
retinanet-scripts work only once

### ISSUE THREAD

**Issue by skumailraza** [fizyr/keras-retinanet#630]
retinanet-scripts like retinanet-convert-model, retinanet-train, retinanet-evaluate work only one time for any user. Have to install and run from a new user every time. Even reinstalling deosn't work.

**Comment by hgaiser** [comment]
What happens if you run it a second time ?

**Comment by skumailraza** [comment]
command not found

**Comment by hgaiser** [comment]
I'll close this issue since I'm pretty sure this issue is related to your environment, not to keras-retinanet.
