### ISSUE TITLE
Warning for boxes

### ISSUE THREAD

**Issue by benjisympa** [fizyr/keras-retinanet#633]
Hello,

I don"t understand why, I have a lot of warning like theses : 

[annotations[invalid_index, :] for invalid_index in invalid_indices]
/people/maurice/.local/lib/python3.6/site-packages/keras_retinanet/preprocessing/generator.py:148: UserWarning: Image with id 237 (shape (3024, 4032, 3)) contains the following invalid boxes: [array([ 950., 2067., 1702., 3499.,    0.]), array([1.669e+03, 2.681e+03, 2.200e+03, 3.184e+03, 1.000e+00])].
  [annotations[invalid_index, :] for invalid_index in invalid_indices]
/people/maurice/.local/lib/python3.6/site-packages/keras_retinanet/preprocessing/generator.py:148: UserWarning: Image with id 18 (shape (3024, 4032, 3)) contains the following invalid boxes: [array([ 276., 1044., 1586., 3112.,    0.])].
  [annotations[invalid_index, :] for invalid_index in invalid_indices]
/people/maurice/.local/lib/python3.6/site-packages/keras_retinanet/preprocessing/generator.py:148: UserWarning: Image with id 30 (shape (3024, 4032, 3)) contains the following invalid boxes: [array([1470., 1061., 2371., 3173.,    0.])].

The network continues the training but it's really strange ?

Thanks.

**Comment by hgaiser** [comment]
It seems your image have height 3024, but your y2 values are bigger than that (3184, 3112 and 3173). Are you sure you didn't swap your x and y values for your boxes? The order is (x1, y1, x2, y2).

**Comment by benjisympa** [comment]
Hum maybe it's just an inversion but what is your axis and repere ?

For me it's : 

|- - - - - > x
|
|    1--|
|    |    |
|    |--2
y

Yes in the cdv file I put x1,y1,x2,y2 but is the shape is inversed ?
I thought that 3024 was the width and 4032 the height, so I need to invert my x and y to be ok right ?

Thanks a lot.

**Comment by hgaiser** [comment]
The shape is printed in matrix notation, so it is (rols, cols, channels), or in other words (height, width, channels).

Other than that, your axis are correct.

**Comment by benjisympa** [comment]
Ok, it's strange, I follow the tutorial. I will try to switch x and y in the csv file so.

**Comment by hgaiser** [comment]
My advice is to use debug.py to check if your annotations are correct.

**Comment by benjisympa** [comment]
Ok, I will try this. Didn't try yet.

Thanks :)

**Comment by benjisympa** [comment]
I try the script, for small images it works but for big image, the axis are inverted.
I don't understand why ?
I see in the code min_side=800, max_side=1333 but I use a min_side and a max_side of 224 for the network and theses values are not used when I use the script debug, it just read the image with opencv and numpy.
So I really don't understand the problem. Have you an idea ?
Thanks.

**Comment by hgaiser** [comment]
For some reason part of your data has inverted axis. Not much I can do about that, so I'll close this issue.
