### ISSUE TITLE
What should I chang if the category is one

### ISSUE THREAD

**Issue by pangwenfeng** [fizyr/keras-retinanet#634]
Hello! I have a question that if my category number is one, what do I need to change in the code? I changed the class.csv and created my own dataset.csv. It work, and the regression loss kept on decreasing, however, the classification loss was not stable. So I want to know what should I change more?

**Comment by hgaiser** [comment]
As this is not an issue with the code I'll close this. This question is better suited for Slack (for which I see you also asked this question).
