### ISSUE TITLE
About the results in the README.md

### ISSUE THREAD

**Issue by kongqiankun** [fizyr/keras-retinanet#635]
Hi, thanks for your code about Retinanet with keras firstly. I have an question about the result you show  in the README.md. I want  to know the result is realised on the dataset(COCO trainval35K) which is proposed in the original paper,or on the dataset(COCO 2017train, 2017val) which is proposed in your code file(train.py).

**Comment by hgaiser** [comment]
We trained on the COCO2017 dataset, but as I understand it, it is equal to trainval35k.

Since this issue is not an issue with the code, I'll close it. Please discuss further on Slack.
