### ISSUE TITLE
no tensorboard file

### ISSUE THREAD

**Issue by jplnasa5** [fizyr/keras-retinanet#638]
When I adjust the number of steps from 1000 to 1000, there is no tensorboard file in the logs folder.
why？

**Comment by de-vri-es** [comment]
Please follow the guides from the issue template: include exactly what steps you're following, what the expected behaviour is and what the actual behaviour is.

There is not enough information in this issue for us to do anything but guess.

**Comment by jplnasa5** [comment]
I know, need to write an absolute path for logs
