### ISSUE TITLE
super() function in  ResNet50RetinaNet.ipynb  raises a TypeError

### ISSUE THREAD

**Issue by avaghefi** [fizyr/keras-retinanet#639]
Hello,

I am trying to load the model using the notebook template: 

`
model_path = os.path.join( '/home/a_vaghefi','resnet50_coco_best_v2.1.0.h5')
model = models.load_model('resnet50_coco_best_v2.1.0.h5', backbone_name='resnet50')
`
It throws the following errors: 
`---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-36-df30331ba6f5> in <module>()
      4 # load retinanet model
      5 #model = models.load_model('resnet50_coco_best_v2.1.0.h5', backbone_name='resnet50')
----> 6 model = models.load_model(model_path, backbone_name='resnet50', convert=True)

~/.local/lib/python3.6/site-packages/keras_retinanet/models/__init__.py in load_model(filepath, backbone_name, convert, nms, class_specific_filter)
     81     import keras.models
     82 
---> 83     model = keras.models.load_model(filepath, custom_objects=backbone(backbone_name).custom_objects)
     84     if convert:
     85         from .retinanet import retinanet_bbox

~/.local/lib/python3.6/site-packages/keras/engine/saving.py in load_model(filepath, custom_objects, compile)
    258             raise ValueError('No model found in config file.')
    259         model_config = json.loads(model_config.decode('utf-8'))
--> 260         model = model_from_config(model_config, custom_objects=custom_objects)
    261 
    262         # set weights

~/.local/lib/python3.6/site-packages/keras/engine/saving.py in model_from_config(config, custom_objects)
    332                         '`Sequential.from_config(config)`?')
    333     from ..layers import deserialize
--> 334     return deserialize(config, custom_objects=custom_objects)
    335 
    336 

~/.local/lib/python3.6/site-packages/keras/layers/__init__.py in deserialize(config, custom_objects)
     53                                     module_objects=globs,
     54                                     custom_objects=custom_objects,
---> 55                                     printable_module_name='layer')

~/.local/lib/python3.6/site-packages/keras/utils/generic_utils.py in deserialize_keras_object(identifier, module_objects, custom_objects, printable_module_name)
    143                     config['config'],
    144                     custom_objects=dict(list(_GLOBAL_CUSTOM_OBJECTS.items()) +
--> 145                                         list(custom_objects.items())))
    146             with CustomObjectScope(custom_objects):
    147                 return cls.from_config(config['config'])

~/.local/lib/python3.6/site-packages/keras/engine/network.py in from_config(cls, config, custom_objects)
   1015         # First, we create all layers and enqueue nodes to be processed
   1016         for layer_data in config['layers']:
-> 1017             process_layer(layer_data)
   1018         # Then we process nodes in order of layer depth.
   1019         # Nodes that cannot yet be processed (if the inbound node

~/.local/lib/python3.6/site-packages/keras/engine/network.py in process_layer(layer_data)
   1001 
   1002             layer = deserialize_layer(layer_data,
-> 1003                                       custom_objects=custom_objects)
   1004             created_layers[layer_name] = layer
   1005 

~/.local/lib/python3.6/site-packages/keras/layers/__init__.py in deserialize(config, custom_objects)
     53                                     module_objects=globs,
     54                                     custom_objects=custom_objects,
---> 55                                     printable_module_name='layer')

~/.local/lib/python3.6/site-packages/keras/utils/generic_utils.py in deserialize_keras_object(identifier, module_objects, custom_objects, printable_module_name)
    145                                         list(custom_objects.items())))
    146             with CustomObjectScope(custom_objects):
--> 147                 return cls.from_config(config['config'])
    148         else:
    149             # Then `cls` may be a function returning a class.

~/.local/lib/python3.6/site-packages/keras/engine/base_layer.py in from_config(cls, config)
   1107             A layer instance.
   1108         """
-> 1109         return cls(**config)
   1110 
   1111     def count_params(self):

~/.local/lib/python3.6/site-packages/keras_retinanet/layers/_misc.py in __init__(self, size, stride, ratios, scales, *args, **kwargs)
     56         ))
     57 
---> 58         super(Anchors, self).__init__(*args, **kwargs)
     59 
     60     def call(self, inputs, **kwargs):

TypeError: super(type, obj): obj must be an instance or subtype of type`

I am wondering if there is any idea on this error?
Thanks

**Comment by hgaiser** [comment]
This is an "[issue](https://github.com/jupyter/help/issues/130)" with the autoreload for jupyter notebook, so I'll close this. If you restart your python kernel it should work fine.
