### ISSUE TITLE
Training my own dataset map is always 0

### ISSUE THREAD

**Issue by jplnasa5** [fizyr/keras-retinanet#640]
There is no problem in training pascal data, but changing to my own data set training map is always
0.
My training data is six categories.
Is it only necessary to modify one place in pascal_voc.py?
```
#voc_classes = {
#    'aeroplane'   : 0,
#    'bicycle'     : 1,
#    'bird'        : 2,
#    'boat'        : 3,
#    'bottle'      : 4,
#    'bus'         : 5,
#    'car'         : 6,
#    'cat'         : 7,
#    'chair'       : 8,
#    'cow'         : 9,
#    'diningtable' : 10,
#    'dog'         : 11,
#    'horse'       : 12,
#    'motorbike'   : 13,
#    'person'      : 14,
#    'pottedplant' : 15,
#    'sheep'       : 16,
#    'sofa'        : 17,
#    'train'       : 18,
#    'tvmonitor'   : 19
#}


voc_classes = {
        'crazing'          :0,
        'inclusion'        :1,
        'patches'          :2,
        'pitted_surface'   :3,
        'rolled-in_scale'  :4,
        'scratches'        :5
        }
```

Any other places need to be modified?

**Comment by jpxrc** [comment]
Which backbone model are you using (e.g. Resnet50, Densenet121, etc.)?

**Comment by jplnasa5** [comment]
resnet50 @jpxrc

**Comment by hgaiser** [comment]
My advice is to use the CSV dataset type as it is more suitable for custom datasets. Since this issue is not an issue with the code I'll close this. Further discussions like this should be done on the Slack channel.
