### ISSUE TITLE
ValueError: not enough values to unpack (expected 3, got 2)

### ISSUE THREAD

**Issue by TimeLCJ** [fizyr/keras-retinanet#653]
After training with voc2007, I tested the saved model with the code of the ResNet50RetinaNet.ipynb file. An error occurred:  `ValueError: not enough values to unpack (expected 3, got 2)`
The error code is here:
`boxes, scores, labels = model.predict_on_batch(np.expand_dims(image, axis=0))`
This model only outputs two values. So I print these two values out. the first tensor has the shape of (1, 160956, 4), it looks like:

> [[[ 0.10952932  0.06446765  0.01941724  0.03779086]
  [ 0.05137292  0.03668761 -0.02232533  0.05901864]
  [ 0.04374445  0.05928183 -0.03446548  0.09051949]
  ...
  [-0.31549963 -0.23872668 -0.16181114 -0.5425864 ]
  [-0.2622641   0.20779261 -0.17956443 -0.26928607]
  [-0.21332532  0.15675361  0.00754777 -0.49741685]]]

The second tensor has the shape of (1, 160956, 20), it looks like:

> [[[0.00712454 0.00589486 0.00574574 ... 0.00622318 0.00622835 0.00628796]
  [0.00695205 0.00548313 0.00590013 ... 0.00615357 0.00589359 0.00658535]
  [0.00676332 0.00554853 0.00635643 ... 0.00619051 0.00683079 0.00745956]
  ...
  [0.00665498 0.00999384 0.00730069 ... 0.00956927 0.00554023 0.0077102 ]
  [0.00661131 0.0104473  0.00842678 ... 0.01117299 0.00580678 0.00805993]
  [0.00646147 0.01029721 0.00897478 ... 0.01222938 0.00611732 0.00783348]]]

How can I output in the correct form?

**Comment by hgaiser** [comment]
Hi, if you check the README you'll see that your question is answered there.

**Comment by TimeLCJ** [comment]
Thank you very much, I should have seen it, but I forgot it, my fault.
