### ISSUE TITLE
ImportError: cannot import name 'custom_objects'

### ISSUE THREAD

**Issue by Peter-Strain** [fizyr/keras-retinanet#654]
I keep getting the error: 

```
from keras_retinanet.models.resnet import custom_objects
ImportError: cannot import name 'custom_objects'
```
I have followed all the instructions from previous errors with no luck. I am following the readme. 

```
git clone https://github.com/fizyr/keras-retinanet.git
cd keras-retinanet/
pip3 install . --user
```
Have also tried: 

`pip3 install --user --upgrade keras-retinanet`

And uninstalling and reinstalling. Nothing seems to be working. 

This is the line I am trying to run: 

`from keras_retinanet.models.resnet import custom_objects`

Does anyone have any idea how to resolve this issue?

**Comment by Peter-Strain** [comment]
Resolved problem. 

Version 2.0 works due to change in /keras-retinanet-0.2/keras_retinanet/models/retinanet.py script.

**Comment by hgaiser** [comment]
This seems to be custom code? It is a bit outdated, we changed our API since then. Have a look at the [example](https://github.com/fizyr/keras-retinanet/blob/master/examples/ResNet50RetinaNet.ipynb) to see how you can load a model now.
