### ISSUE TITLE
Training depletes all CPU resource.

### ISSUE THREAD

**Issue by YJHMITWEB** [fizyr/keras-retinanet#661]
I use a single GPU on my machine which has 4 GPUs in total,  to train the model. However, it seems that it depletes all CPU resource, and I tried to set the train_generator to workers=0 and use_multiprocess=False, and it did not work. 
There are 32 CPUs on my machine, and I also used `htop` to check it, and turned out it generated more than 30 processes...
I'm using keras 2.1.3 and tensorflow 1.4.0.

**Comment by de-vri-es** [comment]
Note that htop by default shows threads the same was as processes. You can tweak it to show them differently or event not at all. So it's quite possible that you are seeing >30 threads rather than >30 processes.

However, there's no code in `keras-retinanet` that explicitly  makes use of multithreading or multiprocessing. It's quite possible that some dependencies internally do. If you can find out which, and how to configure them not to do so, a PR to control this from `train.py` would be welcome.

**Comment by tmontaigu** [comment]
Generally when training with a model with keras/tensorflow if all the CPUs are used, it means that the
training is not done using your GPUs but with your CPUs instead

**Comment by hgaiser** [comment]
Also, try updating keras-retinanet, Keras, tensorflow, cuda and cudnn. At least your tensorflow is quite old.

**Comment by hgaiser** [comment]
Did you find a fix for your issue?

**Comment by YJHMITWEB** [comment]
Thanks for your help. However, the problem still exists, I re-check it by using different servers and they all have this problem. I've tried different version of Keras(2.1.3, 2.1.5, 2.2.0) and Tensorflow(1.3, 1.4), but still didn't solve it. ~~~~

**Comment by hgaiser** [comment]
Could you try updating tensorflow to 1.10? 1.3 and 1.4 are quite old.

Also, as @tmontaigu mentioned, did you check if it is utilizing the GPU at all?

**Comment by YJHMITWEB** [comment]
Thanks, I'll try to update tensorflow, it may take a while because I also need to update CUDA. And I'm pretty sure it runs on GPU, because GPU usage is about 90% and also because my other projects work perfectly on GPU.

**Comment by hgaiser** [comment]
Did you manage to resolve this?

**Comment by hgaiser** [comment]
Just curious, did you fix the issue?

**Comment by YJHMITWEB** [comment]
It turns out that my tensorflow version was too low,  I upgraded it to 1.9 and no more problem.
But I'm still curious about why it happens in lower version.....
And thanks for your help.
