### ISSUE TITLE
Problem with resizing images 

### ISSUE THREAD

**Issue by ahmedbendebba1** [fizyr/keras-retinanet#662]
Hello,
I am working with your code the Retinanet for a task of object detection.
I have discovered that in your  code, you do resize image to picture to fix them in one size 800*1333.
My question do you do the same to the coordiantes of the bounding boxes . if not, the coordinates of bounding box will not be true . if you do that in which pat in the code , because i didn't succeed to find it 
Thank you

**Comment by LaurensHagendoorn** [comment]
https://github.com/fizyr/keras-retinanet/blob/8f7e7414db193832572773ea503c26edab405b96/keras_retinanet/preprocessing/generator.py#L192

**Comment by ahmedbendebba1** [comment]
Thank you very much
