### ISSUE TITLE
ZeroDivisionError

### ISSUE THREAD

**Issue by MichaelMonashev** [fizyr/keras-retinanet#663]
```
Traceback (most recent call last):
  File "./keras_retinanet/bin/evaluate.py", line 165, in <module>
    main()
  File "./keras_retinanet/bin/evaluate.py", line 161, in main
    print('mAP: {:.4f}'.format(precision / present_classes))
ZeroDivisionError: division by zero
```

**Comment by hgaiser** [comment]
@vcarpani could you look into this?

**Comment by vcarpani** [comment]
@hgaiser sure, will look into this ASAP

**Comment by vcarpani** [comment]
@MichaelMonashev can you post here your classes.txt file and the file containing the list of test images?

**Comment by MichaelMonashev** [comment]
```
> cat classes.txt
cat,0
```
I deleted file containing the list of test images. Sorry.

**Comment by vcarpani** [comment]
I believe that the names in your test list did not match the names in the class.txt files.
Could you try to run it again and double check that?

**Comment by MichaelMonashev** [comment]
average_precisions can be empty. Patch:

-         print('mAP: {:.4f}'.format(precision / present_classes))
+        if present_classes > 0
+               print('mAP: {:.4f}'.format(precision / present_classes))
+        else:
+               print('mAP: 0.0')

**Comment by MichaelMonashev** [comment]
Ok. In this case you can show error "Empty test.csv". But not "Division by zero".

**Comment by vcarpani** [comment]
Sure, I will add a check in the test generator ;)

**Comment by vcarpani** [comment]
Issue addressed, closing.
