### ISSUE TITLE
 unrecognized arguments: --multi-gpu-force --multi-gpu 2

### ISSUE THREAD

**Issue by ramadevsaiteja** [fizyr/keras-retinanet#664]
I am trying to train on two gpus but it's giving following error
![screenshot from 2018-09-07 12-29-01](https://user-images.githubusercontent.com/25078260/45203693-77262200-b26c-11e8-997d-2e8786732677.png)

Also I am using two K40m GPU's. How to find ID of these GPU's? It's mentioned in train.py file we need to pass these ID's as arguments(see line 385, --gpu)

**Comment by hgaiser** [comment]
I don't see the command you executed, but I'm guessing you had these flags at the end? The flags need to be passed before the dataset arguments, so for instance:
```shell
retinanet-train --multi-gpu 2 --multi-gpu-force coco /datasets/COCO
```

**Comment by hgaiser** [comment]
I'm assuming that was your issue. Feel free to re-open if this is still a problem.
