### ISSUE TITLE
Using retinanet as a feature extractor

### ISSUE THREAD

**Issue by ovgeorge** [fizyr/keras-retinanet#665]
I have many objects of the same class (different dogs) which are easily distinguished from each other by a human. I'm thinking about using some of the intermediate layers of model trained to detect dogs as a feature extractor to match against known dogs database. Which layer I should use? I'm thinking about using something after pyramid construction, but still haven't got a full grasp of how network works.

**Comment by yhenon** [comment]
You should use a classification network pretrained on imagenet. Note that imagenet already has approximately 90 classes of dogs, so a network trained on it will be very well suited to the task.

I'll go ahead and close this as it is not an issue with the repo.
