### ISSUE TITLE
No module named keras_resnet

### ISSUE THREAD

**Issue by zbxzc35** [fizyr/keras-retinanet#668]
when I run the command‘keras_retinanet/bin/train.py pascal VOCdevkit2007/VOC2007/’，I got an error：
File "keras_retinanet/bin/../../keras_retinanet/models/resnet.py", line 19, in <module>
    import keras_resnet
ImportError: No module named keras_resnet
where is keras_resnet.py,I don't have.

**Comment by zbxzc35** [comment]
I know,using this command,
pip install keras-retinanet --user
then I can get keras_resnet

**Comment by hgaiser** [comment]
You can also specifically install `keras-resnet`.

```shell
pip install keras-resnet --user
```
