### ISSUE TITLE
Got TypeError: __init__() got an unexpected keyword argument 'freeze_bn'

### ISSUE THREAD

**Issue by ssoulhi** [fizyr/keras-retinanet#67]
Hi 
I got this error when running the line #2 of the Jupyter notebook: ResNet50RetinaNet - Pascal VOC: 

 ---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-2-582d332844ca> in <module>()
      1 image_input = keras.layers.Input((None, None, 3))
----> 2 model = keras_retinanet.models.ResNet50RetinaNet(image_input, num_classes=20, weights='imagenet')
      3 
      4 # compile model
      5 model.compile(

/usr/local/lib/python2.7/dist-packages/keras_retinanet/models/resnet.pyc in ResNet50RetinaNet(inputs, weights, *args, **kwargs)
     34         weights_path = weights
     35 
---> 36     resnet = keras_resnet.models.ResNet50(image, include_top=False, freeze_bn=True)
     37 
     38     model = keras_retinanet.models.retinanet_bbox(inputs=inputs, backbone=resnet, *args, **kwargs)

/usr/local/lib/python2.7/dist-packages/keras_resnet/models/_2d.pyc in ResNet50(inputs, blocks, include_top, classes, *args, **kwargs)
    176         blocks = [3, 4, 6, 3]
    177 
--> 178     return ResNet(inputs, blocks, block=keras_resnet.blocks.bottleneck_2d, include_top=include_top, classes=classes, *args, **kwargs)
    179 
    180 

/usr/local/lib/python2.7/dist-packages/keras_resnet/models/_2d.pyc in ResNet(inputs, blocks, block, include_top, classes, *args, **kwargs)
     80     else:
     81         # Else output each stages features
---> 82         return keras.models.Model(inputs=inputs, outputs=outputs, *args, **kwargs)
     83 
     84 

/usr/local/lib/python2.7/dist-packages/keras/legacy/interfaces.pyc in wrapper(*args, **kwargs)
     85                 warnings.warn('Update your `' + object_name +
     86                               '` call to the Keras 2 API: ' + signature, stacklevel=2)
---> 87             return func(*args, **kwargs)
     88         wrapper._original_function = func
     89         return wrapper

TypeError: __init__() got an unexpected keyword argument 'freeze_bn'

**Comment by hgaiser** [comment]
Check the README for installation instructions.

**Comment by ssoulhi** [comment]
Thanks!
