### ISSUE TITLE
Generator raises IndexError when one image has no annotation

### ISSUE THREAD

**Issue by ecoopnet** [fizyr/keras-retinanet#670]
If train/validation datasets has no annotation ( the annotations become np.array([]) ), 
Generator raises `IndexError: too many indices for array` with assertion.
```
  File "path-to-my-venv/lib/python3.5/site-packages/keras_retinanet/preprocessing/generator.py", line 140, in filter_annotations
    (annotations[:, 2] > image.shape[1]) |
IndexError: too many indices for array
```

My solution is to remove images that have empty annotations.
But I thinks it maybe better to skip checking empty annotation.

**Comment by hgaiser** [comment]
Having no annotations is actually quite useful if you want to add images where your object isn't present. The network will learn that everything in that image should be ignored.

Is this a custom generator? Our generators always return an array of shape `(N, 5)`, so if there are no annotations it will return an [array of shape `(0, 5)`](https://github.com/fizyr/keras-retinanet/blob/master/keras_retinanet/preprocessing/csv_generator.py#L204).

```
In [1]: import numpy as np

In [2]: a = np.zeros((0, 5))

In [3]: a[:, 2] > 0
Out[3]: array([], dtype=bool)
```

**Comment by ecoopnet** [comment]
@hgaiser Thank you for quick answer.
Yes, it is my custom generator. 
My problem was resolved after i fixed it to return np.zeros((0,5)) for no annotations.

I didn't know that having no anotations is so much useful. 
It is very good advice for me.
