### ISSUE TITLE
Wrong function name

### ISSUE THREAD

**Issue by MichaelMonashev** [fizyr/keras-retinanet#671]
https://github.com/fizyr/keras-retinanet/blob/master/keras_retinanet/utils/image.py#L26
```
def read_image_bgr(path):
    """ Read an image in BGR format.
    Args
        path: Path to the image.
    """
    image = np.asarray(Image.open(path).convert('RGB'))
return image[:, :, ::-1].copy()
```

I think read_image_rgb() or just read_image() is better name.

**Comment by hgaiser** [comment]
I could understand `read_image()`, but why `read_image_rgb()`? (the output of the function will be in `BGR` order)

**Comment by MichaelMonashev** [comment]
Sorry. I didn`t see ::-1 .
