### ISSUE TITLE
Some confusion about anchors

### ISSUE THREAD

**Issue by Wang-zipeng** [fizyr/keras-retinanet#672]
I have read the code "generate_anchors(base_size=16, ratios=None, scales=None)" in anchors.py. In the 32 size feature map, It has 32\*32 anchor and the anchor directly compute the overlap with ground-truth. My confusion is that 32 pixel feature map is high hierarchical feature map, is true that directly compute  ground-truth with 32\*32 anchor ? needn't resize the ground-truth from raw image to 32 pixel feature map? Or there is something wrong with my understanding

**Comment by hgaiser** [comment]
I don't quite get your question. The base size is the size of the base anchor **in the original image**, so not in the feature map.
