### ISSUE TITLE
About transfer learning

### ISSUE THREAD

**Issue by raven4752** [fizyr/keras-retinanet#686]
Hi, I want to use outputs of some layers of this model as features for my own image like the use of faster-rcnn in https://github.com/peteanderson80/bottom-up-attention. 
Is it possible?  I have checked some layers, their outputs all have a very large number of features ...

**Comment by hgaiser** [comment]
You could check out https://github.com/fizyr/keras-maskrcnn , it basically does what you're looking for, but uses the features to compute masks.

Assuming this resolves your "issue", I'll close this.
