### ISSUE TITLE
Is it possible to implement a Keras Metric for Mean IoU?

### ISSUE THREAD

**Issue by fernandocamargoti** [fizyr/keras-retinanet#690]
I'm using this implementation in a competition with single class localization. Their metric is mean IoU. I wonder if it's possible to implement it as a Keras Metric. With the training model, is it possible? Or would I need to use the same scheme used in the Evaluate?

**Comment by hgaiser** [comment]
The interface of Keras' metrics is quite limited, it accepts a `y_true` and a `y_pred`. The output of keras-retinanet consists of multiple outputs (boxes and classification values). As far as I know there is no way in Keras to define a metric based on multiple outputs.

**Comment by fernandocamargoti** [comment]
Understood. I'm trying to implement a callback like the Evaluate in my project.

**Comment by hgaiser** [comment]
Adding a callback that prints some evaluation should be possible, but a "Keras metric" isn't possible.

**Comment by JeniaNovellusDx** [comment]
check my custom metrics, it also includes mean IOU for multi class segmentation

https://github.com/JeniaNovellusDx/KerasExtras/blob/master/keras_functions.py

**Comment by felipetobars** [comment]
Hi @fernandocamargoai, were you able to implement the MeanIOU metric for a custom dataset?
