### ISSUE TITLE
train.py import bug

### ISSUE THREAD

**Issue by Pilot2204** [fizyr/keras-retinanet#695]
Hi, 
I have made my own dataset according to the Documentation. Now i want to train it. Therefore i ran the following 
`python ../keras_retinanet/bin/train.py csv anno.csv names.csv`

which returned this Error:
`Traceback (most recent call last):`
  `File "../keras_retinanet/bin/train.py", line 35, in <module>`
`    from .. import layers  # noqa: F401`
`  File "../keras_retinanet/bin\..\..\keras_retinanet\layers\__init__.py", line 1, in <module>`
`    from ._misc import RegressBoxes, UpsampleLike, Anchors, ClipBoxes  # noqa: F401`
`  File "../keras_retinanet/bin\..\..\keras_retinanet\layers\_misc.py", line 19, in <module>`
 `   from ..utils import anchors as utils_anchors`
`  File "../keras_retinanet/bin\..\..\keras_retinanet\utils\anchors.py", line 20, in <module>`
 `   from ..utils.compute_overlap import compute_overlap`
`ImportError: DLL load failed: Couldn't find the module`

What am I doing wrong? I have followed the installation instruction and this folder im currently in when running this is also located the master directory. 
Thank you for your help.

**Comment by hgaiser** [comment]
I think your error might be the windows equivalent of the following from the FAQ:

**I get the error `ModuleNotFoundError: No module named 'keras_retinanet.utils.compute_overlap'`, how do I fix this?** Most likely you are running the code from the cloned repository. This is fine, but you need to compile some extensions for this to work (`python setup.py build_ext --inplace`).

**Comment by Pilot2204** [comment]
Thank you for your reply.
Sadly now i get an error running the suggestet command.
Something like this:
`error: command 'D:\\Programme\\Miniconda3\\Scripts\\gcc.bat' failed with exit status 1`
