### ISSUE TITLE
Can't run setup.py build_ext --inplace

### ISSUE THREAD

**Issue by Pilot2204** [fizyr/keras-retinanet#696]
Sadly now i get an error running the suggestet command.
Something like this:
`error: command 'D:\\Programme\\Miniconda3\\Scripts\\gcc.bat' failed with exit status 1`
`collect2.exe: error: ld returned 1 exit status`

_Originally posted by @Pilot2204 in https://github.com/fizyr/keras-retinanet/issues/695#issuecomment-423843640_

**Comment by hgaiser** [comment]
I can't help you, I've never done this on windows. It's up to you to figure
out how to get it to compile the plugin.
