### ISSUE TITLE
Box color using the --save-path argument for evaluate.py 

### ISSUE THREAD

**Issue by void32** [fizyr/keras-retinanet#699]
Hi
I'm curious about the color for the boxes when using the --save-path argument. According to [this issue](https://github.com/fizyr/keras-retinanet/issues/507), the green boxes are ground truth and yellow boxes are the prediction, but what about red boxes?
I guess it has something to do with the score, but what is the threshold then?

Could you please help me find where the colors are defines in the code?

Cheers

**Comment by hgaiser** [comment]
The colors are determined by the predicted / annotated class : https://github.com/fizyr/keras-retinanet/blob/master/keras_retinanet/utils/eval.py#L105-L106

Which are defined here: https://github.com/fizyr/keras-retinanet/blob/master/keras_retinanet/utils/colors.py
