### ISSUE TITLE
mAP on PASCAL VOC

### ISSUE THREAD

**Issue by mkocabas** [fizyr/keras-retinanet#70]
Have you ever tested on PASCAL VOC? If so, could you share the results?

**Comment by hgaiser** [comment]
Trained on Pascal, yes, evaluated Pascal, nope.

**Comment by mkocabas** [comment]
Could you provide the trained model?

**Comment by hgaiser** [comment]
It was a while back, the architecture has changed since then so the model doesn't work anymore. You can try to transfer weights from the COCO model using PR https://github.com/fchollet/keras/pull/8462 and train a bit further. If I find the time I will do that too, no promises though.

**Comment by mkocabas** [comment]
Got it, thanks!

**Comment by taewookim** [comment]
completely NOOB'y question...

how does RetinaNet compare to RCNN (or faster RCNN or any variations of it) in terms of accuracy and speed?  

how about SEnet (squeeze and extract) ? I believe SEnet came in pretty high (maybe even won several 2017 imagenet categories)

**Comment by yhenon** [comment]
>how does RetinaNet compare to RCNN (or faster RCNN or any variations of it) in terms of accuracy and speed?
how about SEnet (squeeze and extract) ? I believe SEnet came in pretty high (maybe even won several 2017 imagenet categories)

Please don't treat Github issues as a general discussion forum. These exist specifically to report issues with the codebase. There is a #keras-retinanet slack on the keras slack for such things: https://keras-slack-autojoin.herokuapp.com/

**Comment by hgaiser** [comment]
[Here](https://delftrobotics-my.sharepoint.com/personal/h_gaiser_fizyr_com/_layouts/15/guestaccess.aspx?docid=0a6c3e58c25794f49b8732c1d4957d0f6&authkey=AdUWXBVSBPM1HlvHKARsQXk&expiration=2017-12-20T10%3A36%3A55.000Z&e=ec065e69d3b947338614a18967281743) is a model I trained on Pascal VOC. I didn't benchmark it since I don't have the tools to do so, but feel free to use / test it.

**Comment by huangcong77** [comment]
Did you train this model on VOC2007 or VOC2007+12？
