### ISSUE TITLE
errors out during Training when passed with --val_annotations and --config 

### ISSUE THREAD

**Issue by shivareddy37** [fizyr/keras-retinanet#701]
When you pass --val_annotations and --config file it errors out when trying to compute the mAP on the val set. I made sure that was the issue because it works fine when I don't use val set.
I will investigate the issue further but i guess what is happening is when predict on batch is being called from trains anchors are not being passed hence the same mismatch.

**Comment by shivareddy37** [comment]
The steps to reproduce the error are pretty simple, In the code leave the anchors as default 
pass a config file with diffrent anchors and pass a --val_annoations while training

**Comment by hgaiser** [comment]
@enricoliscio could you check this out?

**Comment by hgaiser** [comment]
PR #705 should've fixed this issue, so closing.
