### ISSUE TITLE
Would you please help me add custom image in tensorboard？

### ISSUE THREAD

**Issue by Diligentfight** [fizyr/keras-retinanet#703]
Hi，bro.  Could you please add custom image(like feature map) add in tensorboard. Or just teach me how to use callback to add feature map or result in tensorboard event. Thanks very much.

**Comment by hgaiser** [comment]
There's a PR for this: https://github.com/fizyr/keras-retinanet/pull/524 but I haven't looked at it in a while. Feel free to leave your feedback there.

Closing this as it is not an issue with the codebase.
