### ISSUE TITLE
mAP is 0 after changing anchor ratio

### ISSUE THREAD

**Issue by paulcx** [fizyr/keras-retinanet#714]
I followed several issues and modified the retinanet.py for supporting additional anchors. I have not upgrade to the PR version but I believe that the following hard codes should work for now.

AnchorParameters.default = AnchorParameters(
    sizes=[32,64,128,256,512],
    strides=[8,16,32, 64,128],
    ratios=np.array([0.4, 0.8, 1,1.2, 3, 5], keras.backend.floatx()),
    scales=np.array([2 ** 0, 2 ** (1.0 / 3.0), 2 ** (2.0 / 3.0)], keras.backend.floatx()),
)

however, the mAP is always 0 after this changes. I wonder if anyone has same issue or can help.

Thanks!

**Comment by hgaiser** [comment]
Changing the anchors is a complicated process where mistakes are easily made. I suggest trying the latest version with anchors configuration build into retinanet. If there are issues with that, feel free to report those.
