### ISSUE TITLE
issues in utils/image.py/read_image_bgr

### ISSUE THREAD

**Issue by cl2227619761** [fizyr/keras-retinanet#716]
the RGB --> BGR, are you sure the code is doing this?

`def read_image_bgr(path):
    image = np.asarray(Image.open(path).convert('RGB'))  # is this right?
    return image[:, :, ::-1].copy()`

**Comment by hgaiser** [comment]
Pretty sure, yeah. Do you think it doesn't?

**Comment by hgaiser** [comment]
Closing this as I don't think it's an issue.

**Comment by dlwogns0128** [comment]
I don't know why you just use "cv2.imread(path)" ?

The cv2 module is imported in image.py and opencv read image in BGR color space as a default.
Also the return type of imread function is numpy ndarray.

Thank you!

**Comment by hgaiser** [comment]
Added a comment in the code for this, we get this question more often.
https://github.com/fizyr/keras-retinanet/blob/master/keras_retinanet/utils/image.py#L31
