### ISSUE TITLE
Changing the training score threshold

### ISSUE THREAD

**Issue by baljit92** [fizyr/keras-retinanet#718]
Where can I set the score_threshold for my training? Is it possible to change this threshold to, say 0.6?

**Comment by hgaiser** [comment]
The training procedure doesn't require a score threshold, the evaluation does. The evaluation during training can't be configured, but the score_threshold in `evaluate.py` can be configured.

Closing this as it is not an issue with the code base. Please use the Slack channel for further discussions.
