### ISSUE TITLE
issue of debug.py

### ISSUE THREAD

**Issue by tongluoiupui** [fizyr/keras-retinanet#722]
I got all -1 in the box result after following `model.predict_on_batch()` in the example ipynb file.
before that I can convert my training_model to predict model without error, but no bbox obtained in test images stage, got all -1.

I use debug.py like this: 
`python keras_retinanet/bin/debug.py csv  /path/to/my_annotation.txt  /path/to/class_map.csv`
the error is:
: cannot connect to X server 

could anyone please help me ?

**Comment by hgaiser** [comment]
Let's discuss this further on the Slack channel. The issues are reserved for code based issues.

**Comment by matbord** [comment]
> 
> 
> I got all -1 in the box result after following `model.predict_on_batch()` in the example ipynb file.
> before that I can convert my training_model to predict model without error, but no bbox obtained in test images stage, got all -1.
> 
> I use debug.py like this:
> `python keras_retinanet/bin/debug.py csv /path/to/my_annotation.txt /path/to/class_map.csv`
> the error is:
> : cannot connect to X server
> 
> could anyone please help me ?

I have the same error when I'm running the debug.py file. I'm running it on GoogleColab.
How did you solve it?
