### ISSUE TITLE
How to use evaluate with model argument?

### ISSUE THREAD

**Issue by tongluoiupui** [fizyr/keras-retinanet#723]
I try to evaluate with my data and model, but the model argument has error. I can use `csv` in my training, but, is the arguments `model` and `--convert-model` correct in their format? Thanks.

`keras_retinanet/bin/evaluate.py  --convert-model  csv /path/to/xyxy_class1_eval_jpg.csv   /path/to/cls.csv   model   /path/to/saved_resnet50_csv_40.h5`

the error is:
Using TensorFlow backend.
usage: evaluate.py [-h] [--convert-model] [--backbone BACKBONE] [--gpu GPU]
                   [--score-threshold SCORE_THRESHOLD]
                   [--iou-threshold IOU_THRESHOLD]
                   [--max-detections MAX_DETECTIONS] [--save-path SAVE_PATH]
                   [--image-min-side IMAGE_MIN_SIDE]
                   [--image-max-side IMAGE_MAX_SIDE] [--config CONFIG]
                   [--weighted-average]
                   {coco,pascal,csv} ... model
evaluate.py: error: unrecognized arguments: model

**Comment by hgaiser** [comment]
You don't need to mention `model` in the command, it should be replaced with the path to your model.

**Comment by tongluoiupui** [comment]
it works now, thank you.
