### ISSUE TITLE
one class detection got nothing detected?

### ISSUE THREAD

**Issue by MLikelihood** [fizyr/keras-retinanet#724]
Hi there, 

I followed the steps to train retinanet with resnet backbone, my own dataset is in csv format. 

after 18 epochs, loss: 0.7437 - regression_loss: 0.3878 - classification_loss: 0.3558

but the labels predicted are all -1, and box coordinates are all -2. sore -1. 

How should I solve this problem? 

Thank you!

**Comment by MLikelihood** [comment]
@hgaiser

**Comment by MLikelihood** [comment]
My image size is 1024*1024 and I specify both the min side and max side to 512. 
In prediction, I also changed the size to be 512*512. 

Other than that, I barely changed anything. I ran the debug.py. It seems most of the boxes are green.

**Comment by MLikelihood** [comment]
# load retinanet model
model_path = os.path.join('./keras-retinanet/', 'snapshots', 'resnet101_epoch18.h5')
model = models.load_model(model_path, backbone_name='resnet101',convert=True)

IndexError                                Traceback (most recent call last)
<ipython-input-11-58ad454be12a> in <module>()
      4 
      5 # load retinanet model
----> 6 model = models.load_model(model_path, backbone_name='resnet101',convert=True)
      7 
      8 # if the model is not converted to an inference model, use the line below

~/.conda/envs/TFGPU18py36/lib/python3.6/site-packages/keras_retinanet/models/__init__.py in load_model(filepath, backbone_name, convert, nms, class_specific_filter, anchor_params)
     85     if convert:
     86         from .retinanet import retinanet_bbox
---> 87         model = retinanet_bbox(model=model, nms=nms, class_specific_filter=class_specific_filter, anchor_params=anchor_params)
     88 
     89     return model

~/.conda/envs/TFGPU18py36/lib/python3.6/site-packages/keras_retinanet/models/retinanet.py in retinanet_bbox(model, nms, class_specific_filter, name, anchor_params, **kwargs)
    343         class_specific_filter = class_specific_filter,
    344         name                  = 'filtered_detections'
--> 345     )([boxes, classification] + other)
    346 
    347     outputs = detections

~/.conda/envs/TFGPU18py36/lib/python3.6/site-packages/keras/engine/base_layer.py in __call__(self, inputs, **kwargs)
    458             # Actually call the layer,
    459             # collecting output(s), mask(s), and shape(s).
--> 460             output = self.call(inputs, **kwargs)
    461             output_mask = self.compute_mask(inputs, previous_mask)
    462 

~/.conda/envs/TFGPU18py36/lib/python3.6/site-packages/keras_retinanet/layers/filter_detections.py in call(self, inputs, **kwargs)
    177             elems=[boxes, classification, other],
    178             dtype=[keras.backend.floatx(), keras.backend.floatx(), 'int32'] + [o.dtype for o in other],
--> 179             parallel_iterations=self.parallel_iterations
    180         )
    181 

~/.conda/envs/TFGPU18py36/lib/python3.6/site-packages/keras_retinanet/backend/tensorflow_backend.py in map_fn(*args, **kwargs)
     33     """ See https://www.tensorflow.org/versions/master/api_docs/python/tf/map_fn .
     34     """
---> 35     return tensorflow.map_fn(*args, **kwargs)
     36 
     37 

~/.conda/envs/TFGPU18py36/lib/python3.6/site-packages/tensorflow/python/ops/functional_ops.py in map_fn(fn, elems, dtype, parallel_iterations, back_prop, swap_memory, infer_shape, name)
    457         back_prop=back_prop,
    458         swap_memory=swap_memory,
--> 459         maximum_iterations=n)
    460     results_flat = [r.stack() for r in r_a]
    461 

~/.conda/envs/TFGPU18py36/lib/python3.6/site-packages/tensorflow/python/ops/control_flow_ops.py in while_loop(cond, body, loop_vars, shape_invariants, parallel_iterations, back_prop, swap_memory, name, maximum_iterations)
   3207     if loop_context.outer_context is None:
   3208       ops.add_to_collection(ops.GraphKeys.WHILE_CONTEXT, loop_context)
-> 3209     result = loop_context.BuildLoop(cond, body, loop_vars, shape_invariants)
   3210     if maximum_iterations is not None:
   3211       return result[1]

~/.conda/envs/TFGPU18py36/lib/python3.6/site-packages/tensorflow/python/ops/control_flow_ops.py in BuildLoop(self, pred, body, loop_vars, shape_invariants)
   2939       with ops.get_default_graph()._lock:  # pylint: disable=protected-access
   2940         original_body_result, exit_vars = self._BuildLoop(
-> 2941             pred, body, original_loop_vars, loop_vars, shape_invariants)
   2942     finally:
   2943       self.Exit()

~/.conda/envs/TFGPU18py36/lib/python3.6/site-packages/tensorflow/python/ops/control_flow_ops.py in _BuildLoop(self, pred, body, original_loop_vars, loop_vars, shape_invariants)
   2876         flat_sequence=vars_for_body_with_tensor_arrays)
   2877     pre_summaries = ops.get_collection(ops.GraphKeys._SUMMARY_COLLECTION)  # pylint: disable=protected-access
-> 2878     body_result = body(*packed_vars_for_body)
   2879     post_summaries = ops.get_collection(ops.GraphKeys._SUMMARY_COLLECTION)  # pylint: disable=protected-access
   2880     if not nest.is_sequence(body_result):

~/.conda/envs/TFGPU18py36/lib/python3.6/site-packages/tensorflow/python/ops/control_flow_ops.py in <lambda>(i, lv)
   3177         cond = lambda i, lv: (  # pylint: disable=g-long-lambda
   3178             math_ops.logical_and(i < maximum_iterations, orig_cond(*lv)))
-> 3179         body = lambda i, lv: (i + 1, orig_body(*lv))
   3180 
   3181     if context.executing_eagerly():

~/.conda/envs/TFGPU18py36/lib/python3.6/site-packages/tensorflow/python/ops/functional_ops.py in compute(i, tas)
    446       """
    447       packed_values = input_pack([elem_ta.read(i) for elem_ta in elems_ta])
--> 448       packed_fn_values = fn(packed_values)
    449       nest.assert_same_structure(dtype or elems, packed_fn_values)
    450       flat_fn_values = output_flatten(packed_fn_values)

~/.conda/envs/TFGPU18py36/lib/python3.6/site-packages/keras_retinanet/layers/filter_detections.py in _filter_detections(args)
    169                 score_threshold       = self.score_threshold,
    170                 max_detections        = self.max_detections,
--> 171                 nms_threshold         = self.nms_threshold,
    172             )
    173 

~/.conda/envs/TFGPU18py36/lib/python3.6/site-packages/keras_retinanet/layers/filter_detections.py in filter_detections(boxes, classification, other, class_specific_filter, nms, score_threshold, max_detections, nms_threshold)
     72         all_indices = []
     73         # perform per class filtering
---> 74         for c in range(int(classification.shape[1])):
     75             scores = classification[:, c]
     76             labels = c * backend.ones((keras.backend.shape(scores)[0],), dtype='int64')

~/.conda/envs/TFGPU18py36/lib/python3.6/site-packages/tensorflow/python/framework/tensor_shape.py in __getitem__(self, key)
    613         return TensorShape(self._dims[key])
    614       else:
--> 615         return self._dims[key]
    616     else:
    617       if isinstance(key, slice):

IndexError: list index out of range

**Comment by MLikelihood** [comment]
>  The last error indicates your trying to convert an already converted model. Try loading the model without convert=True.



I tried to convert the checkpoint file and load the converted model, it didn't give any predictions. 
I tried to run evaluate.py, but the mean average precision is 0.
Then I tried to load the original checkpoint with "convert=True', it gives the above indexError. 

I tried to check the output of the  csv generator, all the properties are correct, except that after preprocess in caffe mode, a random image (800*800) numpy array mean is 7, not zero. 
The image I tried to predict has mean 19.50056, 6.6605635, -0.24043608 for threee channels. 
 
So, I guess maybe there is array dimension problem somewhere, that would restricts 1 class detection? Or the caffe preprocess is not suitable for this dataset?

**Comment by MLikelihood** [comment]
@hgaiser

**Comment by hgaiser** [comment]
Please don't spam like that, it's quite rude.

I'm guessing you aren't preprocessing your image the same as how it is trained, check out the example to see how your images should be preprocessed for testing.

I'm closing this as it is not an issue with the code. Please continue further discussions on Slack.
