### ISSUE TITLE
question about mAP always 0 in the validation

### ISSUE THREAD

**Issue by tongluoiupui** [fizyr/keras-retinanet#726]
After I have new installation of  RetinaNet, I used default `resnet50` and let code download resent50 .h5 model from https://github.com/fizyr/keras-models/releases/, and I also used validation during training, but the `mAP` is always 0 since the first epoch.  So I use debug.py to check, it can show bbox in my data.  There is no bbox shown after I converted to inference h5 model and use predication like ipynb example file.

The data is from my own dicom images, I converted into jpg before training, `regression_acc` is above 0.3, but `mAP` = 0. 

For this issue, if debug is OK but validation is wrong, where I can start to figure out the problem? from image preprocessing, like coffe mode or tf mode(I tested but not works), some thresholding in the code ? or how to use debug to check what's wrong in the evaluation?

**Comment by tongluoiupui** [comment]
I train very tiny data, only several images, then I can get mAP improved from zero, the preprocessing mode is caffe, may tf is applied to different image, but when using large training data, after some hyperparam changed for different experiments, the mAP are not improved, in most cases they are still zero. Did it take long epochs to wait for mAP improvement?

**Comment by xcaizewu** [comment]
@tongluoiupui Hello, have you found a solution to solve voc 2007 training mAP=0?
