### ISSUE TITLE
How to add learning rate in tensorboard  by using keras.callbacks.TensorBoard()

### ISSUE THREAD

**Issue by tongluoiupui** [fizyr/keras-retinanet#729]
In the `train.py`,  I defined a function custom_log_func(), calling it by tbCallback,  and finally inserted into the list of callbacks. the error is relevant to function arguments. I don't know how to input epoch, logs arguments here in the 'def create_callbacks()', although I can add some code to save `lr` in `def on_epoch_end()` in `common.py` file, but it's better to modify code for the tensorboard.

`def create_callbacks(model, training_model, prediction_model, validation_generator, args):
    """ Creates the callbacks to use during training.

    Args
        model: The base model.
        training_model: The model that is used for training.
        prediction_model: The model that should be used for validation.
        validation_generator: The generator for creating validation data.
        args: parseargs args object.

    Returns:
        A list of callbacks used for training.
    """
    callbacks = []

    tensorboard_callback = None
    base_subpath = args.base_subpath # get_sublog_name_now( )

    def custom_log_func( self, tensorboard, epoch, logs = None ):
        """Add the custom logs to tensorboard. This function is executed at the end of each epoch."""

        # Add learning rate
        optimizer = tensorboard.model.optimizer
        learning_rate = K.eval( model.optimizer.lr)  # Calculate learning rate per epoch here

        return {
            "learning_rate": learning_rate
            }
    tbCallback = keras.callbacks.TensorBoard( log_dir = os.path.join(args.tensorboard_dir,args.base_subpath ),custom_log_func = custom_log_func())

   
    if args.tensorboard_dir:

        tensorboard_callback = keras.callbacks.TensorBoard(
            log_dir                = os.path.join( args.tensorboard_dir, args.base_subpath ),
            histogram_freq         = 0,
            batch_size             = args.batch_size,
            write_graph            = True,
            write_grads            = False,
            write_images           = False,
            embeddings_freq        = 0,
            embeddings_layer_names = None,
            embeddings_metadata    = None,

        )
        callbacks.append(tensorboard_callback)
        callbacks.append(tbCallback)
       
`

Then, got the error:
`  File "keras_retinanet/bin/train_useacc.py", line 161, in create_callbacks
    custom_log_func = custom_log_func())
TypeError: custom_log_func() takes at least 3 arguments (0 given)
`

**Comment by hgaiser** [comment]
Couple of things:
- Your `custom_log_func` takes a `self` argument, why? It's not inside a class.
- You should pass `custom_log_func` without parenthesis, now it is trying to execute it.
- I'm closing this issue as it is not an issue with the code. Please use the Slack channel for questions about usage.
