### ISSUE TITLE
how to change bacth size in train.py for csv version data 

### ISSUE THREAD

**Issue by muhammetp** [fizyr/keras-retinanet#732]
could you explain why  bacth size doenst change even if i change steps_per_Epoch in train.py for csv version data. if there is not relation, how can i change batch size for each step

**Comment by hgaiser** [comment]
One step processes one batch. Changing the number of steps does **not** change the batch size. You can change the batch size with `--batch-size`.

**Comment by muhammetp** [comment]
but where is --batch size i have to update

**Comment by muhammetp** [comment]
further more is this only valid for gpu ? because i run on only cpu. i dont have gpu

**Comment by muhammetp** [comment]
how do i assure that all data are spanned when the batch size is changed

**Comment by ShibaPrasad** [comment]
Hi,
Are you able to figure out how to deal with different batch sizes. the default:

parser.add_argument('--epochs',           help='Number of epochs to train.', type=int, default=50)
parser.add_argument('--steps', help='Number of steps per epoch.', type=int, default=10000)

In my case I have only around 5200 images and need to put it in batches.

Any comments ???
