### ISSUE TITLE
File structure for the coco dataset?

### ISSUE THREAD

**Issue by alexiskattan** [fizyr/keras-retinanet#74]
I'm trying to get the coco and dataset to be read by the sample program.  I got the pascal one working ok!

When I train the coco one I get an error saying `"AttributeError: 'NoneType' object has no attribute 'astype'"` which I **think** is caused by it reading something weird.

I think I'm having trouble with getting the right file structure to work.  For coco2017 how should the annotations, test2017, train2017, val2017 folders be laid out?

**Comment by hgaiser** [comment]
Follow these instructions:

https://github.com/cocodataset/cocoapi/blob/master/README.txt

**Comment by jwnsu** [comment]
The following structure works for me:
  data/coco:
       annotations
       images

**Comment by hgaiser** [comment]
Did this resolve your issue?
