### ISSUE TITLE
First Inference slow and memory intensive

### ISSUE THREAD

**Issue by ErnstTmp** [fizyr/keras-retinanet#747]
Hello, 
I am using a Retinanet with a resnet 152 backbone.
My training Model has 816 MB, the inference model 274 MB (I expected the inference models to be bigger)

When I run inference on several images (predict_on_batch with a batch size of 1), the inference on the first image takes almost 14 minutes, while all the following images are treated in less than 1 second.

During the first inference, Python is on 100 % CPU (1 core), the GPU is empty, and the python jobs takes up to 61 GB RAM (the machine has 132 GB).

What is going on here, and how can I improve this?

Thank you very much for your help,
Ernst

**Comment by hgaiser** [comment]
Are you using a GPU or CPU for the computations? The first one is always slower, but 14 minutes is quite insane. My tips:

- (assuming you're using a tensorflow from a package manager, like pip maybe) install tensorflow 1.11 from source
- try running the code with the `TF_CUDNN_USE_AUTOTUNE=0` environment flag set.

**Comment by ErnstTmp** [comment]
Hi Hans,
thank you very much for your fast help and excuse my late answer - I got some eye injury, and needed some time to recover.

As you suggested, I installed Tensorflow 1.11 from source,  and now everything runs in 0,25 sec per image, even the first one.

Thank you very much!!!
Kind regards
Ernst

**Comment by Hanko666** [comment]
> Hi Hans,
> thank you very much for your fast help and excuse my late answer - I got some eye injury, and needed some time to recover.
> 
> As you suggested, I installed Tensorflow 1.11 from source, and now everything runs in 0,25 sec per image, even the first one.
> 
> Thank you very much!!!
> Kind regards
> Ernst

hi, did you resolve this issue by setting TF_CUDNN_USE_AUTOTUNE=0? 
Thanks.
