### ISSUE TITLE
Inference time too slow

### ISSUE THREAD

**Issue by prateethvnayak** [fizyr/keras-retinanet#750]
I have been using the following config for normal demo implementation on resent50 backbone (as in jupyter notebook)
cudNN version - 9
tensorflow - 1.8

It seems that the tensorflow session does not detect any GPU and the inference is taking place on CPU with a awful speed of 380s per image.

Any thoughts ? 

I am running on Anaconda dist environment python3.6.

**Comment by hgaiser** [comment]
Did you install tensorflow-gpu? Does `nvidia-smi` show GPUs?

Regardless, this isn't really an issue for keras-retinanet, so I'm closing it.

**Comment by prateethvnayak** [comment]
> Did you install tensorflow-gpu? Does `nvidia-smi` show GPUs?
> 
> Regardless, this isn't really an issue for keras-retinanet, so I'm closing it.

Yes, I have installed conda tensorflow-gpu and nvidia-smi shows gpu but no processes running during the inference.
