### ISSUE TITLE
How to speed up using small images ?

### ISSUE THREAD

**Issue by yihchu** [fizyr/keras-retinanet#751]
I tested 480*850 images with default parameters(image-min-side = 800 and 'image-max-side = 1333), and it cost about 70-90ms per image. And then i change 'image-min-side' and 'image-max-side' to 400 and 666(for i want to speed it up), it still cost about 80ms per image using nvidia 1080ti. 

Also, both (800, 1333) and (400, 666) occupied about 7G graphic memory，so i suspect the image was still resized to (800, 1333).

I want to ask if there is other parameters need to change in train.py or convert.py. Or the speed and gpu memory has nothing to do with image's size?

**Comment by hgaiser** [comment]
If you want to be absolutely sure the resizing is done as you expect it, you can print the size of the inputs [here](https://github.com/fizyr/keras-retinanet/blob/master/keras_retinanet/preprocessing/generator.py#L302).

Also, for a small boost, try prepending your command with `LD_PRELOAD="/usr/lib/libtcmalloc.so"` (you might need to install some package for libtcmalloc.so, but Google can help you there).

Closing this as it isn't an issue with the code. For further discussions, please use Slack.
