### ISSUE TITLE
occur error with python setup.py build_ext --inplace running build_ext

### ISSUE THREAD

**Issue by yinggo** [fizyr/keras-retinanet#758]
environment: python 2.7; keras 2.4; 
I have followed the instruction, but when I run the train.py, I meet some error, please help.
`$ pip install . --user`
`
Processing /home/ds1/Downloads/keras-retinanet`
 ` Requirement already satisfied (use --upgrade to upgrade): keras-retinanet===0.5.0 from file:///home/ds1/Downloads/keras-retinanet in /home/ds1/.local/lib/python2.7/site-packages
`
`Requirement already satisfied (use --upgrade to upgrade): keras in /home/ds1/.local/lib/python2.7/site-packages (from keras-retinanet===0.5.0)
`
`Requirement already satisfied (use --upgrade to upgrade): keras-resnet in /home/ds1/.local/lib/python2.7/site-packages (from keras-retinanet===0.5.0)
`
`Requirement already satisfied (use --upgrade to upgrade): six in /home/ds1/.local/lib/python2.7/site-packages (from keras-retinanet===0.5.0)
`
`Requirement already satisfied (use --upgrade to upgrade): scipy in /home/ds1/.local/lib/python2.7/site-packages (from keras-retinanet===0.5.0)
`
`Requirement already satisfied (use --upgrade to upgrade): cython in /home/ds1/.local/lib/python2.7/site-packages (from keras-retinanet===0.5.0)
`
`Requirement already satisfied (use --upgrade to upgrade): Pillow in /home/ds1/.local/lib/python2.7/site-packages (from keras-retinanet===0.5.0)
`
`Requirement already satisfied (use --upgrade to upgrade): opencv-python in /home/ds1/.local/lib/python2.7/site-packages (from keras-retinanet===0.5.0)
`
`Requirement already satisfied (use --upgrade to upgrade): progressbar2 in /home/ds1/.local/lib/python2.7/site-packages (from keras-retinanet===0.5.0)
`
`Requirement already satisfied (use --upgrade to upgrade): keras-preprocessing>=1.0.5 in /home/ds1/.local/lib/python2.7/site-packages (from keras->keras-retinanet===0.5.0)
`
`Requirement already satisfied (use --upgrade to upgrade): numpy>=1.9.1 in /home/ds1/.local/lib/python2.7/site-packages (from keras->keras-retinanet===0.5.0)
`
`Requirement already satisfied (use --upgrade to upgrade): pyyaml in /home/ds1/.local/lib/python2.7/site-packages (from keras->keras-retinanet===0.5.0)
`
`Requirement already satisfied (use --upgrade to upgrade): h5py in /home/ds1/.local/lib/python2.7/site-packages (from keras->keras-retinanet===0.5.0)
`
`Requirement already satisfied (use --upgrade to upgrade): keras-applications>=1.0.6 in /home/ds1/.local/lib/python2.7/site-packages (from keras->keras-retinanet===0.5.0)`
`Requirement already satisfied (use --upgrade to upgrade): python-utils>=2.3.0 in /home/ds1/.local/lib/python2.7/site-packages (from progressbar2->keras-retinanet===0.5.0)
`

`$ keras_retinanet/bin/train.py --help
Using TensorFlow backend.`
`Traceback (most recent call last):
  File "keras_retinanet/bin/train.py", line 35, in <module>
    from .. import layers  # noqa: F401`
`  File "keras_retinanet/bin/../../keras_retinanet/layers/__init__.py", line 1, in <module>
    from ._misc import RegressBoxes, UpsampleLike, Anchors, ClipBoxes  # noqa: F401`
`  File "keras_retinanet/bin/../../keras_retinanet/layers/_misc.py", line 19, in <module>
    from ..utils import anchors as utils_anchors`
`  File "keras_retinanet/bin/../../keras_retinanet/utils/anchors.py", line 20, in <module>
    from ..utils.compute_overlap import compute_overlap`
`ImportError: No module named compute_overlap
`

`python setup.py build_ext --inplace
running build_ext`
`cythoning keras_retinanet/utils/compute_overlap.pyx to keras_retinanet/utils/compute_overlap.c
Traceback (most recent call last):`
`  File "setup.py", line 33, in <module>
    setup_requires = ["cython>=0.28"]`
`  File "/home/ds1/.local/lib/python2.7/site-packages/setuptools/__init__.py", line 131, in setup
    return distutils.core.setup(**attrs)`
`  File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()`
`  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)`
`  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()`
`  File "/home/ds1/.local/lib/python2.7/site-packages/setuptools/command/build_ext.py", line 78, in run
    _build_ext.run(self)`
`  File "/home/ds1/.local/lib/python2.7/site-packages/Cython/Distutils/old_build_ext.py", line 186, in run
    _build_ext.build_ext.run(self)`
`  File "/usr/lib/python2.7/distutils/command/build_ext.py", line 339, in run
    self.build_extensions()`
`  File "/home/ds1/.local/lib/python2.7/site-packages/Cython/Distutils/old_build_ext.py", line 193, in build_extensions
    ext.sources = self.cython_sources(ext.sources, ext)`
`  File "/home/ds1/.local/lib/python2.7/site-packages/Cython/Distutils/old_build_ext.py", line 346, in cython_sources
    full_module_name=module_name)`
`  File "/home/ds1/.local/lib/python2.7/site-packages/Cython/Compiler/Main.py", line 776, in compile
    return compile_single(source, options, full_module_name)`
`  File "/home/ds1/.local/lib/python2.7/site-packages/Cython/Compiler/Main.py", line 725, in compile_single
    return run_pipeline(source, options, full_module_name)`
`  File "/home/ds1/.local/lib/python2.7/site-packages/Cython/Compiler/Main.py", line 477, in run_pipeline
    context = options.create_context()`
`  File "/home/ds1/.local/lib/python2.7/site-packages/Cython/Compiler/Main.py", line 595, in create_context
    self.cplus, self.language_level, options=self)`
`  File "/home/ds1/.local/lib/python2.7/site-packages/Cython/Compiler/Main.py", line 78, in __init__
    from . import Builtin, CythonScope`
`  File "/home/ds1/.local/lib/python2.7/site-packages/Cython/Compiler/CythonScope.py", line 5, in <module>
    from .UtilityCode import CythonUtilityCode`
`  File "/home/ds1/.local/lib/python2.7/site-packages/Cython/Compiler/UtilityCode.py", line 3, in <module>
    from .TreeFragment import parse_from_strings, StringParseContext`
`  File "/home/ds1/.local/lib/python2.7/site-packages/Cython/Compiler/TreeFragment.py", line 17, in <module>
    from .Visitor import VisitorTransform`
`  File "Cython/Compiler/Visitor.py", line 17, in init Cython.Compiler.Visitor`
`  File "/home/ds1/.local/lib/python2.7/site-packages/Cython/Compiler/ExprNodes.py", line 46, in <module>`
`   from .Pythran import (to_pythran, is_pythran_supported_type, is_pythran_supported_operation_type,`
ImportError: cannot import name pythran_is_numpy_func_supported
`

update:
I have used pip to install pythran
`        $> sudo apt-get install libatlas-base-dev`
`        $> sudo apt-get install python-dev python-ply python-networkx python-numpy`

` 
		$> pip install pythran`
Still get the same error..

**Comment by hgaiser** [comment]
Did you check the FAQ?

**Comment by yinggo** [comment]
> Did you check the FAQ?

yes, if I run `python setup.py build_ext --inplace` this, I will get `ImportError: cannot import name pythran_is_numpy_func_supported`

**Comment by hgaiser** [comment]
It seems you have an issue with numpy or python, not with keras-retinanet. You might want to start from a clean python installation and make sure that the `build_ext` command finishes successfully.
