### ISSUE TITLE
TypeError: __init__() missing 1 required positional argument: 'freeze'

### ISSUE THREAD

**Issue by fahaihappy** [fizyr/keras-retinanet#76]
I got the typeerror at     model = keras.models.load_model('../snapshots/resnet50_coco_best_v1.0.0.h5',
 custom_objects=custom_objects), can anyone give me some advice?

**Comment by hgaiser** [comment]
What type error are you getting? It could be because you are using an outdated COCO model.

**Comment by zbsean** [comment]
I have same error. when test image. I set model = keras.models.load_model('../model/best_resnet50_weights.h5', custom_objects=custom_objects).
show error: TypeError: ('Keyword argument not understood:', 'freeze')

**Comment by hgaiser** [comment]
Are you using the `master` version of keras-resnet ?

**Comment by fahaihappy** [comment]
Thank you！！！I use the weights resnet50_coco_best_v1.2.0.h5 which download from README and it works.

**Comment by coldgemini** [comment]
I'm trying to load_weights from my customized network and it report the same issue: TypeError: __init__() missing 1 required positional argument: 'freeze'.
Do you know what is causing this and where to modify the code so as to fix it?
Folowing the standard README flow I didn't get any error though.

**Comment by coldgemini** [comment]
just fixed the issue by add custom_objects inside the resnet.py file instead of inisde of my prediction scripts, so that the batchnorm doesn't get overwritten

custom_objects = retinanet.custom_objects.copy()
custom_objects.update(mobilenet.custom_objects)
custom_objects.update(keras_resnet.custom_objects)

**Comment by XupingZHENG** [comment]
@coldgemini did you work on the mobilenet backbone for retina net? I use my own dataset to train retinanet with mobilenet backbone, everything is ok. But in evaluation I got 
TypeError: __init__() missing 1 required positional argument: 'freeze'
the call stack is almost the same as your previous comment
I follow your instruction to modify the resnet.py, the same error still occurs.

**Comment by ankitshekhawat** [comment]
@XupingZHENG  you need to initiate the mobile net model like this...

```
from keras_retinanet.models import retinanet
from keras.applications.mobilenet import  relu6, DepthwiseConv2D

mobile_net_custom_objects = {
    'relu6': relu6,
    'DepthwiseConv2D': DepthwiseConv2D
}

custom_objects = retinanet.custom_objects.copy()
custom_objects.update(mobile_net_custom_objects)

model_path = os.path.join('.', 'mobilenet128_1.0_csv_03.h5')

# load mobilenet model
model = keras.models.load_model(model_path, custom_objects=custom_objects)```

**Comment by hgaiser** [comment]
> @XupingZHENG you need to initiate the mobile net model like this...
> 
> from keras_retinanet.models import retinanet
> from keras.applications.mobilenet import  relu6, DepthwiseConv2D
> 
> mobile_net_custom_objects = {
>     'relu6': relu6,
>     'DepthwiseConv2D': DepthwiseConv2D
> }
> 
> custom_objects = retinanet.custom_objects.copy()
> custom_objects.update(mobile_net_custom_objects)
> 
> model_path = os.path.join('.', 'mobilenet128_1.0_csv_03.h5')
> 
> # load mobilenet model
> model = keras.models.load_model(model_path, custom_objects=custom_objects)```

Actually this should be enough:

```python
import keras
from keras_retinanet.models.mobilenet import custom_objects

model = keras.models.load_model('/path/to/model.h5', custom_objects=custom_objects)
```

**Comment by XupingZHENG** [comment]
@ankitshekhawat @hgaiser 
thanks, evaluate.py works fine now

**Comment by Ezereal** [comment]
@ankitshekhawat My retinanet don't have attribute 'custom_objects'. what should I do? Thank you.
