### ISSUE TITLE
Multiple boxes for one category in testing

### ISSUE THREAD

**Issue by MAXycccc** [fizyr/keras-retinanet#764]
At first, thank you for your kind sharing.
I met a weird result when I was using pascal voc 2007 database for training and testing. For faster result obtaining, I picked two classes person and chair, and  adjusted the image resize setting to min 400 max 666, which is 1/4 of default setting. The training result showed 0.6 map for all, in detail,  0.7 map for person. 0.4 map for chair, which is acceptable. However, the testing result using notebook script shows a multiple boxes in following. I didnt change anything else.

Can anyone help me to solve this issue.

![111](https://user-images.githubusercontent.com/15268354/47554463-f31f1b00-d93b-11e8-897c-1736ce832751.jpg)

Thank you

**Comment by hgaiser** [comment]
Strange result.. how many images did you use? It feels like the network didn't learn enough yet to find the objects correctly. Also, did you resize the image during inference to 400px as well? That could make a difference.

Anyways, closing this as it is not an issue with the code base. Please use the slack channel for usage questions.
