### ISSUE TITLE
the trained inference model outputs a weird result

### ISSUE THREAD

**Issue by CUGfred** [fizyr/keras-retinanet#765]
i have trained a model and transformed it into inference type(loss=0.11,classification=0.00x,reg=0.10xxx).when i test it.the model outputs a result,while most of them was classified into one class,only few of example was classified into other class(after confirm most were wrong).and i test the model with train set image.it give nothing.could u please note some about this error?thx

**Comment by hgaiser** [comment]
Try `debug.py` to inspect your dataset, most of the times the issue comes from the data.

Closing this as it is not an issue with the code. Please use the slack channel for usage questions.

**Comment by CUGfred** [comment]
thx for help,after training,i ll try the debug.py.i wanna ask if i train with an image[400,200],while test image[1333,800](code default) will result in this.

**Comment by hgaiser** [comment]
It could result in strange results, yeah.
