### ISSUE TITLE
I tried to use vgg19 as backbone i got the error:

### ISSUE THREAD

**Issue by himachalbanik40** [fizyr/keras-retinanet#771]
Using TensorFlow backend.
keras_retinanet/bin/train.py:348: UserWarning: Using experimental backbone vgg19. Only resnet50 has been properly tested.
  warnings.warn('Using experimental backbone {}. Only resnet50 has been properly tested.'.format(parsed_args.backbone))
Traceback (most recent call last):
  File "keras_retinanet/bin/train.py", line 489, in <module>
    main()
  File "keras_retinanet/bin/train.py", line 418, in main
    backbone = models.backbone(args.backbone)
  File "keras_retinanet/bin/../../keras_retinanet/models/__init__.py", line 53, in backbone
    from .vgg import VGGBackbone as b
ImportError: cannot import name VGGBackbone

**Comment by teaddicted** [comment]
I just tried it. Working on my end without any issues.

**Comment by himachalbanik40** [comment]
i ran on latest keras-retinanet.
Problem solved when i executed it for second time.
