### ISSUE TITLE
Problem in loading ResNet-50-model.keras.h5 backbone

### ISSUE THREAD

**Issue by shivamchaubey** [fizyr/keras-retinanet#773]
I am having a problem in loading Resnet backbone. I am running my script in cray HPC system which is not having an internet connection. I have downloaded the ResNet-50-model.keras.h5 and copied in the snapshot directory and also in the main directory keras-retinanet from where I am running PBS script to deploy the code for training. I am getting an SSL error which is obvious but why the code is not picking up the Resnet model which is already there? Is there any path issue? Where do I have to keep this model in the directory? 

Look at the screenshot.
![image](https://user-images.githubusercontent.com/37264992/47836998-5d1e4100-ddd0-11e8-9f0d-359c86f7746f.png)

Please suggest what can be done to resolve this issue?

**Comment by hgaiser** [comment]
It is trying to download the imagenet model, which for some reason it can't. Also, it appears your CUDA is giving an error (one of the first lines in your image). If you place your `ResNet-50-model.keras.h5` model in `$HOME/.keras/models` it should find it.

Closing this as it is not an issue with the code.
