### ISSUE TITLE
Large and small object detection

### ISSUE THREAD

**Issue by himachalbanik40** [fizyr/keras-retinanet#777]
what modifications do i need to do in order to detect small and large object?My images are of resolution 1275 * 1650 and one class of object is there.The size can be as big as 1100 * 1400 and as small as 1190*65.

**Comment by hgaiser** [comment]
Is it a typo or are your objects very oddly shaped? (regarding the 1190 * 65 dimension). If you really have such a high ratio, then most object detectors I know will not work. The more square your object is the better. You can stretch it a little bit, but 1190 * 65 is far too much I'm afraid.

**Comment by himachalbanik40** [comment]
![horioutcs12](https://user-images.githubusercontent.com/38507019/47926595-f8a1d580-dee6-11e8-8c8f-43fd2be5d224.jpg)
I want to detect tabular data from given image,if the size of table is like this (bounding box),what modifications do i need?
xmin=331,ymin=352,xmax=1593,ymax=413 for the given bounding box.

**Comment by himachalbanik40** [comment]
Actually i am thinking of training a separate model for such small tables.

**Comment by hgaiser** [comment]
Wouldn't OCR be a better algorithm for this?

**Comment by himachalbanik40** [comment]
OCR fails for certain type of tables where data is not properly organised.Thats why i thought of this approach.

**Comment by hgaiser** [comment]
Alright, but very elongated objects will not be detected by retinanet (also not by any algorithm in detectron, yolo, ssd and similar algorithms for that matter).

Anyway, I'm closing this as it is not an issue with the code.
