### ISSUE TITLE
User warning invalid boxes

### ISSUE THREAD

**Issue by Anesthesic** [fizyr/keras-retinanet#778]
Please make sure that you follow the steps below when creating an issue.
Only use GitHub issues for issues with the implementation, not for issues with specific datasets or general questions about functionality.
If your issue is an implementation question, please ask your question on the #keras-retinanet Slack channel instead of filing a GitHub issue.
You can find directions for the Slack channel here: https://github.com/fizyr/keras-retinanet#discussions

Thank you!

1. Check that you are up-to-date with the master branch of keras-retinanet.
2. Check that you are up-to-date with the latest version of Keras: https://github.com/keras-team/keras.
3. Check that you are up-to-date with the latest version of TensorFlow.
   The installation instructions can be found here: https://www.tensorflow.org/get_started/os_setup.
4. Check that you have read the entire README.md: https://github.com/fizyr/keras-retinanet/README.md.
   Most noticably the FAQ section shows common issues: https://github.com/fizyr/keras-retinanet#faq.
5. Clearly describe the issues you're having including the expected behaviour, the actual behaviour
   and the steps required to trigger the issue.
6. Include relevant output from the commands you're executing, including full stack traces where relevant.
7. Remove this entire message and replace it with your issue.

**Comment by Anesthesic** [comment]
User warning: Image with id 197 (shape (1080, 1350, 3)) contains the following invalid boxes: [array([742., 538., 825., 414., 0.]), array([ 992., 1008., 1066., 925., 0.])]. Any ideas on why the warning occur? As presented in the logs the bounding boxes are not out of the image dimensions

**Comment by himachalbanik40** [comment]
annotations should be in the format of pathtoimage,xmin,ymin,xmax,ymax,class.As the warning suggests your xmax and ymax are smaller than xmin and ymin.Thats why the warning came.

**Comment by hgaiser** [comment]
@himachalbanik40 answered it nicely, your ymin is larger than your ymax.

**Comment by Anesthesic** [comment]
Problem solved. My mate used labelBox for labeling the data and on some boxes he started from BR not TL, and it resulted in a corner case that I did not cover. Thank you guys for opening my eyes!
