### ISSUE TITLE
How to feed my own data to model

### ISSUE THREAD

**Issue by ShibaPrasad** [fizyr/keras-retinanet#779]
Hi,
I have datasets on patches and would like to feed it into the model. Currently my model is working fine with the existing data set on github code. My data is on .svc/.xml format and would like to write a script for that if needed. 

1) I would like to know where is the data will be feed to the model (which module or function)
2) If the data format of current model is different to that of my experiment data format then -> How to handle those

**Comment by himachalbanik40** [comment]
1.data will be feed to keras-retinanet/bin/train.py 
2.Data format doesnot matter.The backbone architecture should match.If you have a saved model,just pass it when you call train.py

**Comment by ShibaPrasad** [comment]
Thank You himachalbanik40. 
1.data will be feed to keras-retinanet/bin/train.py  (https://github.com/fizyr/keras-retinanet/blob/master/keras_retinanet/bin/train.py)  :  which **_module/function or line of code_** in particular please.

We are annotating our data on XML format and converting it into .svs file for our learning. Currently we are adopting for deep learning and planning to use Faster RCNN model and check our results. 

So our file saved as .svs file.
Would you please guide me how to feed to my current resnet model from this .svs file.

**Comment by himachalbanik40** [comment]
for your own dataset,it should be in csv format containing pathtoimage,xmin,ymin,xmax,ymax,class. I think svs is not supported.
For training on own custom dataset,read the documentation,its clearly mentioned.

**Comment by ShibaPrasad** [comment]
Thank You.

**Comment by Poonamjo** [comment]
Hello,
Can you share the train.py command with all arguments you used for training the existing model
