### ISSUE TITLE
issue with debug.py when input csv contains images with no objects of interest

### ISSUE THREAD

**Issue by amruz** [fizyr/keras-retinanet#781]
I am checking my dataset with debug.py, but its throwing an error when my csv file has no objects of interest as below.

> /keras-retinanet/objectdetection_obj5/falseimages/resized12.jpg,,,,,

The error is as follows

> Traceback (most recent call last):
  File "debug.py", line 242, in <module>
    main()
  File "debug.py", line 238, in main
    run(generator, args, anchor_params=anchor_params)
  File "debug.py", line 189, in run
    positive_indices, _, max_indices = compute_gt_annotations(anchors, annotations['bboxes'])
  File "../../keras_retinanet/utils/anchors.py", line 140, in compute_gt_annotations
    argmax_overlaps_inds = np.argmax(overlaps, axis=1)
  File "/volume/software/common/foreign_packages/NumPy/1.14.5/osl42-x86_64/lib/python2.7/site-packages/numpy/core/fromnumeric.py", line 1004, in argmax
    return _wrapfunc(a, 'argmax', axis=axis, out=out)
  File "/volume/software/common/foreign_packages/NumPy/1.14.5/osl42-x86_64/lib/python2.7/site-packages/numpy/core/fromnumeric.py", line 52, in _wrapfunc
    return getattr(obj, method)(*args, **kwds)
ValueError: attempt to get argmax of an empty sequence

Any guidance is highly appreciated
Thank you in advance

**Comment by hgaiser** [comment]
This could be an issue with debug.py, but I have no time to look at it currently. Could you investigate it?

**Comment by hgaiser** [comment]
Any update on this ?

**Comment by Etienne-Meunier** [comment]
Hey I got the same error, and the thing is that we send an empty annotation dictionnary to compute_gt_annotations so it cannot extract the indices. 
I don't think it's the best way to do but if you place  a condition : if len(annotations['labels']) != 0 
around line 178 to line 202 it will just display the image for thoses cases and so no issue will happen

**Comment by hgaiser** [comment]
A PR to solve this issue would be nice.

**Comment by Etienne-Meunier** [comment]
I just did a Pull request with the change I mentioned upper 😄

**Comment by hgaiser** [comment]
The PR is merged, so I'm closing this issue. Thanks!
