### ISSUE TITLE
Accessing Outside URL

### ISSUE THREAD

**Issue by abidmalikwaterloo** [fizyr/keras-retinanet#782]
I am running the model on a cluster. It doesn't allow the outside connectivity. Therefore, I am getting the following message:

Traceback (most recent call last):
  File "keras_retinanet/bin/train.py", line 493, in <module>
    main()
  File "keras_retinanet/bin/train.py", line 452, in main
    weights = backbone.download_imagenet()
  File "keras_retinanet/bin/../../keras_retinanet/models/resnet.py", line 60, in download_imagenet
    md5_hash=checksum
  File "/sdcc/u/amalik/.local/lib/python3.5/site-packages/keras/utils/data_utils.py", line 226, in get_file
    raise Exception(error_msg.format(origin, e.errno, e.reason))
Exception: URL fetch failure on https://github.com/fizyr/keras-models/releases/download/v0.0.1/ResNet-101-model.keras.h5: None -- [Errno 101] Network is unreachable

Is there a way to overcome this problem. The  IT staff would not allow the outside connectivity.

**Comment by hgaiser** [comment]
You can download the model manually and put it in ~/.keras/models/

**Comment by abidmalikwaterloo** [comment]
@hgaiser Thanks. It works. One more question. If you have four GPUs on a node, how the model use it? what kind of parallelism is it using; data parallelism or model parallelism. I know its not related to the issue. However, I am trying to understand it.

**Comment by hgaiser** [comment]
Multi-GPU is a sketchy feature in Keras and doesn't work well in my opinion. But it duplicates the model on each GPU and splits up the batch so each GPU handles a portion of the input. This means that if you have 4 GPUs, your batch size should be a multiple of 4.
