### ISSUE TITLE
Ideal Input size

### ISSUE THREAD

**Issue by ShibaPrasad** [fizyr/keras-retinanet#783]
What should  we consider:  - for my input image size (regnet50)- (as i have arbitrary image sizes on my own data set)

**Comment by hgaiser** [comment]
Try different values and test the difference, there is no ideal image size that fits all.

**Comment by ShibaPrasad** [comment]
Can the dimension of input image x*y or always x*x

**Comment by hgaiser** [comment]
Your images don't need to be square, if that's what you mean.

**Comment by ShibaPrasad** [comment]
Yes. I am working a pathological images. Out input feel image is not uniform (some times square and some times rectangular). We are trying to figure out what will be idea input size. Base don that we will try to generate further annotations.

**Comment by ShibaPrasad** [comment]
Hi,
I would like to take a suggestion: My image cell regions (175*175). I need to creates lot of patched from there. What you suggest for the patch size. I am not sure how it works for Faster RCNN and also trying to get inside it from paper.

Training:
for the (RPN and Fast R-CNN) training which - method being implemented in code. As the paper suggests 4 methords
