### ISSUE TITLE
Facing problems with relative imports

### ISSUE THREAD

**Issue by DecentMakeover** [fizyr/keras-retinanet#784]
Hi ,

Thanks for sharing your work ,

I am facing some issue with the relative imports, since you have imports like `from ..preprocessing.generator import Generator` i get errors like cannot perform relative imports.

Can you please tell me do i have to set like a global directory path?or is there anything im missing.

Thanks a lot

**Comment by hgaiser** [comment]
What are you trying to do exactly ? If you import a generator in your code it should import the relative imports correctly. If you're trying to import in your code the `Generator` using the relative import, then it won't work.

**Comment by DecentMakeover** [comment]
Thanks for the quick response, 

I am trying to run the pascal_voc.py file, and i am in the main keras-retinanet directory.

It looks like this
![retinanet_erro](https://user-images.githubusercontent.com/25679895/48053305-5cbae700-e1d0-11e8-898e-2b772f62c2d3.png)

**Comment by hgaiser** [comment]
That file is not meant to be executed, it is meant to be imported and used. Only the scripts in `keras_retinanet/bin` are meant to be executed. I assume you're looking to train pascal VOC, try running `python keras_retinanet/bin/train.py --help`.

**Comment by DecentMakeover** [comment]
Oh Okay, 

I am trying to train on custom data, so im guessing ill import functions from this file and use them?
