### ISSUE TITLE
Training runs on single GPU

### ISSUE THREAD

**Issue by Mageshpoondi** [fizyr/keras-retinanet#790]
OS Ubuntu 16.04
Tensorflow : 1.11.0
Keras: 2.2.4
Keras-retinanet - master branch
NVIDIA GPU
```

+-----------------------------------------------------------------------------+
| NVIDIA-SMI 396.44                 Driver Version: 396.44                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla M60           On   | 00000000:00:1D.0 Off |                    0 |
| N/A   50C    P0   116W / 150W |   7345MiB /  7618MiB |     99%      Default |
+-------------------------------+----------------------+----------------------+
|   1  Tesla M60           On   | 00000000:00:1E.0 Off |                    0 |
| N/A   39C    P0    39W / 150W |    150MiB /  7618MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0     10206      C   ...naconda3/envs/tensorflow_p36/bin/python  7334MiB |
|    1     10206      C   ...naconda3/envs/tensorflow_p36/bin/python   139MiB |
+-----------------------------------------------------------------------------+


```
`(tensorflow_p36) ubuntu@ip-:~/keras-retinanet/keras_retinanet/bin$ ls -l
total 44
-rwxrwxr-x 1 ubuntu ubuntu  3027 Nov  9 04:00 convert_model.py

-rwxrwxr-x 1 ubuntu ubuntu  9697 Nov  9 04:00 debug.py

-rwxrwxr-x 1 ubuntu ubuntu  7617 Nov  9 04:00 evaluate.py

-rw-rw-r-- 1 ubuntu ubuntu     0 Nov  9 04:00 __init__.py

-rwxrwxr-x 1 ubuntu ubuntu 19782 Nov  9 04:00 train.py
`
[436](https://github.com/fizyr/keras-retinanet/issues/436)

Data: 1400 annotations on 750 images.
Code: `retinanet-train --batch-size 2 --steps 698 --epochs 50 --snapshot-path logos/snapshots csv logos/retinanet_train.csv logos/retinanet_classes.csv `
Problem: Not able to utilize all the GPU's for training.
Trials: tried changing the number of gpu's and matched the batch sizes with the number of gpus - didn't work.
`export CUDA_VISIBLE_DEVICES = "0,1"` - didn't help

Question: Does keras-retinanet not support multiple gpu's for training?

**Comment by hgaiser** [comment]
Check `retinanet-train --help` for the possible arguments. Having said that, the support of Keras for multi-gpu training is terrible ... so tread carefully :p
