### ISSUE TITLE
Question: Is there data augmentation?

### ISSUE THREAD

**Issue by TimoK93** [fizyr/keras-retinanet#792]
Hi fizyr Team,

one little question: ist there data augmentation implemented in your Training code?

Thank you!

**Comment by eduramiba** [comment]
There is some basic augmentation with the `--random-transform` option: https://github.com/fizyr/keras-retinanet/blob/master/keras_retinanet/bin/train.py#L406

https://github.com/fizyr/keras-retinanet/blob/master/keras_retinanet/bin/train.py#L225

**Comment by TimoK93** [comment]
Ah okay, thanks!
Do you think it is clever to hard copy images and add some more augmentation (e.g. noise) in the training data and in the csv files?

**Comment by kongqiankun** [comment]
according to the train.py code,  if I don't give the --random-transform True , it will run this "transform_generator = random_transform_generator(flip_x_chance=0.5)", will this double my dataset about the image and the annotation? I am looking forward to your reply.

**Comment by eduramiba** [comment]
Yes, it will always do that simple flip transformation as it should never be a problem.

**Comment by kongqiankun** [comment]
Thanks for your reply firstly. If so, when I set the parameters of "batchsize=1", Shall I set the steps that are equal to the double of my dataset? (steps and batchsize are the parameters in train.py)

**Comment by hgaiser** [comment]
@kongqiankun that's up to you. Personally, I'm more a fan of having a static number of steps. Having your number of steps be equal to the number of images in your dataset does not provide any benefit in my opinion.

Closing this as the "issue" seems to be resolved.

**Comment by GoilerElch** [comment]
Hi! I am using retinanet and doing some experiments with image transformation for augmenting my dataset. I think I have nearly the same question as asked before but doesnt seem 100% answered. Does the tranform generator always generate the double amount of images and annotations respectively of the local datatset? If i use --random-transform and check the results with debug.py I just see the transformed images and not the original ones. So it seems for me that training.py just uses the transformed images and not the originals. Am I wrong?
