### ISSUE TITLE
Anchor assignment rule seems slightly different from what the paper says

### ISSUE THREAD

**Issue by KittyLiou** [fizyr/keras-retinanet#797]
In the paper **Focal Loss for Dense Object Detection**, it says that 

> We use the assignment rule from RPN [28] but modified for multiclass detection and with adjusted thresholds.

And according to **Faster R-CNN** paper, 
> We assign a positive label to two kinds of anchors: 
(i) the anchor/anchors with the highest Intersection-overUnion (IoU) overlap with a ground-truth box, or
(ii) an anchor that has an IoU overlap higher than 0.7 with any ground-truth box. 

It says 
> Usually the second condition is sufficient to determine the positive samples; but we still adopt the first
condition for the reason that in some rare cases the second condition may find no positive sample. 

Then I go to see the function `compute_gt_annotations` inside `anchors.py`
```
    overlaps = compute_overlap(anchors.astype(np.float64), annotations.astype(np.float64))
    argmax_overlaps_inds = np.argmax(overlaps, axis=1)
    max_overlaps = overlaps[np.arange(overlaps.shape[0]), argmax_overlaps_inds]

    # assign "dont care" labels
    positive_indices = max_overlaps >= positive_overlap
    ignore_indices = (max_overlaps > negative_overlap) & ~positive_indices

    return positive_indices, ignore_indices, argmax_overlaps_inds
```

It seems that only the second assignment rule is used. 
The anchors that have the highest IoU with a ground-truth box (but smaller than `positive_overlap`) are not labeled as positive.
Is this done on purpose? Or did I miss something?

**Comment by hgaiser** [comment]
Hey, sorry for the late reply.

I vaguely remember having that rule, but that it was giving bad results. Basically when there are no anchors that properly cover an object, it assigns a really bad anchor with low IoU, simply because it has the highest overlap.

@yhenon what is your opinion ?

**Comment by hgaiser** [comment]
Any update on this?

@yhenon ?

**Comment by hgaiser** [comment]
I think it was causing issues because you would have very poor anchors that barely overlap an object, but because they are "the best" match, they get assigned to that annotation. I remember disabling it and getting an improvement in accuracy, but feel free to re-run that test. For now, I'll close this issue.
