### ISSUE TITLE
"python setup.py build_ext --inplace " error

### ISSUE THREAD

**Issue by KKKlose** [fizyr/keras-retinanet#798]
when i run python setup.py build_ext --inplace, the error is:

running build_ext
skipping 'keras_retinanet/utils\compute_overlap.c' Cython extension (up-to-date)
copying build\lib.win-amd64-3.6\keras_retinanet\utils\compute_overlap.cp36-win_amd64.pyd -> keras_retinanet\utils

I don't know how to solve it, what's the problem? 
Thank you !

**Comment by hgaiser** [comment]
That doesn't really look like an error to me. What makes you think it is?

**Comment by KKKlose** [comment]
Sorry ,I make a mistake , there is no error.
Thank you for your response. @hgaiser

**Comment by de-vri-es** [comment]
Thanks for checking back :)

**Comment by Jaffarali123** [comment]
Hello all,
How to run python setup.py build_ext --inplace on windows 7 (64 bit)? 

TIA.
