### ISSUE TITLE
loss: nan - regression_loss: nan - classification_loss: nan

### ISSUE THREAD

**Issue by tttttthy** [fizyr/keras-retinanet#800]
Hello,I trained the model on coco,pascal an my own datasets and start showing loss as nan.Like this：
 2/10000 [..............................] - ETA: 34:21:32 - loss: nan - regre  3/10000 [..............................] - ETA: 34:20:08 - loss: nan - regression_loss: nan - classification_loss: nan

my model parameters show as none like this 
input_1 (InputLayer)            (None, None, None, 3 0                                            
__________________________________________________________________________________________________
padding_conv1 (ZeroPadding2D)   (None, None, None, 3 0           input_1[0][0]
I don't konw why ...please help me

**Comment by EafonChan** [comment]
Hello,I am facing the same issue.Have you solved it please?
