### ISSUE TITLE
Model outputs two parameters rather than three ( boxes, scores, labels).

### ISSUE THREAD

**Issue by thefakhir** [fizyr/keras-retinanet#802]
I have trained my own model with a single class object detection problem. I generated the csv files and gave it to the model to train. Without any error, I have stopped training after 35 epochs and when I run the evaluation.py file, it gives me an error at the following line
boxes, scores,labels = model.predict_on_batch(np.expand_dims(image, axis=0))
with the error

ValueError                                Traceback (most recent call last)

     14 # process image
     15 start = time.time()
---> 16 boxes, scores,labels = model.predict_on_batch(np.expand_dims(image, axis=0))
     17 # boxes, scores, labels = model.predict_on_batch(image)
     18 

ValueError: not enough values to unpack (expected 3, got 2)

Can somebody please guide me here?

**Comment by hgaiser** [comment]
I think you should check the [FAQ](https://github.com/fizyr/keras-retinanet#faq) again.
