### ISSUE TITLE
install completed with error

### ISSUE THREAD

**Issue by Ankalim** [fizyr/keras-retinanet#804]
Hi. I try install like show in Readme and get this error.
Windows 7 x64 
Python 3.6
![photo_2018-11-23_14-47-45](https://user-images.githubusercontent.com/22808739/48942081-0fa87600-ef2f-11e8-98fc-c07b45d68198.jpg)
Thank you!

**Comment by hgaiser** [comment]
That's weird, it's not really showing what went wrong ... Is there no additional information printed beyond this point? What is the content of the keras_retinanet/utils directory currently ?
