### ISSUE TITLE
multiple overlapp boxes prediction

### ISSUE THREAD

**Issue by ssetty** [fizyr/keras-retinanet#805]
Hello,
During prediction I see multiple overlapp boxes. How do I suppress this using non-maximum-suppression (NMS) ?

Thanks

**Comment by hgaiser** [comment]
NMS is already applied, but I'm guessing your objects are rather small and that the overlap is about 50/50. The threshold for NMS is currently set for an IOU of 0.5, you can change it [here](https://github.com/fizyr/keras-retinanet/blob/master/keras_retinanet/layers/filter_detections.py#L29) if you want to (it is not properly exposed currently). You need to recreate your model when you change this. The easiest is to convert your train model to an inference model again.

**Comment by ssetty** [comment]
So I need to decrease NMS value if I still get overlapping bounding boxes? In inference model how do I change this value? 

Any parameter changes suggestions for detection of small objects like scratches from metal surface?

Thanks

**Comment by void32** [comment]
> You need to recreate your model when you change this. The easiest is to convert your train model to an inference model again.



> You need to recreate your model when you change this. The easiest is to convert your train model to an inference model again.

If you send the convert model to a server, should the the NMS settings also be changed there, or are the settings in [filter_detections.py](https://github.com/fizyr/keras-retinanet/blob/master/keras_retinanet/layers/filter_detections.py#L29) only used when recreating/converting a mode?

**Comment by hgaiser** [comment]
> If you send the convert model to a server, should the the NMS settings also be changed there, or are the settings in [filter_detections.py](https://github.com/fizyr/keras-retinanet/blob/master/keras_retinanet/layers/filter_detections.py#L29) only used when recreating/converting a mode?

Only when recreating / converting a model.

Closing this as the issue seems to be resolved.

**Comment by jkstyle2** [comment]
@hgaiser Hi sir, then do we have to retrain the model when we change the NMS's IOU parameter?

**Comment by salihkaragoz** [comment]
@jkstyle2 Not necessary, just change the nms_threshold value, then convert the training model.h5 to the test model.h5
