### ISSUE TITLE
Is there possibile to rewrite this network to 3D network version?

### ISSUE THREAD

**Issue by a6225301** [fizyr/keras-retinanet#806]
Hello, really thanks for this wonderful  repository, and I wonder if possible this network could convert to 3D network version for image cube or voxel detection ?

Thanks a lot.

**Comment by hgaiser** [comment]
Performing detection on 3D space is not trivial, I'd suggest to do some reading on the subject to find out. But to answer your question, it's not possible (both in this implementation and, I would argue, theoretically).
