### ISSUE TITLE
Notice? Keras-resnet has been updated

### ISSUE THREAD

**Issue by ghost** [fizyr/keras-retinanet#815]
After updating the library changed some names
Such as
ResNet50 
ResNet...n
`keras_resnet.models.ResNet50 To  keras_resnet.models.ResNet2D50
#and etc?
`
You will get an error like
`AttributeError: module 'keras_resnet.models' has no attribute 'ResNet50'
`
You can take a look at the [modifications](https://github.com/broadinstitute/keras-resnet) [and](https://github.com/broadinstitute/keras-resnet/blob/master/tests/test_models.py) 

Or you can install an older version like this

`pip install keras-resnet==0.0.8`

**Comment by hgaiser** [comment]
Ah good to know, I didn't notice no :)

Could you make a PR with the changes?

**Comment by mohammed-Emad** [comment]
@hgaiser You mean I can make changes?
This is my honor, certainly I am ready.
I will write the modifications separately and verify them, then consider how to modify them here
Do you advise me about something?

**Comment by hgaiser** [comment]
> @hgaiser You mean I can make changes?

Actually, on second look, it seems like they haven't released a new version of keras-resnet yet. Version 0.1.0 still works fine, but if they release a new version, we should make these changes.

So I'll close this issue for now. Thanks for the notification though, it's good to be aware that they updated their code.

**Comment by mohammed-Emad** [comment]
Thank you, you are right 'version 0.1.0 still works fine'
But it will be on who uses the warehouse in the installation,
`pip install git+https://github.com/broadinstitute/keras-resnet`
Consider those changes.
Anyway I will keep those updates until the final launch
I'll be ready to create a PR about it.
I apologize for writing version 0.0.8.
