### ISSUE TITLE
If I double the COCO dataset by myself about the images and annotations, will it conflict with argumentation in source code?

### ISSUE THREAD

**Issue by kongqiankun** [fizyr/keras-retinanet#818]
now，I train it on COCO dataset using original parameters with Resnet101，but I just get ap 34.9, even not achieving you result with Resnet50. I think the data argumentation may improve the result. So if I double the COCO dataset by myself about the images and annotations, will it conflict with argumentation in source code?

**Comment by hgaiser** [comment]
The augmentation how we have it currently loads an image and applies random transformations. If you double the images in your dataset there shouldn't be an issue.
