### ISSUE TITLE
Batch size and epoch

### ISSUE THREAD

**Issue by ShibaPrasad** [fizyr/keras-retinanet#820]
Hi All,
I have 2 questions and need it quickly. Please help me.
1) I am trying to execute my data sets (5500 images) and need to know - how to split it into batches and epochs.
By default it is:
parser.add_argument('--epochs',           help='Number of epochs to train.', type=int, default=50)
parser.add_argument('--steps', help='Number of steps per epoch.', type=int, default=10000)

Qrs: How to change it based on my datasets and where?

2) After my training on my own data sets from csv files. How to test it. Let say on a single image i would like to test ...
i followed the steps at:
https://github.com/fizyr/keras-retinanet/blob/master/examples/ResNet50RetinaNet.ipynb
and getting  below error:

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-15-977b9caa2b52> in <module>()
     11 # process image
     12 start = time.time()
---> 13 boxes, scores, labels = model.predict_on_batch(np.expand_dims(image, axis=0))
     14 print("processing time: ", time.time() - start)
     15 

ValueError: not enough values to unpack (expected 3, got 2)

**Comment by hgaiser** [comment]
@chanajianyu answered your second question.

For your first question, it doesn't really matter if steps is equal to your dataset size.

You could do it of course by running the training script with `--steps <your_dataset_size>`.

**Comment by ShibaPrasad** [comment]
@hgaiser Thank you. I am able to train and test (based on the instructions). Though i need to improve my experiment  many ways.

But i need another small question .....
What is the best criteria (on the code) to know whether training is over fitting? 
(based on 90% accuracy or 95 or .... on each epoch result  and on a graph)

If in case i need to do code:  where i need to do it?

**Comment by ShibaPrasad** [comment]
Thank you to @chanajianyu  and please advise (for recent question) if any suggestions.
