### ISSUE TITLE
mAP=0

### ISSUE THREAD

**Issue by tttttthy** [fizyr/keras-retinanet#823]
I am sorry to consult you here. This problem has been bothering me for a long time. I followed the instructions to run the program, but playing mAP on pascal is 0, which is the same on my own csv. If you can help me, thank you very much.
M steps(keras-retinanet-0.5.0，2.2.4keras,1.3.0tensorflow-gpu):
pip install numpy --user
python setup.py build_ext --inplace
python keras-retinanet/bin/train.py --weights /home/z840/下载/keras-retinanet-0.5.0/snapshots/resnet50_coco_best_v2.1.0.h5 --steps 9963 --epoch 1 pascal  /media/z840/2c28d972-5dad-453f-9212-dc012dba4f6f/darknet/VOCdevkit/VOC2007
then mAP shows 0
i would close it quickly,thx.

**Comment by tttttthy** [comment]
I think pascal voc2007 is right,i don't know the wrong place.

**Comment by hgaiser** [comment]
Your tensorflow is really old, we're currently on 1.12.0. Could you try updating that to see if it makes a difference ?

**Comment by tttttthy** [comment]
thanks a lot,i will try again

**Comment by zxczhkzxc** [comment]
@tttttthy  hello,do you update the version of tf? and it comes ok?

**Comment by xcaizewu** [comment]
@tttttthy Hello, have you found a solution to solve voc 2007 training mAP=0?

**Comment by tttttthy** [comment]
update tensorflow would solve the problem

**Comment by xcaizewu** [comment]
@tttttthy 

Thank you. I have solved the problem, but did not update tensorflow. I used resnet101 at that time, but just changed resnet50. I'm not sure what went wrong.
