### ISSUE TITLE
Need all objects on training images be annotated?

### ISSUE THREAD

**Issue by TimoK93** [fizyr/keras-retinanet#829]
Hey all,

i have a question regarding the training images and annotations: Do i have to annotate every object on an image or can i leave some without affecting the training.

For example: I have an image with two spoons. Do i exactly have to write two annotations to the csv file or is it okay, if one spoon is not annotated (beause i forgot it while labeling)?

Greeting,
Timo

**Comment by hgaiser** [comment]
The way the targets are computed, everything that isn't annotated is considered not an object. Meaning in your example of two spoons where one is annotated, the network will receive conflicting information and will perform suboptimal.

**Comment by TimoK93** [comment]
Ok, nice to know.
Thanks!
