### ISSUE TITLE
validation mAP on #825 

### ISSUE THREAD

**Issue by ShibaPrasad** [fizyr/keras-retinanet#830]
I am trying to understand more on my previous issue number #825 (closed). It was previously replied by 
@ hgaiser

I used "./train.py --steps=100 --epochs=50 csv path-to/data.csv path-to/Class_mapping.csv --val-annotations path-tovalidation/Singlexml_data.csv" for my validation and also getting the mAP.

Would you please help me - understanding technically - how should I indicate that my job working fine with the mAP values (increasing or decreasing values). What should be ideal.

**Comment by hgaiser** [comment]
There is no useful answer to your question. What is ideal? A score of 1.0 is ideal, but probably not feasible. Anything closer to 1.0 is better.

If you investigate what the mAP value means (it's used throughout literature), you'll find out what it is and how it should be interpreted.

Closing this as it is not an issue with the codebase. Please use the keras-retinanet slack channel for usage questions.
