### ISSUE TITLE
about inference speed

### ISSUE THREAD

**Issue by tttttthy** [fizyr/keras-retinanet#831]
Hello,
         First of all, thank you very much for your code and  answered my questions before. I want to ask you a another question . I predict an image takes two seconds. How can I improve the prediction’s speed?

**Comment by hgaiser** [comment]
Did you run it once? The GPU might still need to "warm up". Try running it
a couple of times. It also depends on which hardware you're currently using
to run this with. If it's too slow, it is too slow, but I'm assuming you
were expecting better speeds.

**Comment by tttttthy** [comment]
Thanks for your reply,my gpu is GTX1080 Ti,I use single GPU to inference.Maybe the reason is the version of tensorflow-gpu.Due to some reasons,my tf-gpu is 1.3 and i have no permission to update it.I used 1.12 cpu tf to train my model,and use 1.3 tf-gpu to inference.Do you think it is a key point？

**Comment by hgaiser** [comment]
Could be, tensorflow 1.3 is quite old indeed. Did you try running inference
multiple times ?

**Comment by tttttthy** [comment]
yes,i tried multiple times.because  I need to give the server to another company soon，so i can't update tf.By the way，Your code is unfriendly to the old version of tf.lol...
any way,thank you.
