### ISSUE TITLE
Training of custom Crack dataset

### ISSUE THREAD

**Issue by rakehsaleem** [fizyr/keras-retinanet#832]
I have been working on this project to custom train it for my crack dataset. At the moment, I have generated the csv files as mentioned, necessary for training with annotations and classes. The step mentioned to custom train data is 
`./keras_maskrcnn/bin/train.py csv /path/to/csv/file/containing/annotations /path/to/csv/file/containing/classes`
But when i run in my jupyter notebook ith my files path specified it give me error. I have attached snippet where my command and the error are mentioned. Kindly guide me how to trained my model in right way. Thanks in advance.
![capture](https://user-images.githubusercontent.com/37826897/49731249-1587b080-fcbe-11e8-8eaf-f911bce17605.PNG)

**Comment by hgaiser** [comment]
I think this discussion is continued on Slack.
