### ISSUE TITLE
problem about KITTI training 

### ISSUE THREAD

**Issue by yuyijie1995** [fizyr/keras-retinanet#837]
When I try to train the KITTI,the error below happened .
![2018-12-13 20-45-23](https://user-images.githubusercontent.com/30818917/49939565-2f243480-ff18-11e8-88d3-731443b66b22.png)
![2018-12-13 20-45-06](https://user-images.githubusercontent.com/30818917/49939645-61ce2d00-ff18-11e8-8b03-9da19ec7cb7d.png)

I do not konw where to find  the subset "val" ,can you tell me how to fix it?

**Comment by hgaiser** [comment]
KITTI is a community contribution, there is no official support for it.

Do you believe this is an issue with the code, or that you are missing something? Github issues should only be used for issues with the code. If you have a usage question, you could try the keras-retinanet slack channel.

**Comment by yuyijie1995** [comment]
I found it  thanks
