### ISSUE TITLE
MxNet backend

### ISSUE THREAD

**Issue by bottleneck18** [fizyr/keras-retinanet#838]
Hello,
is it possible to use MXNet as backend instead of Tensorflow? 
I tried to add MXNEt to the keras.backend.common.dynamic.py file , but it was not working.
Thank you for your help!

**Comment by tensorcoder** [comment]
I'm also looking at how to do this. @hgaiser  Are you saying it is enough to just replace the 13 functions inside tensorflow_backend.py with corresponding mxnet functions, name them the same way and add the mxnet_backend to the dynamic.py file?

**Comment by hgaiser** [comment]
Oefh, it should be, yeah :p

Theoretically all other places where we use tf directly (like when adding a TensorBoard callback) are implemented in such a way that it will only import tf when you specify you want to use tf via command line arguments.
