### ISSUE TITLE
some spelling mistakes in  parse_args(args) 

### ISSUE THREAD

**Issue by qivigor** [fizyr/keras-retinanet#849]
in "keras_retinanet/bin/train.py"
the parameters in the method ‘’def parse_args(args): ‘’
such as：‘’’parser.add_argument('**_--batch-size_**',       help='Size of the batches.', default=1, type=int)‘’’
the **‘’--batch-size‘’** should be spelled as **‘’--batch_size‘’**
so as the '--multi-gpu'......

**Comment by de-vri-es** [comment]
It should not. Why do you think that is the case?

**Comment by qivigor** [comment]
Because you use underline  in the following code:
'''
if args.tensorboard_dir:
        tensorboard_callback = keras.callbacks.TensorBoard(
            log_dir                = args.tensorboard_dir,
            histogram_freq         = 0,
            **batch_size             = args.batch_size**,
            write_graph            = True,
            write_grads            = False,
            write_images           = False,
            embeddings_freq        = 0,
            embeddings_layer_names = None,
            embeddings_metadata    = None
        )
        callbacks.append(tensorboard_callback)
'''
.......so is it a right issue? 
and thank you for your wonderful work！

**Comment by vcarpani** [comment]
ArgumentParser maps "--foo-bar" to "foo_bar" in the argument namespace.

**Comment by qivigor** [comment]
thank you！you are right.  I get it now. 
thanks for your reminder!
