### ISSUE TITLE
Custom model accuracy

### ISSUE THREAD

**Issue by talhadar** [fizyr/keras-retinanet#85]
Hi,

Is there a way to view the accuracy and regression_acc and classification_acc when training a custom model from csv?

**Comment by hgaiser** [comment]
Nope, this is something I still intend to add. Ideally it would give similar statistics as the COCO evaluation tool. So far though I haven't gotten around to look into this.

**Comment by hgaiser** [comment]
Currently I got a seemingly working version on [this](https://github.com/fizyr/keras-retinanet/tree/evaluation) branch. It reports a AP@0.5 of `0.4827` whereas COCO evaluation reports an AP@0.5 of `0.488`. I'm not sure if they use the same measurement for AP.. but it's something I still have to look into.

**Comment by talhadar** [comment]
thank you :)

**Comment by hgaiser** [comment]
This issue is resolved in https://github.com/fizyr/keras-retinanet/pull/231 .
