### ISSUE TITLE
Can't train NN (on any dataset)

### ISSUE THREAD

**Issue by FellonOne** [fizyr/keras-retinanet#850]
I prepared the dataset and started train
And got this error
![errors](https://user-images.githubusercontent.com/26629155/50403338-9915c700-07bf-11e9-9a3d-74dbbf2bd881.jpg)
For everyone dataset (VOC2012, CSV, MS COCO) i got this error. Pls, help
But trained model (BEST COCO weights) work and keras-retinanet gives the result

Python 3.6.7
keras (latest)
tensorflow(latest)

**Comment by de-vri-es** [comment]
Hmm, it might be that somehow on windows, picking the generator fails. As a work-around, it should be possible to not use multiprocessing by not passing `--workers` (or `--workers 0`) to `train.py`.

**Comment by FellonOne** [comment]
> Hmm, it might be that somehow on windows, picking the generator fails. As a work-around, it should be possible to not use multiprocessing by not passing `--workers` (or `--workers 0`) to `train.py`.

It worked! 
--workers 0 and script successfully launched, big thx
