### ISSUE TITLE
IOError: image file is truncated (9 bytes not processed)

### ISSUE THREAD

**Issue by YuChenXiAn** [fizyr/keras-retinanet#855]
2074 1610/2000 [=======================>......] - ETA: 24:10 - loss: 1.7977 - regression_loss: 0.9663 - classification_loss: 0.8314
2075 1611/2000 [=======================>......] - ETA: 24:07 - loss: 1.7975 - regression_loss: 0.9663 - classification_loss: 0.8312
2076 1612/2000 [=======================>......] - ETA: 24:03 - loss: 1.7972 - regression_loss: 0.9662 - classification_loss: 0.8310
2077 1613/2000 [=======================>......] - ETA: 23:59 - loss: 1.7970 - regression_loss: 0.9662 - classification_loss: 0.8308
2078 1614/2000 [=======================>......] - ETA: 23:55 - loss: 1.7967 - regression_loss: 0.9660 - classification_loss: 0.8307
2079 1615/2000 [=======================>......] - ETA: 23:52 - loss: 1.7964 - regression_loss: 0.9660 - classification_loss: 0.8305
2080 1616/2000 [=======================>......] - ETA: 23:48 - loss: 1.7962 - regression_loss: 0.9659 - classification_loss: 0.8303
2081 1617/2000 [=======================>......] - ETA: 23:44 - loss: 1.7959 - regression_loss: 0.9658 - classification_loss: 0.8301
2082 1618/2000 [=======================>......] - ETA: 23:40 - loss: 1.7956 - regression_loss: 0.9657 - classification_loss: 0.8300
2083 1619/2000 [=======================>......] - ETA: 23:37 - loss: 1.7954 - regression_loss: 0.9656 - classification_loss: 0.8298
2084 1620/2000 [=======================>......] - ETA: 23:33 - loss: 1.7952 - regression_loss: 0.9656 - classification_loss: 0.8296
2085 1621/2000 [=======================>......] - ETA: 23:29 - loss: 1.7950 - regression_loss: 0.9656 - classification_loss: 0.8294Traceback (most recent ca     ll last):
2086   File "./bin/train.py", line 510, in <module>
2087     main()
2088   File "./bin/train.py", line 505, in main
2089     max_queue_size=args.max_queue_size
2090   File "/usr/local/lib/python2.7/dist-packages/keras/legacy/interfaces.py", line 91, in wrapper
2091     return func(*args, **kwargs)
2092   File "/usr/local/lib/python2.7/dist-packages/keras/engine/training.py", line 1418, in fit_generator
2093     initial_epoch=initial_epoch)
2094   File "/usr/local/lib/python2.7/dist-packages/keras/engine/training_generator.py", line 181, in fit_generator
2095     generator_output = next(output_generator)
2096   File "/usr/local/lib/python2.7/dist-packages/keras/utils/data_utils.py", line 601, in get
2097     six.reraise(*sys.exc_info())
2098   File "/usr/local/lib/python2.7/dist-packages/keras/utils/data_utils.py", line 595, in get
2099     inputs = self.queue.get(block=True).get()
2100   File "/usr/lib/python2.7/multiprocessing/pool.py", line 567, in get
2101     raise self._value
2102 IOError: image file is truncated (9 bytes not processed)

**Comment by YuChenXiAn** [comment]
can you tell me it is why ? 
When i train : batch=16  gpu number=4

**Comment by hgaiser** [comment]
This means that one of your image files is corrupted. Print which image is being loaded or inspect all images manually and you'll probably see a corrupted image somewhere.

**Comment by YuChenXiAn** [comment]
> 这意味着您的一个图像文件已损坏。打印正在加载的图像或手动检查所有图像，您可能会在某处看到损坏的图像。
i write code file to verifyed my date all JPEF file ,not corrupted.
help me , my date is 50k , crazy!  there will be a anthor way to deal the problem?    thinks!!  
can there be a way to ignore this problem make it can always run

**Comment by YuChenXiAn** [comment]
i write code file to verifyed my data all JPEF file ,not corrupted.
help me , my dataset is 50k , crazy! there will be a anthor way to deal the problem? thanks!!
can there be a way to ignore this problem make it can always run

**Comment by YuChenXiAn** [comment]
> 这意味着您的一个图像文件已损坏。打印正在加载的图像或手动检查所有图像，您可能会在某处看到损坏的图像。

i write code file to verifyed my data all JPEF file ,not corrupted.
help me , my dataset is 50k , crazy! there will be a anthor way to deal the problem? thanks!!
can there be a way to ignore this problem make it can always run

**Comment by hgaiser** [comment]
Hey, sorry, can't help you. Did you use PIL in your verification script?

I'm closing this issue as I'm assuming it is an issue with the data, not with the code.
