### ISSUE TITLE
Get "None" when try to evaluate

### ISSUE THREAD

**Issue by dabasmoti** [fizyr/keras-retinanet#861]
Hi,
running an issue when trying to evaluate
the detections in None
any suggestion?

```
(keras) C:\Users\z\Anaconda3\envs\keras\Lib\site-packages\keras_rnet\keras_retinanet>python bin/evaluate.py csv valc.csv  class.csv D:\Dropbox\DL\open_image\data\resnet50_csv_01.h5
Using TensorFlow backend.
2019-01-06 03:30:17.319312: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX AVX2
Loading model, this may take a second...
Running network: 100% (1 of 1) |#################################################| Elapsed Time: 0:00:11 Time:  0:00:11
Parsing annotations: 100% (1 of 1) |#############################################| Elapsed Time: 0:00:00 Time:  0:00:00
label 0
detections None
Traceback (most recent call last):
  File "bin/evaluate.py", line 188, in <module>
    main()
  File "bin/evaluate.py", line 167, in main
    save_path=args.save_path
  File "bin\..\..\keras_retinanet\utils\eval.py", line 197, in evaluate
    for d in detections:
TypeError: 'NoneType' object is not iterable

(keras) C:\Users\z\Anaconda3\envs\keras\Lib\site-packages\keras_rnet\keras_retinanet>
```

**Comment by hgaiser** [comment]
I'm assuming your classes have a "gap" or don't start from 0? This is an issue that has to be fixed in the evaluator, but in the meantime you could make your classes start from 0 and have no gap.

**Comment by dabasmoti** [comment]
Thank you for your answer!
After 15 epochs i saw in the repository that the classes should start from 0 instead 1.
I have traind my net on 41 classes starting from 1.
Whats the meaning of it?
Thanks!

**Comment by hgaiser** [comment]
> Whats the meaning of it?

The meaning of what? The class values are indices in the output of the network, indices typically start from 0.

Closing this as it seems to be resolved.

**Comment by dabasmoti** [comment]
Of course its tge output net
The meaning of thats i have trained it with no issue starting from 1 with no 0 class
As i mention  above 
I didnt evaluate the net ,so i dont know if all the classes have traind

**Comment by hgaiser** [comment]
If you start from 1, the network will "train" with an additional class (index 0), for which there is no data available. The evaluator should handle this more gracefully, the network is likely trained properly.

**Comment by dabasmoti** [comment]
Thanks.
Great repository!
