### ISSUE TITLE
Based on what to set the number / shape of the anchors?

### ISSUE THREAD

**Issue by clw5180** [fizyr/keras-retinanet#862]
I know using config.ini can change the number / shape of the anchors, 
```
[anchor_parameters]
sizes   = 32 64 128 256 512
strides = 8 16 32 64 128
ratios  = 0.5 1 2 3
scales  = 1 1.2 1.6
```
but I don't know what the value should be. My own dataset has about thousands of pictures with about 0.5 million of records(Some picture has a lot of small objects, such as 1×1, 2×2, 3×3, the largest is about 30×30, nearly all of them are square, and the picture is about 1024*768). I set the ratios to 1 and set the scales to [0.1, 0.2 0.3 ..... to 1], ran the debug.py and found that about half of the objects show up in red, and I don't know how to solve it. Can any one tell me how to set the sizes, strides, ratios and scales for my situations? Thanks a lot!  

Maybe I should change the sizes to [1 2 4 8 16 32] ?

**Comment by martinzlocha** [comment]
Changing the sizes is not a simple process because they are defined by the output sizes of different layers in the neural network. What you can do instead is reduce the scales (eg by diving all by 2). I'm not sure if this will improve the accuracy much given that your objects are really small.

However given that this isn't an issue with RetinaNet it might be best to discuss on Slack.

Also there have been a lot of questions in the past about anchor sizes/scales so I would recommend checking those out.

**Comment by clw5180** [comment]
> Changing the sizes is not a simple process because they are defined by the output sizes of different layers in the neural network. What you can do instead is reduce the scales (eg by diving all by 2). I'm not sure if this will improve the accuracy much given that your objects are really small.
> 
> However given that this isn't an issue with RetinaNet it might be best to discuss on Slack.
> 
> Also there have been a lot of questions in the past about anchor sizes/scales so I would recommend checking those out.
> 
> Edit: After re-reading the question I realized that you already changed the scales. If you can't get a good accuracy even after doing this then you should consider if a simpler approach would work better (eg having a custom simpler neural net).

Hello @martinzlocha , Thank you for your reply. I'm just a noob, maybe 'having a custom simpler neural net' is difficult for me...

Yesterday I tried to change the ratios and scales:
```
    ratios  = np.array([1], keras.backend.floatx()),
    scales  = np.array([0.10,0.15, 0.20,0.29, 0.35,0.51, 0.58,0.88, 1.10,1.59], keras.backend.floatx()),
```
These values of scales originated from a 'get_anchor.py' script from a Yolo2 project，and the accuracy seems ok (I get top 20% in a competition, it will be ended in ten days), but still have much work to be done. I decide to try more values of scales and run the debug.py to see the effect. 

Moreover, the code of prediction set the threshold of score to 0.5. A lot of small objects' scores are lower than 0.5 and being excluded. So I change it to 0.3, and the mAP improved 0.05.

**Comment by martinzlocha** [comment]
Well one thing that you could try is making your anchor boxes bigger for the smallest objects (eg. setting a minimum bounding box to be 5x5). This will only work if your objects are relatively sparse. The reason for this is that if there is more than 50% IoU (Intersection of Union) then you won't get multiple detection. This might work slightly better than using scales of 0.1 etc.

**Comment by clw5180** [comment]
> Well one thing that you could try is making your anchor boxes bigger for the smallest objects (eg. setting a minimum bounding box to be 5x5). This will only work if your objects are relatively sparse. The reason for this is that if there is more than 50% IoU (Intersection of Union) then you won't get multiple detection. This might work slightly better than using scales of 0.1 etc.

Unfortunately, for some pictures the objects can be very dense(the task is to detect people's heads in pictures, and sometimes it can be ~1000 heads in a 1024×768 picture). Yesterday I changed the IoU from 0.5 to 0.3, and the phenomenon of multiple detection are reducing. I'll submit the result and find whether I can get higher mAP. 

Moveover, I didn't split the dataset to validation dataset before (I tried Yolo2 earlier and it seems to have the function to automatically split the dataset), so I don't know whether I'm overfitting. Yesterday I split the dataset and add '--val-annotations'. I hope I can get a better model.

Also, I tried '--backbone=resnet152', however it doesn't work.

**Comment by hgaiser** [comment]
Closing this as it is not an issue with the code. For further discussions, please use the Slack #keras-retinanet channel.

https://github.com/fizyr/keras-retinanet#discussions

**Comment by martinzlocha** [comment]
Sorry for bumping a closed issue however I just had a thought on how you could try changing the sizes and strides parameters. Im using VGG and I changed which layers retinanet uses from (https://github.com/fizyr/keras-retinanet/blob/master/keras_retinanet/models/vgg.py#L97):

```layer_names = ["block3_pool", "block4_pool", "block5_pool"]```

to: 

```layer_names = ["block2_pool", "block3_pool", "block4_pool"]```

This allows you to then divide all of the sizes and strides by 2.

You can do the same with ResNet changing (https://github.com/fizyr/keras-retinanet/blob/master/keras_retinanet/models/resnet.py#L112):

**Comment by juanmanuellopezcorrea** [comment]
Hello Martinzlocha. I try train with --backbone  'vgg19' then 'vgg16', also --backbone 'mobilenet128'  ....... but the https://github.com/fizyr/keras-retinanet/ doesn't works with these models. It only works with 'resnet50'. i don't know what is the problem. Can you give an example to use other models different to resnet50.
Thank you, so much .

**Comment by juanmanuellopezcorrea** [comment]
I call train.py something like that
!keras_retinanet/bin/train.py --freeze-backbone --imagenet-weights --backbone  'vgg16' --config "/content/keras-retinanet/drive/My Drive/Post-emergencia_Madrid/Experimento_5/config.ini"   --image-max-side 2000 --image-min-side 1500 --multi-gpu-force  --random-transform --snapshot-path "keras-retinanet/drive/My Drive/Doc/dharma-team/Proyectos/Investigación/Malezas/Proyectos_activos/Post-emergencia_Madrid/Experimento_2/Snapshot/"  --batch-size 8  --steps 100  --epochs 50  csv  "/content/keras-retinanet/drive/My Drive/Post-emergencia_Madrid/Experimento_5/Dataset/CSVs/G_train_set.csv" "/content/keras-retinanet/drive/My Drive/Post-emergencia_Madrid/Experimento_5/Dataset/CSVs/classes.csv" # --val-annotations "/content/keras-retinanet/drive/My Drive/Post-emergencia_Madrid/Experimento_5/Dataset/CSVs/G_validation_set.csv" 

error: 2020-10-09 15:39:52.477018: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
keras_retinanet/bin/train.py:385: UserWarning: Using experimental backbone vgg16. Only resnet50 has been properly tested.
  warnings.warn('Using experimental backbone {}. Only resnet50 has been properly tested.'.format(parsed_args.backbone))
Traceback (most recent call last):
  File "keras_retinanet/bin/train.py", line 553, in <module>
    main()
  File "keras_retinanet/bin/train.py", line 502, in main
    weights = backbone.download_imagenet()
  File "keras_retinanet/bin/../../keras_retinanet/models/vgg.py", line 39, in download_imagenet
    resource = keras.applications.vgg16.vgg16.WEIGHTS_PATH_NO_TOP
AttributeError: module 'tensorflow.keras.applications.vgg16' has no attribute 'vgg16'
