### ISSUE TITLE
resnet50_coco_best_v2.1.0.h5 model giving multiple outputs for same object

### ISSUE THREAD

**Issue by Poonamjo** [fizyr/keras-retinanet#865]
Please make sure that you follow the steps below when creating an issue.
Only use GitHub issues for issues with the implementation, not for issues with specific datasets or general questions about functionality.
If your issue is an implementation question, please ask your question on the #keras-retinanet Slack channel instead of filing a GitHub issue.
You can find directions for the Slack channel here: https://github.com/fizyr/keras-retinanet#discussions

Thank you!

1. Check that you are up-to-date with the master branch of keras-retinanet.
2. Check that you are up-to-date with the latest version of Keras: https://github.com/keras-team/keras.
3. Check that you are up-to-date with the latest version of TensorFlow.
   The installation instructions can be found here: https://www.tensorflow.org/get_started/os_setup.
4. Check that you have read the entire README.md: https://github.com/fizyr/keras-retinanet/README.md.
   Most noticably the FAQ section shows common issues: https://github.com/fizyr/keras-retinanet#faq.
5. Clearly describe the issues you're having including the expected behaviour, the actual behaviour
   and the steps required to trigger the issue.
6. Include relevant output from the commands you're executing, including full stack traces where relevant.
7. Remove this entire message and replace it with your issue.

**Comment by Poonamjo** [comment]
getting output 
Using TensorFlow backend.
2019-01-07 19:02:21.757536: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX AVX2
tv  :  54.4662594795
tv  :  90.4285371304
tv  :  84.6153616905
tv  :  69.2259967327

**Comment by martinzlocha** [comment]
What is the issue in this case? This looks like a warning which is standard if you install tensorflow from binaries. Refer to https://stackoverflow.com/questions/47068709/your-cpu-supports-instructions-that-this-tensorflow-binary-was-not-compiled-to-u

**Comment by hgaiser** [comment]
Can you describe more clearly what it is you did and what it is you're trying to do? What are the outputs that you shared?

**Comment by hgaiser** [comment]
Oh okay, you're using `imageai`. I hadn't seen that project yet, they appear to use our code. I can't support whatever it is they did. My advice is to ask the maintainers of `imageai` or to use our code.
