### ISSUE TITLE
OOM when setting larger image-min-side and --image-max-side, or more scales of anchor?

### ISSUE THREAD

**Issue by clw5180** [fizyr/keras-retinanet#868]
The default parameter is: --image-min-side=800 --image-max-side=1333. I set batch_size = 1 and set 1 ratios and 10 scales , it's ok to run the code. However, when I set about 10+ scales, or I change --image-min-side=1700 --image-max-side=2100, I got OOM error. Before that I ran the debug.py and found that **the result is much better if I use larger image-min-side and image-max-side**  (most of the bbox becomes green rather than red). So how can I avoid the OOM error? Now I can just change  --image-min-side=1400 --image-max-side=1800, it still not so good. Maybe I should try Ubuntu(now I use Windows) and close the graphical interface to save some graphic memory?
Btw, I use RTX2080. The pictures that I train have a lot of small and dense objects , the size of picture is about 1024×768.

**Comment by hgaiser** [comment]
You could try with less scales, smaller image or a GPU with more memory. Other than that, not much to do.

**Comment by clw5180** [comment]
Thanks.
