### ISSUE TITLE
Python version?

### ISSUE THREAD

**Issue by HuangBo-Terraloupe** [fizyr/keras-retinanet#87]
This repository only works for python3 ?
Dose any one has a docker image that contains everything we need for this repo?

best

**Comment by hgaiser** [comment]
Should be python2/3 compatible (if it isn't, make an issue for that). No docker images are available from my end at least.

**Comment by hgaiser** [comment]
Since today we have a Travis CI to check python2/3 compatibility so it should be easier to find out if there are any issues here. Closing this for now.
