### ISSUE TITLE
InvalidArgumentError: Incompatible shapes: [1,200170] vs. [1,60051]

### ISSUE THREAD

**Issue by clw5180** [fizyr/keras-retinanet#870]
I know this question has been asked many times before, however I don't get the solutions.

I have transfered the model to an inference model, and here is my anchor parameters:

**[anchor_parameters]
sizes = 32 64 128 256 512
strides = 8 16 32 64 128
ratios  = 1
scales  = 0.35 0.58 0.88**

I find that the error is 'Incompatible shapes: [1,200170] vs. [1,60051]', and 200170 = 60051 / 3 * 10, so I use 10 scales such as [0.1, 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1.0] to convert, and the error has gone. But what does the number '10' mean ? I have ever used 10 scales before, but know I just use 3 scales in config.ini and train. Why I must set 10 scales to convert the model to an inference model? Hope someone can help me, thanks a lot!! @hgaiser @martinzlocha    

Maybe I used 10 scales to train and I forget that?

**Comment by martinzlocha** [comment]
This is very strange, you should be always using the same config to train and convert the model and I haven't ever seen a problem with that. I think that when you were training it you used a different config file than you think you did.

**Comment by clw5180** [comment]
> This is very strange, you should be always using the same config to train and convert the model and I haven't ever seen a problem with that. I think that when you were training it you used a different config file than you think you did.

Thank you for taking time to answer me, I think you are right.
