### ISSUE TITLE
What should I do with such outputs for bounding boxes?

### ISSUE THREAD

**Issue by AlexandrWh** [fizyr/keras-retinanet#872]
![image](https://user-images.githubusercontent.com/32090077/51128159-449ebe00-1838-11e9-8702-612ebc33199b.png)

It's the result of the following code:

![image](https://user-images.githubusercontent.com/32090077/51128284-8891c300-1838-11e9-9094-4ab527980ec7.png)

So, how can I translate them into the correct coordinates?

**Comment by hgaiser** [comment]
@martinzlocha has given the answer.

https://github.com/fizyr/keras-retinanet#converting-a-training-model-to-inference-model
