### ISSUE TITLE
Tensor name for inference with tensorflow

### ISSUE THREAD

**Issue by nickguimaraes** [fizyr/keras-retinanet#874]
Hello, I have successfully trained a new model on my own dataset and converted the last recorded snapshot into a .h5 file using convert_model.py 

I want to test my model in real time with tensorflow so, I converted the .h5 file into a .pb
The issue I'm facing is, in order to use the .pb file for inference I need to specify the name of a few nodes in the graph. 

image_tensor
detection_boxes
detection_scores
detection_classes
num_detections

As I trained a Keras model these are not the default names for the nodes.   

Looking at the graph.pbtxt it's is easy to tell that image_tensor (input) was named input_1.
With that I'm able to open the camera but as soon as it detects my object it crashes because it can't output the bounding box, class name, prediction score..

I've exported the graph.pbtxt and uploaded to my google drive.
Here is the link,
https://drive.google.com/open?id=1IXtSH9Y_LQk6LZ7iVXf9GjGY1KebaaUY

I wonder if anyone has faced this and would have an answer or some insight to give me.

**Comment by hgaiser** [comment]
You could create a keras model and print `model.outputs`. It should show the tensorflow names.

Closing this as it is not an issue of our code. Please use the Slack channel (README.md) for questions.
