### ISSUE TITLE
Mobilenet mAP is low on VOC2012

### ISSUE THREAD

**Issue by Ezereal** [fizyr/keras-retinanet#877]
Hello, I use resnet50 backbone to train on VOC0712, and get 74.7mAP on VOC2012 test. I think it's normal. But when I use mobilenet128_1.0 backbone to train on VOC0712, it only get 39.4 mAP on VOC2012 test. Both trainings are use the default parameters and use data augmentation. And my pretrained models come from https://github.com/fchollet/deep-learning-models/releases. I want to know whether mobilenet backbone could get such low mAP or something wrong happened. Could you give me some advice to find it out? Thank you for answer my questions.

**Comment by Ezereal** [comment]
> There have been several questions like this on slack and I think that many users experienced much lower mAP than when using other models. One reason for this low performance could be that mobilenet is a community contribution and it might not have been optimized thoroughly.

Thank you, so you mean it may be that the model I used is not trained well. But I use resnet model from the same source, and it performed well. Maybe it used different training ways, I don't think it contribute so low mAP and maybe there are some other reasons.

**Comment by hgaiser** [comment]
> Thank you, so you mean it may be that the model I used is not trained well. But I use resnet model from the same source, and it performed well. Maybe it used different training ways, I don't think it contribute so low mAP and maybe there are some other reasons.

What @martinzlocha means is that we implemented only the ResNet backbone, the other backbones are from people using keras-retinanet. They might contain inconsistencies with the rest of the code. Additionally, people have reported mobilenet performs significantly worse for object detection, so the issue might also come from that.

Closing this for now as there is no direct issue.

**Comment by Ezereal** [comment]
> > Thank you, so you mean it may be that the model I used is not trained well. But I use resnet model from the same source, and it performed well. Maybe it used different training ways, I don't think it contribute so low mAP and maybe there are some other reasons.
> 
> What @martinzlocha means is that we implemented only the ResNet backbone, the other backbones are from people using keras-retinanet. They might contain inconsistencies with the rest of the code. Additionally, people have reported mobilenet performs significantly worse for object detection, so the issue might also come from that.
> 
> Closing this for now as there is no direct issue.

Thank you very much for reply me! I think i know it.

**Comment by liminghuiv** [comment]
For mobilenet, I saw keras-retinanet is used in vehicle detection:
https://github.com/yangliupku/retinanet_detection
Can someone merge it?
