### ISSUE TITLE
issue of test: about "cl.exe" no such file

### ISSUE THREAD

**Issue by Zweiyuan** [fizyr/keras-retinanet#878]
hi, I just went to test the model. So I run the /examples/ResNet50RetinaNet.ipynb   
 
but ,when i load RetinaNet model, there are some errors such as   

> FileNotFoundError             Traceback (most recent call last)
F:\Anaconda\lib\distutils\spawn.py in _spawn_nt(cmd, search_path, verbose, dry_run)
     68         try:
---> 69             rc = os.spawnv(os.P_WAIT, executable, cmd)
     70         except OSError as exc:
FileNotFoundError: [Errno 2] No such file or directory
During handling of the above exception, another exception occurred:
DistutilsExecError                        Traceback (most recent call last)  

AND  

> F:\Anaconda\lib\distutils\spawn.py in _spawn_nt(cmd, search_path, verbose, dry_run)
     74             raise DistutilsExecError(
---> 75                   "command %r failed: %s" % (cmd, exc.args[-1]))
     76         if rc != 0:
> 
> DistutilsExecError: command 'cl.exe' failed: No such file or directory
> 
> During handling of the above exception, another exception occurred:
> 
> CompileError                              Traceback (most recent call last)

I don't know how to solve it.   
I have installed MS vc++2015.

**Comment by hgaiser** [comment]
This doesn't appear to be a keras-retinanet issue. Did you try googling your error?

https://stackoverflow.com/questions/41724445/python-pip-on-windows-command-cl-exe-failed
