### ISSUE TITLE
BBOX issues

### ISSUE THREAD

**Issue by chexianghong** [fizyr/keras-retinanet#882]
Please make sure that you follow the steps below when creating an issue.
Only use GitHub issues for issues with the implementation, not for issues with specific datasets or general questions about functionality.
If your issue is an implementation question, please ask your question on the #keras-retinanet Slack channel instead of filing a GitHub issue.
You can find directions for the Slack channel here: https://github.com/fizyr/keras-retinanet#discussions

Thank you!

1. Check that you are up-to-date with the master branch of keras-retinanet.
2. Check that you are up-to-date with the latest version of Keras: https://github.com/keras-team/keras.
3. Check that you are up-to-date with the latest version of TensorFlow.
   The installation instructions can be found here: https://www.tensorflow.org/get_started/os_setup.
4. Check that you have read the entire README.md: https://github.com/fizyr/keras-retinanet/README.md.
   Most noticably the FAQ section shows common issues: https://github.com/fizyr/keras-retinanet#faq.
5. Clearly describe the issues you're having including the expected behaviour, the actual behaviour
   and the steps required to trigger the issue.
6. Include relevant output from the commands you're executing, including full stack traces where relevant.
7. Remove this entire message and replace it with your issue.

I have debug my training samples by myself. When train the model using my own datasets, the issue is as below:
![image](https://user-images.githubusercontent.com/33365292/51822901-a838e900-2318-11e9-88a8-1da28adac5a6.png)
The bboxes are within the image. I do not know why it shows Image contains the following invalid boxes. 
The bboxes are reasonable. Could you please give a explanation?

**Comment by hgaiser** [comment]
The shape is printed in numpy format: `(rows, cols, channels)`, boxes are printed `[x1, y1, x2, y2]`, so a box `[73, 0, 211, 213]` is outside of the range because `213` is higher than the number of rows `212`.

Closing this as it is not an issue with the code. Please use the Slack channel for usage questions.

**Comment by rafis** [comment]
Why do limit bboxes to image boundaries? Why don't let model learn on those clamped photos treating them like occluded objects?
