### ISSUE TITLE
Problems with tensorflow eager execution

### ISSUE THREAD

**Issue by planaria158** [fizyr/keras-retinanet#890]
Code loops like this one in default_regression_model:
`    for i in range(4):
          outputs = keras.layers.Conv2D(filters=regression_feature_size, activation='relu',
                            name='pyramid_regression_{}'.format(i), **options )(outputs)
`
Work just fine when I'm running RetinaNet on my Mac (python 1.12, keras 2.2.3).

However, in my attempt to better understand the overall code, I've copied blocks of code into separate python scripts (same versions of python, keras, etc).  Now tensorflow complains that the above loop will not run without eager execution enabled.

My question/issue is more of a tensorflow than a retinanet issue.  However, I'm mystified as to why the above code works when run from the retinanet project folder, but not otherwise.

**Comment by hgaiser** [comment]
It's difficult to say anything meaningful about this issue, maybe your question is better suited on the tensorflow channels?

Closing this as it is not an issue with our code base.
