### ISSUE TITLE
Train RetinaNet without Data Augmentation

### ISSUE THREAD

**Issue by butterbee1609** [fizyr/keras-retinanet#894]
Hello,

I have a question regarding the data augmentation process of the random_transform_generator(). I would like to know if it's possible to train the RetinaNet without the data augmentation of the generator because for some type of images it's maybe not the best solution to transform them in any kind.

`transform_generator = random_transform_generator(
            min_rotation=-0,
            max_rotation=0,
            min_translation=(0, 0),
            max_translation=(0, 0),
            min_shear=0,
            max_shear=0,
            min_scaling=(0, 0),
            max_scaling=(0, 0),
            flip_x_chance=0,
            flip_y_chance=0,
       )`

For my understanding, if I would change the generator parameters to this kind of settings there should be no transformation of the images? But if I train the RetinaNet with this Kind of settings the results within the Training process are like this from the start.

1/1435 [..............................] - ETA: 3:12:34 - loss: 0.0882 - regression_loss: 0.0000e+00 - classification_loss: 0.0882

Instead of the results, I get if I use the normal transformation which looks more like a normal start for a training process.

2/1435 [..............................] - ETA: 2:42:46 - loss: 3.9447 - regression_loss: 2.8130 - classification_loss: 1.1317

Is there any way that I can use untransformed images within the generator?

Regards,
butterbee

**Comment by soldierofhell** [comment]
The default (if you don't set --random-transform flag) is:
`transform_generator = random_transform_generator(flip_x_chance=0.5)` 
If you change this line to
`transform_generator = None`
the Generator will have nothing to do in random_transform_group_entry
Actually in my opinion the default should be None, setting it to flip_x is misleading

**Comment by butterbee1609** [comment]
@soldierofhell I tried it and it worked perfectly in case of the training results. Thank you for your fast and helpful answer.
