### ISSUE TITLE
utils.image.read_image_bgr

### ISSUE THREAD

**Issue by soldierofhell** [fizyr/keras-retinanet#896]
What is the purpose of this function? Why just don't use cv2.imread() and get rid of PIL import?

**Comment by hgaiser** [comment]
We used to do that, but PIL gives much better error handling.

**Comment by soldierofhell** [comment]
Thanks for the explanation.

For those who want to get rid of the PIL on inference one have to remember that cv2.imread reads into (height, width, channels) numpy array
