### ISSUE TITLE
saving model

### ISSUE THREAD

**Issue by sameralmusawiy** [fizyr/keras-retinanet#897]
it is a problem with saving the best model, when in an epoch the "mAP" is improved. its model isn't save such below:
![image](https://user-images.githubusercontent.com/28672970/52523731-b3d9c780-2ca9-11e9-9cd3-c8bbc48bc4f0.png)
here in epoch 2, mAP is 28 and in epoch 1 is 10 but it says not improved.
and another question how can I save the value of mAP with model's name?

**Comment by hgaiser** [comment]
> here in epoch 2, mAP is 28 and in epoch 1 is 10 but it says not improved.

It seems you've made modifications to the train script, I can't tell what you've changed and how this might have affected the saving of snapshots. Normally I just save all snapshots for each epoch and later decide which snapshot to use.

> and another question how can I save the value of mAP with model's name?

Currently this is (as far as I know) not possible. Besides, if you'd save the mAP in the model's name, then you can't save the "best" model only anymore.
