### ISSUE TITLE
how to train my PASCAL data.

### ISSUE THREAD

**Issue by CedarYang** [fizyr/keras-retinanet#899]
how to train my pascal data?
i make data 7 classes.but i only want to train first class,so  i change the code in pascal_voc.py like this "voc_classes = {
   'person'   : 0}"
but i get earro:
 class name 'car' not found in classes: ['person']
what should i do?

**Comment by hgaiser** [comment]
The PASCAL generator will still try to parse each annotation. Removing classes from the list of classes will not ignore them. If you want to train on just a few classes it is up to you to make a "subdataset" from PASCAL.

Closing this as it is not an issue with our code.
