### ISSUE TITLE
hello, I am trying to convert resnet50 model in TFlite model..but i m getting error 

### ISSUE THREAD

**Issue by dhaval455** [fizyr/keras-retinanet#900]
hello, i m trying to convert resnet50 model into tflite model..but i m getting error like
1.13.0-dev20190208
Traceback (most recent call last):
  File "convert.py", line 6, in <module>
    converter = tf.lite.TFLiteConverter.from_keras_model_file("model.h5")
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/lite/python/lite.py", line 404, in from_keras_model_file
    keras_model = _keras.models.load_model(model_file)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/keras/saving/hdf5_format.py", line 216, in load_model
    custom_objects=custom_objects)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/keras/saving/model_config.py", line 55, in model_from_config
    return deserialize(config, custom_objects=custom_objects)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/keras/layers/serialization.py", line 69, in deserialize
    printable_module_name='layer')
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/keras/utils/generic_utils.py", line 192, in deserialize_keras_object
    list(custom_objects.items())))
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/keras/engine/network.py", line 1225, in from_config
    process_layer(layer_data)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/keras/engine/network.py", line 1209, in process_layer
    layer = deserialize_layer(layer_data, custom_objects=custom_objects)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/keras/layers/serialization.py", line 69, in deserialize
    printable_module_name='layer')
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/keras/utils/generic_utils.py", line 194, in deserialize_keras_object
    return cls.from_config(cls_config)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/keras/engine/base_layer.py", line 415, in from_config
    return cls(**config)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/keras/layers/normalization.py", line 153, in __init__
    name=name, trainable=trainable, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/checkpointable/base.py", line 456, in _method_wrapper
    method(self, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/keras/engine/base_layer.py", line 130, in __init__
    raise TypeError('Keyword argument not understood:', kwarg)
TypeError: ('Keyword argument not understood:', 'freeze')

**Comment by hgaiser** [comment]
> TypeError: ('Keyword argument not understood:', 'freeze')

This error usually indicates that you are trying to load a keras-retinanet model without specifying the `custom_objects` required. Without specifying the `custom_objects`, keras will try to use their `BatchNormalization` layer, which doesn't accept the `freeze` argument, but the one in `keras-resnet` does. Check [here](https://github.com/fizyr/keras-retinanet/blob/master/keras_retinanet/models/__init__.py#L83) for an example of how we handle it generically.

Closing this as it is not an issue with our code.

**Comment by dasolyn** [comment]
@liminghuiv Do not use `keras.model.load_model`. You should use `keras_retinanet.models.load_model`.

**Comment by tonmoyborah** [comment]
@dasolyn I am facing another issue, wished to get your help on the matter. When I use the retinanet `load_model`, the function `converter.convert()` from tflite throws error. I suspect it cannot get the input array names and shapes right. Did you convert these retinanet models to tflite? If yes, please help

**Comment by 2696120622** [comment]
> hello, i m trying to convert resnet50 model into tflite model..but i m getting error like
> 1.13.0-dev20190208
> Traceback (most recent call last):
> File "convert.py", line 6, in 
> converter = tf.lite.TFLiteConverter.from_keras_model_file("model.h5")
> File "/usr/local/lib/python3.5/dist-packages/tensorflow/lite/python/lite.py", line 404, in from_keras_model_file
> keras_model = _keras.models.load_model(model_file)
> File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/keras/saving/hdf5_format.py", line 216, in load_model
> custom_objects=custom_objects)
> File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/keras/saving/model_config.py", line 55, in model_from_config
> return deserialize(config, custom_objects=custom_objects)
> File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/keras/layers/serialization.py", line 69, in deserialize
> printable_module_name='layer')
> File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/keras/utils/generic_utils.py", line 192, in deserialize_keras_object
> list(custom_objects.items())))
> File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/keras/engine/network.py", line 1225, in from_config
> process_layer(layer_data)
> File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/keras/engine/network.py", line 1209, in process_layer
> layer = deserialize_layer(layer_data, custom_objects=custom_objects)
> File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/keras/layers/serialization.py", line 69, in deserialize
> printable_module_name='layer')
> File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/keras/utils/generic_utils.py", line 194, in deserialize_keras_object
> return cls.from_config(cls_config)
> File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/keras/engine/base_layer.py", line 415, in from_config
> return cls(**config)
> File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/keras/layers/normalization.py", line 153, in **init**
> name=name, trainable=trainable, **kwargs)
> File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/checkpointable/base.py", line 456, in _method_wrapper
> method(self, *args, **kwargs)
> File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/keras/engine/base_layer.py", line 130, in **init**
> raise TypeError('Keyword argument not understood:', kwarg)
> TypeError: ('Keyword argument not understood:', 'freeze')

@dhaval455 Did you solve it?

**Comment by sodiumLights** [comment]
@dhaval455 Did you solve it?

**Comment by yuvalharpaz** [comment]
> @dasolyn I am facing another issue, wished to get your help on the matter. When I use the retinanet `load_model`, the function `converter.convert()` from tflite throws error. I suspect it cannot get the input array names and shapes right. Did you convert these retinanet models to tflite? If yes, please help.
> 
> The error I get: `ValueError: None is only supported in the 1st dimension. Tensor 'input_1' has invalid shape '[None, None, None, 3]'`

I have the same issue when I trying to convert 'resnet50_coco_best_v2.1.0.h5'.
Did you solved your issue?

**Comment by 2696120622** [comment]
@yuvalharpaz 
You should specify the size of input as [None,height,width,3] by setting the input_shapes when converting like the following.   
`converter = tf.lite.TFLiteConverter.from_keras_model_file(   
    xxx.h5,   
    custom_objects=custom_objects,    
    input_shapes={'input_1':[None,896,896,3], ...},    
    )  
`
If you can convert the model and infer with the converted tf lite model successfully, can you share your converting code?

**Comment by yuvalharpaz** [comment]
export CPATH="/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/"



‫בתאריך יום ב׳, 24 בפבר׳ 2020 ב-12:59 מאת ‪XiangyangBu‬‏ <‪
notifications@github.com‬‏>:‬

**Comment by dasolyn** [comment]
I'm sorry but I don't know about TFLite issue. I just know that we should use `load_model` function from `keras_retinanet`, to load a retinanet model successfully.
