### ISSUE TITLE
There are some issues when I want to change the arguments in train.py.

### ISSUE THREAD

**Issue by Zweiyuan** [fizyr/keras-retinanet#901]
AttributeError: 'Namespace' object has no attribute 'batch_size'

When I changed the argument in train.py , like this:
I only changed the arguments of batch-size and epochs:

Line395 and Line399
```
parser.add_argument('--batch-size=5',       help='Size of the batches.', default=1, type=int)

parser.add_argument('--epochs=200',           help='Number of epochs to train.', type=int, default=50)
```

But , I met a issue:

> Traceback (most recent call last):
  File "keras_retinanet/bin/train.py", line 493, in <module>
    main()
  File "keras_retinanet/bin/train.py", line 437, in main
    train_generator, validation_generator = create_generators(args, backbone.preprocess_image)
  File "keras_retinanet/bin/train.py", line 217, in create_generators
    'batch_size'       : args.batch_size,
AttributeError: 'Namespace' object has no attribute 'batch_size'

Thank you for your advise.

**Comment by LaurensHagendoorn** [comment]
batch-size != batch_size

**Comment by Zweiyuan** [comment]
@LaurensHagendoorn Thank you. But how to solve it?

By the way, if I don't change the parameters(all parameters are default), it can run.

**Comment by LaurensHagendoorn** [comment]
oh interesting, apperntly the - is replaced with _, I figured you just made a typo sorry.
in doing what you did you changed "batch_size" to "batch_size=5" you should instead either properly call the script, or change the default parameter like:
`parser.add_argument('--batch-size` ,      help='Size of the batches.', **default=5**, type=int)

**Comment by hgaiser** [comment]
If you want to hardcode a different default, @LaurensHagendoorn 's solution should work.
