### ISSUE TITLE
Getting predictions for multiple images in "model.predict_on_batch(inputs)".

### ISSUE THREAD

**Issue by Rajat-Mehta** [fizyr/keras-retinanet#902]
I have a test set of 20,000 images and I want to get predictions for those images using my trained retina-net model. I suppose the predict_on_batch method takes a single image at a time but that will take a lot of time in my case. 

Is there a way I can feed multiple images to "model.predict_on_batch(inputs)" and get predictions for 20,000 images without looping over each and every single image? 
Also, how to load these images, do I need to use dataloaders for this?

**Comment by Rajat-Mehta** [comment]
Any suggestions on this ?

**Comment by hgaiser** [comment]
You can load multiple images (depending on your hardware) in one batch and process the batch in one go. It's up to you to make a function that generates these batches though. If you're using one of our generators that is supported, so you could use that, but that does mean you need to format your dataset into one of our supported formats (CSV is recommended). On the other hand, making a function that generates a batch using multiple images shouldn't be that hard.

Closing this as it is not an issue with our code.

**Comment by knobel-dk** [comment]
Here is a simple example:

```python
import numpy as np
inputs = np.concatenate([image[:,np.newaxis] for image in images], axis=0)
boxes, scores, labels = self.model.predict_on_batch(inputs)
```

**Comment by jackie-angelswing** [comment]
@knobel-dk 

Will predict_on_batch allow for a faster inference speed compared to when we feed the model one image at a time?

**Comment by knobel-dk** [comment]
@jackie-angelswing Yes, it will be many times faster. You could test it yourself to see how much faster on your device.

Keep in mind that too many images (also called too big of a batch size) will cause out of memory error so test what size is right for you. If you have a simpel setup you could do 2 or 4 images at once. With a bigger setup 12 or 16 images at once.

Depending on your implementation requirements make sure that the model is loaded once in the beginning of the process and not for every image since loading the model will also take a lot of time.

Good luck.

**Comment by Nimra01** [comment]
I have trained retinanet model on custom dataset, now I have its trained and inference model in .h5 format. I have tested it on images and videos, but now I want it to run on my webcam taking the real time video. I am using this code:
`import cv2
import numpy as np
from PIL import Image
import keras
from keras import models

from keras_retinanet import models
from keras_retinanet.utils.image import read_image_bgr, preprocess_image, resize_image
from keras_retinanet.utils.visualization import draw_box, draw_caption
from keras_retinanet.utils.colors import label_color


#Load the saved model
custom_objects = retinanet.custom_objects.copy()
custom_objects.update(keras_resnet.custom_objects)

#Load model
model = keras.models.load_model('E:/FYP_UAV/Retinanet/cconverted_model.h5', custom_objects=custom_objects)
#model = keras.models.load_model('cconverted_model.h5')
video = cv2.VideoCapture(0)

while True:
        _, frame = video.read()

        #Convert the captured frame into RGB
        im = Image.fromarray(frame, 'RGB')

        #Resizing into 128x128 because we trained the model with this image size.
        im = im.resize((128,128))
        img_array = np.array(im)

        #Our keras model used a 4D tensor, (images x height x width x channel)
        #So changing dimension 128x128x3 into 1x128x128x3 
        img_array = np.expand_dims(img_array, axis=0)

        #Calling the predict method on model to predict 'me' on the image
        prediction = int(model.predict(img_array)[0][0])

        #if prediction is 0, which means I am missing on the image, then show the frame in gray color.
        if prediction == 0:
                frame = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)

        cv2.imshow("Capturing", frame)
        key=cv2.waitKey(1)
        if key == ord('q'):
                break
video.release()
cv2.destroyAllWindows()`

I am getting an error "NameError: name 'retinanet' is not defined". can anyone suggest that how can I run it on live stream of webcam?

**Comment by g-jindal2001** [comment]
> Here is a simple example:
> 
> ```python
> import numpy as np
> inputs = np.concatenate([image[np.newaxis,:] for image in images], axis=0)
> boxes, scores, labels = self.model.predict_on_batch(inputs)
> ```

@knobel-dk  can you please give an example of images variable in this block of code?

**Comment by knobel-dk** [comment]
> > Here is a simple example:
> 
> > 
> 
> > ```python
> 
> > import numpy as np
> 
> > inputs = np.concatenate([image[np.newaxis,:] for image in images], axis=0)
> 
> > boxes, scores, labels = self.model.predict_on_batch(inputs)
> 
> > ```
> 
> 
> 
> @knobel-dk  can you please give an example of images variable in this block of code?

It's already there in the second line inside the list comprehension 👍
