### ISSUE TITLE
--save-path Not working with evaluate.py

### ISSUE THREAD

**Issue by mbufi** [fizyr/keras-retinanet#903]
When using `evaluate.py` , has anyone used the argument `--save-path` successfully? I continues to tell me that the command is not found. When I then looked at `evaluate.py` I see :

`if args.save_path is not None and not os.path.exists(args.save_path):
     os.makedirs(args.save_path)`

Should this be changed? If you got it to work, please let me know! Also, what is it actually saving? Pictures with annotations?

**Comment by mbufi** [comment]
I just tried running another command and it cannot find any commands for some reason. Do you know what could cause this to happen to my install? importing keras_retinanet works. So I know that can't be it..

**Here is command I have used:** 
`retinanet-train --batch-size 4 --steps 436 --epochs 50 \
    --weights resnet50_coco_best_v2.1.0.h5 \
    --gpu 1 \
    --random-transform \
    --tensorboard-dir Sputter/tensorboard \
    --snapshot-path Sputter/snapshots \ 
    csv Sputter/NG_TRAIN/train.csv Sputter/NG_TRAIN/retinanet_classes.csv`

**Here is the Error:** 
`(retinanet_new) mbufi@mbufi:~/MusashiAi/GithubRepos/keras-retinanet$ ./train_retinanet.sh 
Using TensorFlow backend.
usage: retinanet-train [-h]
                       [--snapshot SNAPSHOT | --imagenet-weights | --weights WEIGHTS | --no-weights]
                       [--backbone BACKBONE] [--batch-size BATCH_SIZE]
                       [--gpu GPU] [--multi-gpu MULTI_GPU] [--multi-gpu-force]
                       [--epochs EPOCHS] [--steps STEPS] [--lr LR]
                       [--snapshot-path SNAPSHOT_PATH]
                       [--tensorboard-dir TENSORBOARD_DIR] [--no-snapshots]
                       [--no-evaluation] [--freeze-backbone]
                       [--random-transform] [--image-min-side IMAGE_MIN_SIDE]
                       [--image-max-side IMAGE_MAX_SIDE] [--config CONFIG]
                       [--weighted-average] [--workers WORKERS]
                       [--max-queue-size MAX_QUEUE_SIZE]
                       {coco,pascal,kitti,oid,csv} ...
retinanet-train: error: argument dataset_type: invalid choice: ' ' (choose from 'coco', 'pascal', 'kitti', 'oid', 'csv')
./train_retinanet.sh: line 15: csv: command not found
`

**Comment by de-vri-es** [comment]
You have created a `./train_retinanet.sh` script that is broken.

**Comment by mbufi** [comment]
What's the error? It was working before...

**Comment by de-vri-es** [comment]
There's really no way for us to know, considering we didn't write the script and you haven't shown it to us. You didn't event mention that there was a script, we had to divine that fact for ourselves.

Our guidelines for posting issues is quite clear that you should always include the exact steps to reproduce the problem, and include relevant error output. Your initial issue failed to do either, and you still haven't shown the steps to reproduce. Please make sure that you follow these guidelines when posting to the issue tracker.

Also, please note that support for your own code using retinanet is generally out of scope for this issue tracker, unless the code is exposing a problem with the retinanet API or implementation. That does not appear to be the case here though.

Now, using my powers of divination again (with the help of some tea leaves and coffee residue), I predict that you have an unescaped linebreak or semicolon in your `train_retinanet.sh` script, right before the dataset parameters (starting with `csv`).

**Comment by hgaiser** [comment]
I'm assuming the error is in your script and not in our code. If you feel differently, feel free to reopen and provide some example.
