### ISSUE TITLE
considering duplicate positive prediction as a false positive in eval.py

### ISSUE THREAD

**Issue by mailcorahul** [fizyr/keras-retinanet#904]
I was going through eval.py
line number:205(https://github.com/fizyr/keras-retinanet/blob/master/keras_retinanet/utils/eval.py#L205)
```python
                if max_overlap >= iou_threshold and assigned_annotation not in detected_annotations:
                    false_positives = np.append(false_positives, 0)
                    true_positives  = np.append(true_positives, 1)
                    detected_annotations.append(assigned_annotation)
                else:
                    false_positives = np.append(false_positives, 1)
                    true_positives  = np.append(true_positives, 0)
```

assigned annotation represents the index of already matched ground truth box, if i am not wrong. but if there are other predicted boxes(multiple predictions for one gt) which still overlaps with that same ground truth box, the above code considers it to be a false positive. is that correct?
shouldn't that be regarded as neither a true positive nor a false positive? @hgaiser

**Comment by hgaiser** [comment]
The logic for this evaluation is taken from `py-faster-rcnn`. Whether it is correct or not is difficult to say.

If you can provide evidence that the approach is incorrect according to academic standards ,feel free to re-open this issue.

**Comment by guker** [comment]
you can see https://github.com/facebookresearch/Detectron/blob/05d04d3a024f0991339de45872d02f2f50669b3d/lib/datasets/voc_eval.py#L54

**Comment by mailcorahul** [comment]
@guker thanks!
I know this shouldn't be a big concern since we do NMS on top of it anyway. But I feel that counting them as FPs is not really right as the model is still predicting it correctly.
