### ISSUE TITLE
Use resnet50_coco_best_v2.1.0.h5  and custom csv

### ISSUE THREAD

**Issue by a256673** [fizyr/keras-retinanet#905]
Sorry, My I ask you where can i get coco/weights.h5 ?   I only get resnet50_coco_best_v2.1.0.h5
when i use this h5 and key python keras_retinanet/bin/train.py --weights /path/to/resnet50_coco_best_v2.1.0.h5    csv /path/to/annotations.csv /path/to/classes.csv

I will get "train.py: error: ambiguous option: --weight could match --weights, --weighted-average"

and I key python keras_retinanet/bin/train.py  --imagenet-weights /path/to/resnet50_coco_best_v2.1.0.h5    csv /path/to/annotations.csv /path/to/classes.csv    

I will get " train.py: error: argument dataset_type: invalid choice: '/home/kile/RSNA/keras-retinanet-0.5.0/resnet50_coco_best_v2.1.0.h5' (choose from 'coco', 'pascal', 'kitti', 'oid', 'csv')"

how can i use my dataset and  resnet50_coco_best_v2.1.0.h5 to train ??

**Comment by martinzlocha** [comment]
Try the following (I have added an equal sign):

```python keras_retinanet/bin/train.py --weights=/path/to/resnet50_coco_best_v2.1.0.h5 csv /path/to/annotations.csv /path/to/classes.csv`

**Comment by a256673** [comment]
thank for you, i have been successful by key in "python /home/kile/RSNA/keras-retinanet-0.5.0/keras_retinanet/bin/train.py --weights /home/kile/RSNA/keras-retinanet-0.5.0/resnet50_coco_best_v2.1.0.h5 --snapshot-path /home/kile/RSNA/keras-retinanet-0.5.0/keras_retinanet/bin/snapshots/pretrain --gpu 4,5,6,7 csv /home/kile/RSNA/40/train_25284.csv /home/kile/RSNA/40/classes.csv",
but i do not know why...   XD

**Comment by hgaiser** [comment]
> I will get "train.py: error: ambiguous option: --weight could match --weights, --weighted-average"

By the looks of that error you passed as argument `--weight` and not `--weights` (plural). I'm guessing that this is your issue. I'll close this issue as it appears to be unrelated to our code.
