### ISSUE TITLE
IOU Score question

### ISSUE THREAD

**Issue by butterbee1609** [fizyr/keras-retinanet#910]
Hello,

I have a question regarding the IoU Score. For example, if we have a GT box (green) and a predicted box (red) then we calculate the intersection of the union and we get our score. My question is how is the IOU score interpreted if the predicted box lays in the GT box. So it's more like a subset. Means this that the IOU is 0?

**Take a look at the attached Picture for a visualization.** (Sorry for my bad drawing skills :D)
[Notiz 19.02.2019.pdf](https://github.com/fizyr/keras-retinanet/files/2880295/Notiz.19.02.2019.pdf)

I'm asking this question because I'm wondering how this kind of outcome is interpreted because for my understanding it could be that the predicted box is more accurate than the GT box?

Could someone explain to me how this kind of box situations are handled because I want to know how those affect my mAp score?

Regards,
butterbee

**Comment by hgaiser** [comment]
IOU means **intersection** over **union**. Your case where one box is completely inside the other doesn't change these interpretations. The intersection will be the area of the smaller box, the union will be the area of the bigger box.

Using a real world example, if you have a box of `10x10` and a box of `5x5` which is completely inside the other box, then the intersection is `5 * 5 = 25`, the union is `10 * 10 = 100` so the IOU is `25 / 100 = 0.25`.

Closing this as there is no issue here.
