### ISSUE TITLE
The problem of computer not  responding when the image testing process

### ISSUE THREAD

**Issue by zerok01** [fizyr/keras-retinanet#912]
Hi,
I trained my own data set. Then I converted the model to the inference model. I wanted to test a sample image by ResNet50RetinaNet.ipynb. However, in my model.predict_on_batch line, my computer is not responding and the test process is not running. My Tensorflow version 1.5, GPU 4GB GTX1050ti and Keras version 2.2. Where is the problem? Thanks

**Comment by hgaiser** [comment]
Does the terminal provide any meaningful output? Maybe it fails to find the GPU or some other issue. Some more information would be nice.

Do other tensorflow applications work?

Also, tensorflow 1.5 is quite old, consider updating it to see if that helps.

**Comment by zerok01** [comment]
Thanks for your answer. I have upgraded Tensorflow and the error has been solved. Is there a sample code for object detection on video?

**Comment by hgaiser** [comment]
> Is there a sample code for object detection on video?

Nope, there isn't :)

**Comment by zerok01** [comment]
My problem is solved. Topic may close by admin. Thanks...
