### ISSUE TITLE
How does the model support multiple input image sizes?

### ISSUE THREAD

**Issue by boozyguo** [fizyr/keras-retinanet#914]
The model can input images of various sizes. For convolutions layers, it is ok. 
However, the 'class network' and the 'bbox network' use fully connected layers, I wonder how the model deal with the different numbers of feature maps?
Thank you.

**Comment by jonla1** [comment]
Every fully connected layer can be represented by a convolution layer with a kernel of size 1x1 (the number of filters/depth is the output dimension).

**Comment by boozyguo** [comment]
Thank you @jonla1 .  But I can not find the 1x1 convolution layer in the model. could you help me point out these codes?

**Comment by hgaiser** [comment]
Retinanet doesn't contain any fully connected layers, not even in the classification and regression submodels. They are all convolutional layers.

Closing this as there is no issue here.
