### ISSUE TITLE
changing anchors parameters

### ISSUE THREAD

**Issue by Pked01** [fizyr/keras-retinanet#919]
hello, 
I changed anchors parameters using anchors.py file in utils
I was able to run training successfully, and even in testing model is loading and running fine, but there are no predictions.
Can anyone please explain what are these four parameters 
sizes = [8,16,32, 64, 128],
strides = [8, 16, 32, 64, 128],
ratios = np.array([1], keras.backend.floatx()),
scales = np.array([2 ** 0, 2 ** (1.0 / 3.0), 2 ** (2.0 / 3.0)], keras.backend.floatx()),

https://github.com/fizyr/keras-retinanet/issues/462  its written here that anchor support is not there yet. is it?
how changes i should do for getting correct inference?

**Comment by lazydroid** [comment]
`sizes` are the base sizes of the anchors, like 8x8, 16x16 and so on. besides base sizes there are anchors enlarged according to `scales` and squeezed into rectangles according to the `ratios`. There are 9 basic anchors, repeated at `strides` along the image. all in all there are 57600 anchors evenly distributed over the image.

**Comment by hgaiser** [comment]
@lazydroid answered your question regarding the values. Why you're not getting any predictions is hard to say. Either way, the github issue tracker is not the right place to ask these questions (use the Slack channel), so I'll close this issue.
