### ISSUE TITLE
Re: Time required for the inference

### ISSUE THREAD

**Issue by bundelesneha05** [fizyr/keras-retinanet#921]
I did the inference as suggested in the ResNet50RetinaNet.ipynb using ResNet50 as backbone architecture on Tesla P100-PCIE-16GB.  I have some issues with this,
1. while doing batch processing using, **model.predict_on_batch** time has taken for one image and batch of 2 and 4 images are linear. 
For **2** : 4.94sec, **4**: 3.85 sec

2. Also, when I tried, model.predict() with various batch_size  it also gave, linear time graph for the one vs the stack of images. 
For **2**: 3.77sec, **4**: 3.77sec
This is counterintuitive as this should be in constant time. 

I have tried a similar operation with Tensorflow based SSD mobilenet and do see the same time being taken for 1 image, 2 images, 4 images, etc. The time graph was constant and not linear.
FYI, I wanted to test the model using tensorflow, so I tried to convert.h5 to.pb. I am facing some errors and am opening a different bug for the same.

Thanks in advance!

**Comment by hgaiser** [comment]
Are these times the time per image, for different batch sizes, or the total time for the entire batch?

**Comment by hgaiser** [comment]
Any update on this @bundelesneha05 ?
