### ISSUE TITLE
Bug in AP calculation

### ISSUE THREAD

**Issue by mikebind** [fizyr/keras-retinanet#923]
There is a small bug in the calculation of AP in utils/eval.py, in the function _compute_ap.

In the case were the first recall value is non-zero, which will happen whenever the highest confidence detection is a true positive, the code as currently written will not account for the area contributed by the recall range between 0 and recall[0].  However, this is easy to account for, as we know that the precision in this range is 1 (because there is only one detection being considered, and it is a true positive), and we know that recall[0] is 1/num_annotations, so the missing area is always 1*1/num_annotations.  Also, since num_annotations isn't passed to the _compute_ap function, it's fine to just use recall[0] instead. 

So, if recall[0] == 0, then the current AP calculation is correct, and if recall[0] != 0, then the current AP is off by recall[0].  This means that we can actually just add recall[0] to the current calculation and the result will be correct (though the code might look a little confusing).  Perhaps a little clearer if we multiply it by the first entry in the precision vector (which will be one for the case that we are correcting). 

Current line 54 of eval.py:
`ap = np.sum((mrec[i + 1] - mrec[i]) * mpre[i + 1])`

Corrected line 54 of eval.py:
`ap = np.sum((mrec[i + 1] - mrec[i]) * mpre[i + 1]) + mrec[0] * mpre[0]`

I know there are github mechanisms involving generating a pull request, but I am not a skilled github user, and this is so minor that I figure it is not worth learning that whole system just to suggest a one-line solution to a minor bug.  

Note that the size of this error is 1/num_annotations, so it quickly becomes insignificant for any real data set, but can be quite large for small/toy examples.

**Comment by hgaiser** [comment]
Interesting, I'm not that familiar with the exact calculations of mAP to be honest, but I see your point. We took most of the implementation for computing mAP from [py-faster-rcnn](https://github.com/rbgirshick/py-faster-rcnn), do you see the same issue there as well?

**Comment by mikebind** [comment]
Yes, the code there should give the exact same result.  I should also mention that this bug could also be fixed by inserting a point with zero recall and zero precision at the beginning of the precision and recall vectors.  It is possible that this is guaranteed to happen by some other part of the code, but I have not found whether this is somehow the case.   I will also submit an issue at py-faster-rcnn.

**Comment by qualiaa** [comment]
Is this case not handled by lines 42-43?

    # correct AP calculation
    # first append sentinel values at the end
    mrec = np.concatenate(([0.], recall, [1.]))
    mpre = np.concatenate(([0.], precision, [0.]))

**Comment by hgaiser** [comment]
@mikebind ?

**Comment by mikebind** [comment]
Yup, sorry about that.  I withdraw my issue.  I misread that earlier line as only adding the point to the right end.  Now, my only suggestion is to change that comment to read "first append sentinel values at the ends" instead of "... end"
