### ISSUE TITLE
Retinanet with Oriented Bounding Boxes

### ISSUE THREAD

**Issue by zerok01** [fizyr/keras-retinanet#925]
Hi, 
I have a data set labeled x1, y1, x2, y2, x3, y3, x4, y4 (oriented). Retinanet uses horizontal bbox technique. I want to change the architecture and train with oriented bbox. Where should I begin at this point and what should I do? I read the article, but I couldn't get it right in my head. Please help me. Thanks

**Comment by de-vri-es** [comment]
I'm sorry, but the issues you are describing is out of scope for this issue tracker. You may join the Slack channel instead. See the README for more information.
