### ISSUE TITLE
Convert the tensorflow backend developed model to theano

### ISSUE THREAD

**Issue by shahsahilj** [fizyr/keras-retinanet#927]
I am trying to convert the model from a tensorflow backend to theano backend. But for that, i first need the structure of the model in both the backends . Then i can load the weights in the tensorflow model and convert it layer by layer to theano weights. But, i cannot find the structure of the model and i dont know how to get the theano structure. Can someone please provide a structure of the model that is used in both the backends so that i can proceed with the conversion?

PS - this is the code that i am using for converting the weights: https://github.com/titu1994/Keras-Classification-Models/blob/master/weight_conversion_theano.py

**Comment by hgaiser** [comment]
Currently theano is not supported, because the functions from the backend are not wrapped with theano functions. Did you intend to write those backend functions?

**Comment by hgaiser** [comment]
Any update on this ?

**Comment by shahsahilj** [comment]
I currently do not have enough resources to do the conversion sorry
