### ISSUE TITLE
OOM？

### ISSUE THREAD

**Issue by HuangQinJian** [fizyr/keras-retinanet#928]
[[Node: loss/classification_loss/Mean_2/_2543 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_9461_loss/classification_loss/Mean_2", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

What can I  do?

**Comment by hgaiser** [comment]
It seems your GPU doesn't have enough memory. Either way, this is not an issue for the GitHub tracker, please use the slack channel for usage questions.
