### ISSUE TITLE
train.py: error: unrecognized arguments: --multi-gpu 2

### ISSUE THREAD

**Issue by HuangQinJian** [fizyr/keras-retinanet#929]
I use 
`python keras_retinanet/bin/train.py csv keras_retinanet/CSV/annotations.csv keras_retinanet/CSV/classes.csv --multi-gpu 2`

Then error arose:
`train.py: error: unrecognized arguments: --multi-gpu 2
`

**Comment by hgaiser** [comment]
Every argument after `csv` is handled by the `csv` argument parser, `--multi-gpu` needs to be passed before `csv`. Also, multi-gpu training in Keras is a bit sketchy in my opinion, use it at your own risk ;)
