### ISSUE TITLE
Testing model on pretrained resnet101 and resnet152 weights

### ISSUE THREAD

**Issue by gurjeet8197** [fizyr/keras-retinanet#935]
I am not able to test this model on pre-trained Keras resnet101 and resnet152 weights. I am getting the following error when try to test the model,
ValueError: Cannot create group in read only mode.

**Comment by hgaiser** [comment]
Which pretrained weights are you referring to ?

**Comment by gurjeet8197** [comment]
I am taking weights from [this](https://github.com/keras-team/keras-applications/releases/tag/resnet) repository.

**Comment by hgaiser** [comment]
Those resnets are not compatible with our resnet. The resnet from Keras doesn't follow the official implementation in [caffe](https://github.com/KaimingHe/deep-residual-networks), ours does. There is currently no pretrained COCO network for resnet101 or resnet152.

**Comment by gurjeet8197** [comment]
Thank you for the information.

**Comment by danijames** [comment]
> Those resnets are not compatible with our resnet. The resnet from Keras doesn't follow the official implementation in [caffe](https://github.com/KaimingHe/deep-residual-networks), ours does. There is currently no pretrained COCO network for resnet101 or resnet152.

Is there any resnet101 or resnet152 pretrained weights on keras available by now? if other than COCO? If I get COCO then it will be far better since I am doing some comparison.
