### ISSUE TITLE
ValueError: invalid CSV annotations file: keras_retinanet/CSV/annotations.csv: line 1: malforme                         d x1: invalid literal for int() with base 10: '210.0'

### ISSUE THREAD

**Issue by CapricornZhang** [fizyr/keras-retinanet#936]
When debugging with the csv datasets,I got the ValueError：
ValueError: invalid CSV annotations file: keras_retinanet/CSV/annotations.csv: line 1: malforme                         d x1: invalid literal for int() with base 10: '210.0'.

And the first line of my annotation is as follows:
JPEGImages/20180131_71.jpg,210.0,46.0,730.0,549.0,car

Must the value of 'x1,y1,x2,y2' be integers？

**Comment by hgaiser** [comment]
Yep they must be.

**Comment by CapricornZhang** [comment]
> Yep they must be.
Thank you for your response.
