### ISSUE TITLE
Using the default model(Resnet50) to train my own dataset,when evaluating the mode,I got all the AP 0.0.

### ISSUE THREAD

**Issue by CapricornZhang** [fizyr/keras-retinanet#939]

**Comment by CapricornZhang** [comment]
Even when I evaluating the Resnet50 model with my training dataset , I also get the AP zero.

**Comment by hgaiser** [comment]
The github issues page is not for debugging datasets. Unless you think there's an underlying issue in the code of keras-retinanet, I'll close this issue. Please use the Slack channel for help on usage.
