### ISSUE TITLE
Unable to use model to predict

### ISSUE THREAD

**Issue by chardch** [fizyr/keras-retinanet#941]
I am having trouble predicting with a model that I trained on my own dataset. I trained it using `python keras_retinanet/bin/train.py --backbone=resnet50 --config=anchors.cfg --gpu=0 --snapshot=<my_previous_snapshot> --image-min-side=480 --batch-size=2 --steps=500 --epochs=30 csv .../annotations2_train.csv .../class_map.csv --val-annotations=.../annotations2_val.csv`

This worked fine.
However, when I follow the example juptyer notebook to try to use the model to predict, I get the following shape mismatch error when calling 
`boxes, scores, labels = model.predict_on_batch(np.expand_dims(image, axis=0))`:

`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/keras/engine/training.py", line 1274, in predict_on_batch
    outputs = self.predict_function(ins)
  File "/usr/local/lib/python3.5/dist-packages/keras/backend/tensorflow_backend.py", line 2715, in __call__
    return self._call(inputs)
  File "/usr/local/lib/python3.5/dist-packages/keras/backend/tensorflow_backend.py", line 2675, in _call
    fetched = self._callable_fn(*array_vals)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1439, in __call__
    run_metadata_ptr)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/errors_impl.py", line 528, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: Incompatible shapes: [1,96100] vs. [1,43245]
	 [[{{node boxes/mul_7}}]]`

My steps before calling model.predict_on_batch:
...imports...
`model = models.load_model('./snapshots/...my_snapshot.h5')`
`model = models.convert_model(model)`
`labels_to_names = {0: 'building'}`
`image = read_image_bgr('...my_image')`
`image, scale = resize_image(image, min_side = 480) # to match the size from training`

I didn't have any issues like this previously when predicting on a model that I trained. The only thing I changed this time around was passing in a config file with different anchors.

`anchors.cfg`

`[anchor_parameters]`
`sizes = 16 32 64 128 256`
`strides = 8 16 32 64 128`
`ratios = 0.5 0.75 1 1.5 2`
`scales = 0.8 1 1.2 1.6`

**Comment by hgaiser** [comment]
Anchor params also need to be passed to [`convert_model`](https://github.com/fizyr/keras-retinanet/blob/master/keras_retinanet/models/__init__.py#L86).

**Comment by chardch** [comment]
Thanks for the tip! I'll try that out

**Comment by Samjith888** [comment]
Refer the following to solve this issue
https://github.com/priya-dwivedi/aerial_pedestrian_detection/issues/3#issuecomment-535386616
