### ISSUE TITLE
parse_anchor_parameters has type error

### ISSUE THREAD

**Issue by chardch** [fizyr/keras-retinanet#943]
I am trying to convert my model to an inference model, but need to pass in the anchors from my config file.

When I run
`anchor_parameters = parse_anchor_parameters('anchors.txt')`
I get the following:
`Traceback (most recent call last):`
`  File "<stdin>", line 1, in <module>`
`  File "/usr/local/google/home/chardch/DisasterDetection/building_detection/keras-retinanet/keras_retinanet/utils/config.py", line 31, in parse_anchor_parameters`
`    ratios  = np.array(list(map(float, config['anchor_parameters']['ratios'].split(' '))), keras.backend.floatx())`
`TypeError: string indices must be integers`

my config file, `anchors.txt`
`[anchor_parameters]`
`sizes = 16 32 64 128 256`
`strides = 8 16 32 64 128`
`ratios = 0.75 1 1.5`
`scales = 0.8 1.2 1.6`

Any help with this issue would be greatly appreciated.

**Comment by hgaiser** [comment]
Why aren't you using the retinanet [converter](https://github.com/fizyr/keras-retinanet/blob/master/keras_retinanet/bin/convert_model.py#L53) ?

**Comment by hgaiser** [comment]
Any update on this ?

**Comment by chardch** [comment]
I ended up using the retinanet evaluater to output the results. Thanks for pointing out the converter, but the hack from before was sufficient for my use case.
