### ISSUE TITLE
Evaluation with a csv format trained model gives 0.0 mAP

### ISSUE THREAD

**Issue by tonmoyborah** [fizyr/keras-retinanet#947]
I have used this repository without any complaints for the coco format but now I tried to switch to the csv mode. I made the csv files for the class mappings and annotations as suggested and used the debug script to validate the boxes, they are fine. Then I trained the model with the pretrained coco model provided with the args `--weights` and other normal settings. These are similar to [this](https://github.com/fizyr/keras-retinanet/issues/500#issue-331227518) usage. I trained the model overnight for 30 epochs on custom data, the training abruptly ended at 21 epochs (due to storage issues), the training time evaluation showed an mAP of 91%. So I took the 20th snapshot (the previous snapshot) and created an inference model. Now when I evaluate using the `evaluate.py` file provided, the mAP is 0.0. I run the demo notebook code on some images of the training data itself and I realize the confidence scores are very less (~ 0.25).

I did this again and created a model with train time val AP of 80% and again the evaluate shows 0.0 mAP and there are no detections over 0.6 conf in the val set when I separately visualize them. I have used default sizes for min max image sides.

My arguments were
--epochs
30
--batch-size
2
--random-transform
--backbone
resnet50
--workers
3
--lr
1e-05
--steps
5241
--weights
/path/to/resnet50_coco_best_v2.1.0.h5
--snapshot-path
/path/to/training_models/save-dir
--tensorboard-dir
/path/to/models/tensorboard_logs
csv
/path/to/csv_annotations/train_annotations.txt
/path/to/class_names.txt
--val-annotations
/path/to/val_annotations.txt

**Comment by tonmoyborah** [comment]
I realised , like everytime, the `preprocess_image` function was the problem. I forget to change it everytime I use a new network. The name `preprocess_image` being same everywhere doesn't help either.

**Comment by hgaiser** [comment]
We're open to improvements ;)
