### ISSUE TITLE
How to include text in anchor box as additional feature in training & inference both ?

### ISSUE THREAD

**Issue by x0v** [fizyr/keras-retinanet#948]
The objects that I want to detect contains text as well, so how can i append the text also as a feature in retinanet model ?

**Comment by hgaiser** [comment]
The github issues page is not for usage questions, please use the keras-retinanet Slack channel for that ( see the README.md ).

**Comment by x0v** [comment]
hi @hgaiser 
Thanks for your reply & sorry to post here about this.

README doesn't contain any such details.
and on slack, I don't think so, any body would reply. ([my prior experience with slack channel](https://kerasteam.slack.com/archives/C0UDS3N1E/p1551337485003600))

My thought was to recognise text in anchor boxes and append that as a feature. I am unable to figure out implementation details though.

Please guide me on this.
