### ISSUE TITLE
How to include text in anchor box as additional feature in training & inference both ?

### ISSUE THREAD

**Issue by x0v** [fizyr/keras-retinanet#949]
hi @hgaiser [](url)
Thanks for your reply & sorry to post here about this.

README doesn't contain any such details.
but on slack, I didn't get any response there.

My thought was to recognise text in each of the anchor boxes and append that as a feature. I am unable to figure out implementation details though.

To give better context, please see [this ](https://imgur.com/a/qttNLmo) image. Now suppose, I want to detect both zebra's in different classes, just because of the alphabet written over them. Since this text could be even sentences in more complicated cases, I am seeking for a better approach to include both text and image as feature.

Please guide me on this.

_Originally posted by @x0v in https://github.com/fizyr/keras-retinanet/issues/948#issuecomment-474407507_

**Comment by hgaiser** [comment]
The easiest would be to annotate them as separate classes.

Closing this as there is no issue with the code here.
