### ISSUE TITLE
[Feature-request] Debug should include base path for the csv generator

### ISSUE THREAD

**Issue by sklipnoty** [fizyr/keras-retinanet#950]
`trainingGenerator = csv.CSVGenerator('./input/validation_bbox.csv','./input/class.csv', deepFashionPath, batch_size=10, image_min_side=200, image_max_side=200) 
`

Seems only natural to add this as an option the CSV Debugger.

**Comment by hgaiser** [comment]
The default for the CSV generator is to treat the directory containing the file as the base path. Is this not sufficient ?

**Comment by de-vri-es** [comment]
It would be sufficient mostly, but exposing it as an option doesn't hurt either does it? I'd welcome a PR that does so.

**Comment by sklipnoty** [comment]
I used the base_dir option when making my csv_generators, so if you allow it to be exposed in the preprocessing module, seems it's only logical you allow it in the debug as well.

**Comment by de-vri-es** [comment]
Although it's not clear to me where you would like this option added. As far as I can tell none of the train, debug or evaluate scripts expose an option to change the base path for the CSV generator. So as far as I can tell, they are currently all consistent.

**Comment by hgaiser** [comment]
> I used the base_dir option when making my csv_generators, so if you allow it to be exposed in the preprocessing module, seems it's only logical you allow it in the debug as well.

The risk with that approach is that there are many arguments that you then want to expose in all scripts. While that would be nice, it would also cause an insane list of args. Regardless, if you want to add this argument to *all* scripts, then a PR would be welcome.

**Comment by hgaiser** [comment]
Closing this as there is no direct issue here. If you want to expose that argument, feel free to submit a PR.
