### ISSUE TITLE
How to use evaluate.py to evaluate my test dataset by multi-gpu?

### ISSUE THREAD

**Issue by kalubin-awym** [fizyr/keras-retinanet#951]
I have train my model by train.py and use 4 GPUs, and now I want to evaluate my test dataset by 4 GPUs so it can be more quickly. But when i use "--gpu 0,1,2,3" and run evaluate.py, I just see one gpu has worked, other 3 gups are not worked. So how to achieve to use multi-gpus to evaluate my dataset?
Thank you!

**Comment by zqdeepbluesky** [comment]
hi，have you solved it ? I met the same problem.

**Comment by kalubin-awym** [comment]
> hi，have you solved it ? I met the same problem.

sorry I haven't slove it. I think it need to modify code and use "multi_gpu_model". or make a script to run more python code together, like "python a.py > logs/a.log & python b.py > logs/b.log & python c.py > logs/c.log" and each python code use one of your GPUs.

**Comment by hgaiser** [comment]
Evaluation is currently limited to a single GPU. I forgot what all the reasons for that was; one at least is that using multi-gpu means that some images will have to be zero padded in order to fit in the same batch as other images. This could influence the output of the network.

**Comment by kalubin-awym** [comment]
> Evaluation is currently limited to a single GPU. I forgot what all the reasons for that was; one at least is that using multi-gpu means that some images will have to be zero padded in order to fit in the same batch as other images. This could influence the output of the network.

That's so sad, since i need run more quick to evaluate. Thanks so much for your reply!! ^_^

**Comment by hgaiser** [comment]
👍 

I'll close this issue since I don't think we should change this behaviour.
