### ISSUE TITLE
csv data set problem 

### ISSUE THREAD

**Issue by nosa999** [fizyr/keras-retinanet#954]
Hi,
i run the code on my own csv data set. it has 10 class of objects. and now I want to improve the code in one of the classes that has a low accuracy, I separate images of this class and changed the code and remove last snapshots and run code with the new data set but i see a lot of pictures of other classes that I remove them from my dataset. I add this code to genrator:

![image](https://user-images.githubusercontent.com/40929193/54952699-35d53580-4f64-11e9-8f92-ec0238b8cda4.png)

and the pictures save in tmp folder and these aren't in my dataset and I don't know why they are produced???!!!!

**Comment by hgaiser** [comment]
Please use the Github issue tracker for issues related to the code. For usage questions, use the keras-retinanet Slack channel.
