### ISSUE TITLE
hard negative mining(OHEM) in keras-retinanet

### ISSUE THREAD

**Issue by mailcorahul** [fizyr/keras-retinanet#955]
@hgaiser I have read paper of SSD where they do hard negative mining to tackle class imbalance problem and RetinaNet solves the same with the help of focal loss. I just have a doubt if this repo uses negative mining as well along with focal loss?

1. Is hard negative mining(OHEM) used while training?
2. If not, will it be a good idea to include it (I know that's exactly why focal loss is for), but will it be an added advantage?

**Comment by hgaiser** [comment]
It doesn't use OHEM, whether it's a good idea to add it I don't know. The best way would be to add it and compare :)

Closing this as there is no issue with the code. Please use the Slack channel for discussions.
