### ISSUE TITLE
Custum training using CSV file 

### ISSUE THREAD

**Issue by manish8892** [fizyr/keras-retinanet#958]
I created both csv files
started training on colab  using:
retinanet-train --epochs 5 --steps 100 csv ../CV101/datasets/blood_cell_detection/cell_data.csv ../CV101/datasets/blood_cell_detection/class_mapping.csv

**got this error message:**
 retinanet-train --epochs 5 --steps 100 csv ../CV101/datasets/blood_cell_detection/cell_data.csv ../CV101/datasets/blood_cell_detection/class_mapping.csv
                             ^
SyntaxError: invalid syntax

Thank you!

**Comment by hgaiser** [comment]
Could you post the entire error? Did you make any modifications to the code?

**Comment by manish8892** [comment]
![resnet_error](https://user-images.githubusercontent.com/12843921/55072631-d4d35d80-5048-11e9-80f3-ce409108b769.jpg)

no modifaction is made in the code....
Prepared CSV datasets as per need..
Attached image showing error

**Comment by hgaiser** [comment]
Ah.. that looks like a graphical way to execute python code, but that line is not python code, hence the syntax error.

**Comment by manish8892** [comment]
Ohh , then how it can be trained on custom data on colab ?any way?

**Comment by hgaiser** [comment]
Don't know, never tried it :)
