### ISSUE TITLE
where the code about data augment ?

### ISSUE THREAD

**Issue by Zweiyuan** [fizyr/keras-retinanet#962]
Hey, I want to use "--random-transform" for data augment. 
My images are fruit, so I don't want to flip the image upside down. 
I saw this issue [#572](https://github.com/fizyr/keras-retinanet/issues/572).
But I can't find this code. 
```
# create random transform generator for augmenting training data
if args.random_transform:
    transform_generator = random_transform_generator(
        min_rotation=-0.1,
        max_rotation=0.1,
        min_translation=(-0.1, -0.1),
        max_translation=(0.1, 0.1),
        min_shear=-0.1,
        max_shear=0.1,
        min_scaling=(0.9, 0.9),
        max_scaling=(1.1, 1.1),
        flip_x_chance=0.5,
        #flip_y_chance=0.5,
```

Can someone tell me where this code is?
Thanks!

**Comment by martinzlocha** [comment]
The code is in train.py: https://github.com/fizyr/keras-retinanet/blob/master/keras_retinanet/bin/train.py#L227

**Comment by de-vri-es** [comment]
Fruit can't be upside down?

**Comment by Zweiyuan** [comment]
@martinzlocha   Thanks, I find it. 
@de-vri-es  If the picture is flipped, will it lead to bad results?
