### ISSUE TITLE
large objects detection

### ISSUE THREAD

**Issue by MineIdea** [fizyr/keras-retinanet#966]
I have trained your model correctly on my dataset. And now I want to make some changes,so I delete P3 and P4 layers since the object in my dataset is large.But when I predict it. An error occurs.
the following is the error:

InvalidArgumentError                      Traceback (most recent call last)
<ipython-input-4-bfd8fd68d11e> in <module>
     18     # process image
     19     start = time.time()
---> 20     boxes, scores, labels = model.predict_on_batch(np.expand_dims(image, axis=0))
     21 #     print("processing time: ", time.time() - start)
     22 

~/anaconda3/envs/tf-gpu/lib/python3.6/site-packages/keras/engine/training.py in predict_on_batch(self, x)
   1272             ins = x
   1273         self._make_predict_function()
-> 1274         outputs = self.predict_function(ins)
   1275         return unpack_singleton(outputs)
   1276 

~/anaconda3/envs/tf-gpu/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py in __call__(self, inputs)
   2713                 return self._legacy_call(inputs)
   2714 
-> 2715             return self._call(inputs)
   2716         else:
   2717             if py_any(is_tensor(x) for x in inputs):

~/anaconda3/envs/tf-gpu/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py in _call(self, inputs)
   2673             fetched = self._callable_fn(*array_vals, run_metadata=self.run_metadata)
   2674         else:
-> 2675             fetched = self._callable_fn(*array_vals)
   2676         return fetched[:len(self.outputs)]
   2677 

~/anaconda3/envs/tf-gpu/lib/python3.6/site-packages/tensorflow/python/client/session.py in __call__(self, *args, **kwargs)
   1437           ret = tf_session.TF_SessionRunCallable(
   1438               self._session._session, self._handle, args, status,
-> 1439               run_metadata_ptr)
   1440         if run_metadata:
   1441           proto_data = tf_session.TF_GetBuffer(run_metadata_ptr)

~/anaconda3/envs/tf-gpu/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py in __exit__(self, type_arg, value_arg, traceback_arg)
    526             None, None,
    527             compat.as_text(c_api.TF_Message(self.status.status)),
--> 528             c_api.TF_GetCode(self.status.status))
    529     # Delete the underlying status object from memory otherwise it stays alive
    530     # as there is a reference to status from this from the traceback due to

InvalidArgumentError: Incompatible shapes: [1,182403] vs. [1,2853]
	 [[{{node boxes/mul_1}} = Mul[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"](boxes/mul, boxes/sub)]]
	 [[{{node filtered_detections/map/while/GatherNd_50/_1953}} = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_7321_filtered_detections/map/while/GatherNd_50", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"](^_cloopfiltered_detections/map/while/non_max_suppression/NonMaxSuppressionV3/max_output_size/_1811)]]

I think this error occurs because I have changed the anchor number,but I don't know how to fix it.Can you give me some ideas?

Thank you!!

**Comment by tonmoyborah** [comment]
Did you use the script `convert_model` to convert  your model to an inference one. Also you need to pass the `config.ini` file with anchors to the `convert_model`

**Comment by MineIdea** [comment]
> Did you use the script convert_model to convert  your model to an inference one. Also you need to pass the config.ini file with anchors to the convert_model

yes, I convert it. I've changed the AnchorParameters.default and  pyramid_levels in anchors.py.
the defaut is
AnchorParameters.default = AnchorParameters(
    sizes   = [256, 512],
    strides = [64, 128],
    ratios  = np.array([0.5, 1, 2], keras.backend.floatx()),
    scales  = np.array([2 ** 0, 2 ** (1.0 / 3.0), 2 ** (2.0 / 3.0)], keras.backend.floatx()),
)
and the pyramid_levels is changed to be [6,7].
and now the model could training and convert successfully, but when I predict it on my test dataset, an error occurs just like I mentioned above.
Is the config.ini file necessary?

**Comment by hgaiser** [comment]
Sounds like somewhere it is still using the full list of pyramid values.

However, as this is not an issue with our code, I'll close this. Feel free to discuss further on the Slack channel.
