### ISSUE TITLE
NMS method gives different results than Detectron

### ISSUE THREAD

**Issue by tonmoyborah** [fizyr/keras-retinanet#968]
I don't know for sure if this belongs in the slack channel or here but slack channel doesn't seem very useful anymore and I have been at this, experimenting, for several hours now.
I presume that the nms computation implemented here (from tf backend) is the basic nms method and not soft-nms or something else, right? [This](https://github.com/facebookresearch/Detectron/blob/master/detectron/utils/cython_nms.pyx) is a soft-nms method from detectron. I found a python implementation [here](https://github.com/ZFTurbo/Keras-RetinaNet-for-Open-Images-Challenge-2018/issues/4). The way I am using it now is - I use `--no-nms` during `convert_model` and then use the `demo_retinaNetDetection.py` script with the above `cpu_soft_nms()` function from detectron to get detections. After `predict` function is called, I take all the boxes (--no-nms) and pass them through the `cpu_soft_nms()` function. In this `cpu_soft_nms()` function, there are three methods - basic nms, linear soft-nms and a non-linear method. I presumed that the basic nms method of this function should give me same results as the `nms` implemented in this repository (when I use a model  converted without `--no-nms`), but this is not the case. The mAP reported using this repository's default nms is closer to the non-linear nms method of detectron (still higher though) and higher than the basic nms of detectron by ~0.8 to >1.0 (% mAP). I have tested this by varying many parameters and also by keeping them consistent. 

I wonder if there is an issue with the way I did things or something else.

**Comment by hgaiser** [comment]
It's difficult to say anything about this without being familiar with all NMS methods. If it helps, we are using [this](https://www.tensorflow.org/api_docs/python/tf/image/non_max_suppression) implementation of tensorflow. Regardless, as there is no issue here, I'll close it.

**Comment by tonmoyborah** [comment]
Do you think the issue has anything to do with something else that is done during convert model? Or maybe the no-nms flag doesn't do what I suppose it does?

**Comment by tonmoyborah** [comment]
And the tensorflow one you linked above is the basic nms method. Soft nms was presented in a different paper

**Comment by hgaiser** [comment]
> Do you think the issue has anything to do with something else that is done during convert model? Or maybe the no-nms flag doesn't do what I suppose it does?

Possibly .. the `--no-nms` flag affects this code: https://github.com/fizyr/keras-retinanet/blob/master/keras_retinanet/layers/filter_detections.py#L55-L63

As you see, there are still other filtering steps being done.



> And the tensorflow one you linked above is the basic nms method. Soft nms was presented in a different paper

Yeah I suspected so.
