### ISSUE TITLE
Detectnet dataset

### ISSUE THREAD

**Issue by ontheway16** [fizyr/keras-retinanet#969]
Hello,
I am hoping to use my existing Detectnet dataset (over 50k images with bbox anno.) in retinanet.
I see there's a Kitti option, what else I should do to use my existing data to create a compatible dataset for use in here? Any help is appreciated since I was looking for a long time to try retinanet, to see how it performs over Detectnet.

Thanks!

(I cannot find slack channel invite also, is it still active?)

**Comment by martinzlocha** [comment]
Please have a better look at the README before creating issues. The best option is to use the CSV format: https://github.com/fizyr/keras-retinanet#csv-datasets

To join slack look here: https://github.com/fizyr/keras-retinanet#discussions

**Comment by ontheway16** [comment]
@martinzlocha Thank you for your kind answer. I tried to express "since Kitti and Detectnet have very similar file contents [if I am not wrong], may I directly use existing Detectnet label .txt files with Kitti parameter", other than converting them to indicated CSV format.

And thanks for the Slack link.

Regards,

**Comment by martinzlocha** [comment]
Ahhh sorry I misunderstood. I haven't ever used the kitti parser or the dataset but it might be good to look at the KittiGenerator. To me it seems that the object classes are hardcoded so you might have to fork the repository and modify a few thing.

Code: https://github.com/fizyr/keras-retinanet/blob/master/keras_retinanet/preprocessing/kitti.py
