### ISSUE TITLE
Error in finding 'limits.h' with 'python setup.py build_ext --inplace'

### ISSUE THREAD

**Issue by doneylee** [fizyr/keras-retinanet#970]
Environment: Mac (Mojave), keras: 2.2.4, tensorflow: 1.13.1 python: 3.6

I got the following error when I ran setup.py on my Mac. Actually, I got the same error messages on my PC (Windows) as well. Please help me.

(tflearn) iMac:keras-retinanet shlee$ python setup.py build_ext --inplace
running build_ext
skipping 'keras_retinanet/utils/compute_overlap.c' Cython extension (up-to-date)
building 'keras_retinanet.utils.compute_overlap' extension
gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/shlee/anaconda/envs/tflearn/include -arch x86_64 -I/Users/shlee/anaconda/envs/tflearn/include -arch x86_64 -I/Users/shlee/anaconda/envs/tflearn/include/python3.6m -I/Users/shlee/anaconda/envs/tflearn/lib/python3.6/site-packages/numpy/core/include -c keras_retinanet/utils/compute_overlap.c -o build/temp.macosx-10.7-x86_64-3.6/keras_retinanet/utils/compute_overlap.o
In file included from /Users/shlee/anaconda/envs/tflearn/lib/gcc/x86_64-apple-darwin11.4.2/4.8.5/include-fixed/syslimits.h:7:0,
                 from /Users/shlee/anaconda/envs/tflearn/lib/gcc/x86_64-apple-darwin11.4.2/4.8.5/include-fixed/limits.h:34,
                 from /Users/shlee/anaconda/envs/tflearn/include/python3.6m/Python.h:11,
                 from keras_retinanet/utils/compute_overlap.c:4:
/Users/shlee/anaconda/envs/tflearn/lib/gcc/x86_64-apple-darwin11.4.2/4.8.5/include-fixed/limits.h:168:61: fatal error: limits.h: No such file or directory
 #include_next <limits.h>  /* recurse down to the real one */
                                                             ^
compilation terminated.
error: command 'gcc' failed with exit status 1

**Comment by martinzlocha** [comment]
Have you tried Googling this issue? For example here is a similar one: https://stackoverflow.com/questions/30624829/no-such-file-or-directory-limits-h-when-installing-pillow-on-alpine-linux

However this is not a RetinaNet issue.

**Comment by hgaiser** [comment]
As @martinzlocha mentioned, seems unrelated to retinanet.
