### ISSUE TITLE
Get index from box in ResNet50RetinaNet.ipynb

### ISSUE THREAD

**Issue by Charismata** [fizyr/keras-retinanet#973]
I tried to cut the image by using box list in ResNet50RetinaNet.ipynb
But i found i can't get only a index inside of it
For example I print original b is 
[  7 201 554 625]
[ 11 684 604 890]
[507 105 606 174]
[ 10 135 100 178]
if i try to get index b[0][1] and i get ( IndexError: too many indices for array)
How can i only get index 7 from first array?

**Comment by hgaiser** [comment]
In the example, `b` is only one box (so for instance `[ 7 201 554 625]`). If you want to get the box at index 7:

```python
box_at_index_7 = boxes[0, 7, :]
```
