### ISSUE TITLE
Compile Retinanet

### ISSUE THREAD

**Issue by ashep29** [fizyr/keras-retinanet#975]
Hi,
I would like to modify Retinanet. How do I compile the code to reflect the changes?
Thanks,
Andresa

**Comment by hgaiser** [comment]
Compile? As in C++ compile? keras-retinanet is written in python mainly, there is no need to compile. Only the code that computes bbox overlapping needs to be compiled, as described in the [installation](https://github.com/fizyr/keras-retinanet#installation).
