### ISSUE TITLE
ImportError: No module named compute_overlap

### ISSUE THREAD

**Issue by fengzifrank** [fizyr/keras-retinanet#977]
Model conversion when I test my own data, but such an error can't be solved, I hope I can get help.

Using TensorFlow backend.
Traceback (most recent call last):
  File "./keras_retinanet/bin/convert_model.py", line 34, in <module>
    from ..utils.config import read_config_file, parse_anchor_parameters
  File "./keras_retinanet/bin/../../keras_retinanet/utils/config.py", line 20, in <module>
    from ..utils.anchors import AnchorParameters
  File "./keras_retinanet/bin/../../keras_retinanet/utils/anchors.py", line 20, in <module>
    from ..utils.compute_overlap import compute_overlap
ImportError: No module named compute_overlap

**Comment by hgaiser** [comment]
https://github.com/fizyr/keras-retinanet#faq

**Comment by spaul13** [comment]
I ran the "python setup.py build_ext --inplace" successfully and it generates compute_overlap.cp37-win_amd64.PYD file on windows. But still I am getting the error 
_**ModuleNotFoundError: No module named 'keras_retinanet.utils.compute_overlap'**_

can anyone plz tell me why I am still getting this error and how to solve this error?

**Comment by Dickoabc123** [comment]
hey @spaul13 did you ever resolve this? I am facing the same issues after trying the steps mentioned above and would appreciate any help. Thank you.
