### ISSUE TITLE
ValueError: Unknown loss function:_logcosh

### ISSUE THREAD

**Issue by mayankb2103** [fizyr/keras-retinanet#982]
Error in converting the model

> Using TensorFlow backend.
> 2019-04-24 21:17:38.475687: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
> 2019-04-24 21:17:38.688230: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1105] Found device 0 with properties: 
> name: GeForce GTX 1080 Ti major: 6 minor: 1 memoryClockRate(GHz): 1.582
> pciBusID: 0000:03:00.0
> totalMemory: 10.91GiB freeMemory: 10.63GiB
> 2019-04-24 21:17:38.688278: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1195] Creating TensorFlow device (/device:GPU:0) -> (device: 0, name: GeForce GTX 1080 Ti, pci bus id: 0000:03:00.0, compute capability: 6.1)
> Loading model, this may take a second...
> Traceback (most recent call last):
>   File "evaluate.py", line 178, in <module>
>     main()
>   File "evaluate.py", line 146, in main
>     model = models.load_model(args.model, backbone_name=args.backbone)
>   File "../../keras_retinanet/models/__init__.py", line 83, in load_model
>     model = keras.models.load_model(filepath, custom_objects=backbone(backbone_name).custom_objects)
>   File "/home/iitdgpu/venv/pyc297/lib/python2.7/site-packages/keras/engine/saving.py", line 419, in load_model
>     model = _deserialize_model(f, custom_objects, compile)
>   File "/home/iitdgpu/venv/pyc297/lib/python2.7/site-packages/keras/engine/saving.py", line 312, in _deserialize_model
>     sample_weight_mode=sample_weight_mode)
>   File "/home/iitdgpu/venv/pyc297/lib/python2.7/site-packages/keras/engine/training.py", line 129, in compile
>     loss_functions.append(losses.get(loss.get(name)))
>   File "/home/iitdgpu/venv/pyc297/lib/python2.7/site-packages/keras/losses.py", line 133, in get
>     return deserialize(identifier)
>   File "/home/iitdgpu/venv/pyc297/lib/python2.7/site-packages/keras/losses.py", line 114, in deserialize
>     printable_module_name='loss function')
>   File "/home/iitdgpu/venv/pyc297/lib/python2.7/site-packages/keras/utils/generic_utils.py", line 165, in deserialize_keras_object
>     ':' + function_name)
> ValueError: Unknown loss function:_logcosh

**Comment by hgaiser** [comment]
Are you sure you're loading a keras-retinanet model? I've never heard of the `_logcosh` loss function, doesn't seem to be from keras-retinanet.
