### ISSUE TITLE
cannot train

### ISSUE THREAD

**Issue by qewtqwqqq** [fizyr/keras-retinanet#983]
ImportError: dlopen(keras_retinanet/bin/../../keras_retinanet/utils/compute_overlap.so, 2): no suitable image found.  Did find:
	keras_retinanet/bin/../../keras_retinanet/utils/compute_overlap.so: unknown file type, first eight bytes: 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x00
	/Users/sdk_auto/xumengyao/guazai/retinaNet/keras-retinanet/keras_retinanet/utils/compute_overlap.so: unknown file type, first eight bytes: 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x00

**Comment by martinzlocha** [comment]
This is not a retianet issue however after if you just Google: "unknown file type, first eight bytes: 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x00" then you will  find this post: https://stackoverflow.com/questions/38176039/cant-run-shared-library-compiled-on-ubuntu-on-mac

It seems that you are sharing the compute_overlap binary across different OSes. Make sure that you compile it locally.

**Comment by qewtqwqqq** [comment]
> This is not a retianet issue however after if you just Google: "unknown file type, first eight bytes: 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x00" then you will find this post: https://stackoverflow.com/questions/38176039/cant-run-shared-library-compiled-on-ubuntu-on-mac
> 
> It seems that you are sharing the compute_overlap binary across different OSes. Make sure that you compile it locally.

Thank you, it works.

**Comment by de-vri-es** [comment]
Glad to see the issue is resolved.
