### ISSUE TITLE
Memory Error using COWC dataset

### ISSUE THREAD

**Issue by bluetooth12** [fizyr/keras-retinanet#984]
![image](https://user-images.githubusercontent.com/8892431/56841553-5b937a00-6843-11e9-8d64-04a1daeaf6e6.png)

I am trying to train retinanet from scratch using one big image from the COWC dataset with lots of cars on it and I am getting the error message above. Any ideas what the problem might be?

**Comment by martinzlocha** [comment]
Looks like you don't have enough RAM: https://stackoverflow.com/questions/5537618/memory-errors-and-list-limits/5537764

**Comment by hgaiser** [comment]
Yep, seems @martinzlocha answered this. Assuming this is resolved.
