### ISSUE TITLE
negative bbox coordinate after random transform

### ISSUE THREAD

**Issue by sUtomorrow** [fizyr/keras-retinanet#988]
When the target frame is at the edge of the image, for example, x1, y1, x2, y2 is 0, 0, 200, 200, then after random transform the bbox with keras-retinanet.utils.transform.transform_aabb function, there may cause negative bbox coordinate.

**Comment by de-vri-es** [comment]
I seem to recall clipping the boxes if that happens. Did this actually cause a crash for you?

**Comment by sUtomorrow** [comment]
> I seem to recall clipping the boxes if that happens. Did this actually cause a crash for you?

I found the filter_annotations function is call before random_transform_group function, Is there any other function clip the boxes? there is no crash, but it maybe cause anchor select incorrectly, I found this problem when I tried to add anchor-free branch to the model architecture.

**Comment by de-vri-es** [comment]
I'm not sure. However, there is an old open issue regarding transformations that transform annotations partially out of the image canvas: #223. However, so far nobody has really had any practical issues with the current behaviour so we haven't done anything.

**Comment by hgaiser** [comment]
> I seem to recall clipping the boxes if that happens. Did this actually cause a crash for you?

I don't think we clip boxes after random transformations.

@sUtomorrow is this causing an issue for you, or was it just an observation? I see your point on anchor selection, do you think it will cause large enough errors?

**Comment by hgaiser** [comment]
Any update on this @sUtomorrow ?

**Comment by sUtomorrow** [comment]
I'm sorry no reply for a long time.
There is no big problem in the code, I just think about if it's well to clip the annotation box(which may be changed by random transform) before select positive/negative anchor box.
