### ISSUE TITLE
Unable to open file model

### ISSUE THREAD

**Issue by rezafd23** [fizyr/keras-retinanet#993]
i've trained my own dataset, and convert to inference follow the FAQ instruction, but after i convert my .h5 file and load the model, i got this error

OSError: Unable to open file (unable to open file: name = 'modelres.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)

**Comment by de-vri-es** [comment]
Your issue does not include an exact description of the commands you ran as requested by the issue template. There is not enough information here to properly debug your issue.

However, the error says `No such file or directory`. The path you're giving is most likely incorrect. Please make sure you actually pass the path to the model to the script.

**Comment by ankitAMD** [comment]
same error

**Comment by ankitAMD** [comment]
@rezafd23 Please check this Link you can solve your problem through help in the link.

https://stackoverflow.com/questions/51593527/oserror-unable-to-open-file-unable-to-open-file
